### ISSUE TITLE
Wifiphisher with Termux Android 6.0 : pyric.error: [Errno 13] Permission denie

### ISSUE THREAD

**Issue by masjokonias2018** [wifiphisher/wifiphisher#1021]
```
root@localhost:~# cd wifiphisher
root@localhost:~/wifiphisher# wifiphisher
[*] Starting Wifiphisher 1.4GIT ( https://wifiphisher.org ) at 2018-10-21 01:24
[+] Timezone detected. Setting channel range to 1-13
Traceback (most recent call last):
  File "/usr/local/bin/wifiphisher", line 11, in <module>
    load_entry_point('wifiphisher==1.4', 'console_scripts', 'wifiphisher')()
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.4-py2.7.egg/wifiphisher/pywifiphisher.py", line 686, in run
    engine.start()
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.4-py2.7.egg/wifiphisher/pywifiphisher.py", line 388, in start
    self.network_manager.start()
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.4-py2.7.egg/wifiphisher/common/interfaces.py", line 706, in start
    raise error
pyric.error: [Errno 13] Permission denie
```

**Comment by blackHatMonkey** [comment]
@masjokonias2018 Are you running the latest version?

**Comment by Kry9toN** [comment]
Same my problem

**Comment by blackHatMonkey** [comment]
@masjokonias2018 We currently don't support android environment.

**Comment by Mayanjaint** [comment]
Same here
