### ISSUE TITLE
Error in kali

### ISSUE THREAD

**Issue by C7pH0r** [wifiphisher/wifiphisher#1027]
```
root@kali:~/Desktop/wifiphisher# wifiphisher
[*] Starting Wifiphisher 1.4GIT ( https://wifiphisher.org ) at 2018-11-01 10:59
[+] Timezone detected. Setting channel range to 1-13
Traceback (most recent call last):
  File "/usr/local/bin/wifiphisher", line 11, in <module>
    load_entry_point('wifiphisher==1.4', 'console_scripts', 'wifiphisher')()
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.4-py2.7.egg/wifiphisher/pywifiphisher.py", line 693, in run
    engine.start()
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.4-py2.7.egg/wifiphisher/pywifiphisher.py", line 390, in start
    self.opmode.initialize(args)
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.4-py2.7.egg/wifiphisher/common/opmode.py", line 53, in initialize
    interfaces.is_add_vif_required(args)
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.4-py2.7.egg/wifiphisher/common/interfaces.py", line 798, in is_add_vif_required
    card = pyw.getcard(vif)
  File "/usr/local/lib/python2.7/dist-packages/PyRIC-0.1.6.3-py2.7.egg/pyric/pyw.py", line 269, in getcard
    if nlsock is None: return _nlstub_(getcard, dev)
  File "/usr/local/lib/python2.7/dist-packages/PyRIC-0.1.6.3-py2.7.egg/pyric/pyw.py", line 2236, in _nlstub_
    return fct(*argv)
  File "/usr/local/lib/python2.7/dist-packages/PyRIC-0.1.6.3-py2.7.egg/pyric/pyw.py", line 270, in getcard
    return devinfo(dev, nlsock)['card']
  File "/usr/local/lib/python2.7/dist-packages/PyRIC-0.1.6.3-py2.7.egg/pyric/pyw.py", line 1049, in devinfo
    raise pyric.error(pyric.EPROTONOSUPPORT, "Device does not support nl80211")
pyric.error: [Errno 93] Device does not support nl80211
```

**Comment by sophron** [comment]
This is not a bug. If your card device does not support nl80211, Wifiphisher won't run.

**Comment by nsnyder11** [comment]
plz suggest adapters that support this mode.

**Comment by thongbi9** [comment]
> This is not a bug. If your card device does not support nl80211, Wifiphisher won't run.

Can u give me 1 card can use
