### ISSUE TITLE
Wifiphisher not working on my kali linux

### ISSUE THREAD

**Issue by Amo95** [wifiphisher/wifiphisher#1032]
Before opening a new issue, please make sure that what you are about to report has not been reported already. If not, use the following template for reporting.

**Version**: 
DISTRIB_DESCRIPTION="Kali GNU/Linux Rolling"
PRETTY_NAME="Kali GNU/Linux Rolling"
NAME="Kali GNU/Linux"
ID=kali
VERSION="2018.4"
VERSION_ID="2018.4"
ID_LIKE=debian

**Description**: After installing wifiphisher, i try running it "wifiphisher"... i have tried several ideas and solution via internet but all to no avail. Please i need your help to fix my wifiphisher

**Script output**: root@AJ:~# wifiphisher
Traceback (most recent call last):
  File "/usr/local/bin/wifiphisher", line 11, in <module>
    load_entry_point('wifiphisher==1.4', 'console_scripts', 'wifiphisher')()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 479, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2703, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2321, in load
    return self.resolve()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2327, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.4-py2.7.egg/wifiphisher/pywifiphisher.py", line 21, in <module>
    import wifiphisher.common.extensions as extensions
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.4-py2.7.egg/wifiphisher/common/extensions.py", line 11, in <module>
    import scapy.layers.dot11 as dot11
  File "/usr/local/lib/python2.7/dist-packages/scapy/layers/dot11.py", line 12, in <module>
    from scapy.packet import *
  File "/usr/local/lib/python2.7/dist-packages/scapy/packet.py", line 39
    class Packet(BasePacket, metaclass = Packet_metaclass):
                                       ^
SyntaxError: invalid syntax

**Comment by sophron** [comment]
Have a look at #753.

**Comment by Amo95** [comment]
Thanks a lot... #753 worked for me @sophron

**Comment by Amo95** [comment]
Thanks a lot... #753 worked for me @sophron
