### ISSUE TITLE
SyntaxError: Invalid Syntax (Distro: Parrot Sec OS)

### ISSUE THREAD

**Issue by zyrgo** [wifiphisher/wifiphisher#1048]
```bash
Traceback (most recent call last):
  File "/usr/local/bin/wifiphisher", line 11, in <module>
    load_entry_point('wifiphisher==1.4', 'console_scripts', 'wifiphisher')()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 487, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2728, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2346, in load
    return self.resolve()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2352, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.4-py2.7.egg/wifiphisher/pywifiphisher.py", line 20, in <module>
    import wifiphisher.common.extensions as extensions
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.4-py2.7.egg/wifiphisher/common/extensions.py", line 11, in <module>
    import scapy.layers.dot11 as dot11
  File "/usr/local/lib/python2.7/dist-packages/scapy/layers/dot11.py", line 12, in <module>
    from scapy.packet import *
  File "/usr/local/lib/python2.7/dist-packages/scapy/packet.py", line 39
    class Packet(BasePacket, metaclass = Packet_metaclass):
                                       ^
SyntaxError: invalid syntax
```

**Comment by blackHatMonkey** [comment]
@zyrgo Thanks for opening an issue. It looks like your problem is similar to #900. Take a look at [this](https://github.com/wifiphisher/wifiphisher/issues/900#issuecomment-379475968) solution.

**Comment by zyrgo** [comment]
@blackHatMonkey i have reinstalled scapy but still doesn't work

**Comment by blackHatMonkey** [comment]
@zyrgo Are you getting the exact same error?

**Comment by blackHatMonkey** [comment]
@zyrgo you might also want to take a look at [this](https://github.com/wifiphisher/wifiphisher/issues/753#issuecomment-372937381).

**Comment by piyushx12** [comment]
try sudo

**Comment by zyrgo** [comment]
@blackHatMonkey yes. Same error. Over and over

**Comment by blackHatMonkey** [comment]
@zyrgo Make sure you are deleting both `pip` and `apt`.
```bash
sudo pip2 uninstall scapy
sudo apt-get purge python-scapy
```
After this you can just restart your computer and run
```bash
sudo pip2 install scapy
```
