### ISSUE TITLE
ImportError: No module named tornado.escape

### ISSUE THREAD

**Issue by paveldbest** [wifiphisher/wifiphisher#1050]
I am running kali on raspberry pi. When I tried `sudo python setup.py install # Install any dependencies`, it had the error below 
error: [Errno 21] Is a directory: '/usr/local/bin/wifiphisher'
After that I got the ImportError: No module named tornado.escape while running wihiphisher in /bin.
Anyone could help me with this? Although I think someone mentioned this script on raspberry isn't stable.
Regards

**Comment by blackHatMonkey** [comment]
@paveldbest Thanks for opening an issue. Can you try running:
```bash
sudo pip install tornado
```

**Comment by owenm1993** [comment]
I still have the same problem

**Comment by mguomanila** [comment]
me  too. i install wifiphisher in python 3 and look all the error, so i revert to python 2.7 and it install well, but the moment ./bin/wifiphisher is run in the command line, i got the following error:
Traceback (most recent call last):
  File "./bin/wifiphisher", line 16, in <module>
    from wifiphisher.pywifiphisher import run
  File "/media/git/net_circumvent/wifiphisher/wifiphisher/pywifiphisher.py", line 24, in <module>
    import wifiphisher.common.phishinghttp as phishinghttp
  File "/media/git/net_circumvent/wifiphisher/wifiphisher/common/phishinghttp.py", line 6, in <module>
    from tornado.escape import json_decode
ImportError: No module named tornado.escape

Im using ubuntu 18.10 - thanks!

**Comment by vs4vijay** [comment]
I am getting the same issue on Raspberry Pi, I have created an issue here: https://github.com/wifiphisher/wifiphisher/issues/1121

**Comment by vs4vijay** [comment]
This as well: https://github.com/wifiphisher/wifiphisher/issues/1068#issuecomment-489214008
