### ISSUE TITLE
Chaning IP address from 10.0.0.1 and dnsmasq setting to custom

### ISSUE THREAD

**Issue by hash3liZer** [wifiphisher/wifiphisher#1055]
I'm having this issue of setting ip address. When i run wifiphisher, i receive this error: 

```
Exception in thread Thread-4:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/lib/python2.7/dist-packages/wifiphisher/common/phishinghttp.py", line 180, in runHTTPServer
    https_server.listen(ssl_port, address=ip)
  File "/usr/lib/python2.7/dist-packages/tornado/tcpserver.py", line 144, in listen
    sockets = bind_sockets(port, address=address)
  File "/usr/lib/python2.7/dist-packages/tornado/netutil.py", line 171, in bind_sockets
    sock.bind(sockaddr)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address already in use
```
And a different version of same error occurs when i run with roguehostapd. It seems like something to do with the ip address. I am not able to use the ip `10.0.0.1` at all on my platform. Can you help with changing the default ip address and ranges from dnsmasq?

**Comment by tykkz** [comment]
Your machine probably uses that IP address in some other interface. You can change the dnsmasq configuration with the `--dnsmasq-conf` option.

Can you post the outputs of the following commands:

`iw list`
`iwconfig`
`ifconfig`

**Comment by sophron** [comment]
There is another process listening on the port that Wifiphisher tries to bind (8080). You can either run `lsof -i :8000`, see that process and kill it or edit `wifiphisher/constants.py` and change the listening port to something other than 8080.

**Comment by hash3liZer** [comment]
Yep, i figured it out. The file `constants.py` worked for me. Thanks.
