### ISSUE TITLE
Cant run the wifiphisher

### ISSUE THREAD

**Issue by murillojndem** [wifiphisher/wifiphisher#1062]
So, i`m using parrot distro and I downloaded and extracted files normally, but when I try to open the program typing wifiphysher on the terminal I get the following message

```
Traceback (most recent call last):
  File "/usr/local/bin/wifiphisher", line 11, in <module>
    load_entry_point('wifiphisher==1.4', 'console_scripts', 'wifiphisher')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 487, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2728, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2346, in load
    return self.resolve()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2352, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.4-py2.7.egg/wifiphisher/pywifiphisher.py", line 27, in <module>
    import wifiphisher.common.accesspoint as accesspoint
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.4-py2.7.egg/wifiphisher/common/accesspoint.py", line 7, in <module>
    from roguehostapd import hostapd_controller
ImportError: cannot import name hostapd_controller
```

Didn`t find any topic with this specific error. If u find just tell me and I`ll erase this one. Ty in advance

**Comment by JetseVerschuren** [comment]
It means you run a outdated version of wifiphisher. Did you clone from github? If not try installing from git.
