### ISSUE TITLE
Traceback (most recent call last):

### ISSUE THREAD

**Issue by samuelhutauruk2** [wifiphisher/wifiphisher#1068]
I have installed Wifiphisher 1.4 after that, i type wifiphisher in terminal, it returns these : 
```
Traceback (most recent call last):
  File "/usr/local/bin/wifiphisher", line 9, in <module>
    load_entry_point('wifiphisher==1.4', 'console_scripts', 'wifiphisher')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 542, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2569, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2229, in load
    return self.resolve()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2235, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.4-py2.7.egg/wifiphisher/pywifiphisher.py", line 23, in <module>
    import wifiphisher.common.phishinghttp as phishinghttp
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.4-py2.7.egg/wifiphisher/common/phishinghttp.py", line 3, in <module>
    from tornado.escape import json_decode
  File "/usr/local/lib/python2.7/dist-packages/tornado-6.0a1-py2.7-linux-i686.egg/tornado/escape.py", line 43
    def xhtml_escape(value: Union[str, bytes]) -> str:
                          ^
SyntaxError: invalid syntax
```

```
Linux draconic 4.4.0-31-generic #50-Ubuntu SMP Wed Jul 13 00:06:14 UTC 2016 i686 athlon i686 GNU/Linux
```

**Comment by sophron** [comment]
Can you reinstall `tornado` and try again? 

`pip uninstall tornado`
`python setup.py install` (from within wifiphisher directory)

**Comment by samuelhutauruk2** [comment]
i did that, but seems not working for me.

**Comment by sophron** [comment]
Are you still getting the same error? Can you check which version of `tornado` you have installed and report back?

**Comment by vs4vijay** [comment]
Hey, This issue is still there. I suppose problem is with tornado compatible version.

I am using python 2.7, and I installed `tornado==4.5.3` version (by taking a look at setup.py)... and when I try to run it using `sudo python2 bin/wifiphisher`, I get the same error "ImportError: No module named tornado.escape"

could anyone tell which tornado version is supported in wifiphisher?

**Comment by Mahdi321** [comment]
Same problem here I uni

> Can you reinstall `tornado` and try again?
> 
> `pip uninstall tornado`
> `python setup.py install` (from within wifiphisher directory)

Not solved my problem, too 
Tornado v 6.0.2
```
$ sudo python2 bin/wifiphisher 
Traceback (most recent call last):
  File "bin/wifiphisher", line 16, in <module>
    from wifiphisher.pywifiphisher import run
  File "/home/m/Downloads/wifiphisher-1.4/wifiphisher/pywifiphisher.py", line 23, in <module>
    import wifiphisher.common.phishinghttp as phishinghttp
  File "/home/m/Downloads/wifiphisher-1.4/wifiphisher/common/phishinghttp.py", line 3, in <module>
    from tornado.escape import json_decode
  File "/usr/local/lib/python2.7/dist-packages/tornado-6.0.2-py2.7-linux-x86_64.egg/tornado/escape.py", line 43
    def xhtml_escape(value: Union[str, bytes]) -> str:
                          ^
SyntaxError: invalid syntax
```

**Comment by alexjamwei** [comment]
same error happened to me,pls help

**Comment by victorhfsilva** [comment]
I'm not expert but for me I just reinstalled from source together with the necessary packs and it worked. 

```
sudo apt-get remove wifiphisher
sudo apt-get install -y python3-setuptools libnl-3-dev libnl-genl-3-dev libssl-dev
sudo apt-get update
git clone https://github.com/wifiphisher/wifiphisher.git
cd wifiphisher
sudo python3 setup.py install
```
