### ISSUE TITLE
Tornado error when showing captive portal

### ISSUE THREAD

**Issue by mmomasters** [wifiphisher/wifiphisher#1085]
2019-03-08 22:26:53,203 -              tornado.application - ERROR - Exception in callback None
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/tornado-4.5.3-py2.7-linux-armv7l.egg/tornado/ioloop.py", line 888, in start
    handler_func(fd_obj, events)
  File "/usr/local/lib/python2.7/dist-packages/tornado-4.5.3-py2.7-linux-armv7l.egg/tornado/stack_context.py", line 277, in null_wrapper
    return fn(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tornado-4.5.3-py2.7-linux-armv7l.egg/tornado/iostream.py", line 519, in _handle_events
    self._handle_read()
  File "/usr/local/lib/python2.7/dist-packages/tornado-4.5.3-py2.7-linux-armv7l.egg/tornado/iostream.py", line 1395, in _handle_read
    self._do_ssl_handshake()
  File "/usr/local/lib/python2.7/dist-packages/tornado-4.5.3-py2.7-linux-armv7l.egg/tornado/iostream.py", line 1315, in _do_ssl_handshake
    self.socket.do_handshake()
  File "/usr/lib/python2.7/ssl.py", line 828, in do_handshake
    self._sslobj.do_handshake()
error: [Errno 0] Error

**Comment by sophron** [comment]
This is a known issue. It should not affect the execution of the program. 

You can use our `--logging` option to have a clean output for now.

**Comment by mmomasters** [comment]
All right thank you
