### ISSUE TITLE
Not showing available network

### ISSUE THREAD

**Issue by Stanwarr** [wifiphisher/wifiphisher#1091]
**Version**: c27c2ab1ef9c5c3aad6f9643acb9170cf2c45a73

**Description**: It starts as normal then instead of showing available networks it shows an error.. Giving me the device is busy error meanwhile I tried the airmon-ng check kill command and still same error.
The output of the [iw list](https://pastebin.com/0Z2QFVm4)
**Script output**: 
Exception in thread Thread-5:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.4-py2.7.egg/wifiphisher/common/recon.py", line 186, in _channel_hop
    self._interface, channel)
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.4-py2.7.egg/wifiphisher/common/interfaces.py", line 648, in set_interface_channel
    pyw.chset(card, channel)
  File "/usr/local/lib/python2.7/dist-packages/PyRIC-0.1.6.3-py2.7.egg/pyric/pyw.py", line 1243, in chset
    if nlsock is None: return _nlstub_(chset, card, ch, chw)
  File "/usr/local/lib/python2.7/dist-packages/PyRIC-0.1.6.3-py2.7.egg/pyric/pyw.py", line 2236, in _nlstub_
    return fct(*argv)
  File "/usr/local/lib/python2.7/dist-packages/PyRIC-0.1.6.3-py2.7.egg/pyric/pyw.py", line 1244, in chset
    return freqset(card, channels.ch2rf(ch), chw, nlsock)
  File "/usr/local/lib/python2.7/dist-packages/PyRIC-0.1.6.3-py2.7.egg/pyric/pyw.py", line 1286, in freqset
    if e.errno == pyric.EBUSY: raise pyric.error(e.errno,pyric.strerror(e.errno))
error: [Errno 16] Device or resource busy. Make sure Card is up and no other devices share the same phy

**Comment by Stanwarr** [comment]
Nvm. I fixed this through reinstalling wifiphisher.
