### ISSUE TITLE
wifiphisher on RaspberryPi

### ISSUE THREAD

**Issue by vs4vijay** [wifiphisher/wifiphisher#1121]
Hi All,

I was installing "wifiphisher" on my Raspberry Pie OS "raspian" which is based on Debian Stretch....

When I did "sudo apt-get install wifiphisher", but I found out that wifiphisher sources hasn't been added to "raspian" sources list.

So I though if installing using source, so I downloaded the latest stable 1.4 tar.gzip file and extracted.

I did run `sudo python setup.py install` and ran `sudo python bin/wifiphisher`, I got this error:

```
Traceback (most recent call last):
  File "bin/wifiphisher", line 16, in <module>
    from wifiphisher.pywifiphisher import run
  File "/home/viz/tools/wifiphisher-1.4/wifiphisher/pywifiphisher.py", line 23, in <module>
    import wifiphisher.common.phishinghttp as phishinghttp
  File "/home/viz/tools/wifiphisher-1.4/wifiphisher/common/phishinghttp.py", line 3, in <module>
    from tornado.escape import json_decode
  File "/usr/local/lib/python2.7/dist-packages/tornado-6.0.2-py2.7-linux-armv7l.egg/tornado/escape.py", line 43
    def xhtml_escape(value: Union[str, bytes]) -> str:
                          ^
SyntaxError: invalid syntax
```

I thought this is python3 syntax so I installed the wifiphisher using python3 as follows:

I ran `sudo python3 setup.py install` and ran `sudo python3 bin/wifiphisher`, I got this error:

```
Traceback (most recent call last):
  File "bin/wifiphisher", line 16, in <module>
    from wifiphisher.pywifiphisher import run
  File "/home/viz/tools/wifiphisher-1.4/wifiphisher/pywifiphisher.py", line 226
    print '[' + G + '+' + W + "] Sending SIGKILL to " +\
            ^
SyntaxError: Missing parentheses in call to 'print'
```

I am not sure how do I make it work, I have been struggling with it since hours now. Could anyone help me out.

PS: I install scapy using "sudo apt-get install python-scapy" and "pip install scapy" as well for both python and python3.... Not sure whats the right way.

**Comment by N2Network** [comment]
I've got a ton of hours into wifiphisher on pi 3 b+. I would recommend you download this kernel and go from there - https://re4son-kernel.com/re4son-pi-kernel/

**Comment by vs4vijay** [comment]
Thanks @N2Network

**Comment by vs4vijay** [comment]
@N2Network Just out of curiosity, What does that Kernel do? I read that it will allow the monitor mode, injections etc etc possible. but I have External WiFi Card which is working successfully. So tell me, the reason I am not able to install `wifiphisher` is because of Kernel not being compatible?

**Comment by N2Network** [comment]
> @N2Network Just out of curiosity, What does that Kernel do? I read that it will allow the monitor mode, injections etc etc possible. but I have External WiFi Card which is working successfully. So tell me, the reason I am not able to install `wifiphisher` is because of Kernel not being compatible?

I'm not saying you can't make Stretch work on Pi. I just spent a lot of time messing around with Kali on Pi and that Kernel is what I settled on.  I think the key is it has all the cards compatible with Kali loaded to support monitor mode etc. I'm not an expert. It just made it easier for me.

**Comment by Throwaway684736** [comment]
N2Network, nice. Would you briefly explain how to install it? I mean, if I backup my existing Stretch and run the kernel installer, would it replace the old kernel and leave the rest of the system unharmed?
Also, what about RogueHostAP, is it still broken (or is it not really necessary) ?

**Comment by N2Network** [comment]
Theres an img file you can download and just expand to an sd card. It's called sticky fingers or something like that.
