### ISSUE TITLE
AP not visible, errors in output

### ISSUE THREAD

**Issue by oliverrickfors** [wifiphisher/wifiphisher#1127]
I want to run
`sudo wifiphisher -i wlx00c0caa5f00e --essid "test" -p oauth-login`
with my external nic

```
wlx00c0caa5f00e: flags=4099<UP,BROADCAST,MULTICAST>  mtu 1500
        ether 3e:fc:31:eb:30:7e  txqueuelen 1000  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 17 overruns 0  carrier 0  collisions 0
```

Here's the output:

```
oliver@hp:~$ sudo wifiphisher -i wlx00c0caa5f00e --essid "test" -p oauth-login
[*] Starting Wifiphisher 1.4GIT ( https://wifiphisher.org ) at 2019-05-05 20:35
[+] Timezone detected. Setting channel range to 1-13
[+] Selecting wfphshr-wlan0 interface for the deauthentication attack
[+] Selecting wlx00c0caa5f00e interface for creating the rogue Access Point
[+] Changing wlx00c0caa5f00e MAC addr (BSSID) to 00:00:00:94:fd:03
[+] Changing wlx00c0caa5f00e MAC addr (BSSID) to 00:00:00:c4:86:a1
[+] Sending SIGKILL to wpa_supplicant
[+] Sending SIGKILL to avahi-daemon
[+] Sending SIGKILL to avahi-daemon
[+] Sending SIGKILL to NetworkManager
[*] Cleared leases, started DHCP, set up iptables
[+] Selecting OAuth Login Page template
[*] Starting the fake access point...
[*] Starting HTTP/HTTPS server at ports 8080, 443
Exception in thread Thread-5:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.4-py2.7.egg/wifiphisher/common/phishinghttp.py", line 198, in runHTTPServer
    app.listen(port, address=ip)
  File "/usr/local/lib/python2.7/dist-packages/tornado-4.5.3-py2.7-linux-x86_64.egg/tornado/web.py", line 1944, in listen
    server.listen(port, address)
  File "/usr/local/lib/python2.7/dist-packages/tornado-4.5.3-py2.7-linux-x86_64.egg/tornado/tcpserver.py", line 142, in listen
    sockets = bind_sockets(port, address=address)
  File "/usr/local/lib/python2.7/dist-packages/tornado-4.5.3-py2.7-linux-x86_64.egg/tornado/netutil.py", line 197, in bind_sockets
    sock.bind(sockaddr)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 99] Cannot assign requested address

[+] Show your support!
[+] Follow us: https://twitter.com/wifiphisher
[+] Like us: https://www.facebook.com/Wifiphisher
[+] Captured credentials:
```
Now this screen pops up, looking wierd:
https://imgur.com/a/heSqQHt

I check if I can see the rogue AP but can't find it
So I press esc to be followed by this:
```
Exception IOError: (19, 'No such device') in <bound method L2ListenSocket.__del__ of <scapy.arch.linux.L2ListenSocket object at 0x7fe78859ad10>> ignored
Segmentation fault (core dumped)
```

I'm on linux mint, my nic is alfa awus036ach

**Comment by sophron** [comment]
I don't see anything weird with the screen.

Change `/etc/constants.py` file and edit the NETWORK* constants (e.g. from 10.0.0.0 to 192.168.0.0).
