### ISSUE TITLE
[Errno 95] Operation not supported after Selecting Tamplate

### ISSUE THREAD

**Issue by CokeMaan** [wifiphisher/wifiphisher#1129]
Hello, 
I have the following problem with wifiphisher:

[*] Starting Wifiphisher 1.4GIT ( https://wifiphisher.org ) at 2019-05-10 20:52
[+] Selecting wlan1 interface for the deauthentication attack
[+] Selecting wlan0 interface for creating the rogue Access Point
[+] Sending SIGKILL to wpa_supplicant
[+] Sending SIGKILL to dhclient
[+] Sending SIGKILL to NetworkManager
[+] Changing wlan0 MAC addr (BSSID) to 00:00:00:53:82:04
[+] Changing wlan1 MAC addr to 00:00:00:1b:53:73
[*] Cleared leases, started DHCP, set up iptables
[+] Selecting Firmware Upgrade Page template
[*] Starting the fake access point...
[*] Starting HTTP/HTTPS server at ports 8080, 443
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/lib/python2.7/dist-packages/wifiphisher/common/extensions.py", line 147, in _channel_hop
    int(self._shared_data.target_ap_channel))
  File "/usr/lib/python2.7/dist-packages/wifiphisher/common/interfaces.py", line 651, in set_interface_channel
    pyw.chset(card, channel)
  File "/usr/lib/python2.7/dist-packages/pyric/pyw.py", line 1364, in chset
    return _nlstub_(chset, card, ch, chw)
  File "/usr/lib/python2.7/dist-packages/pyric/pyw.py", line 2408, in _nlstub_
    return fct(*argv)
  File "/usr/lib/python2.7/dist-packages/pyric/pyw.py", line 1366, in chset
    return freqset(card, channels.ch2rf(ch), chw, nlsock)
  File "/usr/lib/python2.7/dist-packages/pyric/pyw.py", line 1416, in freqset
    raise pyric.error(e.errno, e.strerror)
error: [Errno 95] Operation not supported

[+] Show your support!
[+] Follow us: https://twitter.com/wifiphisher
[+] Like us: https://www.facebook.com/Wifiphisher
[+] Captured credentials:
[!] Closing

The Error message appears as soon as i select a attack template.
 I'm running wifiphisher on a Freshly installed Kali with an raspberry pi 3.
The wifi Adapter i use are two TP-Link TL-WN722N.

**Comment by nik-1207** [comment]
i also have the same problem
