### ISSUE TITLE
How fix this

### ISSUE THREAD

**Issue by C7pH0r** [wifiphisher/wifiphisher#1131]
pi@raspberrypi:~/Desktop/wifiphisher $ sudo wifiphisher
[*] Starting Wifiphisher 1.4GIT ( https://wifiphisher.org ) at 2019-05-13 07:22
[+] Timezone detected. Setting channel range to 1-13
ERROR:root:The following error has occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.4-py2.7.egg/wifiphisher/pywifiphisher.py", line 429, in start
    mon_iface, ap_iface = self.network_manager.get_interface_automatically(
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.4-py2.7.egg/wifiphisher/common/interfaces.py", line 609, in get_interface_automatically
    monitor_interface = self.get_interface(has_monitor_mode=True)
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.4-py2.7.egg/wifiphisher/common/interfaces.py", line 598, in get_interface
    raise InterfaceCantBeFoundError((has_monitor_mode, has_ap_mode))
InterfaceCantBeFoundError: Failed to find an interface with monitor mode
[!] Failed to find an interface with monitor mode
[+] Show your support!
[+] Follow us: https://twitter.com/wifiphisher
[+] Like us: https://www.facebook.com/Wifiphisher
[+] Captured credentials:
[!] Closing

**Comment by anakin1028** [comment]
Hi looks like your adaptor doesn't support Monitor mode.
