### ISSUE TITLE
AttributeError exception in scapy

### ISSUE THREAD

**Issue by physics-sp** [wifiphisher/wifiphisher#1146]
When I run wifiphisher I get an exception,
```
Exception in thread Thread-4:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.4-py2.7.egg/wifiphisher/common/recon.py", line 152, in _sniff_packets
    store=0)
  File "/usr/local/lib/python2.7/dist-packages/scapy-2.4.3rc1-py2.7.egg/scapy/sendrecv.py", line 918, in sniff
    r = prn(p)
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.4-py2.7.egg/wifiphisher/common/recon.py", line 73, in _process_packets
    self._create_ap_with_info(packet)
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.4-py2.7.egg/wifiphisher/common/recon.py", line 131, in _create_ap_with_info
    encryption_type = find_encryption_type(packet)
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.4-py2.7.egg/wifiphisher/common/recon.py", line 279, in find_encryption_type
    and elt_section.info.startswith("\x00P\xf2\x01\x01\x00")):
  File "/usr/local/lib/python2.7/dist-packages/scapy-2.4.3rc1-py2.7.egg/scapy/packet.py", line 327, in __getattr__
    return self.payload.__getattr__(attr)
  File "/usr/local/lib/python2.7/dist-packages/scapy-2.4.3rc1-py2.7.egg/scapy/packet.py", line 325, in __getattr__
    fld, v = self.getfield_and_val(attr)
  File "/usr/local/lib/python2.7/dist-packages/scapy-2.4.3rc1-py2.7.egg/scapy/packet.py", line 1431, in getfield_and_val
    raise AttributeError(attr)
AttributeError: info
```
The error is in the **scapy** library, in the startswith() function. I suggest this small change in the **recon.py** file.
```python
    # extract information from packet
    while (isinstance(elt_section, dot11.Dot11Elt)
           or (not encryption_type and not found_wps)):

        try:
            starts_like_wpa = elt_section.info.startswith("\x00P\xf2\x01\x01\x00")
        except AttributeError:
            starts_like_wpa = False
        try:
            starts_like_wps = elt_section.info.startswith("\x00P\xf2\x04")
        except AttributeError:
            starts_like_wps = False

        # check if encryption type is WPA2
        if elt_section.ID == 48:
            encryption_type = "WPA2"
        # check if encryption type is WPA
        elif (elt_section.ID == 221 and starts_like_wpa):
            encryption_type = "WPA"
        # check if WPS IE exists
        if (elt_section.ID == 221 and starts_like_wps):
            found_wps = True

```
After that it seems to work just fine.

**Comment by sophron** [comment]
Hi, which version of scapy are you using?

**Comment by physics-sp** [comment]
$ pip show scapy
Name: scapy
Version: **2.4.3rc1.dev266**
Summary: Scapy: interactive packet manipulation tool
Home-page: https://scapy.net
Author: Philippe BIONDI
Author-email: phil(at)secdev.org
License: GPLv2
Location: /usr/local/lib/python2.7/dist-packages/scapy-2.4.3rc1.dev266-py2.7.egg
Requires: 
Required-by: wifiphisher

**Comment by sophron** [comment]
Thanks for reporting. This should be fixed now.
