### ISSUE TITLE
MemoryError

### ISSUE THREAD

**Issue by Lucraft03** [wifiphisher/wifiphisher#1149]
I'm using Kali Linux on my Android and when I'm executing wifiphisher I have this error:

`Traceback (most recent call last):
  File "/usr/bin/wifiphisher", line 11, in <module>
    load_entry_point('wifiphisher==1.4', 'console_scripts', 'wifiphisher')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2793, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2411, in load
    return self.resolve()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2417, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python2.7/dist-packages/wifiphisher/pywifiphisher.py", line 20, in <module>
    import wifiphisher.common.extensions as extensions
  File "/usr/lib/python2.7/dist-packages/wifiphisher/common/extensions.py", line 11, in <module>
    import scapy.layers.dot11 as dot11
  File "/usr/lib/python2.7/dist-packages/scapy/layers/dot11.py", line 19, in <module>
    from scapy.ansmachine import *
  File "/usr/lib/python2.7/dist-packages/scapy/ansmachine.py", line 16, in <module>
    from scapy.sendrecv import send,sendp,sniff
  File "/usr/lib/python2.7/dist-packages/scapy/sendrecv.py", line 32, in <module>
    import scapy.route
  File "/usr/lib/python2.7/dist-packages/scapy/route.py", line 191, in <module>
    conf.route=Route()
  File "/usr/lib/python2.7/dist-packages/scapy/route.py", line 27, in __init__
    self.resync()
  File "/usr/lib/python2.7/dist-packages/scapy/route.py", line 34, in resync
    from scapy.arch import read_routes
  File "/usr/lib/python2.7/dist-packages/scapy/arch/__init__.py", line 25, in <module>
    from scapy.arch.bpf.core import get_if_raw_addr
  File "/usr/lib/python2.7/dist-packages/scapy/arch/bpf/core.py", line 11, in <module>
    from scapy.arch.common import get_if, get_bpf_pointer
  File "/usr/lib/python2.7/dist-packages/scapy/arch/common.py", line 12, in <module>
    import os, struct, ctypes
  File "/usr/lib/python2.7/ctypes/__init__.py", line 556, in <module>
    _reset_cache()
  File "/usr/lib/python2.7/ctypes/__init__.py", line 276, in _reset_cache
    CFUNCTYPE(c_int)(lambda: None)
MemoryError`

**Comment by sophron** [comment]
Hello, 

We don't support Android and it's not in our current plans.
