### ISSUE TITLE
Just read

### ISSUE THREAD

**Issue by bog244** [wifiphisher/wifiphisher#1152]
root@kali:~# wifiphisher
[*] Starting Wifiphisher 1.4GIT ( https://wifiphisher.org ) at 2019-07-20 16:00
[+] Timezone detected. Setting channel range to 1-13
Traceback (most recent call last):
  File "/usr/local/bin/wifiphisher", line 11, in <module>
    load_entry_point('wifiphisher==1.4', 'console_scripts', 'wifiphisher')()
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.4-py2.7.egg/wifiphisher/pywifiphisher.py", line 693, in run
    engine.start()
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.4-py2.7.egg/wifiphisher/pywifiphisher.py", line 390, in start
    self.opmode.initialize(args)
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.4-py2.7.egg/wifiphisher/common/opmode.py", line 53, in initialize
    interfaces.is_add_vif_required(args)
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.4-py2.7.egg/wifiphisher/common/interfaces.py", line 798, in is_add_vif_required
    card = pyw.getcard(vif)
  File "/usr/local/lib/python2.7/dist-packages/PyRIC-0.1.6.3-py2.7.egg/pyric/pyw.py", line 269, in getcard
    if nlsock is None: return _nlstub_(getcard, dev)
  File "/usr/local/lib/python2.7/dist-packages/PyRIC-0.1.6.3-py2.7.egg/pyric/pyw.py", line 2236, in _nlstub_
    return fct(*argv)
  File "/usr/local/lib/python2.7/dist-packages/PyRIC-0.1.6.3-py2.7.egg/pyric/pyw.py", line 270, in getcard
    return devinfo(dev, nlsock)['card']
  File "/usr/local/lib/python2.7/dist-packages/PyRIC-0.1.6.3-py2.7.egg/pyric/pyw.py", line 1049, in devinfo
    raise pyric.error(pyric.EPROTONOSUPPORT, "Device does not support nl80211")
pyric.error: [Errno 93] Device does not support nl80211

do not answer that this is not a bug is a feature

I have 2 adapters that support monitor mode and AP,
but when I enter a command with arguments, the result does not change ..

**Comment by sophron** [comment]
#1027

**Comment by bog244** [comment]
No)
You can easily fix it, just using another driver for Wi-Fi card, just take the name of the Wi-Fi chip using command:
airmon-ng

- Your very stupid ( -_-)

**Comment by sophron** [comment]
I love you. <3

**Comment by goccikcan** [comment]
And then what should we do next ? I have the chip's name, how can I configure this ?
