### ISSUE TITLE
HandShake Verification not working - AttributeError 'rdpcap'

### ISSUE THREAD

**Issue by rubenkr** [wifiphisher/wifiphisher#1158]
**Version**: Wifiphisher 1.4GIT

**Description**: When running wifiphisher on Archlinux 5.2.4-arch1-1-ARCH on the evil-twin attack everything works smoothly. But when I add the command for verifying handshake capture (-hC) it throws the following error. Can someone please let me know what is missing in rdcap? Thank you very much !

**Script output**: ➜  firmware-upgrade git:(master) ✗ sudo wifiphisher -eI wlp0s29f7u2 -aI wlp0s29f7u1 -cM  -e test123  --logging -lP /home/meee/Desktop/wifiphisher.log -cP /home/meee/Desktop/credentials.log  -hC /home/meee/test123.pcap   

[*] Starting Wifiphisher 1.4GIT ( https://wifiphisher.org ) at 2019-08-02 20:51
[+] Timezone detected. Setting channel range to 1-13
Traceback (most recent call last):
  File "/usr/bin/wifiphisher", line 11, in <module>
    load_entry_point('wifiphisher==1.4', 'console_scripts', 'wifiphisher')()
  File "/usr/lib/python2.7/site-packages/wifiphisher/pywifiphisher.py", line 693, in run
    engine.start()
  File "/usr/lib/python2.7/site-packages/wifiphisher/pywifiphisher.py", line 390, in start
    self.opmode.initialize(args)
  File "/usr/lib/python2.7/site-packages/wifiphisher/common/opmode.py", line 54, in initialize
    self._check_args(args)
  File "/usr/lib/python2.7/site-packages/wifiphisher/common/opmode.py", line 79, in _check_args
    is_valid_handshake_capture(args.handshake_capture):
  File "/usr/lib/python2.7/site-packages/wifiphisher/extensions/handshakeverify.py", line 42, in is_valid_handshake_capture
    pkts = dot11.rdpcap(handshake_path)
AttributeError: 'module' object has no attribute 'rdpcap'

**Comment by SipriusPT** [comment]
Same here, under kali 4.18.0-kali2-amd64. Also I am using a convertion of a *.cap file to *.pcap that I have made using:

`editcap -F pcap input.cap output.pcap`

This is the command used:

`wifiphisher -i wlan0 -nD --logging -hC /root/Documents/fluxion/attacks/Handshake\ Snooper/handshakes/output.pcap`

**Comment by pavonis9** [comment]
Duplicate of #1159

**Comment by pavonis9** [comment]
**I solved the issue.**
Refer to #1159 for solution.
