### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by Platinmaracuja** [wifiphisher/wifiphisher#1167]
hi 
Im from germany so my English is shit ...
i use my own phishing page so maybe my problem comes from there.
everything works perfekt until the moment when the victim connects then this massage :

`Captured credentials:
ERROR:tornado.application:/usr/local/lib/python2.7/dist-packages/wifiphisher-1.4-py2.7.egg/wifiphisher/data/phishing-pages/oauth-login/html/index.html code:
 1  def _tt_execute():  # /usr/local/lib/python2.7/dist-packages/wifiphisher-1.4-py2.7.egg/wifiphisher/data/phishing-pages/oauth-login/html/index.html:0
 2      _tt_buffer = []  # /usr/local/lib/python2.7/dist-packages/wifiphisher-1.4-py2.7.egg/wifiphisher/data/phishing-pages/oauth-login/html/index.html:0
 3      _tt_append = _tt_buffer.append  # /usr/local/lib/python2.7/dist-packages/wifiphisher-1.4-py2.7.egg/wifiphisher/data/phishing-pages/oauth-login/html/index.html:0
 4      _tt_append('\n<!DOCTYPE html>\n<html>\n<head>\n<body rel=color:#ccc;font-family:calibri;>\n<meta charset="UTF-8">\n<img src="file:///root/Downloads/free-wifi-berlin-audible-mediaworx1.jpg" width="100%">\n<title> ')  # /usr/local/lib/python2.7/dist-packages/wifiphisher-1.4-py2.7.egg/wifiphisher/data/phishing-pages/oauth-login/html/index.html:16
 5      _tt_tmp = Free WiFi Berlin  # /usr/local/lib/python2.7/dist-packages/wifiphisher-1.4-py2.7.egg/wifiphisher/data/phishing-pages/oauth-login/html/index.html:16
 6      if isinstance(_tt_tmp, _tt_string_types): _tt_tmp = _tt_utf8(_tt_tmp)  # /usr/local/lib/python2.7/dist-packages/wifiphisher-1.4-py2.7.egg/wifiphisher/data/phishing-pages/oauth-login/html/index.html:16
 7      else: _tt_tmp = _tt_utf8(str(_tt_tmp))  # /usr/local/lib/python2.7/dist-packages/wifiphisher-1.4-py2.7.egg/wifiphisher/data/phishing-pages/oauth-login/html/index.html:16
 8      _tt_tmp = _tt_utf8(xhtml_escape(_tt_tmp))  # /usr/local/lib/python2.7/dist-packages/wifiphisher-1.4-py2.7.egg/wifiphisher/data/phishing-pages/oauth-login/html/index.html:16
 9      _tt_append(_tt_tmp)  # /usr/local/lib/python2.7/dist-packages/wifiphisher-1.4-py2.7.egg/wifiphisher/data/phishing-pages/oauth-login/html/index.html:16
10      _tt_append(' Wi-Fi Service </title>\n<link rel="stylesheet" href="/static/css/reset.css">\n<link rel=\'stylesheet prefetch\' href=\'/static/css/roboto.css\'>\n<link rel=\'stylesheet prefetch\' href=\'/static/css/font-awesome.min.css\'>\n<link rel="stylesheet" href="/static/css/style.css">\n<script src=\'/static/js/jquery.min.js\'></script>\n<script src="/static/js/index.js"></script>\n</head>\n<body>\n\n\n\n\n<div class="pen-title">\n<h1>Get connected to the Internet for free</h1><span></span>\n</div>\n\n<div class="module form-module">\n<div class="form">\n</div>\n<div class="form">\nLogin using <br/> <img src="file:///root/Downloads/facebook-logo.png" width="7%">\n\n<form name="theform" class="theform" method="post" action="oauth.html">\n<input style="BACKGROUND-COLOR: #ffffff;" type="email" placeholder="Email or Phone" name="wfphshr-email" required />\n<input style="BACKGROUND-COLOR: #ffffff;" type="password" placeholder="Password" minlength="5" name="wfphshr-password" required />\n<button style="BACKGROUND-COLOR: #3b5998; class="login-btn"> <font color= #ffffff>Log In</font></button>\n</form>\n<br/>\n<br/>\n<br/>\n<br/>\n<br/>\n<div class="cta"><a id="btn1"><font size="2">Terms of Usage</font></a></div>\n</div>\n\n<div id="myModal" class="modal">\n\n<div class="modal-content">\n<div class="modal-header">\n<span class="close">\xc3\x97</span>\n</div>\n<div class="modal-body"> <font size="0">\n<p>This is a Free WiFi Berlin wireless internet Service ("the Service") provided for use by\ncustomers. All users are required to log-in individually as an independent user.</p>\n<p>\nThe Service is made available provided:\n</p>\n<p>\n(a) You do not use the Service for anything unlawful, immoral or improper;\n</p>\n<p>\n(b) You do not use the Service to make offensive or nuisance communications in whatever form. Such usage\nincludes posting, transmitting, uploading, downloading or otherwise facilitating any content that is\nunlawful, defamatory, threatening, a nuisance, obscene, hateful, abusive, harmful (including but not limited\nto viruses, corrupted files, or any other similar software or programs), a breach of privacy, or which is\notherwise objectionable;\n</p>\n<p>\n(c) You do not use the Service to harm or attempt to harm minors in any way;\n</p>\n<p>\n(d) You do not act nor knowingly permit others to act in such a way that the operation of the Service or our\nsystems will be jeopardized or impaired;\n</p>\n<p>\n(e) You do not use abusive or threatening behavior towards other users of the Service, members of our staff\nor any person in the vicinity of a Wireless LAN Hotspot;\n</p>\n<p>\n(f) You do not use the Service to access or use content in a way that infringes the rights of others;\n</p>\n<p>\n(g) The Service is used in accordance with any third party policies for acceptable use or any relevant\ninternet standards (where applicable).\n</p>\n<p>\n(h) You agree not to resell or re-broadcast any aspect of the Service, whether for profit or otherwise. You\naccept that your entitlement to use the Service is for your personal use only and that you shall not be\nentitled to transfer your entitlement to use the Service to any other person or allow any other person to\nmake use of the Service or of any username or password or other entitlement supplied to you in connection\nwith the Service.\n</p>\n<p>\n(i) You also agree not to modify the Unit or use the Service for any fraudulent purpose, or in such a way as\nto create damage or risk to our business, reputation, employees, subscribers, facilities, third parties or to\nthe public generally.\n</p>\n<p>\n(j) You have no proprietary or ownership rights to any username or password or to a specific IP address, or\ne-mail address assigned to you or your Unit. We may change such addresses at any time or deactivate or\nsuspend Service to any address without prior notice to you if we suspect any unlawful or fraudulent use of\nthe services.</fonts>\n</p>\n</div>\n</div>\n</body>\n</html>\n')  # /usr/local/lib/python2.7/dist-packages/wifiphisher-1.4-py2.7.egg/wifiphisher/data/phishing-pages/oauth-login/html/index.html:120
11      return _tt_utf8('').join(_tt_buffer)  # /usr/local/lib/python2.7/dist-packages/wifiphisher-1.4-py2.7.egg/wifiphisher/data/phishing-pages/oauth-login/html/index.html:0
ERROR:tornado.application:Uncaught exception GET / (10.0.0.94)
HTTPServerRequest(protocol='http', host='www.wikipedia.org', method='GET', uri='/', version='HTTP/1.1', remote_ip='10.0.0.94', headers={'Accept-Language': 'en-GB,en;q=0.8,en-US;q=0.6,en;q=0.4', 'Accept-Encoding': 'gzip,deflate,sdch', 'Connection': 'close', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8', 'User-Agent': 'Dalvik/2.1.0 (Linux; U; Android 7.0; SAMSUNG-SM-G891A Build/NRD90M)', 'Host': 'www.wikipedia.org'})
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 1510, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.4-py2.7.egg/wifiphisher/common/phishinghttp.py", line 96, in get
    self.render(file_path, **template.get_context())
  File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 724, in render
    html = self.render_string(template_name, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 862, in render_string
    t = loader.load(template_name)
  File "/usr/local/lib/python2.7/dist-packages/tornado/template.py", line 427, in load
    self.templates[name] = self._create_template(name)
  File "/usr/local/lib/python2.7/dist-packages/tornado/template.py", line 455, in _create_template
    template = Template(f.read(), name=name, loader=self)
  File "/usr/local/lib/python2.7/dist-packages/tornado/template.py", line 317, in __init__
    "exec", dont_inherit=True)
  File "/usr/local/lib/python2_7/dist-packages/wifiphisher-1_4-py2_7_egg/wifiphisher/data/phishing-pages/oauth-login/html/index_html.generated.py", line 5
    _tt_tmp = Free WiFi Berlin  # /usr/local/lib/python2.7/dist-packages/wifiphisher-1.4-py2.7.egg/wifiphisher/data/phishing-pages/oauth-login/html/index.html:16
                      ^
SyntaxError: invalid syntax
[!] Closing`

is in the console and i do not see anything... but i dont know why 
I hope its a bit understandable 
and i hope you can help me

**Comment by pavonis9** [comment]
@Platinmaracuja It's just a problem of Tornado extension.

Add with your command `--logging` option and everything should be fine.

**Comment by sophron** [comment]
Are you sure you used the correct syntax and placeholders? Can you share your phishing page with us?
