### ISSUE TITLE
Errno 16 Device or resource busy

### ISSUE THREAD

**Issue by mstyp** [wifiphisher/wifiphisher#1181]
Running kali on a raspberry pi 4. 
Installation seemed to work, but when I try to run I get error 16. 

I tried running airmon-ng check kill, but no dice. 

I tried forcing wlan0 to run as the rogue AP and wlan0m to run the the deauth attack but also no dice. 

Tried restarting the pi a couple of times but problem persists. 

What do I try next? 

root@kali:~# wifiphisher
[*] Starting Wifiphisher 1.4GIT ( https://wifiphisher.org ) at 2019-09-14 06:03
[+] Timezone detected. Setting channel range to 1-13
[+] Selecting wlan0 interface for the deauthentication attack
[+] Selecting wlan0mon interface for creating the rogue Access Point
Traceback (most recent call last):
  File "/usr/local/bin/wifiphisher", line 11, in <module>
    load_entry_point('wifiphisher==1.4', 'console_scripts', 'wifiphisher')()
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.4-py2.7.egg/wifiphisher/pywifiphisher.py", line 693, in run
    engine.start()
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.4-py2.7.egg/wifiphisher/pywifiphisher.py", line 459, in start
    args.mac_ap_interface)
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.4-py2.7.egg/wifiphisher/common/interfaces.py", line 496, in set_interface_mac
    self.set_interface_mode(interface_name, "managed")
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.4-py2.7.egg/wifiphisher/common/interfaces.py", line 541, in set_interface_mode
    pyw.modeset(card, mode)
  File "/usr/lib/python2.7/dist-packages/pyric/pyw.py", line 1460, in modeset
    return _nlstub_(modeset, card, mode, flags)
  File "/usr/lib/python2.7/dist-packages/pyric/pyw.py", line 2408, in _nlstub_
    return fct(*argv)
  File "/usr/lib/python2.7/dist-packages/pyric/pyw.py", line 1477, in modeset
    raise pyric.error(e.errno, e.strerror)
pyric.error: [Errno 16] Device or resource busy

**Comment by N2Network** [comment]
For testing have you tried disabling the onboard wlan0 and using an add on adapter. I'm not suggesting it as a long term fix but perhaps it would isolate the adapter as the cause.

**Comment by mstyp** [comment]
> For testing have you tried disabling the onboard wlan0 and using an add on adapter. I'm not suggesting it as a long term fix but perhaps it would isolate the adapter as the cause.

I would like to but I dont own an external wifi adapter, and I am not going to be in a position to get one for several weeks.

**Comment by sophron** [comment]
Have a look at #354.

**Comment by mstyp** [comment]
> Have a look at #354.

I did. I ran airmon-ng check kill as reccomended in both #354 and the more recent #1109 but I am still getting the same error.

**Comment by haroonalhadisk** [comment]
@mstyp I had the same issue. dont know why but these steps actully helped
create a file named startupap.sh add the following lines

service apache2 start
sleep 1
ifconfig wlan0 down
macchanger -A wlan0
ifconfig wlan0 up
sleep 1
hostapd -B /etc/hostapd/hostapd.conf
sleep 2
ifconfig br0 up
ifconfig br0 10.1.1.1 netmask 255.255.255.0
sysctl net.ipv4.ip_forward=1
iptables --flush
iptables -t nat --flush
iptables -t nat -A PREROUTING -i br0 -p udp -m udp --dport 53 -j DNAT --to-destination 10.1.1.1:53
iptables -t nat -A PREROUTING -i br0 -p tcp -m tcp --dport 80 -j DNAT --to-destination 10.1.1.1:80
iptables -t nat -A PREROUTING -i br0 -p tcp -m tcp --dport 443 -j DNAT --to-destination 10.1.1.1:80
iptables -t nat -A POSTROUTING -j MASQUERADE
service dnsmasq start
exit 0

#------------------------------------------------------------------------------------

move the file to root directory
type command  crontab -e
add lines into the file @reboot     sudo sleep 15 && sudo sh /root/startap.sh &
paste the same line 3-4 times and try rebooting. hope this helps

**Comment by Joerny** [comment]
> @mstyp I had the same issue. dont know why but these steps actully helped
> create a file named startupap.sh add the following lines
> 
> service apache2 start
> sleep 1
> ifconfig wlan0 down
> macchanger -A wlan0
> ifconfig wlan0 up
> sleep 1
> hostapd -B /etc/hostapd/hostapd.conf
> sleep 2
> ifconfig br0 up
> ifconfig br0 10.1.1.1 netmask 255.255.255.0
> sysctl net.ipv4.ip_forward=1
> iptables --flush
> iptables -t nat --flush
> iptables -t nat -A PREROUTING -i br0 -p udp -m udp --dport 53 -j DNAT --to-destination 10.1.1.1:53
> iptables -t nat -A PREROUTING -i br0 -p tcp -m tcp --dport 80 -j DNAT --to-destination 10.1.1.1:80
> iptables -t nat -A PREROUTING -i br0 -p tcp -m tcp --dport 443 -j DNAT --to-destination 10.1.1.1:80
> iptables -t nat -A POSTROUTING -j MASQUERADE
> service dnsmasq start
> exit 0
> 
> #------------------------------------------------------------------------------------
> 
> move the file to root directory
> type command crontab -e
> add lines into the file "@reboot sudo sleep 15 && sudo sh /root/startap.sh &"
> paste the same line 3-4 times and try rebooting. hope this helps

@haroonalhadisk What is the content of the /etc/hostapd/hostapd.conf? How is br0 configured?

**Comment by Joerny** [comment]
> > Have a look at #354.
> 
> I did. I ran airmon-ng check kill as reccomended in both #354 and the more recent #1109 but I am still getting the same error.

I managed to start wifiphisher on a raspberry pi. It seems that it do not like the changing of the MAC address. If I start it with `wifiphisher -iNM`, it starts and shows the list of networks as expected.

**Comment by Soutcast** [comment]
I am experiencing the same error on raspberry pi 4 running latest version of kali. I tried:
> I did. I ran airmon-ng check kill as reccomended in both #354 and the more recent #1109 but I am still getting the same error.
and
`wifiphisher -iNM`
but I still get the same error
`pyric.error: [Errno 16] Device or resource busy`

**Comment by yilianziyu** [comment]
I've got the same error!I ran `wifiphisher` on kali2020 pi 3B,and it showed like this:

> [*] Starting Wifiphisher 1.4GIT ( https://wifiphisher.org ) at 2020-05-09 02:01
> [+] Timezone detected. Setting channel range to 1-13
> [+] Selecting mon1 interface for the deauthentication attack
> [+] Selecting wlan0 interface for creating the rogue Access Point
> [+] Changing wlan0 MAC addr (BSSID) to 00:00:00:32:77:c5
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.8/dist-packages/PyRIC-0.1.6.4-py3.8.egg/pyric/pyw.py", line 1378, in modeset
>     _ = nl.nl_recvmsg(nlsock)
>   File "/usr/local/lib/python3.8/dist-packages/PyRIC-0.1.6.4-py3.8.egg/pyric/lib/libnl.py", line 244, in nl_recvmsg
>     msg = nlmsg_fromstream(sock.recv())
>   File "/usr/local/lib/python3.8/dist-packages/PyRIC-0.1.6.4-py3.8.egg/pyric/lib/libnl.py", line 444, in nlmsg_fromstream
>     raise error(abs(e),strerror(abs(e)))
> libnl.error: [Errno 16] Device or resource busy
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/usr/local/bin/wifiphisher", line 11, in <module>
>     load_entry_point('wifiphisher==1.4', 'console_scripts', 'wifiphisher')()
>   File "/usr/local/lib/python3.8/dist-packages/wifiphisher-1.4-py3.8.egg/wifiphisher/pywifiphisher.py", line 719, in run
>     engine.start()
>   File "/usr/local/lib/python3.8/dist-packages/wifiphisher-1.4-py3.8.egg/wifiphisher/pywifiphisher.py", line 482, in start
>     new_mac = self.network_manager.set_interface_mac(mon_iface,
>   File "/usr/local/lib/python3.8/dist-packages/wifiphisher-1.4-py3.8.egg/wifiphisher/common/interfaces.py", line 513, in set_interface_mac
>     self.set_interface_mode(interface_name, "managed")
>   File "/usr/local/lib/python3.8/dist-packages/wifiphisher-1.4-py3.8.egg/wifiphisher/common/interfaces.py", line 558, in set_interface_mode
>     pyw.modeset(card, mode)
>   File "/usr/local/lib/python3.8/dist-packages/PyRIC-0.1.6.4-py3.8.egg/pyric/pyw.py", line 1365, in modeset
>     if nlsock is None: return _nlstub_(modeset, card, mode, flags)
>   File "/usr/local/lib/python3.8/dist-packages/PyRIC-0.1.6.4-py3.8.egg/pyric/pyw.py", line 2279, in _nlstub_
>     return fct(*argv)
>   File "/usr/local/lib/python3.8/dist-packages/PyRIC-0.1.6.4-py3.8.egg/pyric/pyw.py", line 1382, in modeset
>     raise pyric.error(e.errno, e.strerror)
> pyric.error: [Errno 16] Device or resource busy


I ran` iwconfig ` ,and it showed like this:

> iwconfig
> wlan0     IEEE 802.11  ESSID:off/any
>           Mode:Managed  Access Point: Not-Associated
>           Retry short limit:7   RTS thr:off   Fragment thr:off
>           Encryption key:off
>           Power Management:off
> 
> eth0      no wireless extensions.
> 
> mon1      IEEE 802.11  Mode:Monitor  Frequency:2.457 GHz
>           Retry short limit:7   RTS thr:off   Fragment thr:off
>           Power Management:on
> 
> lo        no wireless extensions.
> 

By the way,mon1 is a usb-device,and wlan0 is on-board.I've ran` wifiphisher ` successfully twice,and it was working well,but now,I can't make it all right.Is it caused by some kind of wireless setting?

**Comment by blackjackgg** [comment]
use this you can get a fake ap
sudo  wifiphisher -aI wlan0  -nE  --essid "free wifi" -p oauth-login

**Comment by Zaraaashiigal** [comment]
You should give it up. xD They're just too lazy to work on this anymore and blame the clients instead of their own code!
