### ISSUE TITLE
wifiphisher error

### ISSUE THREAD

**Issue by popadrop** [wifiphisher/wifiphisher#1182]
Traceback (most recent call last):
  File "/usr/bin/wifiphisher", line 11, in <module>
    load_entry_point('wifiphisher==1.4', 'console_scripts', 'wifiphisher')()
  File "/usr/lib/python2.7/dist-packages/wifiphisher/pywifiphisher.py", line 630, in run
    engine.start()
  File "/usr/lib/python2.7/dist-packages/wifiphisher/pywifiphisher.py", line 457, in start
    self.stop()
  File "/usr/lib/python2.7/dist-packages/wifiphisher/pywifiphisher.py", line 262, in stop
    self.network_manager.on_exit()
  File "/usr/lib/python2.7/dist-packages/wifiphisher/common/interfaces.py", line 735, in on_exit
    self.set_interface_mac(interface, mac_address)
  File "/usr/lib/python2.7/dist-packages/wifiphisher/common/interfaces.py", line 496, in set_interface_mac
    raise InvalidMacAddressError(mac_address)
wifiphisher.common.interfaces.InvalidMacAddressError: The provided MAC address 00:c0:ca:5a:2c:66 is invalid

iwconfig output
eth0      no wireless extensions.

lo        no wireless extensions.

wlan0     IEEE 802.11  ESSID:off/any  
          Mode:Managed  Access Point: Not-Associated   Tx-Power=30 dBm   
          Retry short limit:7   RTS thr:off   Fragment thr:off
          Encryption key:off
          Power Management:off

**Comment by popadrop** [comment]
looked for days for an answer sure as hell didnt find it here!!!
https://www.youtube.com/watch?v=WZQpXzJEG8A
Installed missing files as discribe in the above video ..error gone
