### ISSUE TITLE
Can I set the adapter that makes the fake AP to a different one

### ISSUE THREAD

**Issue by dolanbright** [wifiphisher/wifiphisher#1194]
Hi so im kinda new here. I want to use wifiphisher but with 3 wifi adapters. So I have my wlan0 wlan1 wlan2 - 
wlan0 - built-in adapter (not very long range)
wlan1 - Alfa AWUS036NH
wlan2 - Some other long range adapter that CAN'T be put in monitor mode or packet injection

---
So my question is can i make it so wlan1 does the deauthing and wlan2 creates the fake ap so it has longer range?

**Comment by Amurmurmur** [comment]
@dolanbright Of course you can
```
wifiphisher -aI wlan2 -jI wlan1 -p firmware-upgrade --handshake-capture handshake.pcap
```

**Comment by kubiGamer6000** [comment]
> @dolanbright Of course you can
> 
> ```
> wifiphisher -aI wlan2 -jI wlan1 -p firmware-upgrade --handshake-capture handshake.pcap
> ```

Thanks (it's me dolanbright on another profile)! Will try it

**Comment by Amurmurmur** [comment]
@kubiGamer6000 @dolanbright You might not need `--handshake-capture handshake.pcap` if you dont want to grab handshakes

**Comment by dolanbright** [comment]
@Amurmurmur 

Hi! It's me dolan. I found time to try it but I get an error : 

`Traceback (most recent call last):
  File "/usr/local/bin/wifiphisher", line 11, in <module>
    load_entry_point('wifiphisher==1.4', 'console_scripts', 'wifiphisher')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2852, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2443, in load
    return self.resolve()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.4-py2.7.egg/wifiphisher/pywifiphisher.py", line 206, in <module>
    args = parse_args()
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.4-py2.7.egg/wifiphisher/pywifiphisher.py", line 202, in parse_args
    return parser.parse_args()
  File "/usr/lib/python2.7/argparse.py", line 1705, in parse_args
    args, argv = self.parse_known_args(args, namespace)
  File "/usr/lib/python2.7/argparse.py", line 1737, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/usr/lib/python2.7/argparse.py", line 1943, in _parse_known_args
    start_index = consume_optional(start_index)
  File "/usr/lib/python2.7/argparse.py", line 1883, in consume_optional
    take_action(action, args, option_string)
  File "/usr/lib/python2.7/argparse.py", line 1795, in take_action
    argument_values = self._get_values(action, argument_strings)
  File "/usr/lib/python2.7/argparse.py", line 2235, in _get_values
    value = self._get_value(action, arg_string)
  File "/usr/lib/python2.7/argparse.py", line 2264, in _get_value
    result = type_func(arg_string)
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.4-py2.7.egg/wifiphisher/common/opmode.py", line 307, in validate_ap_interface
    interfaces.does_have_mode(interface, "AP")):
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.4-py2.7.egg/wifiphisher/common/interfaces.py", line 950, in does_have_mode
    card = pyric.pyw.getcard(interface)
  File "/usr/local/lib/python2.7/dist-packages/PyRIC-0.1.6.3-py2.7.egg/pyric/pyw.py", line 269, in getcard
    if nlsock is None: return _nlstub_(getcard, dev)
  File "/usr/local/lib/python2.7/dist-packages/PyRIC-0.1.6.3-py2.7.egg/pyric/pyw.py", line 2236, in _nlstub_
    return fct(*argv)
  File "/usr/local/lib/python2.7/dist-packages/PyRIC-0.1.6.3-py2.7.egg/pyric/pyw.py", line 270, in getcard
    return devinfo(dev, nlsock)['card']
  File "/usr/local/lib/python2.7/dist-packages/PyRIC-0.1.6.3-py2.7.egg/pyric/pyw.py", line 1049, in devinfo
    raise pyric.error(pyric.EPROTONOSUPPORT, "Device does not support nl80211")
pyric.error: [Errno 93] Device does not support nl80211`

i used the command `wifiphisher -aI wlan2 -jI wlan1 -p firmware-upgrade` with:

wlan1 - Alfa AWUS036NH

wlan2 - TP-Link TL-WN722N v3 (no monitor mode or packet  injection)

I think wlan2 should be able to make an AP but correct me if im wrong.

Anaways im stuck here. Any help?

**Comment by Amurmurmur** [comment]
@dolanbright I think this issue is relevant https://github.com/wifiphisher/wifiphisher/issues/1027

**Comment by Amurmurmur** [comment]
https://github.com/wifiphisher/wifiphisher/issues/1133
And this one
