### ISSUE TITLE
wifiphisher can't start

### ISSUE THREAD

**Issue by mainmaintai** [wifiphisher/wifiphisher#1204]
root@SILVE:~/wifiphisher# wifiphisher
[*] Starting Wifiphisher 1.4GIT ( https://wifiphisher.org ) at 2019-11-09 23:28
[+] Timezone detected. Setting channel range to 1-13
Traceback (most recent call last):
  File "/usr/local/bin/wifiphisher", line 11, in <module>
    load_entry_point('wifiphisher==1.4', 'console_scripts', 'wifiphisher')()
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.4-py2.7.egg/wifiphisher/pywifiphisher.py", line 694, in run
    engine.start()
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.4-py2.7.egg/wifiphisher/pywifiphisher.py", line 391, in start
    self.opmode.initialize(args)
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.4-py2.7.egg/wifiphisher/common/opmode.py", line 53, in initialize
    interfaces.is_add_vif_required(args)
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.4-py2.7.egg/wifiphisher/common/interfaces.py", line 794, in is_add_vif_required
    for vif in [vif for vif in pyw.interfaces() if pyw.iswireless(vif)]:
  File "/usr/lib/python2.7/dist-packages/pyric/pyw.py", line 159, in iswireless
    return _iostub_(iswireless, dev)
  File "/usr/lib/python2.7/dist-packages/pyric/pyw.py", line 2391, in _iostub_
    return fct(*argv)
  File "/usr/lib/python2.7/dist-packages/pyric/pyw.py", line 170, in iswireless
    else: raise pyric.error(e.errno)
pyric.error: [Errno 22] Invalid parameter

**Comment by buttmuhammadkashif** [comment]
[*] Starting Wifiphisher 1.4GIT ( https://wifiphisher.org ) at 2019-12-02 17:58
[+] Timezone detected. Setting channel range to 1-13
ERROR:root:The following error has occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.4-py2.7.egg/wifiphisher/pywifiphisher.py", line 432, in start
    mon_iface, ap_iface = self.network_manager.get_interface_automatically(
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.4-py2.7.egg/wifiphisher/common/interfaces.py", line 609, in get_interface_automatically
    ap_interface = self.get_interface(has_ap_mode=True)
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.4-py2.7.egg/wifiphisher/common/interfaces.py", line 597, in get_interface
    raise InterfaceCantBeFoundError((has_monitor_mode, has_ap_mode))
InterfaceCantBeFoundError: Failed to find an interface with AP mode
[!] Failed to find an interface with AP mode
[+] Show your support!
[+] Follow us: https://twitter.com/wifiphisher
[+] Like us: https://www.facebook.com/Wifiphisher
[+] Captured credentials:
[!] Closing
