### ISSUE TITLE
roguehostapd not found

### ISSUE THREAD

**Issue by sh1va73** [wifiphisher/wifiphisher#1208]
I followed the instructions for install but when start wifiphisher I get an error:
module not found: no module named roguehostapd. I did install roguehostapd , its on the system so I don't know why this error. I am on Ubuntu.

**Comment by sophron** [comment]
Do you have the output of the installation? There's a chance that `roguehostapd` was not installed properly.

You can go ahead and install it manually: https://github.com/wifiphisher/roguehostapd

**Comment by sh1va73** [comment]
Thanks for the feedback. I did install but the problem is still there. Roguehostapd is installed but I get an error the module is not found.
The problem is only on Ubuntu 18.0.4, on Kali 2019.4 it is working perfectly.

**Comment by sh1va73** [comment]
this is the output:

Traceback (most recent call last):
  File "/usr/local/bin/wifiphisher", line 11, in <module>
    load_entry_point('wifiphisher==1.4', 'console_scripts', 'wifiphisher')()
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 2852, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 2443, in load
    return self.resolve()
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python3.6/dist-packages/wifiphisher-1.4-py3.6.egg/wifiphisher/pywifiphisher.py", line 22, in <module>
    import wifiphisher.common.accesspoint as accesspoint
  File "/usr/local/lib/python3.6/dist-packages/wifiphisher-1.4-py3.6.egg/wifiphisher/common/accesspoint.py", line 12, in <module>
    import roguehostapd.apctrl as apctrl
ModuleNotFoundError: No module named 'roguehostapd'

**Comment by sophron** [comment]
This is because you are using Python3. Use Python2.7 instead.

**Comment by sh1va73** [comment]
Yes it's working now. Thanks.

**Comment by user8432** [comment]
Traceback (most recent call last):
  File "/home/kali/wifiphisher/bin/wifiphisher", line 15, in <module>
    from wifiphisher.pywifiphisher import run
  File "/usr/local/lib/python3.11/dist-packages/wifiphisher-1.4-py3.11.egg/wifiphisher/pywifiphisher.py", line 24, in <module>
    import wifiphisher.common.accesspoint as accesspoint
  File "/usr/local/lib/python3.11/dist-packages/wifiphisher-1.4-py3.11.egg/wifiphisher/common/accesspoint.py", line 11, in <module>
    import roguehostapd.apctrl as apctrl
ModuleNotFoundError: No module named 'roguehostapd'

**Comment by user8432** [comment]
plz help me
