### ISSUE TITLE
Unable to start on fresh install of kali

### ISSUE THREAD

**Issue by dessyc** [wifiphisher/wifiphisher#1213]
Hi
I try to start wifiphiser but i have some problem with understand what wrong... 
`# wifiphisher 
[*] Starting Wifiphisher 1.4GIT ( https://wifiphisher.org ) at 2019-11-18 00:00
[+] Timezone detected. Setting channel range to 1-13
Traceback (most recent call last):
  File "/usr/local/bin/wifiphisher", line 11, in <module>
    load_entry_point('wifiphisher==1.4', 'console_scripts', 'wifiphisher')()
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.4-py2.7.egg/wifiphisher/pywifiphisher.py", line 696, in run
    engine.start()
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.4-py2.7.egg/wifiphisher/pywifiphisher.py", line 393, in start
    self.opmode.initialize(args)
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.4-py2.7.egg/wifiphisher/common/opmode.py", line 54, in initialize
    interfaces.is_add_vif_required(args)
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.4-py2.7.egg/wifiphisher/common/interfaces.py", line 797, in is_add_vif_required
    card = pyw.getcard(vif)
  File "/usr/lib/python2.7/dist-packages/pyric/pyw.py", line 263, in getcard
    return _nlstub_(getcard, dev)
  File "/usr/lib/python2.7/dist-packages/pyric/pyw.py", line 2408, in _nlstub_
    return fct(*argv)
  File "/usr/lib/python2.7/dist-packages/pyric/pyw.py", line 265, in getcard
    return devinfo(dev, nlsock)['card']
  File "/usr/lib/python2.7/dist-packages/pyric/pyw.py", line 1151, in devinfo
    raise pyric.error(pyric.EPROTONOSUPPORT, "Device does not support nl80211")
pyric.error: [Errno 93] Device does not support nl80211
`

**Comment by tanitoo2** [comment]
Hey remove your wifiphiser :
apt-get remove wifiphisher
apt-get autoremove wifiphisher

Once that is done look this and install it like this :https://youtu.be/huAcx0fvQTY

**Comment by seandlg** [comment]
What Wi-Fi-Dongle are you using? It looks like it doesn't support netlink: `Device does not support nl80211`. `iw dev` will list your interfaces. If you use a Kali-VM, `lsusb` will let you see if the USB dongle is passed through correctly.

**Comment by scalpya** [comment]
> Hey remove your wifiphiser :
> apt-get remove wifiphisher
> apt-get autoremove wifiphisher
> 
> Once that is done look this and install it like this :https://youtu.be/huAcx0fvQTY

Thank You !
Working fine... :)

**Comment by scalpya** [comment]
> What Wi-Fi-Dongle are you using? It looks like it doesn't support netlink: `Device does not support nl80211`. `iw dev` will list your interfaces. If you use a Kali-VM, `lsusb` will let you see if the USB dongle is passed through correctly.

This is very strange... I use Alfa USB Realtek8812au chipset i dont know why show mi some diffrent chipset.
