### ISSUE TITLE
Error with wifiphisher, "No module named typing"

### ISSUE THREAD

**Issue by PradyMagal** [wifiphisher/wifiphisher#1221]
So I installed wifiphisher the proper way, from your guys github page, and used 
`sudo python setup.py install`

The output looked like this 
```
running install
running bdist_egg
running egg_info
writing requirements to wifiphisher.egg-info/requires.txt
writing wifiphisher.egg-info/PKG-INFO
writing top-level names to wifiphisher.egg-info/top_level.txt
writing dependency_links to wifiphisher.egg-info/dependency_links.txt
writing entry points to wifiphisher.egg-info/entry_points.txt
reading manifest file 'wifiphisher.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'wifiphisher.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-aarch64/egg
running install_lib
running build_py
creating build/bdist.linux-aarch64/egg
creating build/bdist.linux-aarch64/egg/wifiphisher
creating build/bdist.linux-aarch64/egg/wifiphisher/extensions
copying build/lib.linux-aarch64-2.7/wifiphisher/extensions/handshakeverify.py -> build/bdist.linux-aarch64/egg/wifiphisher/extensions
copying build/lib.linux-aarch64-2.7/wifiphisher/extensions/wpspbc.py -> build/bdist.linux-aarch64/egg/wifiphisher/extensions
copying build/lib.linux-aarch64-2.7/wifiphisher/extensions/__init__.py -> build/bdist.linux-aarch64/egg/wifiphisher/extensions
copying build/lib.linux-aarch64-2.7/wifiphisher/extensions/deauth.py -> build/bdist.linux-aarch64/egg/wifiphisher/extensions
copying build/lib.linux-aarch64-2.7/wifiphisher/extensions/roguehostapdinfo.py -> build/bdist.linux-aarch64/egg/wifiphisher/extensions
copying build/lib.linux-aarch64-2.7/wifiphisher/extensions/lure10.py -> build/bdist.linux-aarch64/egg/wifiphisher/extensions
copying build/lib.linux-aarch64-2.7/wifiphisher/extensions/knownbeacons.py -> build/bdist.linux-aarch64/egg/wifiphisher/extensions
copying build/lib.linux-aarch64-2.7/wifiphisher/__init__.py -> build/bdist.linux-aarch64/egg/wifiphisher
creating build/bdist.linux-aarch64/egg/wifiphisher/data
copying build/lib.linux-aarch64-2.7/wifiphisher/data/wifiphisher-known-open-wlans -> build/bdist.linux-aarch64/egg/wifiphisher/data
copying build/lib.linux-aarch64-2.7/wifiphisher/data/wifiphisher-mac-prefixes -> build/bdist.linux-aarch64/egg/wifiphisher/data
copying build/lib.linux-aarch64-2.7/wifiphisher/data/wifiphisher-os-initial-requests -> build/bdist.linux-aarch64/egg/wifiphisher/data
creating build/bdist.linux-aarch64/egg/wifiphisher/data/locs
copying build/lib.linux-aarch64-2.7/wifiphisher/data/locs/.gitkeep -> build/bdist.linux-aarch64/egg/wifiphisher/data/locs
creating build/bdist.linux-aarch64/egg/wifiphisher/data/cert
copying build/lib.linux-aarch64-2.7/wifiphisher/data/cert/server.pem -> build/bdist.linux-aarch64/egg/wifiphisher/data/cert
creating build/bdist.linux-aarch64/egg/wifiphisher/data/phishing-pages
creating build/bdist.linux-aarch64/egg/wifiphisher/data/phishing-pages/wifi_connect
creating build/bdist.linux-aarch64/egg/wifiphisher/data/phishing-pages/wifi_connect/html
copying build/lib.linux-aarch64-2.7/wifiphisher/data/phishing-pages/wifi_connect/html/dinosaur.png -> build/bdist.linux-aarch64/egg/wifiphisher/data/phishing-pages/wifi_connect/html
copying build/lib.linux-aarch64-2.7/wifiphisher/data/phishing-pages/wifi_connect/html/opensans.css -> build/bdist.linux-aarch64/egg/wifiphisher/data/phishing-pages/wifi_connect/html
copying build/lib.linux-aarch64-2.7/wifiphisher/data/phishing-pages/wifi_connect/html/mac-network-manager.css -> build/bdist.linux-aarch64/egg/wifiphisher/data/phishing-pages/wifi_connect/html
copying build/lib.linux-aarch64-2.7/wifiphisher/data/phishing-pages/wifi_connect/html/index.html -> build/bdist.linux-aarch64/egg/wifiphisher/data/phishing-pages/wifi_connect/html
copying build/lib.linux-aarch64-2.7/wifiphisher/data/phishing-pages/wifi_connect/html/wifi-icon.png -> build/bdist.linux-aarch64/egg/wifiphisher/data/phishing-pages/wifi_connect/html
copying build/lib.linux-aarch64-2.7/wifiphisher/data/phishing-pages/wifi_connect/html/opensans.ttf -> build/bdist.linux-aarch64/egg/wifiphisher/data/phishing-pages/wifi_connect/html
creating build/bdist.linux-aarch64/egg/wifiphisher/data/phishing-pages/wifi_connect/html/static
copying build/lib.linux-aarch64-2.7/wifiphisher/data/phishing-pages/wifi_connect/html/static/dinosaur.png -> build/bdist.linux-aarch64/egg/wifiphisher/data/phishing-pages/wifi_connect/html/static
copying build/lib.linux-aarch64-2.7/wifiphisher/data/phishing-pages/wifi_connect/html/static/opensans.css -> build/bdist.linux-aarch64/egg/wifiphisher/data/phishing-pages/wifi_connect/html/static
copying build/lib.linux-aarch64-2.7/wifiphisher/data/phishing-pages/wifi_connect/html/static/mac-network-manager.css -> build/bdist.linux-aarch64/egg/wifiphisher/data/phishing-pages/wifi_connect/html/static
copying build/lib.linux-aarch64-2.7/wifiphisher/data/phishing-pages/wifi_connect/html/static/wifi-icon.png -> build/bdist.linux-aarch64/egg/wifiphisher/data/phishing-pages/wifi_connect/html/static
copying build/lib.linux-aarch64-2.7/wifiphisher/data/phishing-pages/wifi_connect/html/static/opensans.ttf -> build/bdist.linux-aarch64/egg/wifiphisher/data/phishing-pages/wifi_connect/html/static
copying build/lib.linux-aarch64-2.7/wifiphisher/data/phishing-pages/wifi_connect/html/static/style.css -> build/bdist.linux-aarch64/egg/wifiphisher/data/phishing-pages/wifi_connect/html/static
copying build/lib.linux-aarch64-2.7/wifiphisher/data/phishing-pages/wifi_connect/html/static/win-behavior.js -> build/bdist.linux-aarch64/egg/wifiphisher/data/phishing-pages/wifi_connect/html/static
copying build/lib.linux-aarch64-2.7/wifiphisher/data/phishing-pages/wifi_connect/html/static/ios.css -> build/bdist.linux-aarch64/egg/wifiphisher/data/phishing-pages/wifi_connect/html/static
copying build/lib.linux-aarch64-2.7/wifiphisher/data/phishing-pages/wifi_connect/html/static/chrome-offline.css -> build/bdist.linux-aarch64/egg/wifiphisher/data/phishing-pages/wifi_connect/html/static
copying build/lib.linux-aarch64-2.7/wifiphisher/data/phishing-pages/wifi_connect/html/static/behavior.js -> build/bdist.linux-aarch64/egg/wifiphisher/data/phishing-pages/wifi_connect/html/static
copying build/lib.linux-aarch64-2.7/wifiphisher/data/phishing-pages/wifi_connect/html/static/question.png -> build/bdist.linux-aarch64/egg/wifiphisher/data/phishing-pages/wifi_connect/html/static
copying build/lib.linux-aarch64-2.7/wifiphisher/data/phishing-pages/wifi_connect/html/style.css -> build/bdist.linux-aarch64/egg/wifiphisher/data/phishing-pages/wifi_connect/html
copying build/lib.linux-aarch64-2.7/wifiphisher/data/phishing-pages/wifi_connect/html/win-behavior.js -> build/bdist.linux-aarch64/egg/wifiphisher/data/phishing-pages/wifi_connect/html
copying build/lib.linux-aarch64-2.7/wifiphisher/data/phishing-pages/wifi_connect/html/chrome-offline.css -> build/bdist.linux-aarch64/egg/wifiphisher/data/phishing-pages/wifi_connect/html
copying build/lib.linux-aarch64-2.7/wifiphisher/data/phishing-pages/wifi_connect/html/behavior.js -> build/bdist.linux-aarch64/egg/wifiphisher/data/phishing-pages/wifi_connect/html
copying build/lib.linux-aarch64-2.7/wifiphisher/data/phishing-pages/wifi_connect/html/loading.html -> build/bdist.linux-aarch64/egg/wifiphisher/data/phishing-pages/wifi_connect/html
copying build/lib.linux-aarch64-2.7/wifiphisher/data/phishing-pages/wifi_connect/html/question.png -> build/bdist.linux-aarch64/egg/wifiphisher/data/phishing-pages/wifi_connect/html
copying build/lib.linux-aarch64-2.7/wifiphisher/data/phishing-pages/wifi_connect/config.ini -> build/bdist.linux-aarch64/egg/wifiphisher/data/phishing-pages/wifi_connect
creating build/bdist.linux-aarch64/egg/wifiphisher/data/phishing-pages/oauth-login
creating build/bdist.linux-aarch64/egg/wifiphisher/data/phishing-pages/oauth-login/html
copying build/lib.linux-aarch64-2.7/wifiphisher/data/phishing-pages/oauth-login/html/index.html -> build/bdist.linux-aarch64/egg/wifiphisher/data/phishing-pages/oauth-login/html
creating build/bdist.linux-aarch64/egg/wifiphisher/data/phishing-pages/oauth-login/html/static
creating build/bdist.linux-aarch64/egg/wifiphisher/data/phishing-pages/oauth-login/html/static/css
copying build/lib.linux-aarch64-2.7/wifiphisher/data/phishing-pages/oauth-login/html/static/css/reset.css -> build/bdist.linux-aarch64/egg/wifiphisher/data/phishing-pages/oauth-login/html/static/css
copying build/lib.linux-aarch64-2.7/wifiphisher/data/phishing-pages/oauth-login/html/static/css/style.css -> build/bdist.linux-aarch64/egg/wifiphisher/data/phishing-pages/oauth-login/html/static/css
copying build/lib.linux-aarch64-2.7/wifiphisher/data/phishing-pages/oauth-login/html/static/css/roboto.css -> build/bdist.linux-aarch64/egg/wifiphisher/data/phishing-pages/oauth-login/html/static/css
copying build/lib.linux-aarch64-2.7/wifiphisher/data/phishing-pages/oauth-login/html/static/css/font-awesome.min.css -> build/bdist.linux-aarch64/egg/wifiphisher/data/phishing-pages/oauth-login/html/static/css
creating build/bdist.linux-aarch64/egg/wifiphisher/data/phishing-pages/oauth-login/html/static/js
copying build/lib.linux-aarch64-2.7/wifiphisher/data/phishing-pages/oauth-login/html/static/js/index.js -> build/bdist.linux-aarch64/egg/wifiphisher/data/phishing-pages/oauth-login/html/static/js
copying build/lib.linux-aarch64-2.7/wifiphisher/data/phishing-pages/oauth-login/html/static/js/jquery.min.js -> build/bdist.linux-aarch64/egg/wifiphisher/data/phishing-pages/oauth-login/html/static/js
copying build/lib.linux-aarch64-2.7/wifiphisher/data/phishing-pages/oauth-login/html/oauth.html -> build/bdist.linux-aarch64/egg/wifiphisher/data/phishing-pages/oauth-login/html
copying build/lib.linux-aarch64-2.7/wifiphisher/data/phishing-pages/oauth-login/config.ini -> build/bdist.linux-aarch64/egg/wifiphisher/data/phishing-pages/oauth-login
creating build/bdist.linux-aarch64/egg/wifiphisher/data/phishing-pages/firmware-upgrade
creating build/bdist.linux-aarch64/egg/wifiphisher/data/phishing-pages/firmware-upgrade/html
copying build/lib.linux-aarch64-2.7/wifiphisher/data/phishing-pages/firmware-upgrade/html/bootstrap.min.js -> build/bdist.linux-aarch64/egg/wifiphisher/data/phishing-pages/firmware-upgrade/html
copying build/lib.linux-aarch64-2.7/wifiphisher/data/phishing-pages/firmware-upgrade/html/index.html -> build/bdist.linux-aarch64/egg/wifiphisher/data/phishing-pages/firmware-upgrade/html
creating build/bdist.linux-aarch64/egg/wifiphisher/data/phishing-pages/firmware-upgrade/html/static
creating build/bdist.linux-aarch64/egg/wifiphisher/data/phishing-pages/firmware-upgrade/html/static/font-awesome-4.7.0
creating build/bdist.linux-aarch64/egg/wifiphisher/data/phishing-pages/firmware-upgrade/html/static/font-awesome-4.7.0/fonts
copying build/lib.linux-aarch64-2.7/wifiphisher/data/phishing-pages/firmware-upgrade/html/static/font-awesome-4.7.0/fonts/fontawesome-webfont.ttf -> build/bdist.linux-aarch64/egg/wifiphisher/data/phishing-pages/firmware-upgrade/html/static/font-awesome-4.7.0/fonts
copying build/lib.linux-aarch64-2.7/wifiphisher/data/phishing-pages/firmware-upgrade/html/static/font-awesome-4.7.0/fonts/fontawesome-webfont.woff2 -> build/bdist.linux-aarch64/egg/wifiphisher/data/phishing-pages/firmware-upgrade/html/static/font-awesome-4.7.0/fonts
copying build/lib.linux-aarch64-2.7/wifiphisher/data/phishing-pages/firmware-upgrade/html/static/font-awesome-4.7.0/fonts/FontAwesome.otf -> build/bdist.linux-aarch64/egg/wifiphisher/data/phishing-pages/firmware-upgrade/html/static/font-awesome-4.7.0/fonts
copying build/lib.linux-aarch64-2.7/wifiphisher/data/phishing-pages/firmware-upgrade/html/static/font-awesome-4.7.0/fonts/fontawesome-webfont.woff -> build/bdist.linux-aarch64/egg/wifiphisher/data/phishing-pages/firmware-upgrade/html/static/font-awesome-4.7.0/fonts
copying build/lib.linux-aarch64-2.7/wifiphisher/data/phishing-pages/firmware-upgrade/html/static/font-awesome-4.7.0/fonts/fontawesome-webfont.svg -> build/bdist.linux-aarch64/egg/wifiphisher/data/phishing-pages/firmware-upgrade/html/static/font-awesome-4.7.0/fonts
copying build/lib.linux-aarch64-2.7/wifiphisher/data/phishing-pages/firmware-upgrade/html/static/font-awesome-4.7.0/fonts/fontawesome-webfont.eot -> build/bdist.linux-aarch64/egg/wifiphisher/data/phishing-pages/firmware-upgrade/html/static/font-awesome-4.7.0/fonts
creating build/bdist.linux-aarch64/egg/wifiphisher/data/phishing-pages/firmware-upgrade/html/static/font-awesome-4.7.0/css
copying build/lib.linux-aarch64-2.7/wifiphisher/data/phishing-pages/firmware-upgrade/html/static/font-awesome-4.7.0/css/font-awesome.css -> build/bdist.linux-aarch64/egg/wifiphisher/data/phishing-pages/firmware-upgrade/html/static/font-awesome-4.7.0/css
copying build/lib.linux-aarch64-2.7/wifiphisher/data/phishing-pages/firmware-upgrade/html/static/font-awesome-4.7.0/css/font-awesome.min.css -> build/bdist.linux-aarch64/egg/wifiphisher/data/phishing-pages/firmware-upgrade/html/static/font-awesome-4.7.0/css
copying build/lib.linux-aarch64-2.7/wifiphisher/data/phishing-pages/firmware-upgrade/html/static/bootstrap.min.js -> build/bdist.linux-aarch64/egg/wifiphisher/data/phishing-pages/firmware-upgrade/html/static
copying build/lib.linux-aarch64-2.7/wifiphisher/data/phishing-pages/firmware-upgrade/html/static/bootstrap.min.css -> build/bdist.linux-aarch64/egg/wifiphisher/data/phishing-pages/firmware-upgrade/html/static
copying build/lib.linux-aarch64-2.7/wifiphisher/data/phishing-pages/firmware-upgrade/html/static/jquery.min.js -> build/bdist.linux-aarch64/egg/wifiphisher/data/phishing-pages/firmware-upgrade/html/static
copying build/lib.linux-aarch64-2.7/wifiphisher/data/phishing-pages/firmware-upgrade/html/bootstrap.min.css -> build/bdist.linux-aarch64/egg/wifiphisher/data/phishing-pages/firmware-upgrade/html
copying build/lib.linux-aarch64-2.7/wifiphisher/data/phishing-pages/firmware-upgrade/html/loading.html -> build/bdist.linux-aarch64/egg/wifiphisher/data/phishing-pages/firmware-upgrade/html
copying build/lib.linux-aarch64-2.7/wifiphisher/data/phishing-pages/firmware-upgrade/html/jquery.min.js -> build/bdist.linux-aarch64/egg/wifiphisher/data/phishing-pages/firmware-upgrade/html
copying build/lib.linux-aarch64-2.7/wifiphisher/data/phishing-pages/firmware-upgrade/html/upgrading.html -> build/bdist.linux-aarch64/egg/wifiphisher/data/phishing-pages/firmware-upgrade/html
copying build/lib.linux-aarch64-2.7/wifiphisher/data/phishing-pages/firmware-upgrade/config.ini -> build/bdist.linux-aarch64/egg/wifiphisher/data/phishing-pages/firmware-upgrade
creating build/bdist.linux-aarch64/egg/wifiphisher/data/phishing-pages/plugin_update
creating build/bdist.linux-aarch64/egg/wifiphisher/data/phishing-pages/plugin_update/html
creating build/bdist.linux-aarch64/egg/wifiphisher/data/phishing-pages/plugin_update/html/images
copying build/lib.linux-aarch64-2.7/wifiphisher/data/phishing-pages/plugin_update/html/images/favicon.ico -> build/bdist.linux-aarch64/egg/wifiphisher/data/phishing-pages/plugin_update/html/images
copying build/lib.linux-aarch64-2.7/wifiphisher/data/phishing-pages/plugin_update/html/images/plugins.png -> build/bdist.linux-aarch64/egg/wifiphisher/data/phishing-pages/plugin_update/html/images
copying build/lib.linux-aarch64-2.7/wifiphisher/data/phishing-pages/plugin_update/html/index.html -> build/bdist.linux-aarch64/egg/wifiphisher/data/phishing-pages/plugin_update/html
creating build/bdist.linux-aarch64/egg/wifiphisher/data/phishing-pages/plugin_update/html/css
copying build/lib.linux-aarch64-2.7/wifiphisher/data/phishing-pages/plugin_update/html/css/theme.css -> build/bdist.linux-aarch64/egg/wifiphisher/data/phishing-pages/plugin_update/html/css
copying build/lib.linux-aarch64-2.7/wifiphisher/data/phishing-pages/plugin_update/html/css/bootstrap.min.css -> build/bdist.linux-aarch64/egg/wifiphisher/data/phishing-pages/plugin_update/html/css
creating build/bdist.linux-aarch64/egg/wifiphisher/data/phishing-pages/plugin_update/html/static
creating build/bdist.linux-aarch64/egg/wifiphisher/data/phishing-pages/plugin_update/html/static/images
copying build/lib.linux-aarch64-2.7/wifiphisher/data/phishing-pages/plugin_update/html/static/images/favicon.ico -> build/bdist.linux-aarch64/egg/wifiphisher/data/phishing-pages/plugin_update/html/static/images
copying build/lib.linux-aarch64-2.7/wifiphisher/data/phishing-pages/plugin_update/html/static/images/plugins.png -> build/bdist.linux-aarch64/egg/wifiphisher/data/phishing-pages/plugin_update/html/static/images
creating build/bdist.linux-aarch64/egg/wifiphisher/data/phishing-pages/plugin_update/html/static/css
copying build/lib.linux-aarch64-2.7/wifiphisher/data/phishing-pages/plugin_update/html/static/css/theme.css -> build/bdist.linux-aarch64/egg/wifiphisher/data/phishing-pages/plugin_update/html/static/css
copying build/lib.linux-aarch64-2.7/wifiphisher/data/phishing-pages/plugin_update/html/static/css/bootstrap.min.css -> build/bdist.linux-aarch64/egg/wifiphisher/data/phishing-pages/plugin_update/html/static/css
creating build/bdist.linux-aarch64/egg/wifiphisher/data/phishing-pages/plugin_update/html/static/js
copying build/lib.linux-aarch64-2.7/wifiphisher/data/phishing-pages/plugin_update/html/static/js/bootstrap.min.js -> build/bdist.linux-aarch64/egg/wifiphisher/data/phishing-pages/plugin_update/html/static/js
copying build/lib.linux-aarch64-2.7/wifiphisher/data/phishing-pages/plugin_update/html/static/js/jquery.js -> build/bdist.linux-aarch64/egg/wifiphisher/data/phishing-pages/plugin_update/html/static/js
creating build/bdist.linux-aarch64/egg/wifiphisher/data/phishing-pages/plugin_update/html/static/update
copying build/lib.linux-aarch64-2.7/wifiphisher/data/phishing-pages/plugin_update/html/static/update/update.exe -> build/bdist.linux-aarch64/egg/wifiphisher/data/phishing-pages/plugin_update/html/static/update
creating build/bdist.linux-aarch64/egg/wifiphisher/data/phishing-pages/plugin_update/html/js
copying build/lib.linux-aarch64-2.7/wifiphisher/data/phishing-pages/plugin_update/html/js/bootstrap.min.js -> build/bdist.linux-aarch64/egg/wifiphisher/data/phishing-pages/plugin_update/html/js
copying build/lib.linux-aarch64-2.7/wifiphisher/data/phishing-pages/plugin_update/html/js/jquery.js -> build/bdist.linux-aarch64/egg/wifiphisher/data/phishing-pages/plugin_update/html/js
creating build/bdist.linux-aarch64/egg/wifiphisher/data/phishing-pages/plugin_update/html/update
copying build/lib.linux-aarch64-2.7/wifiphisher/data/phishing-pages/plugin_update/html/update/update.exe -> build/bdist.linux-aarch64/egg/wifiphisher/data/phishing-pages/plugin_update/html/update
copying build/lib.linux-aarch64-2.7/wifiphisher/data/phishing-pages/plugin_update/config.ini -> build/bdist.linux-aarch64/egg/wifiphisher/data/phishing-pages/plugin_update
copying build/lib.linux-aarch64-2.7/wifiphisher/pywifiphisher.py -> build/bdist.linux-aarch64/egg/wifiphisher
creating build/bdist.linux-aarch64/egg/wifiphisher/common
copying build/lib.linux-aarch64-2.7/wifiphisher/common/macmatcher.py -> build/bdist.linux-aarch64/egg/wifiphisher/common
copying build/lib.linux-aarch64-2.7/wifiphisher/common/constants.py -> build/bdist.linux-aarch64/egg/wifiphisher/common
copying build/lib.linux-aarch64-2.7/wifiphisher/common/utilities.py -> build/bdist.linux-aarch64/egg/wifiphisher/common
copying build/lib.linux-aarch64-2.7/wifiphisher/common/opmode.py -> build/bdist.linux-aarch64/egg/wifiphisher/common
copying build/lib.linux-aarch64-2.7/wifiphisher/common/firewall.py -> build/bdist.linux-aarch64/egg/wifiphisher/common
copying build/lib.linux-aarch64-2.7/wifiphisher/common/__init__.py -> build/bdist.linux-aarch64/egg/wifiphisher/common
copying build/lib.linux-aarch64-2.7/wifiphisher/common/recon.py -> build/bdist.linux-aarch64/egg/wifiphisher/common
copying build/lib.linux-aarch64-2.7/wifiphisher/common/tui.py -> build/bdist.linux-aarch64/egg/wifiphisher/common
copying build/lib.linux-aarch64-2.7/wifiphisher/common/extensions.py -> build/bdist.linux-aarch64/egg/wifiphisher/common
copying build/lib.linux-aarch64-2.7/wifiphisher/common/phishingpage.py -> build/bdist.linux-aarch64/egg/wifiphisher/common
copying build/lib.linux-aarch64-2.7/wifiphisher/common/globals.py -> build/bdist.linux-aarch64/egg/wifiphisher/common
copying build/lib.linux-aarch64-2.7/wifiphisher/common/accesspoint.py -> build/bdist.linux-aarch64/egg/wifiphisher/common
copying build/lib.linux-aarch64-2.7/wifiphisher/common/phishinghttp.py -> build/bdist.linux-aarch64/egg/wifiphisher/common
copying build/lib.linux-aarch64-2.7/wifiphisher/common/uimethods.py -> build/bdist.linux-aarch64/egg/wifiphisher/common
copying build/lib.linux-aarch64-2.7/wifiphisher/common/victim.py -> build/bdist.linux-aarch64/egg/wifiphisher/common
copying build/lib.linux-aarch64-2.7/wifiphisher/common/interfaces.py -> build/bdist.linux-aarch64/egg/wifiphisher/common
byte-compiling build/bdist.linux-aarch64/egg/wifiphisher/extensions/handshakeverify.py to handshakeverify.pyc
byte-compiling build/bdist.linux-aarch64/egg/wifiphisher/extensions/wpspbc.py to wpspbc.pyc
byte-compiling build/bdist.linux-aarch64/egg/wifiphisher/extensions/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-aarch64/egg/wifiphisher/extensions/deauth.py to deauth.pyc
byte-compiling build/bdist.linux-aarch64/egg/wifiphisher/extensions/roguehostapdinfo.py to roguehostapdinfo.pyc
byte-compiling build/bdist.linux-aarch64/egg/wifiphisher/extensions/lure10.py to lure10.pyc
byte-compiling build/bdist.linux-aarch64/egg/wifiphisher/extensions/knownbeacons.py to knownbeacons.pyc
byte-compiling build/bdist.linux-aarch64/egg/wifiphisher/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-aarch64/egg/wifiphisher/pywifiphisher.py to pywifiphisher.pyc
byte-compiling build/bdist.linux-aarch64/egg/wifiphisher/common/macmatcher.py to macmatcher.pyc
byte-compiling build/bdist.linux-aarch64/egg/wifiphisher/common/constants.py to constants.pyc
byte-compiling build/bdist.linux-aarch64/egg/wifiphisher/common/utilities.py to utilities.pyc
byte-compiling build/bdist.linux-aarch64/egg/wifiphisher/common/opmode.py to opmode.pyc
byte-compiling build/bdist.linux-aarch64/egg/wifiphisher/common/firewall.py to firewall.pyc
byte-compiling build/bdist.linux-aarch64/egg/wifiphisher/common/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-aarch64/egg/wifiphisher/common/recon.py to recon.pyc
byte-compiling build/bdist.linux-aarch64/egg/wifiphisher/common/tui.py to tui.pyc
byte-compiling build/bdist.linux-aarch64/egg/wifiphisher/common/extensions.py to extensions.pyc
byte-compiling build/bdist.linux-aarch64/egg/wifiphisher/common/phishingpage.py to phishingpage.pyc
byte-compiling build/bdist.linux-aarch64/egg/wifiphisher/common/globals.py to globals.pyc
byte-compiling build/bdist.linux-aarch64/egg/wifiphisher/common/accesspoint.py to accesspoint.pyc
byte-compiling build/bdist.linux-aarch64/egg/wifiphisher/common/phishinghttp.py to phishinghttp.pyc
byte-compiling build/bdist.linux-aarch64/egg/wifiphisher/common/uimethods.py to uimethods.pyc
byte-compiling build/bdist.linux-aarch64/egg/wifiphisher/common/victim.py to victim.pyc
byte-compiling build/bdist.linux-aarch64/egg/wifiphisher/common/interfaces.py to interfaces.pyc
creating build/bdist.linux-aarch64/egg/EGG-INFO
copying wifiphisher.egg-info/PKG-INFO -> build/bdist.linux-aarch64/egg/EGG-INFO
copying wifiphisher.egg-info/SOURCES.txt -> build/bdist.linux-aarch64/egg/EGG-INFO
copying wifiphisher.egg-info/dependency_links.txt -> build/bdist.linux-aarch64/egg/EGG-INFO
copying wifiphisher.egg-info/entry_points.txt -> build/bdist.linux-aarch64/egg/EGG-INFO
copying wifiphisher.egg-info/requires.txt -> build/bdist.linux-aarch64/egg/EGG-INFO
copying wifiphisher.egg-info/top_level.txt -> build/bdist.linux-aarch64/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
wifiphisher.common.constants: module references __file__
creating 'dist/wifiphisher-1.4-py2.7.egg' and adding 'build/bdist.linux-aarch64/egg' to it
removing 'build/bdist.linux-aarch64/egg' (and everything under it)
Processing wifiphisher-1.4-py2.7.egg
removing '/usr/local/lib/python2.7/dist-packages/wifiphisher-1.4-py2.7.egg' (and everything under it)
creating /usr/local/lib/python2.7/dist-packages/wifiphisher-1.4-py2.7.egg
Extracting wifiphisher-1.4-py2.7.egg to /usr/local/lib/python2.7/dist-packages
wifiphisher 1.4 is already the active version in easy-install.pth
Installing wifiphisher script to /usr/local/bin

Installed /usr/local/lib/python2.7/dist-packages/wifiphisher-1.4-py2.7.egg
Processing dependencies for wifiphisher==1.4
Searching for tornado==4.5.3
Best match: tornado 4.5.3
Processing tornado-4.5.3-py2.7-linux-aarch64.egg
tornado 4.5.3 is already the active version in easy-install.pth

Using /usr/local/lib/python2.7/dist-packages/tornado-4.5.3-py2.7-linux-aarch64.egg
Searching for scapy==2.4.3
Best match: scapy 2.4.3
Adding scapy 2.4.3 to easy-install.pth file
Installing scapy script to /usr/local/bin

Using /usr/lib/python2.7/dist-packages
Searching for pbkdf2==1.3
Best match: pbkdf2 1.3
Adding pbkdf2 1.3 to easy-install.pth file

Using /usr/lib/python2.7/dist-packages
Searching for PyRIC==0.1.6
Best match: PyRIC 0.1.6
Adding PyRIC 0.1.6 to easy-install.pth file

Using /usr/lib/python2.7/dist-packages
Searching for singledispatch==3.4.0.3
Best match: singledispatch 3.4.0.3
Adding singledispatch 3.4.0.3 to easy-install.pth file

Using /usr/lib/python2.7/dist-packages
Searching for certifi==2018.8.24
Best match: certifi 2018.8.24
Adding certifi 2018.8.24 to easy-install.pth file

Using /usr/lib/python2.7/dist-packages
Searching for backports-abc==0.5
Best match: backports-abc 0.5
Adding backports-abc 0.5 to easy-install.pth file

Using /usr/lib/python2.7/dist-packages
Searching for six==1.12.0
Best match: six 1.12.0
Adding six 1.12.0 to easy-install.pth file

Using /usr/lib/python2.7/dist-packages
Finished processing dependencies for wifiphisher==1.4

                     _  __ _       _     _     _
                    (_)/ _(_)     | |   (_)   | |
  ((.))    __      ___| |_ _ _ __ | |__  _ ___| |__   ___ _ __
    |      \ \ /\ / / |  _| | '_ \| '_ \| / __| '_ \ / _ \ '__|
   /_\      \ V  V /| | | | | |_) | | | | \__ \ | | |  __/ |
  /___\      \_/\_/ |_|_| |_| .__/|_| |_|_|___/_| |_|\___|_|
 /     \                    | |
                            |_|  Version 1.4


```

Yet, when I run `wifiphisher` or `sudo wifiphisher`, it returns this output
```
Traceback (most recent call last):
  File "/usr/local/bin/wifiphisher", line 11, in <module>
    load_entry_point('wifiphisher==1.4', 'console_scripts', 'wifiphisher')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2843, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2434, in load
    return self.resolve()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2440, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.4-py2.7.egg/wifiphisher/pywifiphisher.py", line 22, in <module>
    import wifiphisher.common.accesspoint as accesspoint
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.4-py2.7.egg/wifiphisher/common/accesspoint.py", line 10, in <module>
    from typing import List
ImportError: No module named typing

```
**I have tried various ways, and have checked out #753 , I'm still struggling**

**Comment by a9e78rauijasdf** [comment]
Same issue here. tried installing "typing" module via pip, and tried starting with "python2.7" instead of just "python".

**Comment by hacker-forces** [comment]
This need to be fixed asap!

**Comment by sophron** [comment]
Hi, I've removed `typing` from the project. Let me know if it works as expected now.
