### ISSUE TITLE
Browser plugin update path

### ISSUE THREAD

**Issue by sstatham** [wifiphisher/wifiphisher#1231]
Hi 
i want use 'Browser plugin update' option , after select that asks for my Payload path.
But Stop and Syntax error after insert path 
this error : 
Traceback (most recent call last):
  File "/usr/local/bin/wifiphisher", line 11, in <module>
    load_entry_point('wifiphisher==1.4', 'console_scripts', 'wifiphisher')()
  File "/usr/local/lib/python3.7/dist-packages/wifiphisher-1.4-py3.7.egg/wifiphisher/pywifiphisher.py", line 709, in run
    engine.start()
  File "/usr/local/lib/python3.7/dist-packages/wifiphisher-1.4-py3.7.egg/wifiphisher/pywifiphisher.py", line 558, in start
    "] to the payload you wish to serve: "))
  File "<string>", line 1
    /var/www/html/shsh.setup.apk
    ^
SyntaxError: invalid syntax

![payload path](https://user-images.githubusercontent.com/59009606/71067743-53999900-218a-11ea-8852-c16b73594d7d.jpg)

**I changed config file in root plugin update phishing page again showed the same Error**

Thank you

**Comment by dafish7** [comment]
yeah ive been getting the same. have you recently reinstalled it before it started to ask you for a payload?

**Comment by sstatham** [comment]
> yeah ive been getting the same. have you recently reinstalled it before it started to ask you for a payload?

i installed all versions and Now installed last version it started to ask you for a payload?

**Comment by theDreamer911** [comment]
I got the answer. after several times trial and error. 
This error is just with writing the PATH, you should use '/your payload location'
example, i have built an metasploit payload inside /root/Desktop/plugin.exe
So, i write like this

[+] Enter the [full path] to the payload you wish to serve: '/root/Desktop/plugin.exe'

and yeah it's done
