### ISSUE TITLE
[!] Failed to find an interface with monitor mode

### ISSUE THREAD

**Issue by MrShaclone** [wifiphisher/wifiphisher#1244]
Hello friend, I was trying to start the script and ended up giving this error, can someone help me? sorry for the mistakes of english, I'm portuguese

I'm using virtual box

[*] Starting Wifiphisher 1.4GIT ( https://wifiphisher.org ) at 2020-01-06 11:28
[+] Timezone detected. Setting channel range to 1-13
ERROR:root:The following error has occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/wifiphisher-1.4-py3.7.egg/wifiphisher/pywifiphisher.py", line 439, in start
    mon_iface, ap_iface = self.network_manager.get_interface_automatically(
  File "/usr/local/lib/python3.7/dist-packages/wifiphisher-1.4-py3.7.egg/wifiphisher/common/interfaces.py", line 608, in get_interface_automatically
    monitor_interface = self.get_interface(has_monitor_mode=True)
  File "/usr/local/lib/python3.7/dist-packages/wifiphisher-1.4-py3.7.egg/wifiphisher/common/interfaces.py", line 597, in get_interface
    raise InterfaceCantBeFoundError((has_monitor_mode, has_ap_mode))
wifiphisher.common.interfaces.InterfaceCantBeFoundError: Failed to find an interface with monitor mode
[!] Failed to find an interface with monitor mode
[+] Show your support!
[+] Follow us: https://twitter.com/wifiphisher
[+] Like us: https://www.facebook.com/Wifiphisher
[+] Captured credentials:
[!] Closing
![print](https://user-images.githubusercontent.com/59567502/71821885-19793400-3072-11ea-9d4c-56e9d0f00370.PNG)

**Comment by akkuratni** [comment]
?
