### ISSUE TITLE
wps-pbc	 phishing scenario doesn't work! 

### ISSUE THREAD

**Issue by minanagehsalalma** [wifiphisher/wifiphisher#1250]
wifiphisher -aI wlan0 -wP  -wAI wlan1 -nE 

After i press the pbc button on my router nothing happens on wifiphisher 
Even if click start upgrade button many times.
![received_479977632940059-1](https://user-images.githubusercontent.com/20546638/72686438-92aa6980-3afd-11ea-8c05-56b8f756bc47.png)

**Comment by sophron** [comment]
We'll have a look at some point. We recently migrated to Python3 and we may have introduced a few bugs.

**Comment by minanagehsalalma** [comment]
> We'll have a look at some point. We recently migrated to Python3 and we may have introduced a few bugs.

I think you would need a full script test after making such a Change.

**Comment by minanagehsalalma** [comment]
```
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.9/dist-packages/wifiphisher-1.4-py3.9.egg/wifiphisher/common/extensions.py", line 368, in _listen
    dot11.sniff(
  File "/usr/local/lib/python3.9/dist-packages/scapy/sendrecv.py", line 1263, in sniff
    sniffer._run(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/scapy/sendrecv.py", line 1210, in _run
    session.on_packet_received(p)
  File "/usr/local/lib/python3.9/dist-packages/scapy/sessions.py", line 108, in on_packet_received
    result = self.prn(pkt)
  File "/usr/local/lib/python3.9/dist-packages/wifiphisher-1.4-py3.9.egg/wifiphisher/common/extensions.py", line 338, in _process_packet
    ext_pkts = extension.get_packet(pkt)
  File "/usr/local/lib/python3.9/dist-packages/wifiphisher-1.4-py3.9.egg/wifiphisher/extensions/wpspbc.py", line 270, in get_packet
    self.wps_state_handler(packet)
  File "/usr/local/lib/python3.9/dist-packages/wifiphisher-1.4-py3.9.egg/wifiphisher/extensions/wpspbc.py", line 223, in wps_state_handler
    has_pbc = self.does_have_wpspbc_ie(packet)
  File "/usr/local/lib/python3.9/dist-packages/wifiphisher-1.4-py3.9.egg/wifiphisher/extensions/wpspbc.py", line 107, in does_have_wpspbc_ie
    elt_section.info.startswith("\x00P\xf2\x04"):
TypeError: startswith first arg must be bytes or a tuple of bytes, not str

```

When trying to run it on python 3.9
