### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by majd285** [wifiphisher/wifiphisher#1258]
websploit
Traceback (most recent call last):
  File "/usr/local/bin/websploit", line 11, in <module>
    load_entry_point('websploit==4.0.3', 'console_scripts', 'websploit')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2852, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2443, in load
    return self.resolve()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python2.7/dist-packages/websploit-4.0.3-py2.7.egg/websploit/websploit.py", line 34
    module.prompt = f"wsf > {line} > "
                                     ^
SyntaxError: invalid syntax

**Comment by sophron** [comment]
Hey, this is Wifiphisher's Github page. We have nothing to do with "websploit".
