### ISSUE TITLE
Exception in thread Thread-5:

### ISSUE THREAD

**Issue by Binary-Bear** [wifiphisher/wifiphisher#1264]
Hi

Firstly thank you for wifiphisher it is an interesting project.

Since updating kali I have not been able to get wifiphisher working again.

It seems as if the http server is the problem.  I have tried purging wifiphisher and all dependencies and reloading everything again with no luck.

Installed

Debian Version = #1 SMP Debian 5.4.8-1kali1 (2020-01-06)

Kali Version = 5.4.0-kali2-amd64

Wifiphisher 1.4GIT

Command used

wifiphisher --nodeauth --essid Free_wifi --logging

If I run Firefox within Kali using the address 10.0.0.1:8080 I do not receive a web page.  This used to work and was one way I tested to make sure things were working.
Thanks for any help.

The error:

```
[*] Starting Wifiphisher 1.4GIT ( https://wifiphisher.org ) at 2020-02-08 16:29
[+] Timezone detected. Setting channel range to 1-13
[+] Selecting wfphshr-wlan0 interface for the deauthentication attack
[+] Selecting wlan0 interface for creating the rogue Access Point
[+] Changing wlan0 MAC addr (BSSID) to 00:00:00:1b:38:3a
[+] Changing wlan0 MAC addr (BSSID) to 00:00:00:6d:8b:bd
[*] Cleared leases, started DHCP, set up iptables
[+] Selecting Firmware Upgrade Page template
[*] Starting the fake access point...
[*] Starting HTTP/HTTPS server at ports 8080, 443
Exception in thread Thread-5:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3/dist-packages/wifiphisher/common/phishinghttp.py", line 199, in runHTTPServer
    app.listen(port, address=ip)
  File "/usr/lib/python3/dist-packages/tornado/web.py", line 2042, in listen
    server.listen(port, address)
  File "/usr/lib/python3/dist-packages/tornado/tcpserver.py", line 144, in listen
    self.add_sockets(sockets)
  File "/usr/lib/python3/dist-packages/tornado/tcpserver.py", line 158, in add_sockets
    sock, self._handle_connection)
  File "/usr/lib/python3/dist-packages/tornado/netutil.py", line 229, in add_accept_handler
    io_loop = IOLoop.current()
  File "/usr/lib/python3/dist-packages/tornado/ioloop.py", line 282, in current
    loop = asyncio.get_event_loop()
  File "/usr/lib/python3.7/asyncio/events.py", line 644, in get_event_loop
    % threading.current_thread().name)
RuntimeError: There is no current event loop in thread 'Thread-5'.

[+] Show your support!
[+] Follow us: https://twitter.com/wifiphisher
[+] Like us: https://www.facebook.com/Wifiphisher
[+] Captured credentials:





```

**Comment by Binary-Bear** [comment]
I have just tried updating kali on a completely separate laptop (but using the same wifi adapter AWUS036NHA) resulting in the same issue as above.

Just to be clear, prior to updating, wifiphisher worked on both systems.

**Comment by Binary-Bear** [comment]
Found a way to solve this.

Purge wifiphisher from Kali

Update kali completely

Download wifiphisher and install manually using python3 install and allow dependencies to be installed

Do not use kali updater again without excluding wifiphisher somehow

I am not sure how users will be able to use apt-get update and exclude wifiphisher

It would be very cool if wifiphisher could just be installed in a single folder and be portable.

Anyway the above procedure works in case it helps someone else

**Comment by sophron** [comment]
Nice, thanks for posting this.

**Comment by Dmitry06** [comment]
Thank you!
