### ISSUE TITLE
 invalid syntax

### ISSUE THREAD

**Issue by CristianoR7Juve** [wifiphisher/wifiphisher#1277]
Can't find what's wrong here

~$ wifiphisher
Traceback (most recent call last):
  File "/usr/local/bin/wifiphisher", line 11, in <module>
    load_entry_point('wifiphisher==1.4', 'console_scripts', 'wifiphisher')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 480, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2693, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2324, in load
    return self.resolve()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2330, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.4-py2.7.egg/wifiphisher/pywifiphisher.py", line 23, in <module>
    import wifiphisher.common.phishinghttp as phishinghttp
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.4-py2.7.egg/wifiphisher/common/phishinghttp.py", line 3, in <module>
    from tornado.escape import json_decode
  File "/usr/local/lib/python2.7/dist-packages/tornado-6.0.4-py2.7-linux-x86_64.egg/tornado/escape.py", line 43
    def xhtml_escape(value: Union[str, bytes]) -> str:
                          ^
SyntaxError: invalid syntax

**Comment by sophron** [comment]
You are using Python2, instead of Python3.
