### ISSUE TITLE
Key error: 'name'

### ISSUE THREAD

**Issue by gameslp** [wifiphisher/wifiphisher#1285]
Traceback (most recent call last):
  File "/usr/local/bin/wifiphisher", line 11, in <module>
    load_entry_point('wifiphisher==1.4', 'console_scripts', 'wifiphisher')()
  File "/usr/local/lib/python3.7/dist-packages/wifiphisher-1.4-py3.7.egg/wifiphisher/pywifiphisher.py", line 708, in run
    engine = WifiphisherEngine()
  File "/usr/local/lib/python3.7/dist-packages/wifiphisher-1.4-py3.7.egg/wifiphisher/pywifiphisher.py", line 320, in __init__
    self.template_manager = phishingpage.TemplateManager()
  File "/usr/local/lib/python3.7/dist-packages/wifiphisher-1.4-py3.7.egg/wifiphisher/common/phishingpage.py", line 320, in __init__
    self.add_user_templates()
  File "/usr/local/lib/python3.7/dist-packages/wifiphisher-1.4-py3.7.egg/wifiphisher/common/phishingpage.py", line 410, in add_user_templates
    local_template = PhishingTemplate(template)
  File "/usr/local/lib/python3.7/dist-packages/wifiphisher-1.4-py3.7.egg/wifiphisher/common/phishingpage.py", line 69, in __init__
    self._display_name = info['name']
KeyError: 'name'

**Comment by sophron** [comment]
Hi @gameslp, 

Have you modified any of the phishing pages? Every phishing page needs to have a `name` variable on the `config.ini` file.

**Comment by gameslp** [comment]
no 

> Hi @gameslp,
> 
> Have you modified any of the phishing pages? Every phishing page needs to have a `name` variable on the `config.ini` file.
