### ISSUE TITLE
handshakeverify.py error verifying a valid pcap

### ISSUE THREAD

**Issue by ManuLinares** [wifiphisher/wifiphisher#1286]
[hodoHandshake.pcap.zip](https://github.com/wifiphisher/wifiphisher/files/4393495/hodoHandshake.pcap.zip)

**Version**: commit 46bdf134d838bb33e1272c598a67c8cf085c5d8d

**Description**: command **sudo wifiphisher --essid Hodo -hC hodoHandshake.pcap** It creates the rogue ap with ssid "Hodo" and select attack "firmware-upgrade". Client then connects, and enters wifi sign-in page. User enters password (in this case **polloconpapas**) and then wifiphisher tornado/web.py fails with message below.

**Script output**: 

> 2020-03-27 03:24:12,955 -              tornado.application - ERROR - Uncaught exception POST /backend/ (10.0.0.100)
> HTTPServerRequest(protocol='http', host='connectivitycheck.gstatic.com', method='POST', uri='/backend/', version='HTTP/1.1', remote_ip='10.0.0.100', headers={'Host': 'connectivitycheck.gstatic.com', 'Connection': 'keep-alive', 'Content-Length': '25', 'Accept': '*/*', 'Origin': 'http://connectivitycheck.gstatic.com', 'X-Requested-With': 'XMLHttpRequest', 'User-Agent': 'Mozilla/5.0 (Linux; Android 8.1.0; Moto G (4) Build/OPJ28.111-22; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/80.0.3987.149 Mobile Safari/537.36', 'Content-Type': 'application/x-www-form-urlencoded; charset=UTF-8', 'Referer': 'http://connectivitycheck.gstatic.com/generate_204', 'Accept-Encoding': 'gzip, deflate', 'Accept-Language': 'en-US,en;q=0.9,es-AR;q=0.8,es;q=0.7'})
> Traceback (most recent call last):
>   File "/usr/lib/python3.8/site-packages/tornado-4.5.3-py3.8-linux-x86_64.egg/tornado/web.py", line 1510, in _execute
>     result = method(*self.path_args, **self.path_kwargs)
>   File "/usr/lib/python3.8/site-packages/wifiphisher-1.4-py3.8.egg/wifiphisher/common/phishinghttp.py", line 68, in post
>     response_to_send[func_name] = callback(json_obj[func_name])
>   File "/usr/lib/python3.8/site-packages/wifiphisher-1.4-py3.8.egg/wifiphisher/extensions/handshakeverify.py", line 250, in psk_verify
>     self._is_done = self._verify_creds(list_data[0])
>   File "/usr/lib/python3.8/site-packages/wifiphisher-1.4-py3.8.egg/wifiphisher/extensions/handshakeverify.py", line 168, in _verify_creds
>     ptk = self._prf512(pmk, constants.CONST_A, const_b)
>   File "/usr/lib/python3.8/site-packages/wifiphisher-1.4-py3.8.egg/wifiphisher/extensions/handshakeverify.py", line 130, in _prf512
>     key, const_a + chr(0x00) + const_b + chr(index), hashlib.sha1)
> **TypeError: can only concatenate str (not "bytes") to str**
> 2020-03-27 03:24:12,964 -                   tornado.access - ERROR - 500 POST /backend/ (10.0.0.100) 106.78ms

**Comment by samjanny** [comment]
As a temporary fix you can substitute your _handshakeverify.py_ extenstion with the one linked below (which uses cowpatty).
[https://pastebin.com/7xYNbhAh](url)

**Comment by sophron** [comment]
Hi @samjanny,

Have you written this code? Do you think you can make a PR? I would happily merge this.

**Comment by samjanny** [comment]
Hi George,
yes, I have written the code. If you desire I can make a pull request.
Happy to see it's appreciated!

Il sab 4 apr 2020, 00:20 George Chatzisofroniou <notifications@github.com>
ha scritto:

**Comment by rodriguezwalter** [comment]
Hi there @sophron , dont mean to bother but how do you use that extension? because when i replace it and i try to do the handshake checkin it says -Hc is not an argument of handshakeverify.py, can you give me some pointers? thanks in advance!

**Comment by ManuLinares** [comment]
dead
