### ISSUE TITLE
"The 'singledispatch' distribution was not found and is required by tornado"

### ISSUE THREAD

**Issue by DarkGuy10** [wifiphisher/wifiphisher#1288]
I am using Kali Linux 2020.1
`root@DarkGuy10:~# uname -a `
`Linux DarkGuy10 5.4.0-kali3-amd64 #1 SMP Debian 5.4.13-1kali1 (2020-01-20) x86_64 GNU/Linux`
On running `wifiphisher` I get
`root@DarkGuy10:~# wifiphisher`
`Traceback (most recent call last):`
`  File "/usr/local/bin/wifiphisher", line 6, in <module>`
 `   from pkg_resources import load_entry_point`
 ` File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3251, in <module>`
   ` @_call_aside`
 ` File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3235, in _call_aside`
  `  f(*args, **kwargs)`
 ` File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3264, in _initialize_master_working_set`
  `  working_set = WorkingSet._build_master()`
`  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 583, in _build_master
 `   ws.require(__requires__)`
  `File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 900, in require`
    `needed = self.resolve(parse_requirements(requirements))`
`  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 786, in resolve`
  `  raise DistributionNotFound(req, requirers)`
`pkg_resources.DistributionNotFound: The 'singledispatch' distribution was not found and is required by tornado`

I have no idea what just happened. Wifiphisher used to work great earlier.
I am really a newbie, no idea what else info must be give. Please bear with me.
Tell me and I'll give all the necessary data.
Thank You, in advance

**Comment by sophron** [comment]
It seems that you installed tornado without a required dependency.
