### ISSUE TITLE
-help  cannot start wifiphisher

### ISSUE THREAD

**Issue by tonystarkboss** [wifiphisher/wifiphisher#1290]
wifiphisher

Traceback (most recent call last):
  File "/usr/local/bin/wifiphisher", line 11, in <module>
    load_entry_point('wifiphisher==1.4', 'console_scripts', 'wifiphisher')()
  File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2852, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2443, in load
    return self.resolve()
  File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python3.8/site-packages/wifiphisher-1.4-py3.8.egg/wifiphisher/pywifiphisher.py", line 37, in <module>
    from six.moves import range, input
ModuleNotFoundError: No module named 'six'

**Comment by newtonsart** [comment]
pip install six
