### ISSUE TITLE
Problem at startup Wifiphisher؟؟

### ISSUE THREAD

**Issue by whitef505** [wifiphisher/wifiphisher#1292]
`                                                                                                               
[*] Starting Wifiphisher 1.4GIT ( https://wifiphisher.org ) at 2020-04-06 19:46                                 
[+] Timezone detected. Setting channel range to 1-13
[+] Selecting wfphshr-wlan0 interface for the deauthentication attack
[+] Selecting wlan1 interface for creating the rogue Access Point
[+] Changing wlan1 MAC addr (BSSID) to 00:00:00:eb:9f:24
[+] Changing wlan1 MAC addr (BSSID) to 00:00:00:60:1a:1d
[+] Sending SIGKILL to wpa_supplicant
[+] Sending SIGKILL to NetworkManager
Traceback (most recent call last):
  File "/usr/bin/wifiphisher", line 11, in <module>
    load_entry_point('wifiphisher==1.4', 'console_scripts', 'wifiphisher')()
  File "/usr/lib/python3/dist-packages/wifiphisher/pywifiphisher.py", line 709, in run
    engine.start()
  File "/usr/lib/python3/dist-packages/wifiphisher/pywifiphisher.py", line 507, in start
    self.fw.redirect_requests_localhost()
  File "/usr/lib/python3/dist-packages/wifiphisher/common/firewall.py", line 51, in redirect_requests_localhost
    "--to-destination {}:{}".format(NETWORK_GW_IP, SSL_PORT)
  File "/usr/lib/python3/dist-packages/wifiphisher/common/utilities.py", line 23, in execute_commands
    _, error = Popen(command.split(), stderr=PIPE, stdout=DN).communicate()
  File "/usr/lib/python3.7/subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.7/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'iptables': 'iptables'`

**Comment by newtonsart** [comment]
> ` [*] Starting Wifiphisher 1.4GIT ( https://wifiphisher.org ) at 2020-04-06 19:46 [+] Timezone detected. Setting channel range to 1-13 [+] Selecting wfphshr-wlan0 interface for the deauthentication attack [+] Selecting wlan1 interface for creating the rogue Access Point [+] Changing wlan1 MAC addr (BSSID) to 00:00:00:eb:9f:24 [+] Changing wlan1 MAC addr (BSSID) to 00:00:00:60:1a:1d [+] Sending SIGKILL to wpa_supplicant [+] Sending SIGKILL to NetworkManager Traceback (most recent call last): File "/usr/bin/wifiphisher", line 11, in <module> load_entry_point('wifiphisher==1.4', 'console_scripts', 'wifiphisher')() File "/usr/lib/python3/dist-packages/wifiphisher/pywifiphisher.py", line 709, in run engine.start() File "/usr/lib/python3/dist-packages/wifiphisher/pywifiphisher.py", line 507, in start self.fw.redirect_requests_localhost() File "/usr/lib/python3/dist-packages/wifiphisher/common/firewall.py", line 51, in redirect_requests_localhost "--to-destination {}:{}".format(NETWORK_GW_IP, SSL_PORT) File "/usr/lib/python3/dist-packages/wifiphisher/common/utilities.py", line 23, in execute_commands _, error = Popen(command.split(), stderr=PIPE, stdout=DN).communicate() File "/usr/lib/python3.7/subprocess.py", line 800, in __init__ restore_signals, start_new_session) File "/usr/lib/python3.7/subprocess.py", line 1551, in _execute_child raise child_exception_type(errno_num, err_msg, err_filename) FileNotFoundError: [Errno 2] No such file or directory: 'iptables': 'iptables'`

sudo apt install iptables

**Comment by whitef505** [comment]
sudo apt install iptables
Reading package lists... Done
Building dependency tree       
Reading state information... Done
iptables is already the newest version (1.8.4-3).
0 upgraded, 0 newly installed, 0 to remove and 274 not upgraded.

**Comment by sophron** [comment]
Hi, 

What distro are you running? What happens if you type "iptables"?

**Comment by whitef505** [comment]
`sudo iptables
iptables v1.8.4 (nf_tables): no command specified
Try `iptables -h' or 'iptables --help' for more information`


Linux version 5.4.0-kali4-amd64

**Comment by taqilee** [comment]
kali@linux:~/Desktop/wifiphisher$ sudo wifiphisher
Traceback (most recent call last):
  File "/usr/local/bin/wifiphisher", line 33, in <module>
    sys.exit(load_entry_point('wifiphisher==1.4', 'console_scripts', 'wifiphisher')())
  File "/usr/local/bin/wifiphisher", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib/python3.9/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/usr/local/lib/python3.9/dist-packages/wifiphisher-1.4-py3.9.egg/wifiphisher/pywifiphisher.py", line 25, in <module>
    import wifiphisher.common.extensions as extensions
  File "/usr/local/lib/python3.9/dist-packages/wifiphisher-1.4-py3.9.egg/wifiphisher/common/extensions.py", line 12, in <module>
    import scapy.arch.linux as linux
  File "/usr/lib/python3/dist-packages/scapy/arch/__init__.py", line 27, in <module>
    from scapy.arch.bpf.core import get_if_raw_addr
  File "/usr/lib/python3/dist-packages/scapy/arch/bpf/core.py", line 30, in <module>
    LIBC = cdll.LoadLibrary(find_library("libc"))
  File "/usr/lib/python3.9/ctypes/util.py", line 341, in find_library
    _get_soname(_findLib_gcc(name)) or _get_soname(_findLib_ld(name))
  File "/usr/lib/python3.9/ctypes/util.py", line 147, in _findLib_gcc
    if not _is_elf(file):
  File "/usr/lib/python3.9/ctypes/util.py", line 99, in _is_elf
    with open(filename, 'br') as thefile:
FileNotFoundError: [Errno 2] No such file or directory: b'liblibc.a'

**Comment by mkdirlove** [comment]
I HAVE A PROBLEM WHEN RUNNING WIFIPHISHER, HOW CAN I FIX THIS?
THANKS.



[*] Starting Wifiphisher 1.4GIT ( https://wifiphisher.org ) at 2021-11-17 17:00
[+] Timezone detected. Setting channel range to 1-13
[+] Selecting wlan1 interface for the deauthentication attack
[+] Selecting wlan0 interface for creating the rogue Access Point
[+] Changing wlan0 MAC addr (BSSID) to 00:00:00:66:6a:a2
[+] Changing wlan0 MAC addr (BSSID) to 00:00:00:a2:9c:1b
Traceback (most recent call last):
  File "/usr/bin/wifiphisher", line 33, in <module>
    sys.exit(load_entry_point('wifiphisher==1.4', 'console_scripts', 'wifiphisher')())
  File "/usr/lib/python3/dist-packages/wifiphisher/pywifiphisher.py", line 728, in run
    engine.start()
  File "/usr/lib/python3/dist-packages/wifiphisher/pywifiphisher.py", line 502, in start
    self.network_manager.unblock_interface(ap_iface)
  File "/usr/lib/python3/dist-packages/wifiphisher/common/interfaces.py", line 647, in unblock_interface
    if pyw.isblocked(card):
  File "/usr/lib/python3/dist-packages/pyric/pyw.py", line 625, in isblocked
    return rfkill.soft_blocked(idx), rfkill.hard_blocked(idx)
  File "/usr/lib/python3/dist-packages/pyric/utils/rfkill.py", line 163, in soft_blocked
    raise pyric.error(errno.ENODEV,"No device at {0}".format(idx))
pyric.error: [Errno 19] No device at None

**Comment by comicallybad** [comment]
> 

Having the same exact error, have spent hours trying to fix it, and I finally fix something, and then it shows I have another package error, once I fix that package error, it goes back to the no module named 
'scapy'

**Comment by comicallybad** [comment]
> scapy

Having the same exact error, have spent hours trying to fix it, and I finally fix something, and then it shows I have another package error, once I fix that package error, it goes back to the no module named
'scapy' although I am not getting the errors after that you are getting.

**Comment by gingerbread-gg** [comment]
Hello, i have the same problem to run the wifiphisher, anyone can help me out?

[+] Timezone detected. Setting channel range to 1-13
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/PyRIC-0.1.6.4-py3.10.egg/pyric/pyw.py", line 1065, in devinfo
    msg = nl.nlmsg_new(nltype=_familyid_(nlsock),
  File "/usr/local/lib/python3.10/dist-packages/PyRIC-0.1.6.4-py3.10.egg/pyric/pyw.py", line 2244, in _familyid_
    rmsg = nl.nl_recvmsg(nlsock)
  File "/usr/local/lib/python3.10/dist-packages/PyRIC-0.1.6.4-py3.10.egg/pyric/lib/libnl.py", line 244, in nl_recvmsg
    msg = nlmsg_fromstream(sock.recv())
  File "/usr/local/lib/python3.10/dist-packages/PyRIC-0.1.6.4-py3.10.egg/pyric/lib/libnl.py", line 444, in nlmsg_fromstream
    raise error(abs(e),strerror(abs(e)))
libnl.error: [Errno 2] No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/wifiphisher", line 33, in <module>
    sys.exit(load_entry_point('wifiphisher==1.4', 'console_scripts', 'wifiphisher')())
  File "/usr/local/lib/python3.10/dist-packages/wifiphisher-1.4-py3.10.egg/wifiphisher/pywifiphisher.py", line 762, in run
    engine.start()
  File "/usr/local/lib/python3.10/dist-packages/wifiphisher-1.4-py3.10.egg/wifiphisher/pywifiphisher.py", line 435, in start
    self.network_manager.start(args)
  File "/usr/local/lib/python3.10/dist-packages/wifiphisher-1.4-py3.10.egg/wifiphisher/common/interfaces.py", line 740, in start
    raise error
  File "/usr/local/lib/python3.10/dist-packages/wifiphisher-1.4-py3.10.egg/wifiphisher/common/interfaces.py", line 728, in start
    card = pyw.getcard(interface)
  File "/usr/local/lib/python3.10/dist-packages/PyRIC-0.1.6.4-py3.10.egg/pyric/pyw.py", line 277, in getcard
    if nlsock is None: return _nlstub_(getcard, dev)
  File "/usr/local/lib/python3.10/dist-packages/PyRIC-0.1.6.4-py3.10.egg/pyric/pyw.py", line 2279, in _nlstub_
    return fct(*argv)
  File "/usr/local/lib/python3.10/dist-packages/PyRIC-0.1.6.4-py3.10.egg/pyric/pyw.py", line 278, in getcard
    return devinfo(dev, nlsock)['card']
  File "/usr/local/lib/python3.10/dist-packages/PyRIC-0.1.6.4-py3.10.egg/pyric/pyw.py", line 1084, in devinfo
    raise pyric.error(e.errno, e.strerror)
pyric.error: [Errno 2] No such file or directory
