### ISSUE TITLE
after update python wifiphisher not work

### ISSUE THREAD

**Issue by payam7293** [wifiphisher/wifiphisher#1295]
Traceback (most recent call last):
  File "/usr/local/bin/wifiphisher", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3252, in <module>
    def _initialize_master_working_set():
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3235, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3264, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 583, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 786, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'wifiphisher==1.4' distribution was not found and is required by the application

**Comment by sophron** [comment]
You probably have messed up by using both `easy_install` and `pip`. 

This is not a Wifiphisher issue. Google is your friend.
