### ISSUE TITLE
Another Issue.

### ISSUE THREAD

**Issue by KworkHacking** [wifiphisher/wifiphisher#1296]
Traceback (most recent call last):
  File "/usr/local/bin/wifiphisher", line 11, in <module>
    load_entry_point('wifiphisher==1.4', 'console_scripts', 'wifiphisher')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2852, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2443, in load
    return self.resolve()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.4-py2.7.egg/wifiphisher/pywifiphisher.py", line 23, in <module>
    import wifiphisher.common.phishinghttp as phishinghttp
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.4-py2.7.egg/wifiphisher/common/phishinghttp.py", line 3, in <module>
    from tornado.escape import json_decode
  File "/usr/local/lib/python2.7/dist-packages/tornado-6.0.4-py2.7-linux-i686.egg/tornado/escape.py", line 43
    def xhtml_escape(value: Union[str, bytes]) -> str:
                          ^
SyntaxError: invalid syntax

**Comment by sophron** [comment]
Use python3.
