### ISSUE TITLE
tornado versions

### ISSUE THREAD

**Issue by nragon** [wifiphisher/wifiphisher#1297]
Is this (AnyThreadEventLoopPolicy) new in tornado 5.0. 
Required version is for 4.5.3

Traceback (most recent call last):
  File "/usr/local/bin/wifiphisher", line 11, in <module>
    load_entry_point('wifiphisher==1.4', 'console_scripts', 'wifiphisher')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2852, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2443, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python3.7/dist-packages/wifiphisher-1.4-py3.7.egg/wifiphisher/pywifiphisher.py", line 31, in <module>
    import wifiphisher.common.phishinghttp as phishinghttp
  File "/usr/local/lib/python3.7/dist-packages/wifiphisher-1.4-py3.7.egg/wifiphisher/common/phishinghttp.py", line 18, in <module>
    asyncio.set_event_loop_policy(tornado.platform.asyncio.AnyThreadEventLoopPolicy())
AttributeError: module 'tornado.platform.asyncio' has no attribute 'AnyThreadEventLoopPolicy'

**Comment by dominikl** [comment]
Looks like it. Seems to work if you simply remove the `4.5.3` restriction in https://github.com/wifiphisher/wifiphisher/blob/master/setup.py#L153 .

**Comment by B-Bear123** [comment]
i have this exact same problem. I have tornado 4.5.3 downloaded but it still won't work any other suggestions?

**Comment by c10wn-00000** [comment]
@dominikl bro , can u be more specific about it ? im new to this can't really understand

**Comment by LOKESHG1234** [comment]
Same problem Please help

**Comment by sergiogoro** [comment]
> Looks like it. Seems to work if you simply remove the `4.5.3` restriction in https://github.com/wifiphisher/wifiphisher/blob/master/setup.py#L153 .

sudo nano wifiphisher/setup.py
at line 150, change tornado version to 6.0.4
save and exit

sudo python3 ./setup.py install

Working now

**Comment by sophron** [comment]
Please update to the latest revision. This should be fixed now.
