### ISSUE TITLE
RuntimeError: There is no current event loop in thread 'Thread-7'.

### ISSUE THREAD

**Issue by gatzbayomba** [wifiphisher/wifiphisher#1300]
File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3/dist-packages/wifiphisher/common/phishinghttp.py", line 199, in runHTTPServer
    app.listen(port, address=ip)
  File "/usr/lib/python3/dist-packages/tornado/web.py", line 2042, in listen
    server.listen(port, address)
  File "/usr/lib/python3/dist-packages/tornado/tcpserver.py", line 144, in listen
    self.add_sockets(sockets)
  File "/usr/lib/python3/dist-packages/tornado/tcpserver.py", line 157, in add_sockets
    self._handlers[sock.fileno()] = add_accept_handler(
  File "/usr/lib/python3/dist-packages/tornado/netutil.py", line 229, in add_accept_handler
    io_loop = IOLoop.current()
  File "/usr/lib/python3/dist-packages/tornado/ioloop.py", line 282, in current
    loop = asyncio.get_event_loop()
  File "/usr/lib/python3.8/asyncio/events.py", line 639, in get_event_loop
    raise RuntimeError('There is no current event loop in thread %r.'
RuntimeError: There is no current event loop in thread 'Thread-7'.

**Comment by sophron** [comment]
Please update to the latest revision. We recently pushed a fix.

**Comment by dgentleman111** [comment]
Thank you! Will do.

**Comment by lcotonea** [comment]
> Im getting the same error. Running Kali Linux 2020
> 
> Exception in thread Thread-7:
> Traceback (most recent call last):
> File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
> self.run()
> File "/usr/lib/python3.8/threading.py", line 870, in run
> self._target(*self._args, **self._kwargs)
> File "/usr/lib/python3/dist-packages/wifiphisher/common/phishinghttp.py", line 199, in runHTTPServer
> app.listen(port, address=ip)
> File "/usr/lib/python3/dist-packages/tornado/web.py", line 2042, in listen
> server.listen(port, address)
> File "/usr/lib/python3/dist-packages/tornado/tcpserver.py", line 144, in listen
> self.add_sockets(sockets)
> File "/usr/lib/python3/dist-packages/tornado/tcpserver.py", line 157, in add_sockets
> self._handlers[sock.fileno()] = add_accept_handler(
> File "/usr/lib/python3/dist-packages/tornado/netutil.py", line 229, in add_accept_handler
> io_loop = IOLoop.current()
> File "/usr/lib/python3/dist-packages/tornado/ioloop.py", line 282, in current
> loop = asyncio.get_event_loop()
> File "/usr/lib/python3.8/asyncio/events.py", line 639, in get_event_loop
> raise RuntimeError('There is no current event loop in thread %r.'
> RuntimeError: There is no current event loop in thread 'Thread-7'.

Did remove the package provided by kali?
`apt-get remove wifiphisher`
