### ISSUE TITLE
i have a problem on the strartup

### ISSUE THREAD

**Issue by lollypo** [wifiphisher/wifiphisher#1301]
root@kali:/home/mycatisblack12/wifiphisher# wifiphisher
Traceback (most recent call last):
  File "/usr/local/bin/wifiphisher", line 11, in <module>
    load_entry_point('wifiphisher==1.4', 'console_scripts', 'wifiphisher')()
  File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2852, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2443, in load
    return self.resolve()
  File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python3.8/site-packages/wifiphisher-1.4-py3.8.egg/wifiphisher/pywifiphisher.py", line 31, in <module>
    import wifiphisher.common.phishinghttp as phishinghttp
  File "/usr/local/lib/python3.8/site-packages/wifiphisher-1.4-py3.8.egg/wifiphisher/common/phishinghttp.py", line 18, in <module>
    asyncio.set_event_loop_policy(tornado.platform.asyncio.AnyThreadEventLoopPolicy())
AttributeError: module 'tornado.platform.asyncio' has no attribute 'AnyThreadEventLoopPolicy'

i have no idea why it is not working. I downloaded the setup with these two codes:
sudo python setup.py install and sudo python3 setup.py 

please someone help me, it worked very fine before but now it doesn't work at all !!!!!!!!!!!!!!!!

**Comment by CollinLeishman** [comment]
Having the same issue.

**Comment by lonewolfss** [comment]
im getting the same thing wish i could figure it out ive tryed everything from updating and reinstalling but i must of missed something

**Comment by wxd11011** [comment]
Having the same issue.

**Comment by wxd11011** [comment]
> Having the same issue.
My solution:
Replace 'tornado == 4.5.3' with 'tornado' in line 154 of file setup.py, then reinstall

**Comment by lonewolfss** [comment]
i tryed this but the file is read only it cannot be changed im stuck

**Comment by lonewolfss** [comment]
still the same problem for me attributeError moduel tornado.platform.asyncio has no attribute anythreadeventlooppolicy

**Comment by wxd11011** [comment]
> still the same problem for me attributeError moduel tornado.platform.asyncio has no attribute anythreadeventlo


> still the same problem for me attributeError moduel tornado.platform.asyncio has no attribute anythreadeventlooppolicy

did you edit the file without su?

**Comment by wxd11011** [comment]
> > > still the same problem for me attributeError moduel tornado.platform.asyncio has no attribute anythreadeventlo
> > 
> > 
> > > still the same problem for me attributeError moduel tornado.platform.asyncio has no attribute anythreadeventlooppolicy
> > 
> > 
> > did you edit the file without su?
> 
> It doesn’t matter i edited it and still won’t work. If im not wrong we have to download tornado because the setup.sh can’t downloaded it automaticly for some reason.

My steps:
1. https://github.com/wifiphisher/wifiphisher.git
2. cd wifiphisher
3. sudo pico setup.py, and replace 'tornado == 4.5.3' with 'tornado' in line 154
4. save change and exit pico
5. sudo python3 setup.py install

by the way ,the os which i use is kali 2020.1

**Comment by vspitz** [comment]
> > > > still the same problem for me attributeError moduel tornado.platform.asyncio has no attribute anythreadeventlo
> > > 
> > > 
> > > > still the same problem for me attributeError moduel tornado.platform.asyncio has no attribute anythreadeventlooppolicy
> > > 
> > > 
> > > did you edit the file without su?
> > 
> > 
> > It doesn’t matter i edited it and still won’t work. If im not wrong we have to download tornado because the setup.sh can’t downloaded it automaticly for some reason.
> 
> My steps:
> 
>     1. git clone https://github.com/wifiphisher/wifiphisher.git
> 
>     2. cd wifiphisher
> 
>     3. sudo pico setup.py, and replace 'tornado == 4.5.3' with 'tornado' in line 154
> 
>     4. save change and exit pico
> 
>     5. sudo python3 setup.py install
> 
> 
> by the way ,the os which i use is kali 2020.1

@lollypo to elaborate on the solution that @wxd11011 provided this works so long as you have not already tried to install wifiphisher because once tornado 4.5.3 is installed, even after you edit setup.py and re-run sudo python3 setup.py install, it will see tornado 4.5.3 as installed meeting the requirement.

This was the problem that I was having as well.  To fix it, do the following:

sudo pip3 uninstall tornado
vim setup.py (edit line 154 as indicated by @wxd11011) write and quit
sudo python3 setup.py install

Then you're good to go.  I just go it working.

**Comment by lollypo** [comment]
Thank you verry much @vspitz it finally worked for me. Can you please add me on instagram it’s elienoujaim9999 i would like to tell you something privetly

**Comment by lollypo** [comment]
Thank you verry much @vspitz it finally worked ❤️❤️❤️❤️👏👏👏👏

**Comment by vspitz** [comment]
> Thank you verry much @vspitz it finally worked heartheartheartheartclapclapclapclap

@lollypo you're welcome.  Happy hunting.

**Comment by lonewolfss** [comment]
i can confirm this worked and fixed the issues my only problem is it dosent show the power % how do i know its fully working still ?

**Comment by lonewolfss** [comment]
@vspitz  dose it actually work for you as i have left this running for hours and nothings happened

**Comment by vspitz** [comment]
@lonewolfss so i ran into the same issue as you.  Program executed but I had the null power problem, i.e. 00%.  I executed one of the attacks, i got as far as successfully deauthing clients before moving on.  Might of been a bit impatient of me, but i was playing around on a test build that i ended nuking today anyway.  I haven't yet tried to get wifiphisher running on my kali build.

**Comment by lonewolfss** [comment]
is there anyway to fix the power % problem i dont know if its working lol

**Comment by sophron** [comment]
Please update to the latest revision. We recently pushed a fix.

**Comment by lonewolfss** [comment]
when was this updated @sophron as i redownloaded it about 5 hours ago
