### ISSUE TITLE
unable to install wifiphisher

### ISSUE THREAD

**Issue by kinghacke2** [wifiphisher/wifiphisher#1303]
Before opening a new issue, please make sure that what you are about to report has not been reported already or is not included on the FAQ page. If not, use the following template for reporting.

Please keep in mind that our developers will prioritize your issue if you provide a detailed and extensive description.

**Version**: Use `git show | grep commit` command and paste here the output.

**Description**: Give a more analytical description here. Let us know how we can reproduce the reported issue. Detail the characteristics of your machine (e.g. Linux distribution and wireless card capabilities) and of the victim devices too (e.g. OS or web browser) if possible. The output of the `iw list` and `iwconfig` commands may also be helpful here.

**Script output**: Paste the output of the tool, including any stack traces.

**Comment by kinghacke2** [comment]
hello friends i am unable to install wifiphisher please help me
root@:~/wifiphisher/bin# ./wifiphisher
Traceback (most recent call last):
  File "./wifiphisher", line 15, in <module>
    from wifiphisher.pywifiphisher import run
  File "/usr/local/lib/python3.8/site-packages/wifiphisher-1.4-py3.8.egg/wifiphisher/pywifiphisher.py", line 31, in <module>
    import wifiphisher.common.phishinghttp as phishinghttp
  File "/usr/local/lib/python3.8/site-packages/wifiphisher-1.4-py3.8.egg/wifiphisher/common/phishinghttp.py", line 18, in <module>
    asyncio.set_event_loop_policy(tornado.platform.asyncio.AnyThreadEventLoopPolicy())
AttributeError: module 'tornado.platform.asyncio' has no attribute 'AnyThreadEventLoopPolicy'
please solve this problem i will be grateful
