### ISSUE TITLE
Traceback (most recent call last):   File "./wifiphisher", line 15, in <module>     from wifiphisher.pywifiphisher import run   File "/usr/local/lib/python3.7/dist-packages/wifiphisher-1.4-py3.7.egg/wifiphisher/pywifiphisher.py", line 31, in <module>     import wifiphisher.common.phishinghttp as phishinghttp   File "/usr/local/lib/python3.7/dist-packages/wifiphisher-1.4-py3.7.egg/wifiphisher/common/phishinghttp.py", line 18, in <module>     asyncio.set_event_loop_policy(tornado.platform.asyncio.AnyThreadEventLoopPolicy()) AttributeError: module 'tornado.platform.asyncio' has no attribute 'AnyThreadEventLoopPolicy'

### ISSUE THREAD

**Issue by LOKESHG1234** [wifiphisher/wifiphisher#1304]

**Comment by LOKESHG1234** [comment]
![Screenshot from 2020-04-17 21-48-20](https://user-images.githubusercontent.com/63283533/79590913-6cdd3280-80f5-11ea-8e5d-7179050bc263.png)

This is the error i get please help..

**Comment by lonewolfss** [comment]
check this post fully fixes the problem https://github.com/wifiphisher/wifiphisher/issues/1301

**Comment by sophron** [comment]
Update to the latest revision. We recently pushed a fix.

**Comment by LOKESHG1234** [comment]
Thanks for the update its working now
