### ISSUE TITLE
WifiPhisher fails when any device that does not support 'nl80211' is attached

### ISSUE THREAD

**Issue by manosf** [wifiphisher/wifiphisher#1319]
**Environment**: I am using the latest version of WifiPhisher, built from source, inside a VM which runs the latest Kali Linux. I am also using 2 network adapters, and `Alfa AWUS036NHA` which supports both AP and monitor mode, and a `TP-Link WN722N` which does NOT support either of these modes.  

I encountered a bug which makes WifiPhisher fail when any adapter that does not support `nl80211` is attached.
My goal is to use the `Alfa` adapter as the main interface and the `TP-Link` as the internet interface.
The error[2] persists when explicitly setting `Alfa` to be used as the main interface (i.e. `$wifiphisher -i wlan1 -iI wlan0 -kN -pI wlan1`) and **even** when I completely ignore `TP-Link` and just use the `Alfa` (i.e. `$wifiphisher -i wlan1`). As soon as I detach the `TP-Link` adapter from my machine, WifiPhisher works as expected.

Here are the relative parts of the output of `nmcli -o`[1] (for reference), and the pyric error[3]:
- [1]:
```
wlan0: connected to XXXX-XXX
        "TP-Link TL-WN722N"
        wifi (r8188eu), D0:37:45:53:B3:D7, hw, mtu 1500
        ip4 default, ip6 default
        inet4 192.168.1.17/24
        route4 0.0.0.0/0
        route4 192.168.1.0/24
        inet6 xxxx:xxx:xx:x:xxx:xxxxx:xxxx:xxxx/xx
        inet6 xxxx::xxxx:xxxx:xxxx:xxxx/xx
        route6 xxxx:xxxx:xxxx::/xx
        route6 ::/x
        route6 xxxx::/xx
        route6 xxxx::/x
 
wlan1: disconnected
        "Qualcomm Atheros AR9271"
        1 connection available
        wifi (ath9k_htc), 2A:9C:D4:C6:F9:0C, autoconnect, hw, mtu 1500
```  
- [2]:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/PyRIC-0.1.6.4-py3.8.egg/pyric/pyw.py", line 1070, in devinfo
    rmsg = nl.nl_recvmsg(nlsock)
  File "/usr/local/lib/python3.8/dist-packages/PyRIC-0.1.6.4-py3.8.egg/pyric/lib/libnl.py", line 244, in nl_recvmsg
    msg = nlmsg_fromstream(sock.recv())
  File "/usr/local/lib/python3.8/dist-packages/PyRIC-0.1.6.4-py3.8.egg/pyric/lib/libnl.py", line 444, in nlmsg_fromstream
    raise error(abs(e),strerror(abs(e)))
libnl.error: [Errno 19] No such device

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/wifiphisher", line 11, in <module>
    load_entry_point('wifiphisher==1.4', 'console_scripts', 'wifiphisher')()
  File "/usr/local/lib/python3.8/dist-packages/wifiphisher-1.4-py3.8.egg/wifiphisher/pywifiphisher.py", line 716, in run
    engine.start()
  File "/usr/local/lib/python3.8/dist-packages/wifiphisher-1.4-py3.8.egg/wifiphisher/pywifiphisher.py", line 407, in start  
    self.opmode.initialize(args)
  File "/usr/local/lib/python3.8/dist-packages/wifiphisher-1.4-py3.8.egg/wifiphisher/common/opmode.py", line 54, in initialize
    interfaces.is_add_vif_required(args)
  File "/usr/local/lib/python3.8/dist-packages/wifiphisher-1.4-py3.8.egg/wifiphisher/common/interfaces.py", line 815, in is_add_vif_required
    card = pyw.getcard(vif)
  File "/usr/local/lib/python3.8/dist-packages/PyRIC-0.1.6.4-py3.8.egg/pyric/pyw.py", line 277, in getcard
    if nlsock is None: return _nlstub_(getcard, dev)
  File "/usr/local/lib/python3.8/dist-packages/PyRIC-0.1.6.4-py3.8.egg/pyric/pyw.py", line 2279, in _nlstub_
    return fct(*argv)
  File "/usr/local/lib/python3.8/dist-packages/PyRIC-0.1.6.4-py3.8.egg/pyric/pyw.py", line 278, in getcard
    return devinfo(dev, nlsock)['card']
  File "/usr/local/lib/python3.8/dist-packages/PyRIC-0.1.6.4-py3.8.egg/pyric/pyw.py", line 1083, in devinfo
    raise pyric.error(pyric.EPROTONOSUPPORT, "Device does not support nl80211")
pyric.error: [Errno 93] Device does not support nl80211
```

**Comment by LeDuc19** [comment]
I just encountered the same problem with @manosf .
I'm using Kali Linux on VirtualBox.
Is there no one who can help us?
