### ISSUE TITLE
Wifiphisher 1.4 tornado/escape.py invalid syntax

### ISSUE THREAD

**Issue by Ben1782** [wifiphisher/wifiphisher#1323]
**Version**: 1.4

**Description**: Hello !
I'm new on linux (ParrotOs) and i would like to learn how system works in-depth.
Firstly, I hope this topic doesn't already exist but this seems to be specific issue, not common (I think), moreover, sorry for my english, I'm french ahah
I use an ALFA external wireless adapter, with the last version of ParrotOs

So, I installed Wifiphisher 1.4 on ParrotOs, but when I try to launch It, with `wifiphiser` command, I got an issue. I tried to understand how to solve It, but I don't again have knowledges. I installed python-tornado, but It didn't fixed wifiphisher.
If you need my `ifconfig` output or anywhat else, don't hesitate !

Could you help me please ?
Also, I'm new on github, and linux community, so please tell me if I'm doing something wrong.
Thanks you !

**Script output**: 

> Traceback (most recent call last):
  File "/usr/local/bin/wifiphisher", line 11, in <module>
    load_entry_point('wifiphisher==1.4', 'console_scripts', 'wifiphisher')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2852, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2443, in load
    return self.resolve()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.4-py2.7.egg/wifiphisher/pywifiphisher.py", line 23, in <module>
    import wifiphisher.common.phishinghttp as phishinghttp
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.4-py2.7.egg/wifiphisher/common/phishinghttp.py", line 3, in <module>
    from tornado.escape import json_decode
  File "/usr/local/lib/python2.7/dist-packages/tornado-6.0.4-py2.7-linux-x86_64.egg/tornado/escape.py", line 43
    def xhtml_escape(value: Union[str, bytes]) -> str:
                                         ^
SyntaxError: invalid syntax

**Comment by agan19** [comment]
same issue here any help out there?

**Comment by JetseVerschuren** [comment]
Try reinstalling from source using python 3, not python 2.
