### ISSUE TITLE
PWR 0% after switching to version 2020 KALI LINUX

### ISSUE THREAD

**Issue by JSFPCBR** [wifiphisher/wifiphisher#1328]
SAVE
I have always used Wifiphisher without problems in KALI LINUX 2019, but when I upgraded to version 2020, PWR APs are at 0%.

Can someone help me?

----------------------------------------------------------------------------------------------------------------------------------------
grep (GNU grep) 3.4 Copyright (C) 2020 KALI LINUX

root@wifi:~# airmon-ng
PHY	Interface	Driver		Chipset
phy0	wlan0		ath9k		Qualcomm Atheros AR9485 Wireless Network Adapter (rev 
---------------------------------------------------------------------------------------------------------------------------------------

**Comment by anonymous1211-min** [comment]
how did u install setup.py i m unable to install it

**Comment by joshesteves23** [comment]
I have also the same problem

**Comment by iso1711** [comment]
I edited recon.py and it works for me now:

def get_rssi(non_decoded_packet):
    # type: (scapy.layers.RadioTap) -> int
    """Return the rssi value of the packet."""
    #try:
    return -(256 - ord(non_decoded_packet[-2:-1]))
    #except TypeError:
        #return -100

**Comment by sophron** [comment]
@iso1711 Please submit a PR.

**Comment by hdawg12** [comment]
where do you go to edit recon.py?

**Comment by sophron** [comment]
@iso1711 Please submit a PR.

**Comment by hdawg12** [comment]
whats a PR? is that a "New Issue"?  Thanks

**Comment by hdawg12** [comment]
iso1711, 
I tried what you said and that didnt work. it gave me these errors:

Traceback (most recent call last):
  File "/usr/local/bin/wifiphisher", line 11, in <module>
    load_entry_point('wifiphisher==1.4', 'console_scripts', 'wifiphisher')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 490, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2859, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2450, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2456, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python3.9/dist-packages/wifiphisher-1.4-py3.9.egg/wifiphisher/pywifiphisher.py", line 33, in <module>
    import wifiphisher.common.recon as recon
  File "/usr/local/lib/python3.9/dist-packages/wifiphisher-1.4-py3.9.egg/wifiphisher/common/recon.py", line 245
    return -(256 - ord(non_decoded_packet[-2:-1]))
IndentationError: unexpected indent
