### ISSUE TITLE
j'essaye de démarré wifiphisher mais voici l'erreur que sa m'affiche

### ISSUE THREAD

**Issue by az123-droid** [wifiphisher/wifiphisher#1360]
Before opening a new issue, please make sure that what you are about to report has not been reported already or is not included on the FAQ page. If not, use the following template for reporting.

Please keep in mind that our developers will prioritize your issue if you provide a detailed and extensive description.

**Version**: Use `git show | grep commit` command and paste here the output.

**Description**: Give a more analytical description here. Let us know how we can reproduce the reported issue. Detail the characteristics of your machine (e.g. Linux distribution and wireless card capabilities) and of the victim devices too (e.g. OS or web browser) if possible. The output of the `iw list` and `iwconfig` commands may also be helpful here.

**Script output**: Paste the output of the tool, including any stack traces.

**Comment by az123-droid** [comment]
#wifiphisher
[*] Starting Wifiphisher 1.4GIT ( https://wifiphisher.org ) at 2020-07-07 19:06
[+] Timezone detected. Setting channel range to 1-13
ERROR:root:The following error has occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/wifiphisher-1.4-py3.8.egg/wifiphisher/pywifiphisher.py", line 455, in start
    mon_iface, ap_iface = self.network_manager.get_interface_automatically(
  File "/usr/local/lib/python3.8/dist-packages/wifiphisher-1.4-py3.8.egg/wifiphisher/common/interfaces.py", line 626, in get_interface_automatically
    monitor_interface = self.get_interface(has_monitor_mode=True)
  File "/usr/local/lib/python3.8/dist-packages/wifiphisher-1.4-py3.8.egg/wifiphisher/common/interfaces.py", line 615, in get_interface
    raise InterfaceCantBeFoundError((has_monitor_mode, has_ap_mode))
wifiphisher.common.interfaces.InterfaceCantBeFoundError: Failed to find an interface with monitor mode
[!] Failed to find an interface with monitor mode
[+] Show your support!
[+] Follow us: https://twitter.com/wifiphisher
[+] Like us: https://www.facebook.com/Wifiphisher
[+] Captured credentials:
[!] Closing

**Comment by az123-droid** [comment]
je ne comprends pas pourquoi cette erreur
