### ISSUE TITLE
 Launch issues

### ISSUE THREAD

**Issue by Slaykz** [wifiphisher/wifiphisher#1365]
I installed wifiphisher correctly, but when I run it this error is displayed: 
`Traceback (most recent call last):
  File "/usr/local/bin/wifiphisher", line 11, in <module>
    load_entry_point('wifiphisher==1.4', 'console_scripts', 'wifiphisher')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 490, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2859, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2450, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2456, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python3.8/dist-packages/wifiphisher-1.4-py3.8.egg/wifiphisher/pywifiphisher.py", line 37, in <module>
    from six.moves import range, input
ModuleNotFoundError: No module named 'six'`

**Comment by sophron** [comment]
https://stackoverflow.com/questions/13967428/importerror-no-module-named-six
