### ISSUE TITLE
Error occurred while running

### ISSUE THREAD

**Issue by aslamshahpd** [wifiphisher/wifiphisher#1403]
_  __ _       _     _     _
                    (_)/ _(_)     | |   (_)   | |
  ((.))    __      ___| |_ _ _ __ | |__  _ ___| |__   ___ _ __
    |      \ \ /\ / / |  _| | '_ \| '_ \| / __| '_ \ / _ \ '__|
   /_\      \ V  V /| | | | | |_) | | | | \__ \ | | |  __/ |
  /___\      \_/\_/ |_|_| |_| .__/|_| |_|_|___/_| |_|\___|_|
 /     \                    | |
                            |_|  Version 1.4

root@kali:# wifiphisher
[*] Starting Wifiphisher 1.4GIT ( https://wifiphisher.org ) at 2020-11-28 08:57
[+] Timezone detected. Setting channel range to 1-13
[+] Selecting wlan0 interface for the deauthentication attack
[+] Selecting p2p0 interface for creating the rogue Access Point
[+] Changing p2p0 MAC addr (BSSID) to 00:00:00:a8:92:42
[+] Changing p2p0 MAC addr (BSSID) to 00:00:00:ac:df:d3
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/PyRIC-0.1.6.4-py3.7.egg/pyric/pyw.py", line 1378, in modeset
    _ = nl.nl_recvmsg(nlsock)
  File "/usr/local/lib/python3.7/dist-packages/PyRIC-0.1.6.4-py3.7.egg/pyric/lib/libnl.py", line 244, in nl_recvmsg
    msg = nlmsg_fromstream(sock.recv())
  File "/usr/local/lib/python3.7/dist-packages/PyRIC-0.1.6.4-py3.7.egg/pyric/lib/libnl.py", line 444, in nlmsg_fromstream
    raise error(abs(e),strerror(abs(e)))
libnl.error: [Errno 95] Operation not supported

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/wifiphisher", line 33, in <module>
    sys.exit(load_entry_point('wifiphisher==1.4', 'console_scripts', 'wifiphisher')())
  File "/usr/local/lib/python3.7/dist-packages/wifiphisher-1.4-py3.7.egg/wifiphisher/pywifiphisher.py", line 728, in run
    engine.start()
  File "/usr/local/lib/python3.7/dist-packages/wifiphisher-1.4-py3.7.egg/wifiphisher/pywifiphisher.py", line 506, in start
    self.network_manager.set_interface_mode(mon_iface, "monitor")
  File "/usr/local/lib/python3.7/dist-packages/wifiphisher-1.4-py3.7.egg/wifiphisher/common/interfaces.py", line 558, in set_interface_mode
    pyw.modeset(card, mode)
  File "/usr/local/lib/python3.7/dist-packages/PyRIC-0.1.6.4-py3.7.egg/pyric/pyw.py", line 1365, in modeset
    if nlsock is None: return _nlstub_(modeset, card, mode, flags)
  File "/usr/local/lib/python3.7/dist-packages/PyRIC-0.1.6.4-py3.7.egg/pyric/pyw.py", line 2279, in _nlstub_
    return fct(*argv)
  File "/usr/local/lib/python3.7/dist-packages/PyRIC-0.1.6.4-py3.7.egg/pyric/pyw.py", line 1382, in modeset
    raise pyric.error(e.errno, e.strerror)
pyric.error: [Errno 95] Operation not supported
root@kali:/sdcard/download/wifiphisher-master/wifiphisher-master# cd
root@kali:~# ls
Termux-Lazyscript                lscript      wordlists
handshakes                       nano.save
install-nethunter-terminal.save  wifiphisher
root@kali:~# wifiphisher
[*] Starting Wifiphisher 1.4GIT ( https://wifiphisher.org ) at 2020-11-28 08:59
[+] Timezone detected. Setting channel range to 1-13
[+] Selecting wlan0 interface for the deauthentication attack
[+] Selecting p2p0 interface for creating the rogue Access Point
[+] Changing p2p0 MAC addr (BSSID) to 00:00:00:b9:69:08
[+] Changing p2p0 MAC addr (BSSID) to 00:00:00:3a:db:d5
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/PyRIC-0.1.6.4-py3.7.egg/pyric/pyw.py", line 1378, in modeset
    _ = nl.nl_recvmsg(nlsock)
  File "/usr/local/lib/python3.7/dist-packages/PyRIC-0.1.6.4-py3.7.egg/pyric/lib/libnl.py", line 244, in nl_recvmsg
    msg = nlmsg_fromstream(sock.recv())
  File "/usr/local/lib/python3.7/dist-packages/PyRIC-0.1.6.4-py3.7.egg/pyric/lib/libnl.py", line 444, in nlmsg_fromstream
    raise error(abs(e),strerror(abs(e)))
libnl.error: [Errno 95] Operation not supported

During handling of the above exception, another exception occurred:

root@kali:~# wifiphisher
[*] Starting Wifiphisher 1.4GIT ( https://wifiphisher.org ) at 2020-11-28 08:59                                                                 [+] Timezone detected. Setting channel range to 1-13
[+] Selecting wlan0 interface for the deauthentication attack           [+] Selecting p2p0 interface for creating the rogue Access Point
[+] Changing p2p0 MAC addr (BSSID) to 00:00:00:77:a3:46
[+] Changing p2p0 MAC addr (BSSID) to 00:00:00:23:5e:ae                 Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/PyRIC-0.1.6.4-py3.7.egg/pyric/pyw.py", line 1378, in modeset                                         _ = nl.nl_recvmsg(nlsock)
  File "/usr/local/lib/python3.7/dist-packages/PyRIC-0.1.6.4-py3.7.egg/pyric/lib/libnl.py", line 244, in nl_recvmsg                                 msg = nlmsg_fromstream(sock.recv())
  File "/usr/local/lib/python3.7/dist-packages/PyRIC-0.1.6.4-py3.7.egg/pyric/lib/libnl.py", line 444, in nlmsg_fromstream                           raise error(abs(e),strerror(abs(e)))
libnl.error: [Errno 95] Operation not supported
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/wifiphisher", line 33, in <module>
    sys.exit(load_entry_point('wifiphisher==1.4', 'console_scripts', 'wifiphisher')())
  File "/usr/local/lib/python3.7/dist-packages/wifiphisher-1.4-py3.7.eggroot@kali:~# wifiphisher
[*] Starting Wifiphisher 1.4GIT ( https://wifiphisher.org ) at 2020-11-28 09:11                                                                 [+] Timezone detected. Setting channel range to 1-13
[+] Selecting wlan0 interface for the deauthentication attack
[+] Selecting p2p0 interface for creating the rogue Access Point        [+] Changing p2p0 MAC addr (BSSID) to 00:00:00:11:10:17
[+] Changing p2p0 MAC addr (BSSID) to 00:00:00:3f:db:53
Traceback (most recent call last):                                        File "/usr/local/lib/python3.7/dist-packages/PyRIC-0.1.6.4-py3.7.egg/pyric/pyw.py", line 1378, in modeset
    _ = nl.nl_recvmsg(nlsock)                                             File "/usr/local/lib/python3.7/dist-packages/PyRIC-0.1.6.4-py3.7.egg/pyric/lib/libnl.py", line 244, in nl_recvmsg
    msg = nlmsg_fromstream(sock.recv())                                   File "/usr/local/lib/python3.7/dist-packages/PyRIC-0.1.6.4-py3.7.egg/pyric/lib/libnl.py", line 444, in nlmsg_fromstream
    raise error(abs(e),strerror(abs(e)))
libnl.error: [Errno 95] Operation not supported

During handling of the above exception, another exception occurred:

root@kali:~# wifiphisher
[*] Starting Wifiphisher 1.4GIT ( https://wifiphisher.org ) at 2020-11-28 09:13                                                                 [+] Timezone detected. Setting channel range to 1-13
[+] Selecting wlan0 interface for the deauthentication attack           [+] Selecting p2p0 interface for creating the rogue Access Point
[+] Changing p2p0 MAC addr (BSSID) to 00:00:00:35:0c:01
[+] Changing p2p0 MAC addr (BSSID) to 00:00:00:52:92:3f                 Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/PyRIC-0.1.6.4-py3.7.egg/pyric/pyw.py", line 1378, in modeset                                         _ = nl.nl_recvmsg(nlsock)
  File "/usr/local/lib/python3.7/dist-packages/PyRIC-0.1.6.4-py3.7.egg/pyric/lib/libnl.py", line 244, in nl_recvmsg                                 msg = nlmsg_fromstream(sock.recv())
  File "/usr/local/lib/python3.7/dist-packages/PyRIC-0.1.6.4-py3.7.egg/pyric/lib/libnl.py", line 444, in nlmsg_fromstream                           raise error(abs(e),strerror(abs(e)))
libnl.error: [Errno 95] Operation not supported
During handling of the above exception, another exception occurred:

root@kali:~# wifiphisher
[*] Starting Wifiphisher 1.4GIT ( https://wifiphisher.org ) at 2020-11-28 09:14                                                                 [+] Timezone detected. Setting channel range to 1-13
[+] Selecting wlan0 interface for the deauthentication attack           [+] Selecting p2p0 interface for creating the rogue Access Point
[+] Changing p2p0 MAC addr (BSSID) to 00:00:00:8c:77:20
[+] Changing p2p0 MAC addr (BSSID) to 00:00:00:89:38:a8                 Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/PyRIC-0.1.6.4-py3.7.egg/pyric/pyw.py", line 1378, in modeset                                         _ = nl.nl_recvmsg(nlsock)
  File "/usr/local/lib/python3.7/dist-packages/PyRIC-0.1.6.4-py3.7.egg/pyric/lib/libnl.py", line 244, in nl_recvmsg                                 msg = nlmsg_fromstream(sock.recv())
  File "/usr/local/lib/python3.7/dist-packages/PyRIC-0.1.6.4-py3.7.egg/pyric/lib/libnl.py", line 444, in nlmsg_fromstream                           raise error(abs(e),strerror(abs(e)))
libnl.error: [Errno 95] Operation not supported
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/wifiphisher", line 33, in <module>
    sys.exit(load_entry_point('wifiphisher==1.4', 'console_scripts', 'wifiphisher')())
  File "/usr/local/lib/python3.7/dist-packages/wifiphisher-1.4-py3.7.egg/wifiphisher/pywifiphisher.py", line 728, in run
    engine.start()
  File "/usr/local/lib/python3.7/dist-packages/wifiphisher-1.4-py3.7.egg/wifiphisher/pywifiphisher.py", line 506, in start
    self.network_manager.set_interface_mode(mon_iface, "monitor")
  File "/usr/local/lib/python3.7/dist-packages/wifiphisher-1.4-py3.7.egg/wifiphisher/common/interfaces.py", line 558, in set_interface_mode
    pyw.modeset(card, mode)
  File "/usr/local/lib/python3.7/dist-packages/PyRIC-0.1.6.4-py3.7.egg/pyric/pyw.py", line 1365, in modeset
    if nlsock is None: return _nlstub_(modeset, card, mode, flags)
  File "/usr/local/lib/python3.7/dist-packages/PyRIC-0.1.6.4-py3.7.egg/pyric/pyw.py", line 2279, in _nlstub_
    return fct(*argv)
  File "/usr/local/lib/python3.7/dist-packages/PyRIC-0.1.6.4-py3.7.egg/pyric/pyw.py", line 1382, in modeset
    raise pyric.error(e.errno, e.strerror)
pyric.error: [Errno 95] Operation not supported
root@kali:~#

**Comment by tykkz** [comment]
Hello there,

As far as I have seen, there are 2 files/folders in the file system that make me think that you are trying to run `wifiphisher` on an Android device: "Termux-Lazyscript" and "install-nethunter"

Far as I know, `wifiphisher` does not work on Android devices without any extra effort to adjust monitor mode WiFi chip. The error you got is trying to explain it.

Have a good day.

**Comment by sophron** [comment]
What @tykkz said.
