### ISSUE TITLE
/usr/local/bin/python3: can't find '__main__' module in '/root/wifiphisher'

### ISSUE THREAD

**Issue by Mustix** [wifiphisher/wifiphisher#1415]
I download new Kali in VB with latest update, everything was working fine on older version, but on new wifiphisher was  blaming me for some reason .was not opening. so i uninstalled the installed again, did everything like tutorial was saying fixed couple errors with url. But wifiphisher still does not work. 
if
 root@kali:~# python3 wifiphisher
i got an answer like this 
/usr/local/bin/python3: can't find '__main__' module in '/root/wifiphisher'
.
if 
root@kali:~# wifiphisher
then i get 
Traceback (most recent call last):
  File "/usr/local/bin/wifiphisher", line 33, in <module>
    sys.exit(load_entry_point('wifiphisher==1.4', 'console_scripts', 'wifiphisher')())
  File "/usr/local/bin/wifiphisher", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/local/lib/python3.9/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/usr/local/lib/python3.9/site-packages/wifiphisher-1.4-py3.9.egg/wifiphisher/pywifiphisher.py", line 25, in <module>
    import wifiphisher.common.extensions as extensions
  File "/usr/local/lib/python3.9/site-packages/wifiphisher-1.4-py3.9.egg/wifiphisher/common/extensions.py", line 12, in <module>
    import scapy.arch.linux as linux
  File "/usr/local/lib/python3.9/site-packages/scapy-2.4.4-py3.9.egg/scapy/arch/__init__.py", line 27, in <module>
    from scapy.arch.bpf.core import get_if_raw_addr
  File "/usr/local/lib/python3.9/site-packages/scapy-2.4.4-py3.9.egg/scapy/arch/bpf/core.py", line 30, in <module>
    LIBC = cdll.LoadLibrary(find_library("libc"))
  File "/usr/local/lib/python3.9/ctypes/util.py", line 330, in find_library
    _get_soname(_findLib_gcc(name)) or _get_soname(_findLib_ld(name))
  File "/usr/local/lib/python3.9/ctypes/util.py", line 147, in _findLib_gcc
    if not _is_elf(file):
  File "/usr/local/lib/python3.9/ctypes/util.py", line 99, in _is_elf
    with open(filename, 'br') as thefile:
FileNotFoundError: [Errno 2] No such file or directory: b'liblibc.a'

Does anyone get same error ? How to fix it ?

**Comment by Mustix** [comment]
i tried this command according to previous issues  

cd /usr/lib/x86_64-linux-gnu/
ln -s -f libc.a liblibc.a
but it only changed  my output for
wifiphisher 
Traceback (most recent call last):
  File "/usr/local/bin/wifiphisher", line 33, in <module>
    sys.exit(load_entry_point('wifiphisher==1.4', 'console_scripts', 'wifiphisher')())
  File "/usr/local/bin/wifiphisher", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/local/lib/python3.9/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/usr/local/lib/python3.9/site-packages/wifiphisher-1.4-py3.9.egg/wifiphisher/pywifiphisher.py", line 31, in <module>
    import wifiphisher.common.phishinghttp as phishinghttp
  File "/usr/local/lib/python3.9/site-packages/wifiphisher-1.4-py3.9.egg/wifiphisher/common/phishinghttp.py", line 10, in <module>
    import tornado.web
  File "/usr/local/lib/python3.9/site-packages/tornado-6.1-py3.9-linux-x86_64.egg/tornado/web.py", line 87, in <module>
    from tornado.httpserver import HTTPServer
  File "/usr/local/lib/python3.9/site-packages/tornado-6.1-py3.9-linux-x86_64.egg/tornado/httpserver.py", line 29, in <module>
    import ssl
  File "/usr/local/lib/python3.9/ssl.py", line 98, in <module>
    import _ssl             # if we can't import it, let the error propagate
ModuleNotFoundError: No module named '_ssl'
