### ISSUE TITLE
error in using wifiphisher

### ISSUE THREAD

**Issue by lalitkumar110301** [wifiphisher/wifiphisher#1416]
I am getting the following porblem :- 

[*] Starting Wifiphisher 1.4GIT ( https://wifiphisher.org ) at 2021-01-14 12:00
[+] Timezone detected. Setting channel range to 1-13
ERROR:root:The following error has occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/wifiphisher-1.4-py3.9.egg/wifiphisher/pywifiphisher.py", line 455, in start
    mon_iface, ap_iface = self.network_manager.get_interface_automatically(
  File "/usr/local/lib/python3.9/dist-packages/wifiphisher-1.4-py3.9.egg/wifiphisher/common/interfaces.py", line 626, in get_interface_automatically
    monitor_interface = self.get_interface(has_monitor_mode=True)
  File "/usr/local/lib/python3.9/dist-packages/wifiphisher-1.4-py3.9.egg/wifiphisher/common/interfaces.py", line 615, in get_interface
    raise InterfaceCantBeFoundError((has_monitor_mode, has_ap_mode))
wifiphisher.common.interfaces.InterfaceCantBeFoundError: Failed to find an interface with monitor mode
[!] Failed to find an interface with monitor mode
[+] Show your support!
[+] Follow us: https://twitter.com/wifiphisher
[+] Like us: https://www.facebook.com/Wifiphisher
[+] Captured credentials:
[!] Closing

**Comment by sophron** [comment]
The error is self-explanatory. You need an interface that supports monitor mode.
