### ISSUE TITLE
issue while inital run

### ISSUE THREAD

**Issue by prajwalbagewadi** [wifiphisher/wifiphisher#1418]
hi guys i installed this tool on kali linux 
sudo apt-get install wifiphisher
sudo wifiphisher
when i run this program following error occurs.

sudo wifiphisher 

Traceback (most recent call last):
  File "/usr/bin/wifiphisher", line 33, in <module>
    sys.exit(load_entry_point('wifiphisher==1.4', 'console_scripts', 'wifiphisher')())
  File "/usr/bin/wifiphisher", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib/python3.9/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/usr/lib/python3/dist-packages/wifiphisher/pywifiphisher.py", line 25, in <module>
    import wifiphisher.common.extensions as extensions
  File "/usr/lib/python3/dist-packages/wifiphisher/common/extensions.py", line 12, in <module>
    import scapy.arch.linux as linux
  File "/usr/lib/python3/dist-packages/scapy/arch/__init__.py", line 28, in <module>
    from scapy.arch.bpf.core import get_if_raw_addr
  File "/usr/lib/python3/dist-packages/scapy/arch/bpf/core.py", line 31, in <module>
    LIBC = cdll.LoadLibrary(find_library("libc"))
  File "/usr/lib/python3.9/ctypes/util.py", line 341, in find_library
    _get_soname(_findLib_gcc(name)) or _get_soname(_findLib_ld(name))
  File "/usr/lib/python3.9/ctypes/util.py", line 147, in _findLib_gcc
    if not _is_elf(file):
  File "/usr/lib/python3.9/ctypes/util.py", line 99, in _is_elf
    with open(filename, 'br') as thefile:
FileNotFoundError: [Errno 2] No such file or directory: b'liblibc.a'

**Comment by prajwalbagewadi** [comment]
code lines that have issue 
line 25
line 33
line 77
line 127
line 1030
line 1007
line 986
line 680
line 790
line 228
line 25
line 12
line 28
line 31
line 341
line 147
line 99

**Comment by xpz3** [comment]
https://github.com/wifiphisher/wifiphisher/issues/1410#issuecomment-753489291
Try this

**Comment by prajwalbagewadi** [comment]
@xpz3 sir what to try ?
The solution in 1410

**Comment by xpz3** [comment]
Click on the link and do as mentioned in the comment.. Open a terminal and type the following
```
cd /usr/lib/x86_64-linux-gnu/
ln -s -f libc.a liblibc.a
```


The run wifiphisher

**Comment by prajwalbagewadi** [comment]
thankyou @xpz3 worked like a charm. :)
