### ISSUE TITLE
wifiphisher IndexError: list index out of range

### ISSUE THREAD

**Issue by joker5bb** [wifiphisher/wifiphisher#1429]
**Version**: 
commit f0be7838b5c39855aa7a1f6b70566e69ad2f4334
**Description**: 
Using ubuntu 20.04.2 and running wifiphisher with any option fails. 

sudo rfkill                                                                                  
ID TYPE      DEVICE      SOFT      HARD
 0 wlan      phy0   unblocked unblocked
 1 wlan      phy3   unblocked unblocked
 2 bluetooth hci0   unblocked unblocked
 3 wlan      phy2   unblocked unblocked
 4 wlan      phy1   unblocked unblocked

sudo airmon-ng                                                                                                                     

PHY	Interface	Driver		Chipset

phy1	wlan0mon	ath9k_htc	Qualcomm Atheros Communications AR9271 802.11n
phy3	wlan1		brcmfmac	Broadcom 4330
phy2	wlan2mon	ath9k_htc	Qualcomm Atheros Communications AR9271 802.11n
phy0	wlp1s0mon	ath9k		Qualcomm Atheros AR958x 802.11abgn Wireless Network Adapter (rev 01)

**Script output**: 

sudo wifiphisher -aI wlan0mon -eI wlan2mon -p firmware-upgrade --handshake-capture psk-01.cap
[*] Starting Wifiphisher 1.4GIT ( https://wifiphisher.org ) at 2021-04-03 01:43
[+] Timezone detected. Setting channel range to 1-13
Traceback (most recent call last):
  File "/usr/local/bin/wifiphisher", line 11, in <module>
    load_entry_point('wifiphisher==1.4', 'console_scripts', 'wifiphisher')()
  File "/usr/local/lib/python3.8/dist-packages/wifiphisher-1.4-py3.8.egg/wifiphisher/pywifiphisher.py", line 728, in run
    engine.start()
  File "/usr/local/lib/python3.8/dist-packages/wifiphisher-1.4-py3.8.egg/wifiphisher/pywifiphisher.py", line 450, in start
    self.network_manager.unblock_interface(mon_iface)
  File "/usr/local/lib/python3.8/dist-packages/wifiphisher-1.4-py3.8.egg/wifiphisher/common/interfaces.py", line 647, in unblock_interface
    if pyw.isblocked(card):
  File "/usr/local/lib/python3.8/dist-packages/PyRIC-0.1.6.4-py3.8.egg/pyric/pyw.py", line 624, in isblocked
    idx = rfkill.getidx(card.phy)
  File "/usr/local/lib/python3.8/dist-packages/PyRIC-0.1.6.4-py3.8.egg/pyric/utils/rfkill.py", line 200, in getidx
    rfks = rfkill_list()
  File "/usr/local/lib/python3.8/dist-packages/PyRIC-0.1.6.4-py3.8.egg/pyric/utils/rfkill.py", line 86, in rfkill_list
    'soft':RFKILL_STATE[s],
IndexError: list index out of range

**Comment by joker5bb** [comment]
i have patch to remove the unblocking, this will fix the error 
diff --git a/wifiphisher/pywifiphisher.py b/wifiphisher/pywifiphisher.py
index 2d7c1bd..8ce1759 100644
--- a/wifiphisher/pywifiphisher.py
+++ b/wifiphisher/pywifiphisher.py
@@ -447,7 +447,7 @@ class WifiphisherEngine:
                     if self.network_manager.is_interface_valid(
                             args.extensionsinterface, "monitor"):
                         mon_iface = args.extensionsinterface
-                        self.network_manager.unblock_interface(mon_iface)
+                        #self.network_manager.unblock_interface(mon_iface)
                     if self.network_manager.is_interface_valid(
                             args.apinterface, "AP"):
                         ap_iface = args.apinterface
@@ -499,8 +499,8 @@ class WifiphisherEngine:
 
             # make sure interfaces are not blocked
             logger.info("Unblocking interfaces")
-            self.network_manager.unblock_interface(ap_iface)
-            self.network_manager.unblock_interface(mon_iface)
+            #self.network_manager.unblock_interface(ap_iface)
+            #self.network_manager.unblock_interface(mon_iface)
             # set monitor mode only when --essid is not given
             if self.opmode.extensions_enabled() or args.essid is None:
                 self.network_manager.set_interface_mode(mon_iface, "monitor")

**Comment by Aka-Ghost-Rider** [comment]
Bro can you explain me methods to apply this patch or your solution for this problem. I am also in same problem so if you could explain me how to solve it step by step. It would be helpful.😊

**Comment by Fishverse** [comment]
Hi @joker5bb, how do i implement this patch? Would you help me ?

**Comment by Gubriel** [comment]
Hi @MathCarv.

First create a new patch file using the git command `git diff >` 

`git diff > changes-file.patch`

Copy the @joker5bb's patch and paste in ***changes-file.patch***

Now save and apply the patch using `git apply` command, like this:

`git apply /path/to/changes-file.patch`

Don't forget to rebuild and reinstall wifiphisher with `python3 setup.py build` and `python3 setup.py install`
