### ISSUE TITLE
Available Phishing Scenario is limited

### ISSUE THREAD

**Issue by nerrazzuri** [wifiphisher/wifiphisher#1443]
Before opening a new issue, please make sure that what you are about to report has not been reported already or is not included on the FAQ page. If not, use the following template for reporting.

Please keep in mind that our developers will prioritize your issue if you provide a detailed and extensive description.

**Version**: Use `git show | grep commit` command and paste here the output.

**Description**: Give a more analytical description here. Let us know how we can reproduce the reported issue. Detail the characteristics of your machine (e.g. Linux distribution and wireless card capabilities) and of the victim devices too (e.g. OS or web browser) if possible. The output of the `iw list` and `iwconfig` commands may also be helpful here.

**Script output**: Paste the output of the tool, including any stack traces.

**Comment by nerrazzuri** [comment]
![image](https://user-images.githubusercontent.com/32594844/123720315-61b79200-d8b6-11eb-82a5-25900c0be9f6.png)
As you can see from the image, only 2 scenarios is shown, firmware upgrade and the OAuth is not in the list. I've checked the wifiphisher folder and the other 2 files are sitting properly in the correct folder, as shown in the image below. Checked the index.html for both OAuth and Firmware Upgrade doesn't seem to be any issue.
![image](https://user-images.githubusercontent.com/32594844/123720423-a3483d00-d8b6-11eb-8b7c-bd0838e0d413.png)
Tried the command -p and it gives the python raised error.
![image](https://user-images.githubusercontent.com/32594844/123720588-fe7a2f80-d8b6-11eb-93e0-d5fb58e193a1.png)

Any issue might cause this?

**Comment by Mayanjaint** [comment]
root@localhost:~/wifiphisher# wifiphisher
[*] Starting Wifiphisher 1.4GIT ( https://wifiphisher.org ) at 2021-07-02 03:28
[+] Timezone detected. Setting channel range to 1-13
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/PyRIC-0.1.6.4-py3.8.egg/pyric/lib/libnl.py", line 187, in nl_socket_alloc
    s = socket.socket(socket.AF_NETLINK,socket.SOCK_RAW,nlh.NETLINK_GENERIC)
  File "/usr/lib/python3.8/socket.py", line 231, in __init__
    _socket.socket.__init__(self, family, type, proto, fileno)
PermissionError: [Errno 13] Permission denied

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/PyRIC-0.1.6.4-py3.8.egg/pyric/pyw.py", line 2277, in _nlstub_
    nlsock = nl.nl_socket_alloc(timeout=2)
  File "/usr/local/lib/python3.8/dist-packages/PyRIC-0.1.6.4-py3.8.egg/pyric/lib/libnl.py", line 193, in nl_socket_alloc
    raise error(e.errno,e.strerror)
libnl.error: [Errno 13] Permission denied

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/wifiphisher", line 11, in <module>
    load_entry_point('wifiphisher==1.4', 'console_scripts', 'wifiphisher')()
  File "/usr/local/lib/python3.8/dist-packages/wifiphisher-1.4-py3.8.egg/wifiphisher/pywifiphisher.py", line 729, in run
    engine.start()
  File "/usr/local/lib/python3.8/dist-packages/wifiphisher-1.4-py3.8.egg/wifiphisher/pywifiphisher.py", line 408, in start
    self.opmode.initialize(args)
  File "/usr/local/lib/python3.8/dist-packages/wifiphisher-1.4-py3.8.egg/wifiphisher/common/opmode.py", line 54, in initialize
    interfaces.is_add_vif_required(args.interface,
  File "/usr/local/lib/python3.8/dist-packages/wifiphisher-1.4-py3.8.egg/wifiphisher/common/interfaces.py", line 813, in is_add_vif_required
    card = pyw.getcard(vif)
  File "/usr/local/lib/python3.8/dist-packages/PyRIC-0.1.6.4-py3.8.egg/pyric/pyw.py", line 277, in getcard
    if nlsock is None: return _nlstub_(getcard, dev)
  File "/usr/local/lib/python3.8/dist-packages/PyRIC-0.1.6.4-py3.8.egg/pyric/pyw.py", line 2281, in _nlstub_
    raise pyric.error(e.errno, pyric.strerror(e.errno))
pyric.error: [Errno 13] Permission denied

**Comment by antyneutron** [comment]
have same problem ...

**Comment by AndreAzzalin** [comment]
When some scenarios are added/removed, you have to reinstall wifiphisher by run:

<code> sudo python setup.py install </code>

It works for me

**Comment by Mayanjaint** [comment]
Thanks ✌️
