### ISSUE TITLE
wifiphisher.common.phishingpage.InvalidTemplate: The given template is either invalid or not available locally!

### ISSUE THREAD

**Issue by antyneutron** [wifiphisher/wifiphisher#1462]
Hello everyone

When i try  `sudo wifiphisher -p wlan1  `

i see :
`*] Starting Wifiphisher 1.4GIT ( https://wifiphisher.org ) at 2021-09-10 16:34
[+] Timezone detected. Setting channel range to 1-13
[+] Selecting wlan0 interface for the deauthentication attack
[+] Selecting wlan1 interface for creating the rogue Access Point
[+] Changing wlan1 MAC addr (BSSID) to 00:00:00:fc:aa:a0
[+] Changing wlan1 MAC addr (BSSID) to 00:00:00:60:d0:6a
[*] Cleared leases, started DHCP, set up iptables
Traceback (most recent call last):
  File "/usr/local/bin/wifiphisher", line 33, in <module>
    sys.exit(load_entry_point('wifiphisher==1.4', 'console_scripts', 'wifiphisher')())
  File "/usr/local/lib/python3.9/dist-packages/wifiphisher-1.4-py3.9.egg/wifiphisher/pywifiphisher.py", line 729, in run
    engine.start()
  File "/usr/local/lib/python3.9/dist-packages/wifiphisher-1.4-py3.9.egg/wifiphisher/pywifiphisher.py", line 563, in start
    template = tui_template_obj.gather_info(args.phishingscenario,
  File "/usr/local/lib/python3.9/dist-packages/wifiphisher-1.4-py3.9.egg/wifiphisher/common/tui.py", line 131, in gather_info
    raise phishingpage.InvalidTemplate
wifiphisher.common.phishingpage.InvalidTemplate: The given template is either invalid or not available locally!
`

what i doit wrong ?

**Comment by Joohnney** [comment]
hey bro.
I have the same problem.

**Comment by five2seven** [comment]
Did you ever get this working? I feel like I've tried everything. I've uninstalled, reinstalled, deleted everything and started over, renamed the phishing page directory, copied a working one and just edited the contents, etc. Still same error when trying to use anything in that folder that isn't part of the 4 initial ones that show up in the scenarios menu. Can't run any other ones from terminal or get them to show up in the menu.

**Comment by Concara3443** [comment]
Any solution?
