### ISSUE TITLE
pyric issue does not allow to start wifiphiser with two interfaces

### ISSUE THREAD

**Issue by andreagonzalez2k** [wifiphisher/wifiphisher#1473]
Kali up to date version. Wifiphiser last version.

└─# ./wifiphisher -aI wlan0mon -eI wlan2mon                                                                              1 ⨯
[*] Starting Wifiphisher 1.4GIT ( https://wifiphisher.org ) at 2021-10-31 14:41
[+] Timezone detected. Setting channel range to 1-13
Traceback (most recent call last):
  File "/home/a/Documentos/wifi/wifiphisher/bin/./wifiphisher", line 24, in <module>
    run()
  File "/usr/local/lib/python3.9/dist-packages/wifiphisher-1.4-py3.9.egg/wifiphisher/pywifiphisher.py", line 729, in run
    engine.start()
  File "/usr/local/lib/python3.9/dist-packages/wifiphisher-1.4-py3.9.egg/wifiphisher/pywifiphisher.py", line 451, in start
    self.network_manager.unblock_interface(mon_iface)
  File "/usr/local/lib/python3.9/dist-packages/wifiphisher-1.4-py3.9.egg/wifiphisher/common/interfaces.py", line 647, in unblock_interface
    if pyw.isblocked(card):
  File "/usr/local/lib/python3.9/dist-packages/PyRIC-0.1.6.4-py3.9.egg/pyric/pyw.py", line 625, in isblocked
    return rfkill.soft_blocked(idx), rfkill.hard_blocked(idx)
  File "/usr/local/lib/python3.9/dist-packages/PyRIC-0.1.6.4-py3.9.egg/pyric/utils/rfkill.py", line 163, in soft_blocked
    raise pyric.error(errno.ENODEV,"No device at {0}".format(idx))
pyric.error: [Errno 19] No device at None

It only allows me to use the command "./wifiphisher -aI wlan0mon -nE", but it disables the cheching of whether the introduced key is correct or not.

Both interfaces wlan0mon and wlan2mon exist and are in monitor mode:

└─# airmon-ng                                                                                                            1 ⨯
PHY     Interface       Driver          Chipset
phy10   wlan0mon        ath9k_htc       Qualcomm Atheros Communications AR9271 802.11n
phy11   wlan1           8812au          Realtek Semiconductor Corp. RTL8812AU 802.11a/b/g/n/ac 2T2R DB WLAN Adapter
phy12   wlan2mon        rt73usb         D-Link System AirPlus G DWL-G122(rev.C1) [Ralink RT2571W]
phy13   wlan3           mt7601u         Ralink Technology, Corp. MT7601U
phy14   wlan4           p54usb          Alcatel Telecom SpeedTouch 121g Wireless Dongle

**Comment by sahdow3256** [comment]
Hey bro I have same problem
you have resolve ?

**Comment by bateser** [comment]
same here, any update on a fix yet ?

**Comment by TurfJakkals** [comment]
#1474

**Comment by cond8r** [comment]
I just found out what the problem is, I only keep one wireless card, through ifconfig wlan0 down, and then run sudo wifiphisher and it works!

**Comment by TurfJakkals** [comment]
> I just found out what the problem is, I only keep one wireless card, through ifconfig wlan0 down, and then run sudo wifiphisher and it works!

Could you perhaps explain your process a bit more clearer please?

**Comment by cond8r** [comment]
![image](https://user-images.githubusercontent.com/67705220/152492659-f9bebf0a-d8db-46da-a18d-c338156cc9dc.jpeg)

**Comment by juan662** [comment]
Qtal brodr ., Tengo ese mismo problema al ejecutar wifiphisher con las dos tarjetas de red

] Iniciando Wifiphisher 1.4GIT ( https://wifiphisher.org/ ) a las 2021-10-31 14:41
[+] Zona horaria detectada. Configuración del rango de canales en 1-13
Rastreo (última llamada más reciente):
Archivo "/home/a/Documentos/wifi/wifiphisher/bin/./wifiphisher", línea 24, en
run()
Archivo "/usr/local/lib /python3.9/dist-packages/wifiphisher-1.4-py3.9.egg/wifiphisher/pywifiphisher.py", línea 729, en run
engine.start()
Archivo "/usr/local/lib/python3.9/dist -packages/wifiphisher-1.4-py3.9.egg/wifiphisher/pywifiphisher.py", línea 451, en start
self.network_manager.unblock_interface(mon_iface)
Archivo "/usr/local/lib/python3.9/dist-packages/wifiphisher-1.4-py3.9.egg/wifiphisher/common/interfaces.py", línea 647, en unblock_interface
si pyw.isblocked(card):
Archivo "/usr/local/lib/python3.9/dist-packages/PyRIC-0.1.6.4-py3.9.egg/pyric/pyw.py", línea 625, en isblocked
return rfkill.soft_blocked(idx), rfkill. archivo hard_blocked(idx)
"/usr/local/lib/python3.9/dist-packages/PyRIC-0.1.6.4-py3.9.egg/pyric/utils/rfkill.py", línea 163, en soft_blocked
raise pyric. error(errno.ENODEV,"No hay dispositivo en {0}".format(idx))
pyric.error: [Errno 19] No hay dispositivo en Ninguno

**Comment by juan662** [comment]
Aque se debe este error ., Al quitarle la tarjeta inalámbrica USB me funciona perfectamente , cual es motivo del error ....
