### ISSUE TITLE
Running wifiphisher in Kali Linux 2021.3

### ISSUE THREAD

**Issue by MalikSploit** [wifiphisher/wifiphisher#1474]
I'm using the latest version of wifiphisher (1.4) after the installation of setup.py i run wifiphisher and i get this. Does anyone know what i should do please ?

┌──(root💀kali)-[~]
└─# wifiphisher
[*] Starting Wifiphisher 1.4GIT ( https://wifiphisher.org ) at 2021-11-01 13:19
[+] Timezone detected. Setting channel range to 1-13
[+] Selecting wlan0 interface for the deauthentication attack
[+] Selecting wfphshr-wlan0 interface for creating the rogue Access Point
[+] Changing wfphshr-wlan0 MAC addr (BSSID) to 00:00:00:9d:32:6b
[+] Changing wfphshr-wlan0 MAC addr (BSSID) to 00:00:00:f4:95:22
Traceback (most recent call last):
  File "/usr/local/bin/wifiphisher", line 33, in <module>
    sys.exit(load_entry_point('wifiphisher==1.4', 'console_scripts', 'wifiphisher')())
  File "/usr/lib/python3/dist-packages/wifiphisher/pywifiphisher.py", line 728, in run
    engine.start()
  File "/usr/lib/python3/dist-packages/wifiphisher/pywifiphisher.py", line 502, in start
    self.network_manager.unblock_interface(ap_iface)
  File "/usr/lib/python3/dist-packages/wifiphisher/common/interfaces.py", line 647, in unblock_interface
    if pyw.isblocked(card):
  File "/usr/lib/python3/dist-packages/pyric/pyw.py", line 625, in isblocked
    return rfkill.soft_blocked(idx), rfkill.hard_blocked(idx)
  File "/usr/lib/python3/dist-packages/pyric/utils/rfkill.py", line 163, in soft_blocked
    raise pyric.error(errno.ENODEV,"No device at {0}".format(idx))
pyric.error: [Errno 19] No device at None

**Comment by sahdow3256** [comment]
Hey bro I have same problem 
you have resolve ?

**Comment by LizardRoot** [comment]
Hi. Help pls.

I'm using the latest version of wifiphisher (1.4)

On Kali 2021.3

My adapters:
Bus 001 Device 004: ID 148f:3070 Ralink Technology, Corp. RT2870/RT3070 Wireless Adapter
Bus 001 Device 003: ID 148f:3070 Ralink Technology, Corp. RT2870/RT3070 Wireless Adapter

My VM:
on VirtualBox 6.1.28 Oracle VM VirtualBox Extension Pack (usb 3.0 connected via Extension Pack)

[iwconfig.txt](https://github.com/wifiphisher/wifiphisher/files/7533725/iwconfig.txt)

[iw list.txt](https://github.com/wifiphisher/wifiphisher/files/7533726/iw.list.txt)

My error:
Traceback (most recent call last):
  File "/usr/local/bin/wifiphisher", line 33, in <module>
    sys.exit(load_entry_point('wifiphisher==1.4', 'console_scripts', 'wifiphisher')())
  File "/usr/local/lib/python3.9/dist-packages/wifiphisher-1.4-py3.9.egg/wifiphisher/pywifiphisher.py", line 729, in run
    engine.start()
  File "/usr/local/lib/python3.9/dist-packages/wifiphisher-1.4-py3.9.egg/wifiphisher/pywifiphisher.py", line 503, in start
    self.network_manager.unblock_interface(ap_iface)
  File "/usr/local/lib/python3.9/dist-packages/wifiphisher-1.4-py3.9.egg/wifiphisher/common/interfaces.py", line 647, in unblock_interface
    if pyw.isblocked(card):
  File "/usr/local/lib/python3.9/dist-packages/PyRIC-0.1.6.4-py3.9.egg/pyric/pyw.py", line 625, in isblocked
    return rfkill.soft_blocked(idx), rfkill.hard_blocked(idx)
  File "/usr/local/lib/python3.9/dist-packages/PyRIC-0.1.6.4-py3.9.egg/pyric/utils/rfkill.py", line 163, in soft_blocked
    raise pyric.error(errno.ENODEV,"No device at {0}".format(idx))
pyric.error: [Errno 19] No device at None

**Comment by MalikSploit** [comment]
@LizardRoot Your adapter does not support monitor, and Wifiphisher is waiting for a wireless adapter that supports monitor mode to do a de-authentication attack (ex : TP-Link TL-WN722N V1). That should be why you have this problem.

**Comment by sahdow3256** [comment]
use wifipumpkin3 wifiphisher not work

**Comment by LizardRoot** [comment]
> @LizardRoot Your adapter does not support monitor, and Wifiphisher is waiting for a wireless adapter that supports monitor mode to do a de-authentication attack (ex : TP-Link TL-WN722N V1). That should be why you have this problem.

lsusb
`Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 001 Device 007: ID 0bda:b728 Realtek Semiconductor Corp. 802.11 n WLAN
Bus 001 Device 006: ID 0bda:0129 Realtek Semiconductor Corp. RTS5129 Card Reader Controller
Bus 001 Device 005: ID 13d3:5727 IMC Networks 802.11 n WLAN
Bus 001 Device 004: ID 05e3:0608 Genesys Logic, Inc. Hub
Bus 001 Device 003: ID 148f:3070 Ralink Technology, Corp. RT2870/RT3070 Wireless Adapter
Bus 001 Device 002: ID 148f:3070 Ralink Technology, Corp. RT2870/RT3070 Wireless Adapter
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
`

iwconfig
`wlx6cfdb9882614  IEEE 802.11  ESSID:off/any  
          Mode:Managed  Access Point: Not-Associated   Tx-Power=20 dBm   
          Retry short  long limit:2   RTS thr:off   Fragment thr:off
          Encryption key:off
          Power Management:off
          
wlp2s0    IEEE 802.11  ESSID:"2,4G_from_Bill_Gates"  
          Mode:Managed  Frequency:2.422 GHz  Access Point: 10:50:72:21:69:28   
          Bit Rate=72.2 Mb/s   Tx-Power=20 dBm   
          Retry short limit:7   RTS thr=2347 B   Fragment thr:off
          Encryption key:off
          Power Management:on
          Link Quality=70/70  Signal level=-32 dBm  
          Rx invalid nwid:0  Rx invalid crypt:0  Rx invalid frag:0
          Tx excessive retries:0  Invalid misc:20   Missed beacon:0

wlx0013ef3f006e  IEEE 802.11  ESSID:off/any  
          Mode:Managed  Access Point: Not-Associated   Tx-Power=20 dBm   
          Retry short  long limit:2   RTS thr:off   Fragment thr:off
          Encryption key:off
          Power Management:off
`

airmon-ng
`PHY	Interface	Driver		Chipset

phy0	wlp2s0		rtl8723be	Realtek Semiconductor Co., Ltd. RTL8723BE PCIe Wireless Network Adapter
phy1	wlx0013ef3f006e	rt2800usb	Ralink Technology, Corp. RT2870/RT3070
phy2	wlx6cfdb9882614	rt2800usb	Ralink Technology, Corp. RT2870/RT3070
`

airmon-ng start "interface"
`Found 2 processes that could cause trouble.
Kill them using 'airmon-ng check kill' before putting
the card in monitor mode, they will interfere by changing channels
and sometimes putting the interface back in managed mode

    PID Name
   2328 avahi-daemon
   2329 avahi-daemon

PHY	Interface	Driver		Chipset

phy2	wlan0mon	rt2800usb	Ralink Technology, Corp. RT2870/RT3070
phy0	wlp2s0		rtl8723be	Realtek Semiconductor Co., Ltd. RTL8723BE PCIe Wireless Network Adapter
phy1	wlx0013ef3f006e	rt2800usb	Ralink Technology, Corp. RT2870/RT3070
Interface wlx0013ef3f006emon is too long for linux so it will be renamed to the old style (wlan#) name.

		(mac80211 monitor mode vif enabled on [phy1]wlan1mon
		(mac80211 station mode vif disabled for [phy1]wlx0013ef3f006e)
`

iwconfig
`wlp2s0    IEEE 802.11  ESSID:off/any  
          Mode:Managed  Access Point: Not-Associated   Tx-Power=20 dBm   
          Retry short limit:7   RTS thr=2347 B   Fragment thr:off
          Encryption key:off
          Power Management:on
          
wlan1mon  IEEE 802.11  Mode:Monitor  Tx-Power=20 dBm   
          Retry short  long limit:2   RTS thr:off   Fragment thr:off
          Power Management:off
          
wlan0mon  IEEE 802.11  Mode:Monitor  Tx-Power=20 dBm   
          Retry short  long limit:2   RTS thr:off   Fragment thr:off
          Power Management:off
`

and inject some working via aireplay-ng -9 "interface"

**Comment by bricco1981** [comment]
iw dev wlan0 del

**Comment by WILDBIRDY92** [comment]
Does anybody have some news concerning the fix of this bug ?
I have the same problem than MalikSploit and I use 2 wifi adapters that support monitoring and injection mode so, the bug don't come from the adapters

**Comment by jhondepp69** [comment]
> I'm using the latest version of wifiphisher (1.4) after the installation of setup.py(which ended correctly) i run wifiphisher and i get this. Does anyone know what i should do please ?
> 
> ┌──(rootskullkali)-[~] └─# wifiphisher [*] Starting Wifiphisher 1.4GIT ( https://wifiphisher.org ) at 2021-11-01 13:19 [+] Timezone detected. Setting channel range to 1-13 [+] Selecting wlan0 interface for the deauthentication attack [+] Selecting wfphshr-wlan0 interface for creating the rogue Access Point [+] Changing wfphshr-wlan0 MAC addr (BSSID) to 00:00:00:9d:32:6b [+] Changing wfphshr-wlan0 MAC addr (BSSID) to 00:00:00:f4:95:22 Traceback (most recent call last): File "/usr/local/bin/wifiphisher", line 33, in sys.exit(load_entry_point('wifiphisher==1.4', 'console_scripts', 'wifiphisher')()) File "/usr/lib/python3/dist-packages/wifiphisher/pywifiphisher.py", line 728, in run engine.start() File "/usr/lib/python3/dist-packages/wifiphisher/pywifiphisher.py", line 502, in start self.network_manager.unblock_interface(ap_iface) File "/usr/lib/python3/dist-packages/wifiphisher/common/interfaces.py", line 647, in unblock_interface if pyw.isblocked(card): File "/usr/lib/python3/dist-packages/pyric/pyw.py", line 625, in isblocked return rfkill.soft_blocked(idx), rfkill.hard_blocked(idx) File "/usr/lib/python3/dist-packages/pyric/utils/rfkill.py", line 163, in soft_blocked raise pyric.error(errno.ENODEV,"No device at {0}".format(idx)) pyric.error: [Errno 19] No device at None

i have the same problem after upgrading to kalilinux version 2021.3

**Comment by Mayh3m4Kickz** [comment]
Hi guys I have spent the last week trying to figure out this error but I have had no luck. However I have found a solution. I downloaded an older version of parrot 4.6.
I installed it in a virtual machine without updating it or upgrading it just for the sole purpose of using Wifiphisher.

**Comment by Mayh3m4Kickz** [comment]
> > I'm using the latest version of wifiphisher (1.4) after the installation of setup.py(which ended correctly) i run wifiphisher and i get this. Does anyone know what i should do please ?
> > ┌──(rootskullkali)-[~] └─# wifiphisher [*] Starting Wifiphisher 1.4GIT ( https://wifiphisher.org ) at 2021-11-01 13:19 [+] Timezone detected. Setting channel range to 1-13 [+] Selecting wlan0 interface for the deauthentication attack [+] Selecting wfphshr-wlan0 interface for creating the rogue Access Point [+] Changing wfphshr-wlan0 MAC addr (BSSID) to 00:00:00:9d:32:6b [+] Changing wfphshr-wlan0 MAC addr (BSSID) to 00:00:00:f4:95:22 Traceback (most recent call last): File "/usr/local/bin/wifiphisher", line 33, in sys.exit(load_entry_point('wifiphisher==1.4', 'console_scripts', 'wifiphisher')()) File "/usr/lib/python3/dist-packages/wifiphisher/pywifiphisher.py", line 728, in run engine.start() File "/usr/lib/python3/dist-packages/wifiphisher/pywifiphisher.py", line 502, in start self.network_manager.unblock_interface(ap_iface) File "/usr/lib/python3/dist-packages/wifiphisher/common/interfaces.py", line 647, in unblock_interface if pyw.isblocked(card): File "/usr/lib/python3/dist-packages/pyric/pyw.py", line 625, in isblocked return rfkill.soft_blocked(idx), rfkill.hard_blocked(idx) File "/usr/lib/python3/dist-packages/pyric/utils/rfkill.py", line 163, in soft_blocked raise pyric.error(errno.ENODEV,"No device at {0}".format(idx)) pyric.error: [Errno 19] No device at None
> 
> i have the same problem after upgrading to kalilinux version 2021.3

https://github.com/wifiphisher/wifiphisher/issues/1474#issuecomment-988638702

**Comment by Mayh3m4Kickz** [comment]
> Does anybody have some news concerning the fix of this bug ? I have the same problem than MalikSploit and I use 2 wifi adapters that support monitoring and injection mode so, the bug don't come from the adapters

https://github.com/wifiphisher/wifiphisher/issues/1474#issuecomment-988638702

**Comment by sophron** [comment]
Pushed a commit that fixes this. Please update to the latest revision and try again.
