### ISSUE TITLE
error using for kalilinux 2021.4

### ISSUE THREAD

**Issue by jhondepp69** [wifiphisher/wifiphisher#1480]
[*] Starting Wifiphisher 1.4GIT ( https://wifiphisher.org ) at 2021-12-12 10:01
[+] Timezone detected. Setting channel range to 1-13
[+] Selecting wlan0 interface for the deauthentication attack
[+] Selecting wlan1 interface for creating the rogue Access Point
[+] Changing wlan1 MAC addr (BSSID) to 00:00:00:ac:4a:21
[+] Changing wlan1 MAC addr (BSSID) to 00:00:00:75:66:97
Traceback (most recent call last):
  File "/usr/local/bin/wifiphisher", line 33, in <module>
    sys.exit(load_entry_point('wifiphisher==1.4', 'console_scripts', 'wifiphisher')())
  File "/usr/local/lib/python3.9/dist-packages/wifiphisher-1.4-py3.9.egg/wifiphisher/pywifiphisher.py", line 729, in run
    engine.start()
  File "/usr/local/lib/python3.9/dist-packages/wifiphisher-1.4-py3.9.egg/wifiphisher/pywifiphisher.py", line 503, in start
    self.network_manager.unblock_interface(ap_iface)
  File "/usr/local/lib/python3.9/dist-packages/wifiphisher-1.4-py3.9.egg/wifiphisher/common/interfaces.py", line 647, in unblock_interface
    if pyw.isblocked(card):
  File "/usr/local/lib/python3.9/dist-packages/PyRIC-0.1.6.4-py3.9.egg/pyric/pyw.py", line 625, in isblocked
    return rfkill.soft_blocked(idx), rfkill.hard_blocked(idx)
  File "/usr/local/lib/python3.9/dist-packages/PyRIC-0.1.6.4-py3.9.egg/pyric/utils/rfkill.py", line 163, in soft_blocked
    raise pyric.error(errno.ENODEV,"No device at {0}".format(idx))
pyric.error: [Errno 19] No device at None

**Comment by cond8r** [comment]
I just found out what the problem is, I only keep one wireless card, through ifconfig wlan0 down, and then run sudo wifiphisher and it works!
