### ISSUE TITLE
8814au chipset - pyric.error: [Errno 19] No device at None

### ISSUE THREAD

**Issue by brandontict** [wifiphisher/wifiphisher#1482]
Only run into this issue when using my ALFA AWUS1900 . Chipset is 8814au , working monitor mode and injection with no issues .

Fully updated python modules on latest kali rolling . 

**Version**: wifiphisher Latest 1.4

**Description**:  When attempting to run wifiphisher, with or without setting devices using  -aI and -eI  flags, I  receive script error. 

This particular error only happens when using ALFA AWUS1900, as mentioned . 

**Script output**:  

`wifiphisher -kB -nD -iNM -aI wlan0 -eI wlan1
[*] Starting Wifiphisher 1.4GIT ( https://wifiphisher.org ) at 2021-12-12 19:05
[+] Timezone detected. Setting channel range to 1-13
Traceback (most recent call last):
  File "/usr/local/bin/wifiphisher", line 33, in <module>
    sys.exit(load_entry_point('wifiphisher==1.4', 'console_scripts', 'wifiphisher')())
  File "/usr/local/lib/python3.9/dist-packages/wifiphisher-1.4-py3.9.egg/wifiphisher/pywifiphisher.py", line 729, in run
    engine.start()
  File "/usr/local/lib/python3.9/dist-packages/wifiphisher-1.4-py3.9.egg/wifiphisher/pywifiphisher.py", line 451, in start
    self.network_manager.unblock_interface(mon_iface)
  File "/usr/local/lib/python3.9/dist-packages/wifiphisher-1.4-py3.9.egg/wifiphisher/common/interfaces.py", line 647, in unblock_interface
    if pyw.isblocked(card):
  File "/usr/local/lib/python3.9/dist-packages/PyRIC-0.1.6.4-py3.9.egg/pyric/pyw.py", line 625, in isblocked
    return rfkill.soft_blocked(idx), rfkill.hard_blocked(idx)
  File "/usr/local/lib/python3.9/dist-packages/PyRIC-0.1.6.4-py3.9.egg/pyric/utils/rfkill.py", line 163, in soft_blocked
    raise pyric.error(errno.ENODEV,"No device at {0}".format(idx))
pyric.error: [Errno 19] No device at None
`

**Comment by Herakules1999** [comment]
bro, you solved your problem them?

**Comment by brandontict** [comment]
Sadly ,I have not :(

**Comment by Ergrv** [comment]
not nor not not not


در تاریخ جمعه ۱۱ فوریهٔ ۲۰۲۲،‏ ۲۱:۱۷ brandontict ***@***.***>
نوشت:

**Comment by i3xpl01t** [comment]
Hi, the problem is that it is not possible to use the tool with an Alfa network adapter with 8814AU chipset, it is impossible to use.
![4EFABB68-8617-4924-BFA4-636DBF6487E7](https://user-images.githubusercontent.com/100308339/155852441-f23e4e1e-3a3b-402f-be06-97e627709767.jpeg)

**Comment by sophron** [comment]
Pushed a commit that fixes this. Please update to the latest revision and try again.

**Comment by i3xpl01t** [comment]
Hi Sophron, I already did the update of the tool and it continues presenting the same error.  Thank you very much I hope you can help me. 😁

**Comment by i3xpl01t** [comment]
Hi Sophron, I already did the update of the tool and it continues
presenting the same error. Thank you very much I hope you can help me. 😁

**Comment by LobuzFx** [comment]
> Hi Sophron, I already did the update of the tool and it continues presenting the same error. Thank you very much I hope you can help me. grin

I have the same thing, you managed to run?

**Comment by dxfantome** [comment]
the same problème.
I'm sad I can't find a solution
![16533207194428717453578408559150](https://user-images.githubusercontent.com/67840680/169857530-653f1440-ad64-403c-8891-6a2a0ee5b320.jpg)
