### ISSUE TITLE
Error executing the tool  wifiphisher -how fix that

### ISSUE THREAD

**Issue by mounirg10** [wifiphisher/wifiphisher#1491]
─# wifiphisher             
[*] Starting Wifiphisher 1.4GIT ( https://wifiphisher.org ) at 2022-01-10 23:45
[+] Timezone detected. Setting channel range to 1-13
[+] Selecting wlan0 interface for the deauthentication attack
[+] Selecting wfphshr-wlan0 interface for creating the rogue Access Point
[!] The MAC address could not be set. (Tried 00:00:00:80:8c:29)
Traceback (most recent call last):
  File "/usr/local/bin/wifiphisher", line 33, in <module>
    sys.exit(load_entry_point('wifiphisher==1.4', 'console_scripts', 'wifiphisher')())
  File "/usr/local/lib/python3.9/dist-packages/wifiphisher-1.4-py3.9.egg/wifiphisher/pywifiphisher.py", line 729, in run
    engine.start()
  File "/usr/local/lib/python3.9/dist-packages/wifiphisher-1.4-py3.9.egg/wifiphisher/pywifiphisher.py", line 503, in start
    self.network_manager.unblock_interface(ap_iface)
  File "/usr/local/lib/python3.9/dist-packages/wifiphisher-1.4-py3.9.egg/wifiphisher/common/interfaces.py", line 647, in unblock_interface
    if pyw.isblocked(card):
  File "/usr/local/lib/python3.9/dist-packages/PyRIC-0.1.6.4-py3.9.egg/pyric/pyw.py", line 625, in isblocked
    return rfkill.soft_blocked(idx), rfkill.hard_blocked(idx)
  File "/usr/local/lib/python3.9/dist-packages/PyRIC-0.1.6.4-py3.9.egg/pyric/utils/rfkill.py", line 163, in soft_blocked
    raise pyric.error(errno.ENODEV,"No device at {0}".format(idx))
pyric.error: [Errno 19] No device at None

**Comment by Ngh45** [comment]
I have also same problem

**Comment by juan662** [comment]
Hola muchachos ., An solucionado dicho problema estoy en las mismas a que se debe este error , yo lo tengo cuando ejecutó wifiphisher con las dos tarjetas al quitarle la tarjeta USB me funciona perfectamente x que este error .,,,,,

**Comment by devilmen80** [comment]
ok try to install it from database with apt.
If still don't work you must change the file interfaces.py that was modified from the author of this program. There is a new commit. Now it works.https://github.com/wifiphisher/wifiphisher/issues/1471
