### ISSUE TITLE
Can't use two wireless adapters get  soft_blocked error

### ISSUE THREAD

**Issue by minanagehsalalma** [wifiphisher/wifiphisher#1493]
```
Traceback (most recent call last):
  File "/usr/local/bin/wifiphisher", line 33, in <module>
    sys.exit(load_entry_point('wifiphisher==1.4', 'console_scripts', 'wifiphisher')())
  File "/usr/local/lib/python3.9/dist-packages/wifiphisher-1.4-py3.9.egg/wifiphisher/pywifiphisher.py", line 729, in run
    engine.start()
  File "/usr/local/lib/python3.9/dist-packages/wifiphisher-1.4-py3.9.egg/wifiphisher/pywifiphisher.py", line 504, in start
    self.network_manager.unblock_interface(mon_iface)
  File "/usr/local/lib/python3.9/dist-packages/wifiphisher-1.4-py3.9.egg/wifiphisher/common/interfaces.py", line 647, in unblock_interface
    if pyw.isblocked(card):
  File "/usr/local/lib/python3.9/dist-packages/PyRIC-0.1.6.4-py3.9.egg/pyric/pyw.py", line 625, in isblocked
    return rfkill.soft_blocked(idx), rfkill.hard_blocked(idx)
  File "/usr/local/lib/python3.9/dist-packages/PyRIC-0.1.6.4-py3.9.egg/pyric/utils/rfkill.py", line 163, in soft_blocked
    raise pyric.error(errno.ENODEV,"No device at {0}".format(idx))
pyric.error: [Errno 19] No device at None

```

**Comment by juan662** [comment]
Veo y noto que este error es bastante común yo también tengo el mismo error con las dos tarjetas ., Que as solucionado. Se sabe muy poco de este error

**Comment by minanagehsalalma** [comment]
> Veo y noto que este error es bastante común yo también tengo el mismo error con las dos tarjetas ., Que as solucionado. Se sabe muy poco de este error

@juan662 The repo is in english and the issue is english 

and you come here speaking Spanish ? 🤨

What is the Solution tho ?
