### ISSUE TITLE
rfkill_list() assigning weird idx values in the rfks dict

### ISSUE THREAD

**Issue by needl3** [wifiphisher/wifiphisher#1498]
## Issue at this state:
`commit 90b095a7f66ecdab167af2e857196ae0d9702aed (HEAD -> master, origin/master, origin/HEAD)
Author: George Chatzisofroniou <sophron@latthi.com>
Date:   Fri Jan 14 19:01:39 2022 -0600`

## Info

- I am using `Arch Linux` with kernel `5.16.2-arch1-1`
- Supports `rfkill` or has /dev/rfkill
- Have AP capable internal wifi card
- `rfkill list` output
```
$ rfkill list
0: ideapad_wlan: Wireless LAN
	Soft blocked: no
	Hard blocked: no
1: ideapad_bluetooth: Bluetooth
	Soft blocked: yes
	Hard blocked: no
2: hci0: Bluetooth
	Soft blocked: no
	Hard blocked: no
3: phy0: Wireless LAN
	Soft blocked: no
	Hard blocked: no
```

- `/sys/class` has
``` 
$ ls /sys/class/ieee80211/
phy0
```

## Stacktrace?
```
$ sudo wifiphisher -e "Name" -p firmware_upgrade
[*] Starting Wifiphisher 1.4GIT ( https://wifiphisher.org ) at 2022-01-26 17:56
[+] Timezone detected. Setting channel range to 1-13
[+] Selecting wfphshr-wlan0 interface for the deauthentication attack
[+] Selecting wlan0 interface for creating the rogue Access Point
[+] Changing wlan0 MAC addr (BSSID) to 00:00:00:93:33:bf
[+] Changing wlan0 MAC addr (BSSID) to 00:00:00:0a:fb:3c
Traceback (most recent call last):
  File "/usr/bin/wifiphisher", line 33, in <module>
    sys.exit(load_entry_point('wifiphisher==1.4', 'console_scripts', 'wifiphisher')())
  File "/usr/lib/python3.10/site-packages/wifiphisher-1.4-py3.10.egg/wifiphisher/pywifiphisher.py", line 729, in run
    engine.start()
  File "/usr/lib/python3.10/site-packages/wifiphisher-1.4-py3.10.egg/wifiphisher/pywifiphisher.py", line 503, in start
    self.network_manager.unblock_interface(ap_iface)
  File "/usr/lib/python3.10/site-packages/wifiphisher-1.4-py3.10.egg/wifiphisher/common/interfaces.py", line 647, in unblock_interface
    if pyw.isblocked(card):
  File "/usr/lib/python3.10/site-packages/pyric/pyw.py", line 605, in isblocked
    idx = rfkill.getidx(card.phy)
  File "/usr/lib/python3.10/site-packages/pyric/utils/rfkill.py", line 200, in getidx
    rfks = rfkill_list()
  File "/usr/lib/python3.10/site-packages/pyric/utils/rfkill.py", line 86, in rfkill_list
    'soft':RFKILL_STATE[s],
IndexError: list index out of range

```

## What I think is wrong
There was weird return on `/usr/lib/python3.10/site-packages/pyric/net/wireless/rfkill_h.py`'s `rfkill_event()` function's packed struct with `hard` and `soft` parameters other than `0` and `1` used to infer `RFKILL_STATE`'s values. Also, upon checking the stream bytes and it's unpacked form I receive the below output which definitely isn't what's expected.
I just inserted ```print(struct.unpack(rfkh.rfk_rfkill_event,stream), stream)``` somewhere inside `rfkill_list()` and here's the output.

### Output
```
(0, 1, 0, 0, 0) b'\x00\x00\x00\x00\x01\x00\x00\x00'
{'ideapad_wlan': {'idx': 0, 'type': 'wlan', 'soft': False, 'hard': False}}
(256, 0, 2, 0, 1) b'\x00\x01\x00\x00\x00\x02\x00\x01'
{'ideapad_wlan': {'idx': 0, 'type': 'wlan', 'soft': False, 'hard': False}}
(131072, 0, 0, 2, 0) b'\x00\x00\x02\x00\x00\x00\x02\x00'
[Finished in 79ms]
```

Note: I don't think it's `wifiphisher`'s issue to be honest and if I'm on a right track on this issue. I just opened this issue to just confirm if this is reproducible and is real. Should I open another issue in `wraith-wireless/PyRIC`?
Please ask for any other info if required. Thanks!

**Comment by anvinbiju** [comment]
How to slow this bro.I am using kali Linux please help me

**Comment by Retr02332** [comment]
Confirm this...

**Comment by runsisi** [comment]
```bash
$ sudo wifiphisher -kN -i  wlp4s0
[*] Starting Wifiphisher 1.4GIT ( https://wifiphisher.org ) at 2022-10-24 20:28
[+] Timezone detected. Setting channel range to 1-13
[+] Selecting wfphshr-wlan0 interface for the deauthentication attack
[+] Selecting wlp4s0 interface for creating the rogue Access Point
[+] Changing wlp4s0 MAC addr (BSSID) to 00:00:00:06:31:36
[+] Changing wlp4s0 MAC addr (BSSID) to 00:00:00:4e:8b:9d
Traceback (most recent call last):
  File "/usr/local/bin/wifiphisher", line 33, in <module>
    sys.exit(load_entry_point('wifiphisher==1.4', 'console_scripts', 'wifiphisher')())
  File "/usr/local/lib/python3.10/dist-packages/wifiphisher-1.4-py3.10.egg/wifiphisher/pywifiphisher.py", line 762, in run
    engine.start()
  File "/usr/local/lib/python3.10/dist-packages/wifiphisher-1.4-py3.10.egg/wifiphisher/pywifiphisher.py", line 536, in start
    self.network_manager.unblock_interface(ap_iface)
  File "/usr/local/lib/python3.10/dist-packages/wifiphisher-1.4-py3.10.egg/wifiphisher/common/interfaces.py", line 648, in unblock_interface
    if pyw.isblocked(card):
  File "/usr/local/lib/python3.10/dist-packages/PyRIC-0.1.6.4-py3.10.egg/pyric/pyw.py", line 624, in isblocked
    idx = rfkill.getidx(card.phy)
  File "/usr/local/lib/python3.10/dist-packages/PyRIC-0.1.6.4-py3.10.egg/pyric/utils/rfkill.py", line 200, in getidx
    rfks = rfkill_list()
  File "/usr/local/lib/python3.10/dist-packages/PyRIC-0.1.6.4-py3.10.egg/pyric/utils/rfkill.py", line 86, in rfkill_list
    'soft':RFKILL_STATE[s],
IndexError: list index out of range
```

reproducible on Ubuntu 22.04 :(

**Comment by runsisi** [comment]
broken since linux kernel 5.11[^1], pyric should be patched..

[^1]: rfkill: add a reason to the HW rfkill state
https://github.com/torvalds/linux/commit/14486c82612a177cb910980c70ba900827ca0894

**Comment by Gubriel** [comment]
This worked fine for me. #1429

_Running on Ubuntu 22.04.2_
