### ISSUE TITLE
Can't start wifiphisher solution please

### ISSUE THREAD

**Issue by Erumike** [wifiphisher/wifiphisher#1499]
Hello everyone whenever i start my wifiphisher I get the folling error please how do i resolve it

[*] Starting Wifiphisher 1.4GIT ( https://wifiphisher.org ) at 2022-01-26 14:40
[+] Timezone detected. Setting channel range to 1-13
[+] Selecting wlan0 interface for the deauthentication attack
[+] Selecting wfphshr-wlan0 interface for creating the rogue Access Point
[+] Changing wfphshr-wlan0 MAC addr (BSSID) to 00:00:00:3b:b4:93
[+] Changing wfphshr-wlan0 MAC addr (BSSID) to 00:00:00:67:18:98
Traceback (most recent call last):
  File "/usr/local/bin/wifiphisher", line 33, in <module>
    sys.exit(load_entry_point('wifiphisher==1.4', 'console_scripts', 'wifiphisher')())
  File "/usr/local/lib/python3.9/dist-packages/wifiphisher-1.4-py3.9.egg/wifiphisher/pywifiphisher.py", line 729, in run
    engine.start()
  File "/usr/local/lib/python3.9/dist-packages/wifiphisher-1.4-py3.9.egg/wifiphisher/pywifiphisher.py", line 503, in start
    self.network_manager.unblock_interface(ap_iface)
  File "/usr/local/lib/python3.9/dist-packages/wifiphisher-1.4-py3.9.egg/wifiphisher/common/interfaces.py", line 647, in unblock_interface
    if pyw.isblocked(card):
  File "/usr/local/lib/python3.9/dist-packages/PyRIC-0.1.6.4-py3.9.egg/pyric/pyw.py", line 624, in isblocked
    idx = rfkill.getidx(card.phy)
  File "/usr/local/lib/python3.9/dist-packages/PyRIC-0.1.6.4-py3.9.egg/pyric/utils/rfkill.py", line 200, in getidx
    rfks = rfkill_list()
  File "/usr/local/lib/python3.9/dist-packages/PyRIC-0.1.6.4-py3.9.egg/pyric/utils/rfkill.py", line 86, in rfkill_list
    'soft':RFKILL_STATE[s],
IndexError: list index out of range

**Comment by brandontict** [comment]
I receive exact error. 

I am on latest version of Kali 2021 rolling. 

Alfa drivers are up to date. 

I have been using Wifiphisher for years, great program. I am stumped at this point and welcome any insight !  

I have tried disabling network manager as well as manually setting card into monitor mode, and using airmon-ng . No luck .

**Comment by devilmen80** [comment]
ok try to install it from database with apt.
If still don't work you must change the file interfaces.py that was modified from the author of this program. There is a new commit. #1471

**Comment by ZXF-BW** [comment]
I fixed it. Here is how I made it: [https://github.com/wifiphisher/wifiphisher/issues/1522#issuecomment-1174117620](https://github.com/wifiphisher/wifiphisher/issues/1522#issuecomment-1174117620)
