### ISSUE TITLE
import scapy.arch.lixux as linux ModuleNotFoundError: No module named 'scapy'

### ISSUE THREAD

**Issue by comicallybad** [wifiphisher/wifiphisher#1506]
I am on the latest version of wifiphisher, and I am running Kali Linux. I keep getting this error I will list below. I have tried everything, a lot of solution say to `sudo apt-get install python-scapy` however, it says that package is not found, did you mean `python3-scapy`? I was able to troubleshoot and resolve all the missing packages that the errors kept showing, but this one I cannot find a solution for. I have tried every solution I could find, and all resulted in the same error, or put me back to the earlier packages that weren't found being not found again, and I would have to go through the process of fixing that. As well, `easy_install` is not being installed with the setup.py. It's not much of an issue, but I can't install easy_install.

Anyways here is my full error (I can run `sudo python3 setup.py install` and `sudo python3 setup.py build` with no errors at all, if I try to just run `sudo python setup.py install` I am told that I must use python3):
```
Traceback (most recent call last):
  File "/usr/local/bin/wifiphisher", line 33, in <module>
    sys.exit(load_entry_point('wifiphisher==1.4', 'console_scripts', 'wifiphisher')())
  File "/usr/local/bin/wifiphisher", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib/python3.9/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/usr/local/lib/python3.9/dist-packages/wifiphisher-1.4-py3.9.egg/wifiphisher/pywifiphisher.py", line 25, in <module>
    import wifiphisher.common.extensions as extensions
  File "/usr/local/lib/python3.9/dist-packages/wifiphisher-1.4-py3.9.egg/wifiphisher/common/extensions.py", line 12, in <module>
    import scapy.arch.linux as linux
ModuleNotFoundError: No module named 'scapy'
```
If I try to run `scapy --version` I get this:
```
Traceback (most recent call last):
  File "/usr/local/bin/scapy", line 33, in <module>
    sys.exit(load_entry_point('scapy==2.4.4', 'console_scripts', 'scapy')())
  File "/usr/local/bin/scapy", line 22, in importlib_load_entry_point
    for entry_point in distribution(dist_name).entry_points
  File "/usr/lib/python3.9/importlib/metadata.py", line 524, in distribution
    return Distribution.from_name(distribution_name)
  File "/usr/lib/python3.9/importlib/metadata.py", line 187, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: scapy
```

**Comment by comicallybad** [comment]
This is my `sudo ./setup.py install` log:
```
sudo ./setup.py install
running install
/usr/local/lib/python3.9/dist-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
/usr/local/lib/python3.9/dist-packages/setuptools/command/easy_install.py:160: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
/usr/local/lib/python3.9/dist-packages/pkg_resources/__init__.py:122: PkgResourcesDeprecationWarning: 1.12.1-git20200711.33e2d80-dfsg1-0.6 is an invalid version and will not be supported in a future release
  warnings.warn(
running bdist_egg
running egg_info
writing wifiphisher.egg-info/PKG-INFO
writing dependency_links to wifiphisher.egg-info/dependency_links.txt
writing entry points to wifiphisher.egg-info/entry_points.txt
writing requirements to wifiphisher.egg-info/requires.txt
writing top-level names to wifiphisher.egg-info/top_level.txt
reading manifest file 'wifiphisher.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
adding license file 'LICENSE.txt'
writing manifest file 'wifiphisher.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/wifiphisher
copying build/lib/wifiphisher/pywifiphisher.py -> build/bdist.linux-x86_64/egg/wifiphisher
creating build/bdist.linux-x86_64/egg/wifiphisher/common
copying build/lib/wifiphisher/common/interfaces.py -> build/bdist.linux-x86_64/egg/wifiphisher/common
copying build/lib/wifiphisher/common/accesspoint.py -> build/bdist.linux-x86_64/egg/wifiphisher/common
copying build/lib/wifiphisher/common/uimethods.py -> build/bdist.linux-x86_64/egg/wifiphisher/common
copying build/lib/wifiphisher/common/phishingpage.py -> build/bdist.linux-x86_64/egg/wifiphisher/common
copying build/lib/wifiphisher/common/opmode.py -> build/bdist.linux-x86_64/egg/wifiphisher/common
copying build/lib/wifiphisher/common/firewall.py -> build/bdist.linux-x86_64/egg/wifiphisher/common
copying build/lib/wifiphisher/common/constants.py -> build/bdist.linux-x86_64/egg/wifiphisher/common
copying build/lib/wifiphisher/common/utilities.py -> build/bdist.linux-x86_64/egg/wifiphisher/common
copying build/lib/wifiphisher/common/macmatcher.py -> build/bdist.linux-x86_64/egg/wifiphisher/common
copying build/lib/wifiphisher/common/victim.py -> build/bdist.linux-x86_64/egg/wifiphisher/common
copying build/lib/wifiphisher/common/recon.py -> build/bdist.linux-x86_64/egg/wifiphisher/common
copying build/lib/wifiphisher/common/__init__.py -> build/bdist.linux-x86_64/egg/wifiphisher/common
copying build/lib/wifiphisher/common/globals.py -> build/bdist.linux-x86_64/egg/wifiphisher/common
copying build/lib/wifiphisher/common/phishinghttp.py -> build/bdist.linux-x86_64/egg/wifiphisher/common
copying build/lib/wifiphisher/common/tui.py -> build/bdist.linux-x86_64/egg/wifiphisher/common
copying build/lib/wifiphisher/common/extensions.py -> build/bdist.linux-x86_64/egg/wifiphisher/common
creating build/bdist.linux-x86_64/egg/wifiphisher/extensions
copying build/lib/wifiphisher/extensions/wpspbc.py -> build/bdist.linux-x86_64/egg/wifiphisher/extensions
copying build/lib/wifiphisher/extensions/handshakeverify.py -> build/bdist.linux-x86_64/egg/wifiphisher/extensions
copying build/lib/wifiphisher/extensions/roguehostapdinfo.py -> build/bdist.linux-x86_64/egg/wifiphisher/extensions
copying build/lib/wifiphisher/extensions/__init__.py -> build/bdist.linux-x86_64/egg/wifiphisher/extensions
copying build/lib/wifiphisher/extensions/knownbeacons.py -> build/bdist.linux-x86_64/egg/wifiphisher/extensions
copying build/lib/wifiphisher/extensions/deauth.py -> build/bdist.linux-x86_64/egg/wifiphisher/extensions
copying build/lib/wifiphisher/extensions/lure10.py -> build/bdist.linux-x86_64/egg/wifiphisher/extensions
copying build/lib/wifiphisher/__init__.py -> build/bdist.linux-x86_64/egg/wifiphisher
creating build/bdist.linux-x86_64/egg/wifiphisher/data
copying build/lib/wifiphisher/data/wifiphisher-known-open-wlans -> build/bdist.linux-x86_64/egg/wifiphisher/data
creating build/bdist.linux-x86_64/egg/wifiphisher/data/cert
copying build/lib/wifiphisher/data/cert/server.pem -> build/bdist.linux-x86_64/egg/wifiphisher/data/cert
creating build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages
creating build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/firmware-upgrade
creating build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/firmware-upgrade/html
copying build/lib/wifiphisher/data/phishing-pages/firmware-upgrade/html/loading.html -> build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/firmware-upgrade/html
copying build/lib/wifiphisher/data/phishing-pages/firmware-upgrade/html/bootstrap.min.css -> build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/firmware-upgrade/html
copying build/lib/wifiphisher/data/phishing-pages/firmware-upgrade/html/upgrading.html -> build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/firmware-upgrade/html
copying build/lib/wifiphisher/data/phishing-pages/firmware-upgrade/html/index.html -> build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/firmware-upgrade/html
copying build/lib/wifiphisher/data/phishing-pages/firmware-upgrade/html/jquery.min.js -> build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/firmware-upgrade/html
copying build/lib/wifiphisher/data/phishing-pages/firmware-upgrade/html/bootstrap.min.js -> build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/firmware-upgrade/html
creating build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/firmware-upgrade/html/static
copying build/lib/wifiphisher/data/phishing-pages/firmware-upgrade/html/static/bootstrap.min.css -> build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/firmware-upgrade/html/static
copying build/lib/wifiphisher/data/phishing-pages/firmware-upgrade/html/static/jquery.min.js -> build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/firmware-upgrade/html/static
creating build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/firmware-upgrade/html/static/font-awesome-4.7.0
creating build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/firmware-upgrade/html/static/font-awesome-4.7.0/css
copying build/lib/wifiphisher/data/phishing-pages/firmware-upgrade/html/static/font-awesome-4.7.0/css/font-awesome.css -> build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/firmware-upgrade/html/static/font-awesome-4.7.0/css
copying build/lib/wifiphisher/data/phishing-pages/firmware-upgrade/html/static/font-awesome-4.7.0/css/font-awesome.min.css -> build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/firmware-upgrade/html/static/font-awesome-4.7.0/css
creating build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/firmware-upgrade/html/static/font-awesome-4.7.0/fonts
copying build/lib/wifiphisher/data/phishing-pages/firmware-upgrade/html/static/font-awesome-4.7.0/fonts/fontawesome-webfont.eot -> build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/firmware-upgrade/html/static/font-awesome-4.7.0/fonts
copying build/lib/wifiphisher/data/phishing-pages/firmware-upgrade/html/static/font-awesome-4.7.0/fonts/fontawesome-webfont.woff -> build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/firmware-upgrade/html/static/font-awesome-4.7.0/fonts
copying build/lib/wifiphisher/data/phishing-pages/firmware-upgrade/html/static/font-awesome-4.7.0/fonts/fontawesome-webfont.woff2 -> build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/firmware-upgrade/html/static/font-awesome-4.7.0/fonts
copying build/lib/wifiphisher/data/phishing-pages/firmware-upgrade/html/static/font-awesome-4.7.0/fonts/fontawesome-webfont.ttf -> build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/firmware-upgrade/html/static/font-awesome-4.7.0/fonts
copying build/lib/wifiphisher/data/phishing-pages/firmware-upgrade/html/static/font-awesome-4.7.0/fonts/fontawesome-webfont.svg -> build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/firmware-upgrade/html/static/font-awesome-4.7.0/fonts
copying build/lib/wifiphisher/data/phishing-pages/firmware-upgrade/html/static/font-awesome-4.7.0/fonts/FontAwesome.otf -> build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/firmware-upgrade/html/static/font-awesome-4.7.0/fonts
copying build/lib/wifiphisher/data/phishing-pages/firmware-upgrade/html/static/bootstrap.min.js -> build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/firmware-upgrade/html/static
copying build/lib/wifiphisher/data/phishing-pages/firmware-upgrade/config.ini -> build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/firmware-upgrade
creating build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/plugin_update
creating build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/plugin_update/html
creating build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/plugin_update/html/js
copying build/lib/wifiphisher/data/phishing-pages/plugin_update/html/js/jquery.js -> build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/plugin_update/html/js
copying build/lib/wifiphisher/data/phishing-pages/plugin_update/html/js/bootstrap.min.js -> build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/plugin_update/html/js
creating build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/plugin_update/html/css
copying build/lib/wifiphisher/data/phishing-pages/plugin_update/html/css/bootstrap.min.css -> build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/plugin_update/html/css
copying build/lib/wifiphisher/data/phishing-pages/plugin_update/html/css/theme.css -> build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/plugin_update/html/css
copying build/lib/wifiphisher/data/phishing-pages/plugin_update/html/index.html -> build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/plugin_update/html
creating build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/plugin_update/html/images
copying build/lib/wifiphisher/data/phishing-pages/plugin_update/html/images/favicon.ico -> build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/plugin_update/html/images
copying build/lib/wifiphisher/data/phishing-pages/plugin_update/html/images/plugins.png -> build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/plugin_update/html/images
creating build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/plugin_update/html/static
creating build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/plugin_update/html/static/js
copying build/lib/wifiphisher/data/phishing-pages/plugin_update/html/static/js/jquery.js -> build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/plugin_update/html/static/js
copying build/lib/wifiphisher/data/phishing-pages/plugin_update/html/static/js/bootstrap.min.js -> build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/plugin_update/html/static/js
creating build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/plugin_update/html/static/css
copying build/lib/wifiphisher/data/phishing-pages/plugin_update/html/static/css/bootstrap.min.css -> build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/plugin_update/html/static/css
copying build/lib/wifiphisher/data/phishing-pages/plugin_update/html/static/css/theme.css -> build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/plugin_update/html/static/css
creating build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/plugin_update/html/static/images
copying build/lib/wifiphisher/data/phishing-pages/plugin_update/html/static/images/favicon.ico -> build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/plugin_update/html/static/images
copying build/lib/wifiphisher/data/phishing-pages/plugin_update/html/static/images/plugins.png -> build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/plugin_update/html/static/images
creating build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/plugin_update/html/static/update
copying build/lib/wifiphisher/data/phishing-pages/plugin_update/html/static/update/update.exe -> build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/plugin_update/html/static/update
creating build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/plugin_update/html/update
copying build/lib/wifiphisher/data/phishing-pages/plugin_update/html/update/update.exe -> build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/plugin_update/html/update
copying build/lib/wifiphisher/data/phishing-pages/plugin_update/config.ini -> build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/plugin_update
creating build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/oauth-login
creating build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/oauth-login/html
copying build/lib/wifiphisher/data/phishing-pages/oauth-login/html/login.html -> build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/oauth-login/html
copying build/lib/wifiphisher/data/phishing-pages/oauth-login/html/index.html -> build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/oauth-login/html
copying build/lib/wifiphisher/data/phishing-pages/oauth-login/html/fail.html -> build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/oauth-login/html
copying build/lib/wifiphisher/data/phishing-pages/oauth-login/html/template.html -> build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/oauth-login/html
creating build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/oauth-login/html/static
creating build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/oauth-login/html/static/js
copying build/lib/wifiphisher/data/phishing-pages/oauth-login/html/static/js/popup.js -> build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/oauth-login/html/static/js
copying build/lib/wifiphisher/data/phishing-pages/oauth-login/html/static/js/jquery.min.js -> build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/oauth-login/html/static/js
copying build/lib/wifiphisher/data/phishing-pages/oauth-login/html/static/js/index.js -> build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/oauth-login/html/static/js
copying build/lib/wifiphisher/data/phishing-pages/oauth-login/html/static/js/jsframe.js -> build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/oauth-login/html/static/js
creating build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/oauth-login/html/static/css
copying build/lib/wifiphisher/data/phishing-pages/oauth-login/html/static/css/font-awesome.css -> build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/oauth-login/html/static/css
copying build/lib/wifiphisher/data/phishing-pages/oauth-login/html/static/css/roboto.css -> build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/oauth-login/html/static/css
copying build/lib/wifiphisher/data/phishing-pages/oauth-login/html/static/css/normalize.min.css -> build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/oauth-login/html/static/css
copying build/lib/wifiphisher/data/phishing-pages/oauth-login/html/static/css/reset.css -> build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/oauth-login/html/static/css
copying build/lib/wifiphisher/data/phishing-pages/oauth-login/html/static/css/font-awesome.min.css -> build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/oauth-login/html/static/css
copying build/lib/wifiphisher/data/phishing-pages/oauth-login/html/static/css/style.css -> build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/oauth-login/html/static/css
copying build/lib/wifiphisher/data/phishing-pages/oauth-login/html/static/ssl.png -> build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/oauth-login/html/static
copying build/lib/wifiphisher/data/phishing-pages/oauth-login/html/oauth.html -> build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/oauth-login/html
copying build/lib/wifiphisher/data/phishing-pages/oauth-login/config.ini -> build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/oauth-login
creating build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/wifi_connect
creating build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/wifi_connect/html
copying build/lib/wifiphisher/data/phishing-pages/wifi_connect/html/opensans.ttf -> build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/wifi_connect/html
copying build/lib/wifiphisher/data/phishing-pages/wifi_connect/html/loading.html -> build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/wifi_connect/html
copying build/lib/wifiphisher/data/phishing-pages/wifi_connect/html/dinosaur.png -> build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/wifi_connect/html
copying build/lib/wifiphisher/data/phishing-pages/wifi_connect/html/wifi-icon.png -> build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/wifi_connect/html
copying build/lib/wifiphisher/data/phishing-pages/wifi_connect/html/mac-network-manager.css -> build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/wifi_connect/html
copying build/lib/wifiphisher/data/phishing-pages/wifi_connect/html/index.html -> build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/wifi_connect/html
copying build/lib/wifiphisher/data/phishing-pages/wifi_connect/html/win-behavior.js -> build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/wifi_connect/html
copying build/lib/wifiphisher/data/phishing-pages/wifi_connect/html/chrome-offline.css -> build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/wifi_connect/html
copying build/lib/wifiphisher/data/phishing-pages/wifi_connect/html/question.png -> build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/wifi_connect/html
copying build/lib/wifiphisher/data/phishing-pages/wifi_connect/html/behavior.js -> build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/wifi_connect/html
copying build/lib/wifiphisher/data/phishing-pages/wifi_connect/html/opensans.css -> build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/wifi_connect/html
copying build/lib/wifiphisher/data/phishing-pages/wifi_connect/html/style.css -> build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/wifi_connect/html
creating build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/wifi_connect/html/static
copying build/lib/wifiphisher/data/phishing-pages/wifi_connect/html/static/opensans.ttf -> build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/wifi_connect/html/static
copying build/lib/wifiphisher/data/phishing-pages/wifi_connect/html/static/dinosaur.png -> build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/wifi_connect/html/static
copying build/lib/wifiphisher/data/phishing-pages/wifi_connect/html/static/wifi-icon.png -> build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/wifi_connect/html/static
copying build/lib/wifiphisher/data/phishing-pages/wifi_connect/html/static/mac-network-manager.css -> build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/wifi_connect/html/static
copying build/lib/wifiphisher/data/phishing-pages/wifi_connect/html/static/win-behavior.js -> build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/wifi_connect/html/static
copying build/lib/wifiphisher/data/phishing-pages/wifi_connect/html/static/ios.css -> build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/wifi_connect/html/static
copying build/lib/wifiphisher/data/phishing-pages/wifi_connect/html/static/chrome-offline.css -> build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/wifi_connect/html/static
copying build/lib/wifiphisher/data/phishing-pages/wifi_connect/html/static/question.png -> build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/wifi_connect/html/static
copying build/lib/wifiphisher/data/phishing-pages/wifi_connect/html/static/behavior.js -> build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/wifi_connect/html/static
copying build/lib/wifiphisher/data/phishing-pages/wifi_connect/html/static/opensans.css -> build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/wifi_connect/html/static
copying build/lib/wifiphisher/data/phishing-pages/wifi_connect/html/static/style.css -> build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/wifi_connect/html/static
copying build/lib/wifiphisher/data/phishing-pages/wifi_connect/config.ini -> build/bdist.linux-x86_64/egg/wifiphisher/data/phishing-pages/wifi_connect
creating build/bdist.linux-x86_64/egg/wifiphisher/data/locs
copying build/lib/wifiphisher/data/locs/.gitkeep -> build/bdist.linux-x86_64/egg/wifiphisher/data/locs
copying build/lib/wifiphisher/data/wifiphisher-mac-prefixes -> build/bdist.linux-x86_64/egg/wifiphisher/data
copying build/lib/wifiphisher/data/wifiphisher-os-initial-requests -> build/bdist.linux-x86_64/egg/wifiphisher/data
byte-compiling build/bdist.linux-x86_64/egg/wifiphisher/pywifiphisher.py to pywifiphisher.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/wifiphisher/common/interfaces.py to interfaces.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/wifiphisher/common/accesspoint.py to accesspoint.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/wifiphisher/common/uimethods.py to uimethods.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/wifiphisher/common/phishingpage.py to phishingpage.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/wifiphisher/common/opmode.py to opmode.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/wifiphisher/common/firewall.py to firewall.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/wifiphisher/common/constants.py to constants.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/wifiphisher/common/utilities.py to utilities.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/wifiphisher/common/macmatcher.py to macmatcher.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/wifiphisher/common/victim.py to victim.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/wifiphisher/common/recon.py to recon.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/wifiphisher/common/__init__.py to __init__.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/wifiphisher/common/globals.py to globals.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/wifiphisher/common/phishinghttp.py to phishinghttp.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/wifiphisher/common/tui.py to tui.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/wifiphisher/common/extensions.py to extensions.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/wifiphisher/extensions/wpspbc.py to wpspbc.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/wifiphisher/extensions/handshakeverify.py to handshakeverify.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/wifiphisher/extensions/roguehostapdinfo.py to roguehostapdinfo.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/wifiphisher/extensions/__init__.py to __init__.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/wifiphisher/extensions/knownbeacons.py to knownbeacons.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/wifiphisher/extensions/deauth.py to deauth.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/wifiphisher/extensions/lure10.py to lure10.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/wifiphisher/__init__.py to __init__.cpython-39.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying wifiphisher.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying wifiphisher.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying wifiphisher.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying wifiphisher.egg-info/entry_points.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying wifiphisher.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying wifiphisher.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
wifiphisher.common.__pycache__.constants.cpython-39: module references __file__
creating 'dist/wifiphisher-1.4-py3.9.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing wifiphisher-1.4-py3.9.egg
removing '/usr/lib/python3.9/site-packages/wifiphisher-1.4-py3.9.egg' (and everything under it)
creating /usr/lib/python3.9/site-packages/wifiphisher-1.4-py3.9.egg
Extracting wifiphisher-1.4-py3.9.egg to /usr/lib/python3.9/site-packages
wifiphisher 1.4 is already the active version in easy-install.pth
Installing wifiphisher script to /usr/bin

Installed /usr/lib/python3.9/site-packages/wifiphisher-1.4-py3.9.egg
/usr/local/lib/python3.9/dist-packages/pkg_resources/__init__.py:122: PkgResourcesDeprecationWarning:  is an invalid version and will not be supported in a future release
  warnings.warn(
Processing dependencies for wifiphisher==1.4
Searching for tornado==6.1
Best match: tornado 6.1
Processing tornado-6.1-py3.9-linux-x86_64.egg
tornado 6.1 is already the active version in easy-install.pth

Using /usr/lib/python3.9/site-packages/tornado-6.1-py3.9-linux-x86_64.egg
Searching for scapy==2.4.5
Best match: scapy 2.4.5
Processing scapy-2.4.5-py3.9.egg
scapy 2.4.5 is already the active version in easy-install.pth
Installing UTscapy script to /usr/bin
Installing scapy script to /usr/bin

Using /usr/lib/python3.9/site-packages/scapy-2.4.5-py3.9.egg
Searching for roguehostapd==1.1.2
Best match: roguehostapd 1.1.2
Processing roguehostapd-1.1.2-py3.9-linux-x86_64.egg
roguehostapd 1.1.2 is already the active version in easy-install.pth

Using /usr/local/lib/python3.9/dist-packages/roguehostapd-1.1.2-py3.9-linux-x86_64.egg
Searching for PyRIC==0.1.6.4
Best match: PyRIC 0.1.6.4
Processing PyRIC-0.1.6.4-py3.9.egg
PyRIC 0.1.6.4 is already the active version in easy-install.pth

Using /usr/local/lib/python3.9/dist-packages/PyRIC-0.1.6.4-py3.9.egg
Searching for pbkdf2==1.3
Best match: pbkdf2 1.3
Processing pbkdf2-1.3-py3.9.egg
pbkdf2 1.3 is already the active version in easy-install.pth

Using /usr/local/lib/python3.9/dist-packages/pbkdf2-1.3-py3.9.egg
Finished processing dependencies for wifiphisher==1.4
```

**Comment by devilmen80** [comment]
ok try to install it from database with apt.
If still don't work you must change the file interface.py that was modified from the author of this program. There is a new commit.
