### ISSUE TITLE
Module not found error: No module named 'pyric'

### ISSUE THREAD

**Issue by CrissGill** [wifiphisher/wifiphisher#1512]

**Comment by achdu0000** [comment]
I have the same error. ):

**Comment by anees-tech** [comment]
I have also the same issue...

**Comment by anees-tech** [comment]
> ┌──(root㉿kali)-[/home/criss/wifiphisher] └─# wifiphisher [*] Starting Wifiphisher 1.4GIT ( https://wifiphisher.org ) at 2022-04-01 15:40 [+] Timezone detected. Setting channel range to 1-13 [+] Selecting wlan0 interface for the deauthentication attack [+] Selecting wlan1 interface for creating the rogue Access Point [+] Changing wlan1 MAC addr (BSSID) to 00:00:00:fe:ea:55 [+] Changing wlan1 MAC addr (BSSID) to 00:00:00:10:b8:99 Traceback (most recent call last): File "/usr/local/bin/wifiphisher", line 33, in sys.exit(load_entry_point('wifiphisher==1.4', 'console_scripts', 'wifiphisher')()) File "/usr/local/lib/python3.9/dist-packages/wifiphisher-1.4-py3.9.egg/wifiphisher/pywifiphisher.py", line 729, in run engine.start() File "/usr/local/lib/python3.9/dist-packages/wifiphisher-1.4-py3.9.egg/wifiphisher/pywifiphisher.py", line 503, in start self.network_manager.unblock_interface(ap_iface) File "/usr/local/lib/python3.9/dist-packages/wifiphisher-1.4-py3.9.egg/wifiphisher/common/interfaces.py", line 648, in unblock_interface if pyw.isblocked(card): File "/usr/local/lib/python3.9/dist-packages/PyRIC-0.1.6.4-py3.9.egg/pyric/pyw.py", line 624, in isblocked idx = rfkill.getidx(card.phy) File "/usr/local/lib/python3.9/dist-packages/PyRIC-0.1.6.4-py3.9.egg/pyric/utils/rfkill.py", line 200, in getidx rfks = rfkill_list() File "/usr/local/lib/python3.9/dist-packages/PyRIC-0.1.6.4-py3.9.egg/pyric/utils/rfkill.py", line 86, in rfkill_list 'soft':RFKILL_STATE[s], IndexError: list index out of range




Do You find something>>>>?????????????

**Comment by achdu0000** [comment]
It seems no one maintains the wifiphisher. What a pity!

**Comment by ZXF-BW** [comment]
I fixed it. Here is how I made it: [https://github.com/wifiphisher/wifiphisher/issues/1522#issuecomment-1174117620](https://github.com/wifiphisher/wifiphisher/issues/1522#issuecomment-1174117620)
