### ISSUE TITLE
system not suppoarted 

### ISSUE THREAD

**Issue by kishwordulal** [wifiphisher/wifiphisher#1528]
[*] Starting Wifiphisher 1.4GIT ( https://wifiphisher.org ) at 2022-07-07 06:58
[+] Timezone detected. Setting channel range to 1-13
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pyric/pyw.py", line 1070, in devinfo
    rmsg = nl.nl_recvmsg(nlsock)
  File "/usr/lib/python3/dist-packages/pyric/lib/libnl.py", line 244, in nl_recvmsg
    msg = nlmsg_fromstream(sock.recv())
  File "/usr/lib/python3/dist-packages/pyric/lib/libnl.py", line 444, in nlmsg_fromstream
    raise error(abs(e),strerror(abs(e)))
libnl.error: [Errno 19] No such device

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/wifiphisher", line 33, in <module>
    sys.exit(load_entry_point('wifiphisher==1.4', 'console_scripts', 'wifiphisher')())
  File "/usr/lib/python3/dist-packages/wifiphisher/pywifiphisher.py", line 728, in run
    engine.start()
  File "/usr/lib/python3/dist-packages/wifiphisher/pywifiphisher.py", line 407, in start
    self.opmode.initialize(args)
  File "/usr/lib/python3/dist-packages/wifiphisher/common/opmode.py", line 54, in initialize
    interfaces.is_add_vif_required(args.interface, 
  File "/usr/lib/python3/dist-packages/wifiphisher/common/interfaces.py", line 813, in is_add_vif_required
    card = pyw.getcard(vif)
  File "/usr/lib/python3/dist-packages/pyric/pyw.py", line 277, in getcard
    if nlsock is None: return _nlstub_(getcard, dev)
  File "/usr/lib/python3/dist-packages/pyric/pyw.py", line 2279, in _nlstub_
    return fct(*argv)
  File "/usr/lib/python3/dist-packages/pyric/pyw.py", line 278, in getcard
    return devinfo(dev, nlsock)['card']
  File "/usr/lib/python3/dist-packages/pyric/pyw.py", line 1083, in devinfo
    raise pyric.error(pyric.EPROTONOSUPPORT, "Device does not support nl80211")
pyric.error: [Errno 93] Device does not support nl80211

**Comment by kishwordulal1234** [comment]
why it is invalide
