### ISSUE TITLE
python setup.py install gives error

### ISSUE THREAD

**Issue by zodiacc20** [wifiphisher/wifiphisher#1568]
(root㉿kali)-[/home/zodiac/wifiphisher]
└─# sudo python setup.py install
running install
/usr/local/lib/python3.10/dist-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/setuptools/command/easy_install.py:144: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
Traceback (most recent call last):
  File "/home/zodiac/wifiphisher/setup.py", line 169, in <module>
    setup(name=NAME, author=AUTHOR, author_email=AUTHOR_EMAIL, description=DESCRIPTION,
  File "/usr/local/lib/python3.10/dist-packages/setuptools/__init__.py", line 108, in setup
    return distutils.core.setup(**attrs)
  File "/usr/local/lib/python3.10/dist-packages/setuptools/_distutils/core.py", line 185, in setup
    return run_commands(dist)
  File "/usr/local/lib/python3.10/dist-packages/setuptools/_distutils/core.py", line 201, in run_commands
    dist.run_commands()
  File "/usr/local/lib/python3.10/dist-packages/setuptools/_distutils/dist.py", line 969, in run_commands
    self.run_command(cmd)
  File "/usr/local/lib/python3.10/dist-packages/setuptools/dist.py", line 1213, in run_command
    super().run_command(command)
  File "/usr/local/lib/python3.10/dist-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/usr/local/lib/python3.10/dist-packages/setuptools/command/install.py", line 74, in run
    self.do_egg_install()
  File "/usr/local/lib/python3.10/dist-packages/setuptools/command/install.py", line 117, in do_egg_install
    cmd.ensure_finalized()  # finalize before bdist_egg munges install cmd
  File "/usr/local/lib/python3.10/dist-packages/setuptools/_distutils/cmd.py", line 111, in ensure_finalized
    self.finalize_options()
  File "/usr/local/lib/python3.10/dist-packages/setuptools/command/easy_install.py", line 311, in finalize_options
    self.local_index = Environment(self.shadow_path + sys.path)
  File "/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py", line 1044, in __init__
    self.scan(search_path)
  File "/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py", line 1077, in scan
    self.add(dist)
  File "/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py", line 1096, in add
    dists.sort(key=operator.attrgetter('hashcmp'), reverse=True)
  File "/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py", line 2631, in hashcmp
    self.parsed_version,
  File "/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py", line 2685, in parsed_version
    raise packaging.version.InvalidVersion(f"{str(ex)} {info}") from None
pkg_resources.extern.packaging.version.InvalidVersion: Invalid version: '2.3.0-nmu1-b1' (package: python-apt)

plz help

**Comment by RassimKerassin** [comment]
How did you solve the problem?

**Comment by zodiacc20** [comment]
I couldn't solve the problem. I found another alternative repository.

I am sorry for my late answer

**Comment by zodiacc20** [comment]
> How did you solve the problem?

I couldn't solve the problem. I found another alternative repository.

I am sorry for my late answer

**Comment by craftycram** [comment]
I'm experiencing the issue as well

**Comment by W4RR3N7-3XP14Y** [comment]
i have both of these issues too!

root@kali:~# git clone https://github.com/wifiphisher/wifiphisher.git 
Cloning into 'wifiphisher'...
remote: Enumerating objects: 3964, done.
remote: Counting objects: 100% (17/17), done.
remote: Compressing objects: 100% (15/15), done.
remote: Total 3964 (delta 3), reused 7 (delta 2), pack-reused 3947
Receiving objects: 100% (3964/3964), 12.56 MiB | 7.82 MiB/s, done.
Resolving deltas: 100% (2497/2497), done.
root@kali:~# cd wifiphisher
root@kali:~/wifiphisher# sudo python setup.py install
Please use Python 3 to install Wifiphisher.
root@kali:~/wifiphisher# sudo python3 setup.py install
/root/wifiphisher/setup.py:19: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
  import distutils.sysconfig
/root/wifiphisher/setup.py:19: DeprecationWarning: The distutils.sysconfig module is deprecated, use sysconfig instead
  import distutils.sysconfig
/tmp/tmp_netlink_we3k00we/test_netlink.c:2:10: fatal error: netlink/netlink.h: No such file or directory
    2 | #include <netlink/netlink.h>
      |          ^~~~~~~~~~~~~~~~~~~
compilation terminated.
The development package for netlink is required for the compilation of roguehostapd. Please install it and rerun the script (e.g. on Debian-based systems run: apt-get install libnl-3-dev libnl-genl-3-dev
