### ISSUE TITLE
In start up: TypeError: write() argument must be str, not bytes 

### ISSUE THREAD

**Issue by eskahacker** [wifiphisher/wifiphisher#1583]
ubuntu23@ubuntu23-VirtualBox:~$ sudo wifiphisher 
[*] Starting Wifiphisher 1.4GIT ( https://wifiphisher.org ) at 2023-04-17 20:52
[+] Timezone detected. Setting channel range to 1-13
[+] Selecting wfphshr-wlan0 interface for the deauthentication attack
[+] Selecting wlx90f652107b45 interface for creating the rogue Access Point
[+] Changing wlx90f652107b45 MAC addr (BSSID) to 00:00:00:68:ca:2c
[+] Changing wlx90f652107b45 MAC addr (BSSID) to 00:00:00:18:f0:3a
Traceback (most recent call last):
  File "/usr/local/bin/wifiphisher", line 33, in <module>
    sys.exit(load_entry_point('wifiphisher==1.4', 'console_scripts', 'wifiphisher')())
  File "/usr/local/lib/python3.10/dist-packages/wifiphisher-1.4-py3.10.egg/wifiphisher/pywifiphisher.py", line 762, in run
    engine.start()
  File "/usr/local/lib/python3.10/dist-packages/wifiphisher-1.4-py3.10.egg/wifiphisher/pywifiphisher.py", line 536, in start
    self.network_manager.unblock_interface(ap_iface)
  File "/usr/local/lib/python3.10/dist-packages/wifiphisher-1.4-py3.10.egg/wifiphisher/common/interfaces.py", line 649, in unblock_interface
    pyw.unblock(card)
  File "/usr/local/lib/python3.10/dist-packages/PyRIC-0.1.6.4-py3.10.egg/pyric/pyw.py", line 649, in unblock
    rfkill.rfkill_unblock(idx)
  File "/usr/local/lib/python3.10/dist-packages/PyRIC-0.1.6.4-py3.10.egg/pyric/utils/rfkill.py", line 135, in rfkill_unblock
    fout.write(rfke)
TypeError: write() argument must be str, not bytes

**Comment by eskahacker** [comment]
Ubuntu version: 20.04
VirtualBox version: 7.1
wifi adapter: Atheros AR9271
