### ISSUE TITLE
scapy.layers.dot11 Error !!! 

### ISSUE THREAD

**Issue by kali64amd** [wifiphisher/wifiphisher#1591]
ISSUE :-1

─$ sudo python wifiphisher 
Traceback (most recent call last):
  File "wifiphisher", line 16, in <module>
    
  File "/home/shinobix/Desktop/Tool/wifiphisher/wifiphisher/pywifiphisher.py", line 20, in <module>
    import wifiphisher.common.extensions as extensions
  File "/home/shinobix/Desktop/Tool/wifiphisher/wifiphisher/common/extensions.py", line 11, in <module>
    import scapy.layers.dot11 as dot11
ImportError: No module named scapy.layers.dot11

I HAVE TRY :-1: 

sudo apt remove python-scapy
sudo pip install scapy OR sudo apt-get install sudo apt-get install python-scapy

Still Issue hasn't solve yet, I do believe it has been replace it with python3-scapy however it has already installed in kali.

So i'm clueless.

**Comment by Anonymous-Jr-3301** [comment]
same here
