### ISSUE TITLE
Wirfiphisher is not being launched. Please help if anyone knows how

### ISSUE THREAD

**Issue by ErlingHolann** [wifiphisher/wifiphisher#1592]
Installed wifiphisher, all according to the instructions. At startup , it outputs this kind of thing.I 've searched a bunch of sites, but I haven't found anything that would help. The "roguehostapd" module was installed separately, but the problem has not disappeared

Traceback (most recent call last):
  File "/usr/local/bin/wifiphisher", line 33, in <module>
    sys.exit(load_entry_point('wifiphisher==1.4', 'console_scripts', 'wifiphisher')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/bin/wifiphisher", line 25, in importlib_load_entry_point
    return next(matches).load()
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/metadata/__init__.py", line 202, in load
    module = import_module(match.group('module'))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/local/lib/python3.11/dist-packages/wifiphisher-1.4-py3.11.egg/wifiphisher/pywifiphisher.py", line 24, in <module>
    import wifiphisher.common.accesspoint as accesspoint
  File "/usr/local/lib/python3.11/dist-packages/wifiphisher-1.4-py3.11.egg/wifiphisher/common/accesspoint.py", line 11, in <module>
    import roguehostapd.apctrl as apctrl
ModuleNotFoundError: No module named 'roguehostapd'

**Comment by Oliverxyzabc** [comment]
Same issue how did you solved it?

**Comment by Oliverxyzabc** [comment]
I found a solution!!!! This will fix the problem

this probably an issue with "setuptools" being outdated.

pip install --upgrade setuptools
