### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by niroop893** [wifiphisher/wifiphisher#1595]
I have installed wifiphisher on ubuntu 22.04 getting the below error,

Traceback (most recent call last):
  File "/home/niroop/wifiphisher/bin/./wifiphisher", line 24, in <module>
    run()
  File "/usr/local/lib/python3.10/dist-packages/wifiphisher-1.4-py3.10.egg/wifiphisher/pywifiphisher.py", line 762, in run
    engine.start()
  File "/usr/local/lib/python3.10/dist-packages/wifiphisher-1.4-py3.10.egg/wifiphisher/pywifiphisher.py", line 536, in start
    self.network_manager.unblock_interface(ap_iface)
  File "/usr/local/lib/python3.10/dist-packages/wifiphisher-1.4-py3.10.egg/wifiphisher/common/interfaces.py", line 648, in unblock_interface
    if pyw.isblocked(card):
  File "/usr/local/lib/python3.10/dist-packages/PyRIC-0.1.6.4-py3.10.egg/pyric/pyw.py", line 624, in isblocked
    idx = rfkill.getidx(card.phy)
  File "/usr/local/lib/python3.10/dist-packages/PyRIC-0.1.6.4-py3.10.egg/pyric/utils/rfkill.py", line 200, in getidx
    rfks = rfkill_list()
  File "/usr/local/lib/python3.10/dist-packages/PyRIC-0.1.6.4-py3.10.egg/pyric/utils/rfkill.py", line 86, in rfkill_list
    'soft':RFKILL_STATE[s],
IndexError: list index out of range

root@CT00569:/home/niroop/wifiphisher# rfkill list
0: ideapad_wlan: Wireless LAN
	Soft blocked: no
	Hard blocked: no
1: ideapad_bluetooth: Bluetooth
	Soft blocked: no
	Hard blocked: no
2: hci0: Bluetooth
	Soft blocked: no
	Hard blocked: no
3: phy0: Wireless LAN
	Soft blocked: no
	Hard blocked: no
root@CT00569:/home/niroop/wifiphisher#

**Comment by Gubriel** [comment]
This worked fine for me. #1429
