### ISSUE TITLE
phishing pages going crazy and some not

### ISSUE THREAD

**Issue by richoffpints** [wifiphisher/wifiphisher#1610]
some of my phing pages with are copys basically with diffrnt pictures and writing just nug out every looks fine "deauth, deauth.. " then out of no were the page breaks and one lineses index for the page isnt found and a few mroe trace back errors and such ,i cant find anything on it any ideas any bod eles running into similar problem? im ussaly able to find problems on my own so its not me being stupid or not knoledable my pages are litterly like, copys besides words and pics.

**Comment by richoffpints** [comment]
File "/usr/local/lib/python3.11/dist-packages/wifiphisher-1.4-py3.11.egg/wifiphisher/common/phishinghttp.py", line 102, in get                                                                                                         
           self.render(file_path, **template.get_context())                                                     
                                                             File "/usr/lib/python3/dist-packages/tornado/web.py", line 940, in render                                                                                          
                          html = self.render_string(template_name, **kwargs)                                    
                                                                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                              
                    File "/usr/lib/python3/dist-packages/tornado/web.py", line 1086, in render_string           
                                                                                                         t = loader.load(template_name)                                                                                         
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^                                                       
                                                           File "/usr/lib/python3/dist-packages/tornado/template.py", line 446, in load                                                                                         
                           self.templates[name] = self._create_template(name)                                   
                                                                                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                             
                     File "/usr/lib/python3/dist-packages/tornado/template.py", line 476, in _create_template   
                                                                                                                 with open(path, "rb") as f:                                                                                    
                                     ^^^^^^^^^^^^^^^^                                                           
                                                     FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/lib/python3.11/dist-packages/wifiphisher-1.4-py3.11.egg/wifiphisher/data/phishing-pages/combie/html/index.html'                                                                                                        
        Uncaught exception GET / (10.0.0.64)                                                                    
                                            HTTPServerRequest(protocol='http', host='netcts.cdn-apple.com', method='GET', uri='/', version='HTTP/1.0', remote_ip='10.0.0.64')                                                   
                                                             Traceback (most recent call last):                 
                                                                                                 File "/usr/lib/python3/dist-packages/tornado/web.py", line 1784, in _execute                                                   
                                                                 result = method(*self.path_args, **self.path_kwargs)                                                                                                           
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                   
                                                               File "/usr/local/lib/python3.11/dist-packages/wifiphisher-1.4-py3.11.egg/wifiphisher/common/phishinghttp.py", line 102, in get                                   
                                                                                 self.render(file_path, **template.get_context())                                                                                               
                   File "/usr/lib/python3/dist-packages/tornado/web.py", line 940, in render                    
                                                                                                html = self.render_string(template_name, **kwargs)                                                                              
                                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                        
                                                                                          File "/usr/lib/python3/dist-packages/tornado/web.py", line 1086, in render_string                                                     
                                                               t = loader.load(template_name)                   
                                                                                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                 
                 File "/usr/lib/python3/dist-packages/tornado/template.py", line 446, in load                   
                                                                                                 self.templates[name] = self._create_template(name)                                                                             
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^                       
                                                                                           File "/usr/lib/python3/dist-packages/tornado/template.py", line 476, in _create_template                                             
                                                                       with open(path, "rb") as f:              
                                                                                                           ^^^^^^^^^^^^^^^^                                                                                                     
           FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/lib/python3.11/dist-packages/wifiphisher-1.4-py3.11.egg/wifiphisher/data/phishing-pages/combie/html/index.html'

**Comment by richoffpints** [comment]
thats what comes up, and when that comes up the person cant connect to the portal but connects to the hot spot,
