### ISSUE TITLE
error while trying to select an interface

### ISSUE THREAD

**Issue by winqdev** [wifiphisher/wifiphisher#1626]
`└─# wifiphisher -i wlan1           
[*] Starting Wifiphisher 1.4GIT ( https://wifiphisher.org ) at 2023-12-25 14:02
[+] Timezone detected. Setting channel range to 1-13
Traceback (most recent call last):
  File "/usr/local/bin/wifiphisher", line 33, in <module>
    sys.exit(load_entry_point('wifiphisher==1.4', 'console_scripts', 'wifiphisher')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/wifiphisher-1.4-py3.11.egg/wifiphisher/pywifiphisher.py", line 762, in run
    engine.start()
  File "/usr/local/lib/python3.11/dist-packages/wifiphisher-1.4-py3.11.egg/wifiphisher/pywifiphisher.py", line 431, in start
    self.opmode.initialize(args)
  File "/usr/local/lib/python3.11/dist-packages/wifiphisher-1.4-py3.11.egg/wifiphisher/common/opmode.py", line 54, in initialize
    interfaces.is_add_vif_required(args.interface, 
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/wifiphisher-1.4-py3.11.egg/wifiphisher/common/interfaces.py", line 839, in is_add_vif_required
    raise InvalidInterfaceError(main_interface)
wifiphisher.common.interfaces.InvalidInterfaceError: The provided interface "wlan1" is invali`

**Comment by winqdev** [comment]
**My interfaces:**

`airmon-ng start wlan1         

Found 2 processes that could cause trouble.
Kill them using 'airmon-ng check kill' before putting
the card in monitor mode, they will interfere by changing channels
and sometimes putting the interface back in managed mode

    PID Name
   7620 NetworkManager
   7634 wpa_supplicant

PHY     Interface       Driver          Chipset

phy0    wlan0           ath9k           Qualcomm Atheros AR9462 Wireless Network Adapter (rev 01)
phy1    wlan1           mt7601u         Ralink Technology, Corp. MT7601U
                (mac80211 monitor mode already enabled for [phy1]wlan1 on [phy1]10)`

**Comment by winqdev** [comment]
ah, my wifi adapter just doesn't support AP mode
