### ISSUE TITLE
error on running

### ISSUE THREAD

**Issue by Aggelos11** [wifiphisher/wifiphisher#1638]
udo wifiphisher
[*] Starting Wifiphisher 1.4GIT ( https://wifiphisher.org/ ) at 2024-03-15 21:04
[+] Timezone detected. Setting channel range to 1-13
[+] Selecting wlan0 interface for the deauthentication attack
[+] Selecting wlan1 interface for creating the rogue Access Point
[+] Changing wlan1 MAC addr (BSSID) to 00:00:00:d4:12:aa
[+] Changing wlan1 MAC addr (BSSID) to 00:00:00:52:12:4b
Traceback (most recent call last):
File "/usr/bin/wifiphisher", line 33, in
sys.exit(load_entry_point('wifiphisher==1.4', 'console_scripts', 'wifiphisher')())
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3/dist-packages/wifiphisher/pywifiphisher.py", line 762, in run
engine.start()
File "/usr/lib/python3/dist-packages/wifiphisher/pywifiphisher.py", line 536, in start
self.network_manager.unblock_interface(ap_iface)
File "/usr/lib/python3/dist-packages/wifiphisher/common/interfaces.py", line 649, in unblock_interface
pyw.unblock(card)
File "/usr/local/lib/python3.11/dist-packages/pyric/pyw.py", line 628, in unblock
rfkill.rfkill_unblock(idx)
File "/usr/local/lib/python3.11/dist-packages/pyric/utils/rfkill.py", line 135, in rfkill_unblock
fout.write(rfke)
TypeError: write() argument must be str, not bytes

**Comment by dijey099** [comment]
edit rfkill.py file like follow and replace `fout = open(dpath, 'w')` to `fout = open(dpath, 'wb')`
`nano /usr/local/lib/python3.11/dist-packages/pyric/utils/rfkill.py`

**Comment by Aggelos11** [comment]
Will that fix it ??

**Comment by Aggelos11** [comment]
> edit rfkill.py file like follow and replace `fout = open(dpath, 'w')` to `fout = open(dpath, 'wb')` `nano /usr/local/lib/python3.11/dist-packages/pyric/utils/rfkill.py`

Will it fix it?

**Comment by ttinkywinky45** [comment]
**Hi 👽 ! If you are interested in ⚙️Advanced Phishing⚙️ and the ✨Evilginx3✨ tool then I offer you Google Gmail and Custom Phishlets (Paypal, Cryptos...) with a ✅Free Tutorial✅ which arrives if the 📈Telegram reaches 50 Subscribers📈
⏳ GOOGLE GMAIL PHISHLET 2024 WITH PROOF ⏳
 ->
⛔https://www.youtube.com/watch?v=nA47UknIE6A⛔
---
🔓 Ask your questions and a free tutorial from 50 subs on telegram !!!
->
📩https://t.me/Noremorse1011📩**

![evilginx_background](https://github.com/kgretzky/evilginx2/assets/144027798/0e448f68-ecdc-49a4-a4f4-23dbed7cb971)

**Comment by mr-pmillz** [comment]
> > edit rfkill.py file like follow and replace `fout = open(dpath, 'w')` to `fout = open(dpath, 'wb')` `nano /usr/local/lib/python3.11/dist-packages/pyric/utils/rfkill.py`
> 
> Will it fix it?

yes:

```bash
# need to edit rfkill.py, update python3.1X path in /usr/local/lib as needed:
sudo sed -i "s/fout = open(dpath, 'w')/fout = open(dpath, 'wb')/g" /usr/local/lib/python3.13/dist-packages/pyric/utils/rfkill.py
```
