### ISSUE TITLE
pyric.error: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by DartLord5000** [wifiphisher/wifiphisher#1645]
[*] Starting Wifiphisher 1.4GIT ( https://wifiphisher.org ) at 2024-04-02 03:02
[+] Timezone detected. Setting channel range to 1-13
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/PyRIC-0.1.6.4-py3.11.egg/pyric/pyw.py", line 1065, in devinfo
    msg = nl.nlmsg_new(nltype=_familyid_(nlsock),
                              ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/PyRIC-0.1.6.4-py3.11.egg/pyric/pyw.py", line 2244, in _familyid_
    rmsg = nl.nl_recvmsg(nlsock)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/PyRIC-0.1.6.4-py3.11.egg/pyric/lib/libnl.py", line 244, in nl_recvmsg
    msg = nlmsg_fromstream(sock.recv())
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/PyRIC-0.1.6.4-py3.11.egg/pyric/lib/libnl.py", line 444, in nlmsg_fromstream
    raise error(abs(e),strerror(abs(e)))
libnl.error: [Errno 2] No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/wifiphisher", line 33, in <module>
    sys.exit(load_entry_point('wifiphisher==1.4', 'console_scripts', 'wifiphisher')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/wifiphisher-1.4-py3.11.egg/wifiphisher/pywifiphisher.py", line 762, in run
    engine.start()
  File "/usr/local/lib/python3.11/dist-packages/wifiphisher-1.4-py3.11.egg/wifiphisher/pywifiphisher.py", line 435, in start
    self.network_manager.start(args)
  File "/usr/local/lib/python3.11/dist-packages/wifiphisher-1.4-py3.11.egg/wifiphisher/common/interfaces.py", line 740, in start
    raise error
  File "/usr/local/lib/python3.11/dist-packages/wifiphisher-1.4-py3.11.egg/wifiphisher/common/interfaces.py", line 728, in start
    card = pyw.getcard(interface)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/PyRIC-0.1.6.4-py3.11.egg/pyric/pyw.py", line 277, in getcard
    if nlsock is None: return _nlstub_(getcard, dev)
                              ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/PyRIC-0.1.6.4-py3.11.egg/pyric/pyw.py", line 2279, in _nlstub_
    return fct(*argv)
           ^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/PyRIC-0.1.6.4-py3.11.egg/pyric/pyw.py", line 278, in getcard
    return devinfo(dev, nlsock)['card']
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/PyRIC-0.1.6.4-py3.11.egg/pyric/pyw.py", line 1084, in devinfo
    raise pyric.error(e.errno, e.strerror)
pyric.error: [Errno 2] No such file or directory

**Comment by ttinkywinky45** [comment]
**Hi 👽 ! If you are interested in ⚙️Advanced Phishing⚙️ and the ✨Evilginx3✨ tool then I offer you Google Gmail and Custom Phishlets (Paypal, Cryptos...) with a ✅Free Tutorial✅ which arrives if the 📈Telegram reaches 50 Subscribers📈
⏳ GOOGLE GMAIL PHISHLET 2024 WITH PROOF ⏳
 ->
⛔https://www.youtube.com/watch?v=nA47UknIE6A⛔
---
🔓 Ask your questions and a free tutorial from 50 subs on telegram !!!
->
📩https://t.me/Noremorse1011📩**

![evilginx_background](https://github.com/kgretzky/evilginx2/assets/144027798/0e448f68-ecdc-49a4-a4f4-23dbed7cb971)
