### ISSUE TITLE
Nethunter

### ISSUE THREAD

**Issue by dr1408** [wifiphisher/wifiphisher#1646]
I saw videos on youtube with people using the tool with one adapter on nethunter i put internal chip to monitor mode and choosed the external adapter for deauth  .. used this command : wifiphisher -aI wlan0 -eI wlan1

![019E32FB-9D43-4285-BC97-99D4DAA4E4D1](https://github.com/wifiphisher/wifiphisher/assets/39735654/217c16c1-b179-4a4d-8fcd-cce737f159ca)

This is the output : 

wifiphisher -eI wlan1 -aI wlan0
[*] Starting Wifiphisher 1.4GIT ( https://wifiphisher.org ) at 2024-04-03 10:16
[+] Timezone detected. Setting channel range to 1-13
[+] Selecting wlan1 interface for the deauthentication attack
[+] Selecting wlan0 interface for creating the rogue Access Point
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pyric/pyw.py", line 1378, in modeset
    _ = nl.nl_recvmsg(nlsock)
        ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/pyric/lib/libnl.py", line 244, in nl_recvmsg
    msg = nlmsg_fromstream(sock.recv())
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/pyric/lib/libnl.py", line 444, in nlmsg_fromstream
    raise error(abs(e),strerror(abs(e)))
libnl.error: [Errno 95] Operation not supported

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/wifiphisher", line 33, in <module>
    sys.exit(load_entry_point('wifiphisher==1.4', 'console_scripts', 'wifiphisher')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/wifiphisher/pywifiphisher.py", line 762, in run
    engine.start()
  File "/usr/lib/python3/dist-packages/wifiphisher/pywifiphisher.py", line 518, in start
    new_mac = self.network_manager.set_interface_mac(ap_iface,
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/wifiphisher/common/interfaces.py", line 513, in set_interface_mac
    self.set_interface_mode(interface_name, "managed")
  File "/usr/lib/python3/dist-packages/wifiphisher/common/interfaces.py", line 558, in set_interface_mode
    pyw.modeset(card, mode)
  File "/usr/lib/python3/dist-packages/pyric/pyw.py", line 1365, in modeset
    if nlsock is None: return _nlstub_(modeset, card, mode, flags)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/pyric/pyw.py", line 2279, in _nlstub_
    return fct(*argv)
           ^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/pyric/pyw.py", line 1382, in modeset
    raise pyric.error(e.errno, e.strerror)
pyric.error: [Errno 95] Operation not supported

i know it is a duplicate but nobody is answering to old issues thats why i opened new one maybe will get a help thanks in advance

**Comment by ttinkywinky45** [comment]
**Hi 👽 ! If you are interested in ⚙️Advanced Phishing⚙️ and the ✨Evilginx3✨ tool then I offer you Google Gmail and Custom Phishlets (Paypal, Cryptos...) with a ✅Free Tutorial✅ which arrives if the 📈Telegram reaches 50 Subscribers📈
⏳ GOOGLE GMAIL PHISHLET 2024 WITH PROOF ⏳
 ->
⛔https://www.youtube.com/watch?v=nA47UknIE6A⛔
---
🔓 Ask your questions and a free tutorial from 50 subs on telegram !!!
->
📩https://t.me/Noremorse1011📩**

![evilginx_background](https://github.com/kgretzky/evilginx2/assets/144027798/0e448f68-ecdc-49a4-a4f4-23dbed7cb971)

**Comment by dr1408** [comment]
My internal card and my adapter both support monitor mode sir

**Comment by whiter0s** [comment]
Could you please send the model of the wifi card and adapter please?

**Comment by dr1408** [comment]
Its tb-link wn722n version 4 .. it supports monitor mode and packet injection

**Comment by whiter0s** [comment]
Hey again, sorry for responding at this late time, but the adapter you are using does support monitor mode, and by coincidence it is the same one I have, for the adapter to work you have to install a certain driver, i recommend checking out this guide.
https://github.com/davidbombal/Kali-Linux/blob/main/TP-Link%20TL-WN722N%20adapter

**Comment by dr1408** [comment]
No worries sir just to confirm are you using wifiphisher on nethunter on android device or you are using kali linux on laptop

**Comment by whiter0s** [comment]
Hello again!.I am currently using kali linux on my laptop, but I also am in possesion of a phone running nethunter that a use frequently

**Comment by dr1408** [comment]
Ok if you use wifiphisher with one adapter only with nethunter can you show me the commands
