### ISSUE TITLE
Unable to Start wifiphisher - Kali 2024.3

### ISSUE THREAD

**Issue by LorenzzoBazzanella** [wifiphisher/wifiphisher#1661]
Before opening a new issue, please make sure that what you are about to report has not been reported already or is not included on the FAQ page. If not, use the following template for reporting.

Please keep in mind that our developers will prioritize your issue if you provide a detailed and extensive description.

I am having an issue starting Wifiphisher.

I have tried other fixes described in various issues, such as installing the following libraries: libnl-3-dev, libnl-genl-3-dev, and libnl-3-dev libnl-genl-3-dev.

Can you assist me with this?

-----------------------------------------------------------------------------------------------------------------------------------------------
Python Version
Python 3.11.9

-----------------------------------------------------------------------------------------------------------------------------------------------
**Version**: Use `git show | grep commit` command and paste here the output.
git show | grep commit            
commit bc4a077e090d59b065cf2c65b0ec1890b9eb4698

-----------------------------------------------------------------------------------------------------------------------------------------------
**Description**: Give a more analytical description here. Let us know how we can reproduce the reported issue. Detail the characteristics of your machine (e.g. Linux distribution and wireless card capabilities) and of the victim devices too (e.g. OS or web browser) if possible. The output of the `iw list` and `iwconfig` commands may also be helpful here.

iwconfig:
lo        no wireless extensions.

eth0      no wireless extensions.

wlan0     IEEE 802.11  Mode:Monitor  Tx-Power=20 dBm   
          Retry short limit:7   RTS thr:off   Fragment thr:off
          Power Management:off

-----------------------------------------------------------------------------------------------------------------------------------------------
lsusb:
wlan0 = Ralink Technology, Corp. MT7601U Wireless Adapter
ID = 148f:7601

-----------------------------------------------------------------------------------------------------------------------------------------------
cat /etc/os-release:   
PRETTY_NAME="Kali GNU/Linux Rolling"
NAME="Kali GNU/Linux"
VERSION_ID="2024.3"
VERSION="2024.3"
VERSION_CODENAME=kali-rolling
ID=kali
ID_LIKE=debian
HOME_URL="https://www.kali.org/"
SUPPORT_URL="https://forums.kali.org/"
BUG_REPORT_URL="https://bugs.kali.org/"
ANSI_COLOR="1;31"

-----------------------------------------------------------------------------------------------------------------------------------------------
**Script output**: Paste the output of the tool, including any stack traces.
[*] Starting Wifiphisher 1.4GIT ( https://wifiphisher.org ) at 2024-08-22 15:24
[+] Timezone detected. Setting channel range to 1-13
ERROR:root:The following error has occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/wifiphisher-1.4-py3.11.egg/wifiphisher/pywifiphisher.py", line 489, in start
    mon_iface, ap_iface = self.network_manager.get_interface_automatically(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/wifiphisher-1.4-py3.11.egg/wifiphisher/common/interfaces.py", line 626, in get_interface_automatically
    monitor_interface = self.get_interface(has_monitor_mode=True)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/wifiphisher-1.4-py3.11.egg/wifiphisher/common/interfaces.py", line 615, in get_interface
    raise InterfaceCantBeFoundError((has_monitor_mode, has_ap_mode))
wifiphisher.common.interfaces.InterfaceCantBeFoundError: Failed to find an interface with monitor mode
[!] Failed to find an interface with monitor mode
[+] Show your support!
[+] Follow us: https://twitter.com/wifiphisher
[+] Like us: https://www.facebook.com/Wifiphisher
[+] Captured credentials:
[!] Closing

**Comment by Hastaluego123** [comment]
same issues...

**Comment by jiwsman** [comment]
same issues

**Comment by Storynow** [comment]
> same issues

老哥，咋样了。
