### ISSUE TITLE
No module named wifiphisher.pywifiphisher

### ISSUE THREAD

**Issue by WAK92** [wifiphisher/wifiphisher#339]
Version : kali-linux-light-2016.1-light-i686,
Summary: After i download and install the script using (sudo python setup.py install), i get the following error
Output: Traceback (most recent call last):
  File "/usr/local/bin/wifiphisher", line 11, in <module>
    load_entry_point('wifiphisher==1.1', 'console_scripts', 'wifiphisher')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/**init**.py", line 565, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/**init**.py", line 2589, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/**init**.py", line 2249, in load
    return self.resolve()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/**init**.py", line 2255, in resolve
    module = **import**(self.module_name, fromlist=['**name**'], level=0)
ImportError: No module named wifiphisher.pywifiphisher

**Comment by abdullahebrahim** [comment]
I'm with the same errors :-1:

**Comment by laozi999** [comment]
have you tried running the actual python file like this?
`sudo python ./wifiphisher/bin/wifiphisher`

**Comment by mcocigra** [comment]
Is this solved or not

**Comment by blackHatMonkey** [comment]
@WAK92 Can you please confirm that this problem is solved or not?
