### ISSUE TITLE
Error on ssl.do_handshake()

### ISSUE THREAD

**Issue by cicina** [wifiphisher/wifiphisher#439]
Hello, sorry to bother you. 

here is what happened when I run tool:
![screenshot_from_2017_02_07_15_32_24](https://cloud.githubusercontent.com/assets/25112506/23366742/dcc00278-fcd5-11e6-9e81-ba67bf216d2a.png)

Also when user type password, its captured and its visible:
![screenshot_from_2017_02_07_15_33_51](https://cloud.githubusercontent.com/assets/25112506/23366752/e40e2c26-fcd5-11e6-94fa-2d7d3b4b0160.png)

Problem is just that Its ugly. also problems with seeing connected users and jamming progress.
Do you have any idea what is wrong? I have re-downloaded tool but didn't help.

Edited by @blackhatmonkey for formating.

**Comment by blackHatMonkey** [comment]
Hi @cicina I'm currently busy with improving other parts of `Wifiphisher` so unless @sophron is able to find the issue, it's gonna take some time before it gets fixed.

**Comment by alternatexp** [comment]
This is because 3 log files are being being concatenated in one terminal and shrunk down to 5 lines only for no practical reason whatsoever.

I say append to one log file with distinct colouring (as done in bettercap), or 3 log files each in a separate terminal window.

**Comment by blackHatMonkey** [comment]
@sophron Do we know what is causing this error?

**Comment by MrAeon** [comment]
is there a way to fix this? Or is it being worked on? Just wondering why it affects me as it doesnt seemt o affect anyone - can I do anything my end to make it go away?

**Comment by vincentcox-ordina** [comment]
### How to reproduce:
1) Use the oath template
2) Use a windows 10 computer* (physical device) and connect to the rogue access point

*Version:
![image](https://cloud.githubusercontent.com/assets/23059427/26191498/64b2d586-3bae-11e7-8d3d-55df365a06cb.png)
*Applied Policies on device:
```
            GPO: LocalIntranet
                Folder Id: Software\Policies\Microsoft\Windows\CurrentVersion\Internet Settings\Zones\1\1A00
                Value:       0, 0, 0, 0
                State:       Enabled

            GPO: Filter IT Policy - Lockscreen
                Folder Id: Software\Policies\Microsoft\Windows\Control Panel\Desktop\ScreenSaveTimeOut
                Value:       51, 0, 48, 0, 48, 0, 0, 0
                State:       Enabled
   Applied Group Policy Objects
    -----------------------------
        LocalIntranet
        CompatibilitySites
        IE Favorites
        Modern Authentication Outlook 2013
        Filter IT Policy - Lockscreen
        Default Domain Policy

```
Regedit:
![image](https://cloud.githubusercontent.com/assets/23059427/26191775/887988a6-3baf-11e7-8592-31d4d42c78e8.png)


### What happens:
**on the windows 10 computer** the link "http://go.microsoft.com/fwlink/?LinkID=219472&clcid=0x409" opens which shows the phishing page (HTML only). Additional sources like /static/.../style.css or images are not loaded because the browser loads them from "http://go.microsoft.com/fwlink/static/.../style.css". 

**On the Kali device running the script:** 
It spit out SSL errors, the terminal is displaying multiple outputs troughout each other (the ssl errors are displayed over the normal dashboard results, which makes it a mess).

**Fix for the wrongly loaded sources:**
I edited my page to include all CSS code in the same page, and base64 all images into my HTML. Then I edited the POST URL to 10.0.0.1/POST to catch the login credentials.

**However the SSL errors and wrong display of the terminal is something I cannot fix.**

### Actions:
- Are there any log files I can attach to this thread? Which one should I attach?
- Or is there a time I can show this to you? 
- Should I make a screenrecording?

**Comment by blackHatMonkey** [comment]
@cicina Do you still get the same error on the latest release(`Github`)?

**Comment by blackHatMonkey** [comment]
@cicina I'm closing this issue due to inactivity. Feel free to reopen if needed.

**Comment by blackHatMonkey** [comment]
@InTheEndButFightingBack Can you run `wifiphisher` like so:
```
wifiphisher --log-file
```
or if you are using it as a standalone
```
python2 bin/wifiphisher --log-file
```

**Comment by gorbedm** [comment]
Hy!

First of all, i dont run wifiphisher on kali, so if you want to close the issue then sorry for bothering.

I run it on a freshly installed raspbian (check the dependencies, dont see any that related only kali).
Wifiphisher work fine, expect the python error above. 
Log file look like this: 
[wifiphisher.log](https://github.com/wifiphisher/wifiphisher/files/1822162/wifiphisher.log)

Use headless pi with ssh. If i run it in the ssh terminal the error is visible on the output. If i use it in `screen`, the error invisble in the output, but it is in the linked log file.

command: wifiphisher -aI wlan1 --essid "test" -nE -p oauth-login -kB --logging
connected device: android 6.0.1

Finally, i want to congrats to th devs, amazing tools!

Best regards,
    Daniel

**Comment by Dice2048** [comment]
I have this on two errornumbers 0 and 113
 :; both on same function : _do_ssl_handshake

`4ERROR:tornado.application:Exception in callback None
                                                                                                                              Traceback (most recent call last):
                                  File "/usr/local/lib/python2.7/dist-packages/tornado-4.5.3-py2.7-linux-armv7l.egg/tornado/ioloop.py", line 888, in start
                              handler_func(fd_obj, events)
                                                            File "/usr/local/lib/python2.7/dist-packages/tornado-4.5.3-py2.7-linux-armv7l.egg/tornado/stack_context.py", line 277, in null_wrapper
                                                                      return fn(*args, **kwargs)
                                                                                                  File "/usr/local/lib/python2.7/dist-packages/tornado-4.5.3-py2.7-linux-armv7l.egg/tornado/iostream.py", line 519, in _handle_events
                                                                                                         self._handle_read()
                                                                                                                              File "/usr/local/lib/python2.7/dist-packages/tornado-4.5.3-py2.7-linux-armv7l.egg/tornado/iostream.py", line 1395, in _handle_read
                                                                                                                                   self._do_ssl_handshake()
                             File "/usr/local/lib/python2.7/dist-packages/tornado-4.5.3-py2.7-linux-armv7l.egg/tornado/iostream.py", line 1315, in _do_ssl_handshake
                                        self.socket.do_handshake()
                                                                    File "/usr/lib/python2.7/ssl.py", line 846, in do_handshake
                                                                                                                                   self._sslobj.do_handshake()
                              error: [Errno 113] No route to host

`

`HTTP requests: ERROR:tornado.application:Exception in callback None
[*] GET request from 10.0.0.14 for http://clients3.google.com/generate_204/usr/local/lib/python2.7/dist-packages/wifiphisher-1.4[*] GET request from 10.0.0.16 for http://maps.googleapis.com/maps/api/elevation/xml?locations=52.078239,4.863256&sensor=falsements to Unicode - interpreting them as being unequall.egg/tornado/ioloop.py", line 888, in start
                                  File "/usr/local/  if ssid == self._data.target_ap_essid:3-py2.7-linux-armv7l.egg/tornado/ioloop.py", line 888, in start                                                                                                       File "/usr/local/lib/pyth    handler_func(fd_obj, events)3-py2.7-linux-armv7l.egg/tornado/stack_context.py", line 277, in null_wrapper                                                     File "/usr/local/lib/python2.7/dist-packages/tornado-4.5.3-py2.7-linux-armv7l.egg/tornado/stack_context.py", line 277, in null_wrapper
                                       File "/usr/local/lib/python    return fn(*args, **kwargs)3-py2.7-linux-armv7l.egg/tornado/iostream.py", line 519, in _handle_events                                                        File "/usr/local/lib/python2.7/dist-packages/tornado-4.5.3-py2.7-linux-armv7l.egg/tornado/iostream.py", line 519, in _handle_events
                                                                   File "/usr/local/lib/python2.7/dis    self._handle_read()3-py2.7-linux-armv7l.egg/tornado/iostream.py", line 1395, in _handle_read                                                         File "/usr/local/lib/python2.7/dist-packages/tornado-4.5.3-py2.7-linux-armv7l.egg/tornado/iostream.py", line 1395, in _handle_read
                                                                                                   File "/usr/local/lib/python2    self._do_ssl_handshake().3-py2.7-linux-armv7l.egg/tornado/iostream.py", line 1315, in _do_ssl_handshake
                             File "/usr/local/lib/python2.7/dist-packages/tornado-4.5.3-py2.7-linux-armv7l.egg/tornado/iostream.py", line 1315, in _do_ssl_handshake
          File "/usr/lib/python2.7/s    self.socket.do_handshake()ake
                                                                    File "/usr/lib/python2.7/ssl.py", line 846, in do_handshake
                                                                                                    error: [Errno 0] Error         self._sslobj.do_handshake()
                              error: [Errno 0] Error`

I dont mind the error itself, but not capturing credentials either

**Comment by Dice2048** [comment]
^^ rPi 3, disabled onboard adapter :
Bus 001 Device 007: ID 0bda:8812 Realtek Semiconductor Corp. RTL8812AU 802.11a/b/g/n/ac WLAN Adapter
Bus 001 Device 004: ID 0cf3:9271 Atheros Communications, Inc. AR9271 802.11n
Bus 001 Device 006: ID 0424:7800 Standard Microsystems Corp.
Bus 001 Device 003: ID 0424:2514 Standard Microsystems Corp. USB 2.0 Hub
Bus 001 Device 002: ID 0424:2514 Standard Microsystems Corp. USB 2.0 Hub
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub


iwconfig:
wlan0     IEEE 802.11  ESSID:off/any
          Mode:Managed  Access Point: Not-Associated   Tx-Power=20 dBm
          Retry short limit:7   RTS thr:off   Fragment thr:off
          Encryption key:off
          Power Management:off

eth0      no wireless extensions.

lo        no wireless extensions.

wlan1     IEEE 802.11  ESSID:off/any
          Mode:Managed  Access Point: Not-Associated   Tx-Power=18 dBm
          Retry short limit:7   RTS thr:off   Fragment thr:off
          Encryption key:off
          Power Management:off

**Comment by tykkz** [comment]
When a victim machine with Windows OS connects to the Rogue AP created, Windows internally performs some checks with SSL encrypted sites and drops the connection if the certificate is not trusted. Since Wifiphisher uses self-signed certificate, the SSL connection drops and we see these ugly error messages.

To fix it, we have two options:

1. We can add the following line to here at [phishinghttp.py](https://github.com/wifiphisher/wifiphisher/blob/master/wifiphisher/common/phishinghttp.py#L19) and all these errors will be gone forever. This may cause some unknown problems that I have not foreseen, but as far as I can tell, it works in Kali and Ubuntu machines.

`logging.getLogger('tornado.application').disabled = True`

2. We can pass the `'tornado.application'` logs to a file in the `/tmp/` directory, just for debug purposes.

I can do a PR and fix the issue, waiting for your comments.

**Comment by sophron** [comment]
Hi @tykkz,

Can we pass `tornado.application` to our custom logging methods?

**Comment by tykkz** [comment]
I assume that "custom logging methods" means running `wifiphisher` with `--logging` option? If so, yes. 

If people runs with  `--logging` option, then these errors are not visible in the user interface and written directly to the `wifiphisher.log` file (or the file given with the `--logpath` option).

So, one other option could be making   `--logging` option default.. Bear in mind that some people will complain when they see these errors in the log file.

**Comment by sophron** [comment]
> I assume that "custom logging methods" means running wifiphisher with --logging option? If so, yes.

Yes, I mean all the methods provided by the `logging` module.

> If people runs with --logging option, then these errors are not visible in the user interface and written directly to the wifiphisher.log file (or the file given with the --logpath option).

Correct.

> So, one other option could be making --logging option default.. Bear in mind that some people will complain when they see these errors in the log file.

I don't think there is a reason to make it enabled by default. There are many different kinds of logging levels and the user may adjust what he wants to see. This specific error should be put under the "DEBUG" level.
