### ISSUE TITLE
Add android support

### ISSUE THREAD

**Issue by Dirkstaal** [wifiphisher/wifiphisher#486]
Hi can you please port this tool so that it could be runned from an android terminal with root 

If it will be possible ?

**Comment by blackHatMonkey** [comment]
@Dirkstaal Are you talking about `Kali Linux NetHunter`?

**Comment by Dirkstaal** [comment]
No i want to use it on android without an usb wifi adapter

**Comment by sophron** [comment]
I'm afraid it's not possible to use Wifiphisher on Android. Even in a rooted device, many of the tool's dependencies are not supporting the platform.

**Comment by alternatexp** [comment]
@Dirkstaal most likely your phone's wireless card won't allow monitor mode, so you'll need an OTG cable + wireless USB adapter. Some phones need a OTG Y-splitter cable to enable charging at the same time as some phones can't power the wireless interface sufficiently.

**Comment by sophron** [comment]
Since Android's C runtime library (bionic) is not binary compatible with the GNU libc or an X server, (which Linux uses), I imagine problems porting different libraries, e.g. `ncurses`. The Linux kernel is also modified. I'm not sure if `Pyric` would behave normally and of-course users still need a monitor-mode WiFi kernel/driver.

Maybe it is possible, but it will require so many hacks that I believe it doesn't worth the effort. Instead, we can focus on making it work on NetHunter.

**Comment by jeretc** [comment]
does it not support on Nethunter? i'm getting this error :

[*] Starting Wifiphisher 1.2GIT at 2017-03-08 11:36
Traceback (most recent call last):
  File "bin/wifiphisher", line 12, in <module>
    run()
  File "/root/wifiphisher/wifiphisher/pywifiphisher.py", line 773, in run
    engine = WifiphisherEngine()
  File "/root/wifiphisher/wifiphisher/pywifiphisher.py", line 531, in __init__
    self.network_manager = interfaces.NetworkManager()
  File "/root/wifiphisher/wifiphisher/common/interfaces.py", line 238, in __init__
    self._interfaces[interface] = NetworkAdapter(interface)
  File "/root/wifiphisher/wifiphisher/common/interfaces.py", line 150, in __init__
    card = pyw.getcard(name)
  File "/usr/local/lib/python2.7/dist-packages/PyRIC-0.1.6.3-py2.7.egg/pyric/pyw.py", line 269, in getcard
    if nlsock is None: return _nlstub_(getcard, dev)
  File "/usr/local/lib/python2.7/dist-packages/PyRIC-0.1.6.3-py2.7.egg/pyric/pyw.py", line 2236, in _nlstub_
    return fct(*argv)
  File "/usr/local/lib/python2.7/dist-packages/PyRIC-0.1.6.3-py2.7.egg/pyric/pyw.py", line 270, in getcard
    return devinfo(dev, nlsock)['card']
  File "/usr/local/lib/python2.7/dist-packages/PyRIC-0.1.6.3-py2.7.egg/pyric/pyw.py", line 1057, in devinfo
    'mac': _hex2mac_(nl.nla_find(rmsg, nl80211h.NL80211_ATTR_MAC)),
  File "/usr/local/lib/python2.7/dist-packages/PyRIC-0.1.6.3-py2.7.egg/pyric/pyw.py", line 1821, in _hex2mac_
    return ":".join(['{0:02x}'.format(c) for c in v])
TypeError: 'NoneType' object is not iterable

**Comment by blackHatMonkey** [comment]
@jeretc `Wifiphisher` only supports `Kali` Linux at the moment. That being said `Nethunter` support is planned for future see #341.

**Comment by sophron** [comment]
There's already an issue for Nethunter (#341). Porting the project on Android is out of our scope.
