### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'replace'

### ISSUE THREAD

**Issue by Zawadidone** [wifiphisher/wifiphisher#489]
When i run 
wifiphisher --nojamming --essid "FREE WIFI" -p oauth-login
this is the output 
Traceback (most recent call last):
  File "/usr/local/bin/wifiphisher", line 11, in <module>
    load_entry_point('wifiphisher==1.2', 'console_scripts', 'wifiphisher')()
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.2-py2.7.egg/wifiphisher/pywifiphisher.py", line 1056, in run
    ap_logo_path = template.use_file(mac_matcher.get_vendor_logo_path(ap_mac))
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.2-py2.7.egg/wifiphisher/macmatcher.py", line 101, in get_vendor_logo_path
    mac_identifier = mac_address.replace(':', '').upper()[0:6]
AttributeError: 'NoneType' object has no attribute 'replace'

**Comment by blackHatMonkey** [comment]
Hi @Zawadidone I will take a look at it and let you know when the fix is ready :smile:.

**Comment by Zawadidone** [comment]
Okay thanks

**Comment by blackHatMonkey** [comment]
@Zawadidone A new patch has been posted. Please check with the latest version and see if the problem persists.

**Comment by Zawadidone** [comment]
No it isn't fixed 
When i run 
wifiphisher --nojamming --essid "FREE " -p oauth-login
The output is 
Traceback (most recent call last):
  File "/usr/local/bin/wifiphisher", line 11, in <module>
    load_entry_point('wifiphisher==1.2', 'console_scripts', 'wifiphisher')()
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.2-py2.7.egg/wifiphisher/pywifiphisher.py", line 794, in run
    'target_ap_channel': args.channel or "",
AttributeError: 'Namespace' object has no attribute 'channel'

**Comment by orla11** [comment]
Same problem here: 

Traceback (most recent call last):
File "/usr/local/bin/wifiphisher", line 11, in
load_entry_point('wifiphisher==1.2', 'console_scripts', 'wifiphisher')()
File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.2-py2.7.egg/wifiphisher/pywifiphisher.py", line 794, in run
'target_ap_channel': args.channel or "",
AttributeError: 'Namespace' object has no attribute 'channel'

**Comment by Zawadidone** [comment]
It works thank you for the support
