### ISSUE TITLE
IOError: [Errno 2] No such file or directory: '/proc/net/dev' in bash on ubuntu on windows  

### ISSUE THREAD

**Issue by hichamox** [wifiphisher/wifiphisher#498]
hey there i m trying to install wifisphier on bash on ubuntu on windows  but it's wont work it's keep showing me this message 

```bash
Traceback (most recent call last):
  File "/usr/local/bin/wifiphisher", line 9, in <module>
    load_entry_point('wifiphisher==1.2', 'console_scripts', 'wifiphisher')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 351, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2363, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2088, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.2-py2.7.egg/wifiphisher/pywifiphisher.py", line 14, in <module>
    import deauth
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.2-py2.7.egg/wifiphisher/deauth.py", line 9, in <module>
    import scapy.layers.dot11 as dot11
  File "/usr/lib/python2.7/dist-packages/scapy/layers/dot11.py", line 14, in <module>
    from scapy.plist import PacketList
  File "/usr/lib/python2.7/dist-packages/scapy/plist.py", line 19, in <module>
    import arch
  File "/usr/lib/python2.7/dist-packages/scapy/arch/__init__.py", line 71, in <module>
    from linux import *
  File "/usr/lib/python2.7/dist-packages/scapy/arch/linux.py", line 513, in <module>
    conf.iface = get_working_if()
  File "/usr/lib/python2.7/dist-packages/scapy/arch/linux.py", line 100, in get_working_if
    for i in get_if_list():
  File "/usr/lib/python2.7/dist-packages/scapy/arch/linux.py", line 92, in get_if_list
    f=open("/proc/net/dev","r")
IOError: [Errno 2] No such file or directory: '/proc/net/dev'
```

**Comment by sophron** [comment]
Is this Bash on Windows? I doubt Wifiphisher will work there. From what I see, this is a bug with ifconfig: https://github.com/Microsoft/BashOnWindows/issues/602

**Comment by alternatexp** [comment]
"on bash on ubuntu on windows"

Are you using a virtual machine? 
Or literally using windows CMD to install Wifiphisher on an Ubuntu partition?

**Comment by hichamox** [comment]
@alternatexp  bash on ubuntu on windows is intergration of ubuntu terminal on windows it's new feature on windows 10 sqlmap and other paython scripts works well only wifiphisher won't work

**Comment by alternatexp** [comment]
@hichamox true that, I had no idea that existed so I can't help you out on this one sorry :/

**Comment by blackHatMonkey** [comment]
@hichamox I'm guessing you have to wait till "Creators" update.

**Comment by blackHatMonkey** [comment]
@hichamox Since this bug is not related to `wifiphisher` I'm closing this. Feel free to open if necessary.
