### ISSUE TITLE
what is this?

### ISSUE THREAD

**Issue by Miayke** [wifiphisher/wifiphisher#500]
i download latest version of wifiphisher i install again 

Wifi list is displayed and it falls into this fault

`root@kshadow:~/wifiphisher# wifiphisher
[*] Starting Wifiphisher 1.2GIT at 2017-03-05 15:07
[+] Selecting wlan1 interface for the deauthentication attack
[+] Selecting wlan0 interface for creating the rogue Access Point
[*] Cleared leases, started DHCP, set up iptables
Traceback (most recent call last):
  File "/usr/local/bin/wifiphisher", line 9, in <module>
    load_entry_point('wifiphisher==1.2', 'console_scripts', 'wifiphisher')()
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.2-py2.7.egg/wifiphisher/pywifiphisher.py", line 774, in run
    engine.start()
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.2-py2.7.egg/wifiphisher/pywifiphisher.py", line 628, in start
    access_point = curses.wrapper(select_access_point, mon_iface, self.mac_matcher)
  File "/usr/lib/python2.7/curses/wrapper.py", line 43, in wrapper
    return func(stdscr, *args, **kwds)
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.2-py2.7.egg/wifiphisher/pywifiphisher.py", line 329, in select_access_point
    display_access_points((screen, box, access_points, total_ap_number, page_number, position), mac_matcher)
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.2-py2.7.egg/wifiphisher/pywifiphisher.py", line 486, in display_access_points
    access_point.get_number_connected_clients(), vendor))
UnicodeEncodeError: 'ascii' codec can't encode character u'\u011f' in position 4: ordinal not in range(128)

`

**Comment by sophron** [comment]
See $496.

**Comment by Miayke** [comment]
I think these characters do not support the WiFi list, ı, ü, ğ, ö, ş, İ, Ğ, Ü, Ö, Ş, Ç

There was no such problem in the old version

**Comment by laozi999** [comment]
Rather than throwing an error and quitting, these APs should be ignored until they are supported

**Comment by Miayke** [comment]
I think the problem is the characters in the wifi names  i think dunno
