### ISSUE TITLE
Error scapy-layers-dot11

### ISSUE THREAD

**Issue by alross371** [wifiphisher/wifiphisher#507]
I was able to complete the wifiphisher installation. However, when I typed the command "wifiphisher " I got this error "scapy-layers-dot11"
Any help would be appreciated. Thanks .

**Comment by blackHatMonkey** [comment]
@alross371 Did you solve this problem?

**Comment by brianmituka** [comment]
I'm having the same issue, but I cant find when it was closed..

**Comment by brianmituka** [comment]
`Traceback (most recent call last):
  File "/usr/local/bin/wifiphisher", line 11, in <module>
    load_entry_point('wifiphisher==1.2', 'console_scripts', 'wifiphisher')()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 560, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2648, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2302, in load
    return self.resolve()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2308, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.2-py2.7.egg/wifiphisher/pywifiphisher.py", line 18, in <module>
    import wifiphisher.common.deauth as deauth
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.2-py2.7.egg/wifiphisher/common/deauth.py", line 9, in <module>
    import scapy.layers.dot11 as dot11
ImportError: No module named scapy.layers.dot11
`
that is output i am getting when I run

**Comment by blackHatMonkey** [comment]
@brianmituka You must install `scapy` module. You can install `scapy` using `pip` like so:
```bash
[sudo] pip install scapy
```
or using `apt`
```bash
[sudo] apt-get install python-scapy
```
Let me know if you need more help.

**Comment by blackHatMonkey** [comment]
I'm closing this issue as it would seem the problem has been resolved. @brianmituka Feel free to comment if you have any more issues.

**Comment by azamet90** [comment]
> I'm closing this issue as it would seem the problem has been resolved. @brianmituka Feel free to comment if you have any more issues.

im using ubuntu and scapy is installed but i get this error
WARNING:scapy.runtime:DNS decompression loop detected

**Comment by Cvar1984** [comment]
> @brianmituka You must install `scapy` module. You can install `scapy` using `pip` like so:
> 
> ```shell
> [sudo] pip install scapy
> ```
> 
> or using `apt`
> 
> ```shell
> [sudo] apt-get install python-scapy
> ```
> 
> Let me know if you need more help.

i got new error after install scapy

Traceback (most recent call last):
  File "/usr/local/bin/wifiphisher", line 11, in <module>
    load_entry_point('wifiphisher==1.3', 'console_scripts', 'wifiphisher')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2793, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2411, in load
    return self.resolve()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2417, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.3-py2.7.egg/wifiphisher/pywifiphisher.py", line 21, in <module>
    import wifiphisher.common.phishinghttp as phishinghttp
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.3-py2.7.egg/wifiphisher/common/phishinghttp.py", line 2, in <module>
    import tornado.ioloop
  File "/usr/local/lib/python2.7/dist-packages/tornado-6.0.3-py2.7-linux-x86_64.egg/tornado/ioloop.py", line 67
    def fileno(self) -> int:
                     ^
SyntaxError: invalid syntax
