### ISSUE TITLE
Device unable to connect to the fake ap 

### ISSUE THREAD

**Issue by malashhab** [wifiphisher/wifiphisher#522]
hi fellows i'm using raspbian os and I installed wifiphisher on it but whenever I wanna open wifiphisher it show me the aps in the area and when I choose one the deauthenticate works perfectly but the fake aps the program makes doesn't connect I tried with my iPhone 7 to connect to it and it doesn't connect and I even tried with my galaxy s7 edge but it's the same issue even tho it worked only 1 time using the network manger scenario even sometimes when I choose the network I wanna fake the fake ap doesn't show please help me 
![1](https://cloud.githubusercontent.com/assets/26499289/24069931/d98c962c-0bc4-11e7-9285-51bf12b86019.png)
![2](https://cloud.githubusercontent.com/assets/26499289/24069932/dacab82a-0bc4-11e7-9262-8a04a112edf0.png)

**Comment by Splinter0** [comment]
I have i Raspberry pi model 3 B, and it works just fine using a TL-WN722N as second wireless card.
I takes quite a lot of time to start the AP for the Raspberry pi ( not a lot considering that is a RPi ) but after max 2 min everything is running.
Which RPi model are u using, and version of raspbian? Also which card are you using as secondary?
@malashhab

**Comment by malashhab** [comment]
I'm using the raspberry pi 3 and I'm using alpha awus036h and for me it worked only 3 or 4 times but then stopped working again it's so annoying

**Comment by malashhab** [comment]
Traceback (most recent call last):
  File "/usr/local/bin/wifiphisher", line 9, in <module>
    load_entry_point('wifiphisher==1.2', 'console_scripts', 'wifiphisher')()
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.2-py2.7.egg/wifiphi                                                                                        sher/pywifiphisher.py", line 774, in run
    engine.start()
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.2-py2.7.egg/wifiphi                                                                                        sher/pywifiphisher.py", line 628, in start
    access_point = curses.wrapper(select_access_point, mon_iface, self.mac_match                                                                                        er)
  File "/usr/lib/python2.7/curses/wrapper.py", line 43, in wrapper
    return func(stdscr, *args, **kwds)
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.2-py2.7.egg/wifiphi                                                                                        sher/pywifiphisher.py", line 329, in select_access_point
    display_access_points((screen, box, access_points, total_ap_number, page_num                                                                                        ber, position), mac_matcher)
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.2-py2.7.egg/wifiphi                                                                                        sher/pywifiphisher.py", line 494, in display_access_points
    box.addstr(item_position-(max_row*(page_number-1)), 2, display_text, normal_                                                                                        text)
TypeError: must be string without null bytes, not str

now this shows up @Splinter0

**Comment by Splinter0** [comment]
at the moment the only thing i can suggest is update everything possible ( see distro-update as well ) on your system, grab the new wifiphisher version and relaunch setup.py.
Do a quick research and see if all drivers for your card are installed.
@malashhab @sophron I mention sophron he might know more than me ( probably XD )

**Comment by malashhab** [comment]
how can I check the drivers i'm new to Linux and raspberry pi please help me :) 
@Splinter0

**Comment by Splinter0** [comment]
@malashhab Don't worry when i'm free i'll search as well :+1:
