### ISSUE TITLE
Whenever I start wifiphisher this shows up 

### ISSUE THREAD

**Issue by malashhab** [wifiphisher/wifiphisher#526]
Pleas help me whenever I start the wifiphisher to search for networks this code shows up it's so annoying and infuriating I'm using the raspbian 

```bash
Traceback (most recent call last):
  File "/usr/local/bin/wifiphisher", line 9, in <module>
    load_entry_point('wifiphisher==1.2', 'console_scripts', 'wifiphisher')()
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.2-py2.7.egg/wifiphishe
/pywifiphisher.py", line 774, in run
    engine.start()
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.2-py2.7.egg/wifiphishe
/pywifiphisher.py", line 628, in start
    access_point = curses.wrapper(select_access_point, mon_iface, self.mac_matcher)
  File "/usr/lib/python2.7/curses/wrapper.py", line 43, in wrapper
    return func(stdscr, *args, **kwds)
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.2-py2.7.egg/wifiphishe
/pywifiphisher.py", line 329, in select_access_point
    display_access_points((screen, box, access_points, total_ap_number, page_number
 position), mac_matcher)
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.2-py2.7.egg/wifiphishe
/pywifiphisher.py", line 492, in display_access_points
    display_text, highlight_text)
TypeError: must be string without null bytes, not str
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.2-py2.7.egg/wifiphishe
/common/recon.py", line 302, in _sniff_packets
    store=0)
  File "/usr/lib/python2.7/dist-packages/scapy/sendrecv.py", line 586, in sniff
    r = prn(p)
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.2-py2.7.egg/wifiphishe
/common/recon.py", line 183, in _process_packets
    self._create_ap_with_info(packet)
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.2-py2.7.egg/wifiphishe
/common/recon.py", line 208, in _create_ap_with_info
    channel = str(ord(packet[dot11.Dot11Elt:3].info))
```

**Comment by blackHatMonkey** [comment]
Hi @malashhab tanks for opening an issue. I will take a look at it and let you know.
