### ISSUE TITLE
TypeError: ord() expected a character

### ISSUE THREAD

**Issue by leon245** [wifiphisher/wifiphisher#545]
A few seconds after startup, these errors appear:

```bash
Exception in thread Thread-1:                                                                    
Traceback (most recent call last):                                  
File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner self.run()                                                                                                                                         
File "/usr/lib/python2.7/threading.py", line 754, in run self.__target(*self.__args, **self.__kwargs)                                
File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.2-py2.7.egg/wifiphisher/common/recon.py", line 304, in _sniff_packets store=0)                                                                    
File "/usr/lib/python2.7/dist-packages/scapy/sendrecv.py", line 620, in sniff r = prn(p) File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.2-py2.7.egg/wifiphisher/common/recon.py", line 185, in _process_packets self._create_ap_with_info(packet)        
File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.2-py2.7.egg/wifiphisher/common/recon.py", line 210, in _create_ap_with_info                                                              
    channel = str(ord(packet[dot11.Dot11Elt:3].info))         
TypeError: ord() expected a character, but string of length 4 found        
```
The second problem is that all ap power is 0%.

**Comment by blackHatMonkey** [comment]
Thanks @leon245 for opening an issue. I will take a look at it and let you know :smile:.

**Comment by blackHatMonkey** [comment]
@leon245 Can you test it with the latest version and report if it is still there?

**Comment by blackHatMonkey** [comment]
@leon245 A patch has been committed. Please update to the latest version and check if the problem still exits.

**Comment by blackHatMonkey** [comment]
@leon245x Try it with the latest update. The power problem should be solved now :smile:.
