### ISSUE TITLE
parenthesis problems in pyhton file

### ISSUE THREAD

**Issue by aliemresafak** [wifiphisher/wifiphisher#547]
Before opening a new issue, please make sure that what you are about to report has not been reported already. If not, use the following template for reporting:

**Version**: 3bc4d26ceb53b11e2f9dbe9ca8c7234e176bdbc7

**Distribution**: Antergos

**Summary**: I installed seamlessly. But it gives the following error when trying to open.

**Script output**: Traceback (most recent call last):
  File "/usr/bin/wifiphisher", line 11, in <module> load_entry_point('wifiphisher==1.2', 'console_scripts', 'wifiphisher')()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 560, in load_entry_point return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2648, in  return ep.load()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2302, in  return self.resolve()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2308, in  
module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3.6/site-packages/wifiphisher-1.2-py3.6.egg/wifiphisher/pywifiphisher.py", line 192
   print "\nAvailable Phishing Scenarios:\n"
                                            ^
SyntaxError: Missing parentheses in call to 'print'

**Comment by blackHatMonkey** [comment]
@aliemresafak Thanks for opening an issue. What command are you running to start `wifiphisher`?

**Comment by Splinter0** [comment]
@aliemresafak You are probably using a version of python 3+. Try to start the program with python 2.7
( default python installed in every distro )

**Comment by aliemresafak** [comment]
I ran as wifiphisher --nojamming

**Comment by Splinter0** [comment]
@aliemresafak Did you run ```./wifiphisher --nojamming```? if you did and you still get the error, check what python version do you have as default. You should have 2.7 ( important that it isn't 3+ )

**Comment by aliemresafak** [comment]
how may i install python 2.7 i checked python version. it is 3.6.0

**Comment by aliemresafak** [comment]
I installed wifiphisher with python2 setup.py install. Error messages changed.
Traceback (most recent call last):
  File "/usr/bin/wifiphisher", line 11, in <module>
    load_entry_point('wifiphisher==1.2', 'console_scripts', 'wifiphisher')()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 560, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2648, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2302, in load
    return self.resolve()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2308, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python2.7/site-packages/wifiphisher-1.2-py2.7.egg/wifiphisher/pywifiphisher.py", line 18, in <module>
    import wifiphisher.common.deauth as deauth
  File "/usr/lib/python2.7/site-packages/wifiphisher-1.2-py2.7.egg/wifiphisher/common/deauth.py", line 9, in <module>
    import scapy.layers.dot11 as dot11
ImportError: No module named scapy.layers.dot11

**Comment by blackHatMonkey** [comment]
You need to install `scapy` module which can be done using `pip`:
```bash
[sudo] pip install scapy
```
you also need `hostapd` and `dnsmasq`.

**Comment by aliemresafak** [comment]
@blackHatMonkey Thank you for everything. I fixed.

**Comment by christmex** [comment]
i have this error, i using all like above, but i cant fixed the error


Traceback (most recent call last):
  File "wifiphisher/bin/wifiphisher", line 16, in <module>
    
  File "/root/wifiphisher/wifiphisher/pywifiphisher.py", line 20, in <module>
    import wifiphisher.common.extensions as extensions
  File "/root/wifiphisher/wifiphisher/common/extensions.py", line 11, in <module>
    import scapy.layers.dot11 as dot11
  File "/usr/local/lib/python2.7/dist-packages/scapy/layers/dot11.py", line 12, in <module>
    from scapy.packet import *
  File "/usr/local/lib/python2.7/dist-packages/scapy/packet.py", line 39
    class Packet(BasePacket, metaclass = Packet_metaclass):
                                       ^
SyntaxError: invalid syntax


i get the error code like that , please help
