### ISSUE TITLE
When i use -nJ option I got this errors .

### ISSUE THREAD

**Issue by LuYuChengProject** [wifiphisher/wifiphisher#554]
Hey, When I use the this cmd :
  ->     airmon-ng start wlan0 
 ->     wifiphisher -nJ -e "iPhone" -p oath-login
I got no such files error , is anything wrong with my operation?

error : Traceback (most recent call last):
  File "/usr/local/bin/wifiphisher", line 9, in <module>
    load_entry_point('wifiphisher==1.2', 'console_scripts', 'wifiphisher')()
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.2-py2.7.egg/wifiphisher/pywifiphisher.py", line 896, in run
    start_ap(ap_iface.get_name(), channel, essid, args)
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.2-py2.7.egg/wifiphisher/pywifiphisher.py", line 430, in start_ap
    hostapd_proc = Popen(['hostapd', '/tmp/hostapd.conf'], stdout=DN, stderr=DN)
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

**Comment by Splinter0** [comment]
@LuYuChengProject It seems like hostapd isn't installed as it should. I suggest to clone the newest version of wifiphisher and run ```sudo setup.py install``` again. If it still doesn't work try to uninstall you hostapd version and re run the setup.
Let me know if it works :+1: 
@blackHatMonkey

**Comment by LuYuChengProject** [comment]
yep,it works thanks ! :+1:
