### ISSUE TITLE
Duplicate of #507

### ISSUE THREAD

**Issue by ranahaani** [wifiphisher/wifiphisher#621]
```bash
Traceback (most recent call last):
  File "/usr/local/bin/wifiphisher", line 9, in <module>
    load_entry_point('wifiphisher==1.3', 'console_scripts', 'wifiphisher')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 542, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2569, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2229, in load
    return self.resolve()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2235, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.3-py2.7.egg/wifiphisher/pywifiphisher.py", line 18, in <mod
ule>
    import wifiphisher.common.deauth as deauth
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.3-py2.7.egg/wifiphisher/common/deauth.py", line 10, in <mod
ule>
    import scapy.layers.dot11 as dot11
ImportError: No module named scapy.layers.dot11
```

**Comment by blackHatMonkey** [comment]
Hi @ranahaani You are missing the `scapy` module. I suggest you install `wifiphisher` using pip so that all the dependencies are installed automatically.
