### ISSUE TITLE
AttributeError: 'module' object has no attribute 'InvalidInternetInterfaceError'

### ISSUE THREAD

**Issue by HashKT** [wifiphisher/wifiphisher#632]
I have tried different things but nothing works still the same error when starting.
When i type wifiphisher, error comes up...

```bash
[*] Starting Wifiphisher 1.3GIT at 2017-06-10 15:49
Traceback (most recent call last):
  File "/usr/local/bin/wifiphisher", line 11, in <module>
    load_entry_point('wifiphisher==1.3', 'console_scripts', 'wifiphisher')()
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.3-py2.7.egg/wifiphisher/pywifiphisher.py", line 801, in run
    engine.start()
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.3-py2.7.egg/wifiphisher/pywifiphisher.py", line 621, in start
    interfaces.InvalidInternetInterfaceError,
AttributeError: 'module' object has no attribute 'InvalidInternetInterfaceError'
```
this is my ifconfig:
```
eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.1.145  netmask 255.255.255.0  broadcast 192.168.1.255
        inet6 2001:7d0:87cc:7180:20c:29ff:fecc:d5d5  prefixlen 64  scopeid 0x0<global>
        inet6 2001:7d0:87cc:7180:5092:3af7:8be:d2d9  prefixlen 64  scopeid 0x0<global>
        inet6 fe80::20c:29ff:fecc:d5d5  prefixlen 64  scopeid 0x20<link>
        ether 00:0c:29:cc:d5:d5  txqueuelen 1000  (Ethernet)
        RX packets 20926  bytes 16539489 (15.7 MiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 15328  bytes 1945872 (1.8 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 1  (Local Loopback)
        RX packets 58  bytes 9055 (8.8 KiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 58  bytes 9055 (8.8 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

wlan0: flags=4099<UP,BROADCAST,MULTICAST>  mtu 1500
        ether 16:08:24:be:cd:c2  txqueuelen 1000  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

wlan1: flags=4099<UP,BROADCAST,MULTICAST>  mtu 1500
        ether ea:19:55:5d:36:27  txqueuelen 1000  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
```

**Comment by blackHatMonkey** [comment]
Hi @HashKT Can you update to the latest version and try again. It seems that the error was removed with this b7650289b765c01a6ab22de1bca0a354ce4265d0 commit if I'm not mistaken @anakin1028.

**Comment by anakin1028** [comment]
@blackHatMonkey yes I have removed this exception since we no-longer need to check the card is not wireless for doing internet connection.

**Comment by HashKT** [comment]
How can i uninstall wifiphisher. I tried pip unistall wifiphisher and it worked then i installed wifiphisher with apt-get install wifiphisher but now theres another error

**Comment by anakin1028** [comment]
@HashKT Have you tried install wifiphisher by pip ? Have a look on #614.

**Comment by blackHatMonkey** [comment]
@HashKT The latest fix is not on the `PyPI` yet. So you have to download it from `Github` and either install it or just run it. You can take a look at [this](http://wifiphisher.readthedocs.io/en/latest/getting_started.html#using-browser) for more information.
