### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'close'

### ISSUE THREAD

**Issue by actuzo** [wifiphisher/wifiphisher#646]
I installed and there was no problem, but at the moment of running.....
```
[*] Starting Wifiphisher 1.3GIT at 2017-06-19 12:22
[!] Interface "ALL" is controlled by NetworkManager.You need to manually set the devices that should be ignored by NetworkManager using the keyfile plugin (unmanaged-directive). For example, '[keyfile] unmanaged-devices=interface-name:"ALL"' needs to be added in your NetworkManager configuration file.
[+] Captured credentials:
Traceback (most recent call last):
  File "./wifiphisher", line 12, in <module>
    
  File "/opt/wifiphisher-master/wifiphisher/pywifiphisher.py", line 892, in run
    engine.start()
  File "/opt/wifiphisher-master/wifiphisher/pywifiphisher.py", line 692, in start
    self.stop()
  File "/opt/wifiphisher-master/wifiphisher/pywifiphisher.py", line 585, in stop
    self.em.on_exit()
  File "/opt/wifiphisher-master/wifiphisher/common/extensions.py", line 184, in on_exit
    self._socket.close()
AttributeError: 'NoneType' object has no attribute 'close'
```

thanks.

**Comment by sophron** [comment]
I believe you are running `wifiphisher` from here: https://github.com/sophron/wifiphisher

Download the version from here instead: https://github.com/wifiphisher/wifiphisher
