### ISSUE TITLE
pyric.error: [Errno 76] Name not unique on network

### ISSUE THREAD

**Issue by alilord** [wifiphisher/wifiphisher#701]
```
root@kali:~# wifiphisher
[*] Starting Wifiphisher 1.3 at 2017-08-10 00:20
[+] Selecting wlan0 interface for the deauthentication attack
[+] Selecting mon0 interface for creating the rogue Access Point
[*] Cleared leases, started DHCP, set up iptables


Available Phishing Scenarios:

1 - Firmware Upgrade Page
	A router configuration page without logos or brands asking for WPA/WPA2 password due to a firmware upgrade. Mobile-friendly.

2 - Network Manager Connect
	Imitates the behavior of the network manager. This template shows Chrome's "Connection Failed" page and displays a network manager window through the page asking for the pre-shared key. Currently, the network managers of Windows and MAC OS are supported.

3 - OAuth Login Page
	A free Wi-Fi Service asking for Facebook credentials to authenticate using OAuth

4 - Browser Plugin Update
	A generic browser plugin update page that can be used to serve payloads to the victims.


[+] Choose the [num] of the scenario you wish to use: 3
[+] Selecting OAuth Login Page template
[*] Starting the fake access point...
[+] Failed to start the fake access point! (hostapd error)
[+] Try a different wireless interface using -aI option.
[+] Captured credentials:
Traceback (most recent call last):
  File "/usr/local/bin/wifiphisher", line 9, in <module>
    load_entry_point('wifiphisher==1.3', 'console_scripts', 'wifiphisher')()
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.3-py2.7.egg/wifiphisher/pywifiphisher.py", line 776, in run
    engine.start()
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.3-py2.7.egg/wifiphisher/pywifiphisher.py", line 704, in start
    self.stop()
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.3-py2.7.egg/wifiphisher/pywifiphisher.py", line 541, in stop
    self.network_manager.on_exit()
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.3-py2.7.egg/wifiphisher/common/interfaces.py", line 396, in on_exit
    self.reset_ifaces_to_managed()
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.3-py2.7.egg/wifiphisher/common/interfaces.py", line 385, in reset_ifaces_to_managed
    self.set_interface_mode(i, "managed")
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.3-py2.7.egg/wifiphisher/common/interfaces.py", line 272, in set_interface_mode
    pyw.up(card)
  File "/usr/local/lib/python2.7/dist-packages/PyRIC-0.1.6.3-py2.7.egg/pyric/pyw.py", line 572, in up
    if iosock is None: return _iostub_(up, card)
  File "/usr/local/lib/python2.7/dist-packages/PyRIC-0.1.6.3-py2.7.egg/pyric/pyw.py", line 2217, in _iostub_
    return fct(*argv)
  File "/usr/local/lib/python2.7/dist-packages/PyRIC-0.1.6.3-py2.7.egg/pyric/pyw.py", line 577, in up
    _flagsset_(card.dev, _setf_(flags, ifh.IFF_UP), iosock)
  File "/usr/local/lib/python2.7/dist-packages/PyRIC-0.1.6.3-py2.7.egg/pyric/pyw.py", line 1926, in _flagsset_
    raise pyric.error(e.errno, e.strerror)
pyric.error: [Errno 76] Name not unique on network
root@kali:~# 
```
............................................................................

Hello . I can not run most commands
Only this is    raise pyric.error(e.errno, e.strerror)
pyric.error: [Errno 76] Name not unique on network
please guide me
How to fix this problem

**Comment by anakin1028** [comment]
You should check whether your card support the AP mode.

1. check the interface name by `iw dev`
2. use command `iw phy phy0 info |grep "Supported interface" -A15` to check the supported modes
    [NOTE] : you should replace phy0 with the name you observe in `iw dev`, and you can dump the result of the two cards (One will be used as jamming and the other is AP) in this thread.

**Comment by blackHatMonkey** [comment]
@alilord I'm closing this issue due to inactivity. Feel free to reopen if needed.
