### ISSUE TITLE
in docker run wifiphisher, tip: pyric.error: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by shoulder1205** [wifiphisher/wifiphisher#703]
```
root@d06fed8190b8:~/wifiphisher# python bin/wifiphisher
[*] Starting Wifiphisher 1.3GIT ( https://wifiphisher.org ) at 2017-08-13 07:35
Traceback (most recent call last):
File "bin/wifiphisher", line 12, in
run()
File "/root/wifiphisher/wifiphisher/pywifiphisher.py", line 783, in run
engine.start()
File "/root/wifiphisher/wifiphisher/pywifiphisher.py", line 529, in start
self.network_manager.start()
File "/root/wifiphisher/wifiphisher/common/interfaces.py", line 610, in start
raise error
pyric.error: [Errno 2] No such file or directory

root@d06fed8190b8:~/wifiphisher# pip install pyric
Requirement already satisfied: pyric in /usr/local/lib/python2.7/dist-packages/PyRIC-0.1.6.3-py2.7.egg

root@d06fed8190b8:~/wifiphisher# pip install -U pyric
Requirement already up-to-date: pyric in /usr/local/lib/python2.7/dist-packages/PyRIC-0.1.6.3-py2.7.egg
```

**Comment by shoulder1205** [comment]
root@d06fed8190b8:~/wifiphisher# python bin/wifiphisher
[*] Starting Wifiphisher 1.3GIT ( https://wifiphisher.org ) at 2017-08-13 07:35
Traceback (most recent call last):
  File "bin/wifiphisher", line 12, in <module>
    run()
  File "/root/wifiphisher/wifiphisher/pywifiphisher.py", line 783, in run
    engine.start()
  File "/root/wifiphisher/wifiphisher/pywifiphisher.py", line 529, in start
    self.network_manager.start()
  File "/root/wifiphisher/wifiphisher/common/interfaces.py", line 610, in start
    raise error
pyric.error: [Errno 2] No such file or directory

root@d06fed8190b8:~/wifiphisher# pip install pyric
Requirement already satisfied: pyric in /usr/local/lib/python2.7/dist-packages/PyRIC-0.1.6.3-py2.7.egg

root@d06fed8190b8:~/wifiphisher# pip install -U pyric
Requirement already up-to-date: pyric in /usr/local/lib/python2.7/dist-packages/PyRIC-0.1.6.3-py2.7.egg

**Comment by blackHatMonkey** [comment]
@shoulder1205 Thanks for filing a bug report. Are you using docker to run `wifiphisher`?
