### ISSUE TITLE
Traceback: with kali on Pi

### ISSUE THREAD

**Issue by davetayl** [wifiphisher/wifiphisher#710]
I've just installed wifiphisher on a PI3 running the latest version of kali 2017 with the Re4son kernel.

Python is v2.7.13
uname: Linux <removed> 4.4.50-Re4son-v7+ #20 SMP Wed Jul 26 07:41:10 AEST 2017 armv7l GNU/Linux

The install had no errors, however when I try to run the application I get the following.
-----------------------------------------------------------------------------------------------------------------
root@<removed>:~/Downloads/wifiphisher# wifiphisher -iI eth1 -aI wlan1 -nJ -e <removed -qS
[*] Starting Wifiphisher 1.3GIT ( https://wifiphisher.org ) at 2017-08-17 12:31
[+] Selecting wlan1 interface for creating the rogue Access Point
[+] Changing wlan1 MAC addr (BSSID) to 00:00:00:9d:a7:0b
[*] Cleared leases, started DHCP, set up iptables
Traceback (most recent call last):
  File "/usr/local/bin/wifiphisher", line 11, in <module>
    load_entry_point('wifiphisher==1.3', 'console_scripts', 'wifiphisher')()
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.3-py2.7.egg/wifiphisher/pywifiphisher.py", line 786, in run
    engine.start()
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.3-py2.7.egg/wifiphisher/pywifiphisher.py", line 658, in start
    template = tui_template_obj.gather_info(args.phishingscenario, self.template_manager)
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.3-py2.7.egg/wifiphisher/common/tui.py", line 133, in gather_info
    template_names)
  File "/usr/lib/python2.7/curses/wrapper.py", line 43, in wrapper
    return func(stdscr, *args, **kwds)
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.3-py2.7.egg/wifiphisher/common/tui.py", line 255, in display_info
    curses.curs_set(0)
_curses.error: curs_set() returned ERR
-----------------------------------------------------------------------------------------------------------------

Any help greatly appreciated.

**Comment by davetayl** [comment]
Update: This only occurs over an ssh session, on an attached console there is no problem.

**Comment by davetayl** [comment]
Solved: I was using SecureCRT to access the kali instance, the default terminal emulation type is VT100 with doesn't support curses. By changing to terminal type "Linux" everything worked correctly. Attaching from another linux box worked perfectly.

**Comment by anakin1028** [comment]
@davetayl  good to hear about that : )
