### ISSUE TITLE
OSError: [Errno 100] Network is down.

### ISSUE THREAD

**Issue by berrysamson** [wifiphisher/wifiphisher#748]
Hello all, 

it seems recently my machine has started playing silly buggers whilst running wifiphisher.
Sadly the command wifiphisher -aI wlan0 -jI wlan1 ends in errno 100, the full error is as follows...
```
wifiphisher -jI wlan0 -aI wlan1
[*] Starting Wifiphisher 1.1GIT at 2017-09-15 23:54
[+] Selecting wlan0 interface for the deauthentication attack
[+] Selecting wlan1 interface for creating the rogue Access Point
[*] Cleared leases, started DHCP, set up iptables
Traceback (most recent call last):
  File "/usr/bin/wifiphisher", line 9, in <module>
    load_entry_point('wifiphisher==1.1', 'console_scripts', 'wifiphisher')()
  File "/usr/lib/python2.7/dist-packages/wifiphisher/pywifiphisher.py", line 814, in run
    sniffing(mon_iface.get_name(), targeting_cb)
  File "/usr/lib/python2.7/dist-packages/wifiphisher/pywifiphisher.py", line 221, in sniffing
    sniff(iface=interface, prn=cb, store=0, stop_filter=stopfilter)
  File "/usr/lib/python2.7/dist-packages/scapy/sendrecv.py", line 593, in sniff
    **karg)]
  File "/usr/lib/python2.7/dist-packages/scapy/arch/linux.py", line 510, in __init__
    _flush_fd(self.ins)
  File "/usr/lib/python2.7/dist-packages/scapy/arch/linux.py", line 312, in _flush_fd
    os.read(fd,MTU)
OSError: [Errno 100] Network is down
```
After, I am required to "service network-manager restart" in order to reconnect to wifi. Both my internal wifi and external dongle (TL-WN722N) work to connect to access points.

Its odd as last I used wifiphisher it was working without issues.

Any ideas? If you need any more information I'd be happy to provide.

**Comment by sophron** [comment]
Hi @berrysamson,

#751 was merged yesterday that may has solved this. Can you update to the latest revision and try again?
