### ISSUE TITLE
UnboundLocalError: local variable 'mon_iface' referenced before assignment

### ISSUE THREAD

**Issue by vovawed** [wifiphisher/wifiphisher#764]
```
root@kali:~/Desktop/wifiphisher# wifiphisher 
[*] Starting Wifiphisher 1.3GIT ( https://wifiphisher.org ) at 2017-09-27 12:47
Traceback (most recent call last):
  File "/usr/local/bin/wifiphisher", line 11, in <module>
    load_entry_point('wifiphisher==1.3', 'console_scripts', 'wifiphisher')()
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.3-py2.7.egg/wifiphisher/pywifiphisher.py", line 716, in run
    engine.start()
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.3-py2.7.egg/wifiphisher/pywifiphisher.py", line 526, in start
    logger.exception("Setting {} to monitor mode".format(mon_iface))
UnboundLocalError: local variable 'mon_iface' referenced before assignment
```

**Comment by Hypsie** [comment]
I got the same error !

**Comment by Hypsie** [comment]
I use a raspberry 3 with raspbian jessie.

**Comment by blackHatMonkey** [comment]
@vovawed @Hypsie Thanks for opening an issue. We are aware of the problem and a fix will be out soon. One of the members will update this thread once a patch has been merged.
