### ISSUE TITLE
The provided MAC address is invalid

### ISSUE THREAD

**Issue by jadbara** [wifiphisher/wifiphisher#776]
`[*] Starting Wifiphisher 1.3GIT ( https://wifiphisher.org ) at 2017-10-11 09:36
[+] Selecting wlan1 interface for the deauthentication attack
[+] Selecting wlan0 interface for creating the rogue Access Point
Traceback (most recent call last):
  File "/usr/local/bin/wifiphisher", line 11, in <module>
    load_entry_point('wifiphisher==1.3', 'console_scripts', 'wifiphisher')()
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.3-py2.7.egg/wifiphisher/pywifiphisher.py", line 560, in run
    engine.start()
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.3-py2.7.egg/wifiphisher/pywifiphisher.py", line 326, in start
    self.network_manager.set_interface_mac_random(ap_iface)
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.3-py2.7.egg/wifiphisher/common/interfaces.py", line 531, in set_interface_mac_random
    self.set_interface_mac(interface_name, new_mac_address)
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.3-py2.7.egg/wifiphisher/common/interfaces.py", line 493, in set_interface_mac
    raise InvalidMacAddressError(mac_address)
wifiphisher.common.interfaces.InvalidMacAddressError: The provided MAC address 00:00:00:fb:5d:70 is invalid
`

**Comment by anakin1028** [comment]
Please provide with `-iNM` first. Looks like your card doesn't support changing MAC addreSs via nl80211. Thanks

**Comment by jadbara** [comment]
Thank you very much .. Solved 😃

**Comment by anakin1028** [comment]
NP we'll improve tHis part soon.

**Comment by sophron** [comment]
Yes, if MAC randomization fails, we should raise an exception and inform the user.

**Comment by anakin1028** [comment]
Should we terminate the program due to this exception and inform users or just print `[!] MAC address randomization fail!` and let the program run continuously?

**Comment by sophron** [comment]
I think the tool should keep running. Users that want to cancel the operation can Ctrl+C to abort.

**Comment by anakin1028** [comment]
Agree with this : )
