### ISSUE TITLE
error in python setup.py install

### ISSUE THREAD

**Issue by charcchii** [wifiphisher/wifiphisher#780]
```
~\Documents\GitHub\wifiphisher [master ≡]> python setup.py install
Traceback (most recent call last):
  File "setup.py", line 137, in <module>
    get_libdbus()
  File "setup.py", line 108, in get_libdbus
    install = raw_input(("[" + constants.T + "*" + constants.W + "] libdbus-1 no
t found " +
NameError: name 'raw_input' is not defined
```

**Comment by blackHatMonkey** [comment]
@charcchii Make sure that you are running `setup.py` with `python2` and not `python3`.

**Comment by charcchii** [comment]
I am using windows 7 and python 2.7

**Comment by charcchii** [comment]
[←[31m-←[0m] libdbus-1 not found. Please install libdbus-1 (i.e. using your pack
age manager)
~\Documents\GitHub\wifiphisher [master ≡]> pip install libdbus-1 this is the error i get next

**Comment by charcchii** [comment]
~\Documents\GitHub\wifiphisher [master ≡]> python setup.py install
[←[93m*←[0m] libdbus-1 not found install now? [y/n] y
[←[31m-←[0m] libdbus-1 not found. Please install libdbus-1 (i.e. using your pack
age manager)
~\Documents\GitHub\wifiphisher [master ≡]> pip install dbus-python
Collecting dbus-python
  Using cached dbus-python-1.2.4.tar.gz
Building wheels for collected packages: dbus-python
  Running setup.py bdist_wheel for dbus-python ... error
  Complete output from command c:\python27\python.exe -u -c "import setuptools,
tokenize;__file__='c:\\users\\charcchii\\appdata\\local\\temp\\pip-build-akxinz\
\dbus-python\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read(
).replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_w
heel -d c:\users\charcchii\appdata\local\temp\tmpd15_bcpip-wheel- --python-tag c
p27:
  running bdist_wheel
  running build
  creating c:\users\charcchii\appdata\local\temp\pip-build-akxinz\dbus-python\bu
ild
  creating c:\users\charcchii\appdata\local\temp\pip-build-akxinz\dbus-python\bu
ild\temp.win32-2.7
  error: [Error 193] %1 is not a valid Win32 application

here is another error when I try to get dbus services

**Comment by blackHatMonkey** [comment]
@charcchii Unfortunately it will not work on windows as `dbus` is a `Linux` only library. So you either have to install `Linux` locally or in a `virtual machine`.

**Comment by charcchii** [comment]
Okay will try it on a vm

**Comment by blackHatMonkey** [comment]
@charcchii I'm closing this issue due to inactivity. Feel free to re-open if needed 😄 .

**Comment by Abvatous** [comment]
Hello~
I had the installded problem .too~
My Version is Python 2.7.12+.But After taping   "python setup.py install",i just got:

Download error on https://pypi.python.org/simple/blessings/: [Errno -2] Name or service not known -- Some packages may not be found!
Couldn't find index page for 'blessings' (maybe misspelled?)

Please~~

**Comment by tomsi113** [comment]
Solution for problem:
It's easy... all you have to do is install dbus-glib
on my mac i've used `brew install dbus-glib`
