### ISSUE TITLE
can't use wifiphisher on arch linux

### ISSUE THREAD

**Issue by ls4cfk** [wifiphisher/wifiphisher#800]
[root@ls4cfk wifiphisher]# wifiphisher
Traceback (most recent call last):
  File "/usr/bin/wifiphisher", line 11, in <module>
    load_entry_point('wifiphisher==1.3', 'console_scripts', 'wifiphisher')()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 570, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2755, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2409, in load
    return self.resolve()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2415, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python2.7/site-packages/wifiphisher-1.3-py2.7.egg/wifiphisher/pywifiphisher.py", line 25, in <module>
    import wifiphisher.common.interfaces as interfaces
  File "/usr/lib/python2.7/site-packages/wifiphisher-1.3-py2.7.egg/wifiphisher/common/interfaces.py", line 11, in <module>
    import dbus
ImportError: No module named dbus

i installed it with a python 2 , but i cant start

**Comment by ls4cfk** [comment]
new error ;-;

root@ls4cfk wifiphisher]# wifiphisher
Traceback (most recent call last):
  File "/usr/bin/wifiphisher", line 11, in <module>
    load_entry_point('wifiphisher==1.3', 'console_scripts', 'wifiphisher')()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 570, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2755, in load_entry_point
    return ep.load()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2409, in load
    return self.resolve()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2415, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3.6/site-packages/wifiphisher-1.3-py3.6.egg/wifiphisher/pywifiphisher.py", line 220
    print '[' + G + '+' + W + "] Sending SIGKILL to " +\
            ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(print '[' + G + '+' + W + "] Sending SIGKILL to " +\)?
[root@ls4cfk wifiphisher]#

**Comment by anakin1028** [comment]
can you show the output of `python` on the command line?
from the stdout:
```
File "/usr/lib/python3.6/site-packages/pkg_resources/init.py", line 2415, in resolve
module = import(self.module_name, fromlist=['name'], level=0)
File "/usr/lib/python3.6/site-packages/wifiphisher-1.3-py3.6.egg/wifiphisher/pywifiphisher.py", line 220
print '[' + G + '+' + W + "] Sending SIGKILL to " +
^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(print '[' + G + '+' + W + "] Sending SIGKILL to " +)?
```

It seems wifiphisher is installed under `python3`?

**Comment by ls4cfk** [comment]
i don't know how but i fixed it
![screenshot from 2017-11-05 20-31-32](https://user-images.githubusercontent.com/18011049/32416803-6e22acf4-c268-11e7-9872-aa8b042a929a.png)

**Comment by vishal-sudo** [comment]
> i don't know how but i fixed it
> ![screenshot from 2017-11-05 20-31-32](https://user-images.githubusercontent.com/18011049/32416803-6e22acf4-c268-11e7-9872-aa8b042a929a.png)

Could You Help to run this I got the same issue!!

**Comment by ls4cfk** [comment]
> > i don't know how but i fixed it
> > ![screenshot from 2017-11-05 20-31-32](https://user-images.githubusercontent.com/18011049/32416803-6e22acf4-c268-11e7-9872-aa8b042a929a.png)
> 
> Could You Help to run this I got the same issue!!

Buddy, it was 3 years ago.

Install requirements with pip3 and run code with python3. that would solve the issue.

**Comment by vishal-sudo** [comment]
> > > i don't know how but i fixed it
> > > ![screenshot from 2017-11-05 20-31-32](https://user-images.githubusercontent.com/18011049/32416803-6e22acf4-c268-11e7-9872-aa8b042a929a.png)
> > 
> > 
> > Could You Help to run this I got the same issue!!
> 
> Buddy, it was 3 years ago.
> 
> Install requirements with pip3 and run code with python3. that would solve the issue.

i know its 3year old post but facing same issue and didn't find any solution...
btw thx for help..
