### ISSUE TITLE
Problem starting with wifiphisher on kali nethunter(arm64)

### ISSUE THREAD

**Issue by lightakun** [wifiphisher/wifiphisher#819]
I own a leeco le2 having nethunter installed
wifiphisher runs with following error codes
```
root@kali:~/wifiphisher# wifiphisher
[*] Starting Wifiphisher 1.3GIT ( https://wifiphisher.org ) at 2017-11-29 03:19
Traceback (most recent call last):
  File "/usr/local/bin/wifiphisher", line 11, in <module>
    load_entry_point('wifiphisher==1.3', 'console_scripts', 'wifiphisher')()
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.3-py2.7.egg/wifiphisher/pywifiphisher.py", line 574, in run
    engine.start()
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.3-py2.7.egg/wifiphisher/pywifiphisher.py", line 278, in start
    self.opmode.initialize(args)
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.3-py2.7.egg/wifiphisher/common/opmode.py", line 52, in initialize
    interfaces.is_add_vif_required(args)
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.3-py2.7.egg/wifiphisher/common/interfaces.py", line 791, in is_add_vif_required
    for vif in [vif for vif in pyw.interfaces() if pyw.iswireless(vif)]:
  File "/usr/lib/python2.7/dist-packages/pyric/pyw.py", line 160, in iswireless
    return _iostub_(iswireless, dev)
  File "/usr/lib/python2.7/dist-packages/pyric/pyw.py", line 2250, in _iostub_
    return fct(*argv)
  File "/usr/lib/python2.7/dist-packages/pyric/pyw.py", line 171, in iswireless
    else: raise pyric.error(e.errno, e.strerror)
pyric.error: [Errno 22] Invalid argument
root@kali:~/wifiphisher#
```
I run python setup.py first and all the dependies are installed 
Please get to me soon

Edited by @blackhatmonkey: fixed the error wrap.

**Comment by JetseVerschuren** [comment]
Can you wrap that snippet in code tags?

**Comment by lightakun** [comment]
@JetseVerschuren
Here the code clearly
http://freetexthost.com/d2oiiwn4hl

**Comment by blackHatMonkey** [comment]
@lightakun Unfortuantely Nethunter is not currently supported. It seems the tool has dificualty finding the correct interfaces.

**Comment by lightakun** [comment]
@blackHatMonkey
Okay no problem! :)

**Comment by Denzel-Washington** [comment]
hi does wifiphisher support nethunter now?

**Comment by sophron** [comment]
No, there is no progress on this. I'm still lacking a device that runs NetHunter.

**Comment by Decapitater** [comment]
@sophron 
now ?
