### ISSUE TITLE
setup tools not working

### ISSUE THREAD

**Issue by yigitcolakoglu** [wifiphisher/wifiphisher#831]
**Description**: 

OK, so I have been trying to install a tool called "WifiPhisher" on my PC. However, as I try to run the setup.py file, I get this error(I am using python 2.7.14 btw) :

```
root@UNIC0RN:~/wifiphisher# sudo python setup.py install 
Traceback (most recent call last):
  File "setup.py", line 10, in <module>
    from setuptools import setup, find_packages, Command
ImportError: No module named setuptools
```

so, I tried installing setup tools using :

`root@UNIC0RN:~# sudo pip install setuptools`

However, it said
`
Requirement already satisfied: setuptools in /usr/lib/python2.7/dist-packages`

I am stuck rn. Would appreciate any help on making it work. ( I am using the last distribution of kali linux btw)

**Comment by JetseVerschuren** [comment]
What does `python --version` return?

**Comment by yigitcolakoglu** [comment]
@JetseVerschuren  `Python 2.7.14 :: Anaconda, Inc.`

**Comment by JetseVerschuren** [comment]
Try `python -m pip install --upgrade pip setuptools`

**Comment by yigitcolakoglu** [comment]
I get this `Exception:
Traceback (most recent call last):
  File "/root/anaconda2/lib/python2.7/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/root/anaconda2/lib/python2.7/site-packages/pip/commands/install.py", line 272, in run
    with self._build_session(options) as session:
  File "/root/anaconda2/lib/python2.7/site-packages/pip/basecommand.py", line 72, in _build_session
    insecure_hosts=options.trusted_hosts,
  File "/root/anaconda2/lib/python2.7/site-packages/pip/download.py", line 329, in __init__
    self.headers["User-Agent"] = user_agent()
  File "/root/anaconda2/lib/python2.7/site-packages/pip/download.py", line 93, in user_agent
    from pip._vendor import distro
  File "/root/anaconda2/lib/python2.7/site-packages/pip/_vendor/distro.py", line 1050, in <module>
    _distro = LinuxDistribution()
  File "/root/anaconda2/lib/python2.7/site-packages/pip/_vendor/distro.py", line 594, in __init__
    if include_lsb else {}
  File "/root/anaconda2/lib/python2.7/site-packages/pip/_vendor/distro.py", line 933, in _get_lsb_release_info
    raise subprocess.CalledProcessError(code, cmd, stdout)
CalledProcessError: Command 'lsb_release -a' returned non-zero exit status 134
Traceback (most recent call last):
  File "/root/anaconda2/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/root/anaconda2/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/root/anaconda2/lib/python2.7/site-packages/pip/__main__.py", line 19, in <module>
    sys.exit(pip.main())
  File "/root/anaconda2/lib/python2.7/site-packages/pip/__init__.py", line 233, in main
    return command.main(cmd_args)
  File "/root/anaconda2/lib/python2.7/site-packages/pip/basecommand.py", line 251, in main
    timeout=min(5, options.timeout)) as session:
  File "/root/anaconda2/lib/python2.7/site-packages/pip/basecommand.py", line 72, in _build_session
    insecure_hosts=options.trusted_hosts,
  File "/root/anaconda2/lib/python2.7/site-packages/pip/download.py", line 329, in __init__
    self.headers["User-Agent"] = user_agent()
  File "/root/anaconda2/lib/python2.7/site-packages/pip/download.py", line 93, in user_agent
    from pip._vendor import distro
  File "/root/anaconda2/lib/python2.7/site-packages/pip/_vendor/distro.py", line 1050, in <module>
    _distro = LinuxDistribution()
  File "/root/anaconda2/lib/python2.7/site-packages/pip/_vendor/distro.py", line 594, in __init__
    if include_lsb else {}
  File "/root/anaconda2/lib/python2.7/site-packages/pip/_vendor/distro.py", line 933, in _get_lsb_release_info
    raise subprocess.CalledProcessError(code, cmd, stdout)
subprocess.CalledProcessError: Command 'lsb_release -a' returned non-zero exit status 134
`

**Comment by JetseVerschuren** [comment]
Are you on Kali Linux?

**Comment by yigitcolakoglu** [comment]
@JetseVerschuren  yes why?

**Comment by JetseVerschuren** [comment]
Ok, can you try
`apt-get purge python-pip`
`apt-get install python-setuptools`
`easy_install -U pip`

**Comment by nagyar9966** [comment]
user_options = []
  File "/data/data/com.termux/files/usr/tmp/easy_install-7x_asny6/roguehostapd-1.2.3/roguehostapd/config/hostapdconfig.py", line 9, in <module>
ModuleNotFoundError: No module named 'ConfigParser'
My error, what about this?
