### ISSUE TITLE
Issues/OSError: [Errno 2] No such file or directory:

### ISSUE THREAD

**Issue by Hizzly** [wifiphisher/wifiphisher#844]
Hello! I have very strange issue.So i put new phishing-extra pages in /wifiphisher/data/phishing-page and when i start the Terminal and trying to use them (sudo wifiphisher --noextensions --essid "something" -p ( for example i using google-login) google-login. and i got this error.
```
 sudo wifiphisher --noextensions --essid "Free Wifi " -p google-login
[*] Starting Wifiphisher 1.4 ( https://wifiphisher.org ) at 2018-01-15 10:57
Traceback (most recent call last):
  File "/usr/local/bin/wifiphisher", line 11, in <module>
    load_entry_point('wifiphisher==1.4', 'console_scripts', 'wifiphisher')()
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.4-py2.7.egg/wifiphisher/pywifiphisher.py", line 616, in run
    engine = WifiphisherEngine()
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.4-py2.7.egg/wifiphisher/pywifiphisher.py", line 235, in __init__
    self.template_manager = phishingpage.TemplateManager()
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.4-py2.7.egg/wifiphisher/common/phishingpage.py", line 308, in __init__
    self.add_user_templates()
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.4-py2.7.egg/wifiphisher/common/phishingpage.py", line 389, in add_user_templates
    user_templates = self.find_user_templates()
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.4-py2.7.egg/wifiphisher/common/phishingpage.py", line 366, in find_user_templates
    is_valid, output = self.is_valid_template(name)
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.4-py2.7.egg/wifiphisher/common/phishingpage.py", line 333, in is_valid_template
    tdir = os.listdir(os.path.join(dir_path, constants.SCENARIO_HTML_DIR))
OSError: [Errno 2] No such file or directory: '/usr/local/lib/python2.7/dist-packages/wifiphisher-1.4-py2.7.egg/wifiphisher/data/phishing-pages/facebook-login/html/'
```
I'll be very glad if we solve this problem :)

**Comment by anakin1028** [comment]
When you put the new phishing scenario, hAve you do the `python setup.py install` again?

**Comment by Hizzly** [comment]
yes,i do it ,but nothing different happen i mean after the setup.py install in the terminal 
showing me how they are "installed" but when i try to use them i got this error.

**Comment by anakin1028** [comment]
We don't maintain the phishing scenarios repo and I guess maybe the directory structure has problem for that phishing scenario.

Can you check the path in [Errno 2], `..facebook-login..` and see if there has such directory?

**Comment by anakin1028** [comment]
@Hizzly this should be fixed for now. You can first update the `extra-phishing-pages` repo since we have a fix for that repo yesterday. Then just copy the desired phishing scenario into wifiphisher as before.

**Comment by Hizzly** [comment]
Thx :))

2018-01-28 15:34 GMT+02:00 Anakin <notifications@github.com>:

**Comment by Hizzly** [comment]
Hey,

I just signed the petition "Защити свободата си на изразяване от новата
директива за авторското право" and wanted to see if you could help by
adding your name.

Our goal is to reach 99,699 signatures and we need more support. You can
read more and sign the petition here:

http://chng.it/hbvnFtdtPN

Thanks!
Nikolai
