### ISSUE TITLE
Running terminal via serial on Pi Zero get _curses.error: curs_set() returned ERR

### ISSUE THREAD

**Issue by gitxmax** [wifiphisher/wifiphisher#845]
**Version**
Latest

**Description**
I run my terminal via the serial output of Raspberry Pi Zero W, to spare the only usb port , for the external wifi dongle.
Sadly, Wifiphisher, seems to have a problem with that, giving me  the "_curses.error: curs_set() returned ERR" and messing up the whole wifi network, until reboot.

**Script output**: Paste the output of the tool, including any stack traces.

Traceback (most recent call last):
  File "/usr/local/bin/wifiphisher", line 11, in <module>
    load_entry_point('wifiphisher==1.4', 'console_scripts', 'wifiphisher')()
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.4-py2.7.egg/wifiphisher/pywifiphisher.py", line 617, in run
    engine.start()
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.4-py2.7.egg/wifiphisher/pywifiphisher.py", line 442, in start
    ap_info_object)
  File "/usr/lib/python2.7/curses/wrapper.py", line 43, in wrapper
    return func(stdscr, *args, **kwds)
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.4-py2.7.egg/wifiphisher/common/tui.py", line 504, in gather_info
    curses.curs_set(0)
_curses.error: curs_set() returned ERR

**Comment by anakin1028** [comment]
@gitxmax can you pull the newest commit and try again to see if the error get fixed?
Looks like there already someone has the same issue:
[curses error](https://github.com/zkanda/PathPicker/commit/9ac916d4ef89eec982865404c1668c1934eeedb1
