### ISSUE TITLE
WiFi Phisher wont  start? Please help a noobie

### ISSUE THREAD

**Issue by JohannesDerWahre** [wifiphisher/wifiphisher#850]
I type in the Terminal(Linux) 

cd wifiphisher
then
python bin/wifiphisher

and then it comes this:
Traceback (most recent call last):
  File "bin/wifiphisher", line 16, in <module>
    from wifiphisher.pywifiphisher import run
  File "/root/wifiphisher/wifiphisher/pywifiphisher.py", line 12, in <module>
    import curses
  File "/usr/local/lib/python2.7/curses/__init__.py", line 15, in <module>
    from _curses import *
ImportError: No module named _curses

Here a Screen video:
[https://streamable.com/9zf2r](url)

Regards 
Johannes

**Comment by anakin1028** [comment]
It seems that the _curse module is missing in your environment. Do you use Kali for testing?

**Comment by anakin1028** [comment]
Also can you show the output of the following command:
`python --version`
