### ISSUE TITLE
Cant run wifiphisher

### ISSUE THREAD

**Issue by 9acca9** [wifiphisher/wifiphisher#852]
Hi to all.
Cant run wifiphisher
Im using archlinux (manjaro).

sudo wifiphisher
Traceback (most recent call last):
  File "/usr/bin/wifiphisher", line 11, in <module>
    load_entry_point('wifiphisher==1.4', 'console_scripts', 'wifiphisher')()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 564, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2662, in load_entry_point
    return ep.load()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2316, in load
    return self.resolve()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2322, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3.6/site-packages/wifiphisher-1.4-py3.6.egg/wifiphisher/pywifiphisher.py", line 226
    print '[' + G + '+' + W + "] Sending SIGKILL to " +\
            ^
SyntaxError: Missing parentheses in call to 'print'

**Comment by anakin1028** [comment]
You should use Python2.7 to run wifiphisher.
