### ISSUE TITLE
Wifiphisher v1.4 won't install

### ISSUE THREAD

**Issue by yasinsaeed007** [wifiphisher/wifiphisher#861]
Hi Guys,

I have tried to install wifiphisher 1.4 literally 100 times but i still get the same issue... i installed 2017.1 and 2 and 3 now i am on 2018.1 every single platform has same issue, i have Aethros supported wireless usb adapter and one is builtin which is good for monitor mode...

i will paste the logs and please suggest me how to solve this issue before you you suggest me any basic rules i think i have done all that by reading previous queries and no solution so far.

i have latest and old kali repo installed, fully updated and upgrade no issue with that, 

i have latest aircrack -ng, python 2.7 , latest pyric, latest matplotic, tcpdump, latest hostapd, latest setup tools, literally everything i tried from previous problems but no help.

Please help me solve this problem urgently.

Regards

> 
Installed /usr/local/lib/python2.7/dist-packages/wifiphisher-1.4-py2.7.egg
Processing dependencies for wifiphisher==1.4
Searching for roguehostapd
Reading https://pypi.python.org/simple/roguehostapd/
Downloading https://pypi.python.org/packages/05/8e/0ac5ed46c27aa20b70cb25bea71bc74cb1c68321fbee94968fae9a59b7e2/roguehostapd-1.1.7.tar.gz#md5=7d6bca2cff06f995951077151a50a597
Best match: roguehostapd 1.1.7
Processing roguehostapd-1.1.7.tar.gz
Writing /tmp/easy_install-_1iZQ9/roguehostapd-1.1.7/setup.cfg
Running roguehostapd-1.1.7/setup.py -q bdist_egg --dist-dir /tmp/easy_install-_1iZQ9/roguehostapd-1.1.7/egg-dist-tmp-3k69Ul
Traceback (most recent call last):
  File "setup.py", line 127, in <module>
    install_requires=INSTALL_REQUIRES, classifiers=CLASSIFIERS, url=URL, cmdclass=CMDCLASS)
  File "/usr/local/lib/python2.7/dist-packages/setuptools-38.4.0-py2.7.egg/setuptools/__init__.py", line 129, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/local/lib/python2.7/dist-packages/setuptools-38.4.0-py2.7.egg/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/usr/local/lib/python2.7/dist-packages/setuptools-38.4.0-py2.7.egg/setuptools/command/install.py", line 117, in do_egg_install
    cmd.run()
  File "/usr/local/lib/python2.7/dist-packages/setuptools-38.4.0-py2.7.egg/setuptools/command/easy_install.py", line 412, in run
    self.easy_install(spec, not self.no_deps)
  File "/usr/local/lib/python2.7/dist-packages/setuptools-38.4.0-py2.7.egg/setuptools/command/easy_install.py", line 654, in easy_install
    return self.install_item(None, spec, tmpdir, deps, True)
  File "/usr/local/lib/python2.7/dist-packages/setuptools-38.4.0-py2.7.egg/setuptools/command/easy_install.py", line 701, in install_item
    self.process_distribution(spec, dist, deps)
  File "/usr/local/lib/python2.7/dist-packages/setuptools-38.4.0-py2.7.egg/setuptools/command/easy_install.py", line 746, in process_distribution
    [requirement], self.local_index, self.easy_install
  File "/usr/local/lib/python2.7/dist-packages/setuptools-38.4.0-py2.7.egg/pkg_resources/__init__.py", line 866, in resolve
    replace_conflicting=replace_conflicting
  File "/usr/local/lib/python2.7/dist-packages/setuptools-38.4.0-py2.7.egg/pkg_resources/__init__.py", line 1146, in best_match
    return self.obtain(req, installer)
  File "/usr/local/lib/python2.7/dist-packages/setuptools-38.4.0-py2.7.egg/pkg_resources/__init__.py", line 1158, in obtain
    return installer(requirement)
  File "/usr/local/lib/python2.7/dist-packages/setuptools-38.4.0-py2.7.egg/setuptools/command/easy_install.py", line 673, in easy_install
    return self.install_item(spec, dist.location, tmpdir, deps)
  File "/usr/local/lib/python2.7/dist-packages/setuptools-38.4.0-py2.7.egg/setuptools/command/easy_install.py", line 699, in install_item
    dists = self.install_eggs(spec, download, tmpdir)
  File "/usr/local/lib/python2.7/dist-packages/setuptools-38.4.0-py2.7.egg/setuptools/command/easy_install.py", line 882, in install_eggs
    return self.build_and_install(setup_script, setup_base)
  File "/usr/local/lib/python2.7/dist-packages/setuptools-38.4.0-py2.7.egg/setuptools/command/easy_install.py", line 1150, in build_and_install
    self.run_setup(setup_script, setup_base, args)
  File "/usr/local/lib/python2.7/dist-packages/setuptools-38.4.0-py2.7.egg/setuptools/command/easy_install.py", line 1136, in run_setup
    run_setup(setup_script, args)
  File "/usr/local/lib/python2.7/dist-packages/setuptools-38.4.0-py2.7.egg/setuptools/sandbox.py", line 253, in run_setup
    raise
  File "/usr/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python2.7/dist-packages/setuptools-38.4.0-py2.7.egg/setuptools/sandbox.py", line 195, in setup_context
    yield
  File "/usr/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python2.7/dist-packages/setuptools-38.4.0-py2.7.egg/setuptools/sandbox.py", line 166, in save_modules
    saved_exc.resume()
  File "/usr/local/lib/python2.7/dist-packages/setuptools-38.4.0-py2.7.egg/setuptools/sandbox.py", line 141, in resume
    six.reraise(type, exc, self._tb)
  File "/usr/local/lib/python2.7/dist-packages/setuptools-38.4.0-py2.7.egg/setuptools/sandbox.py", line 154, in save_modules
    yield saved
  File "/usr/local/lib/python2.7/dist-packages/setuptools-38.4.0-py2.7.egg/setuptools/sandbox.py", line 195, in setup_context
    yield
  File "/usr/local/lib/python2.7/dist-packages/setuptools-38.4.0-py2.7.egg/setuptools/sandbox.py", line 250, in run_setup
    _execfile(setup_script, ns)
  File "/usr/local/lib/python2.7/dist-packages/setuptools-38.4.0-py2.7.egg/setuptools/sandbox.py", line 45, in _execfile
    exec(code, globals, locals)
  File "/tmp/easy_install-_1iZQ9/roguehostapd-1.1.7/setup.py", line 9, in <module>
    from ctypes.util import find_library
ImportError: No module named hostapd_build.build_files

> `

**Comment by bricco1981** [comment]
same here wifiphisher 1.3 is fine but no 1.4

**Comment by anakin1028** [comment]
Hi all, this is a known issue since `wifiphisher` is dependent on `roguehostapd`, but we have a issue for roguehostapd now. We'll fix it soon! Thanks:)

**Comment by anakin1028** [comment]
@yasinsaeed007, this is the same issue in #860. I will close this first, and we may track this issue in #860.

**Comment by yasinsaeed007** [comment]
Okay guys, i have fixed the issue and now everything is fine...
