### ISSUE TITLE
?

### ISSUE THREAD

**Issue by linuxbased** [wifiphisher/wifiphisher#868]
`Traceback (most recent call last):
  File "/usr/local/bin/wifiphisher", line 9, in <module>
    load_entry_point('wifiphisher==1.4', 'console_scripts', 'wifiphisher')()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 565, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 2697, in load_entry_point
    return ep.load()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 2370, in load
    return self.resolve()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 2376, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/Library/Python/2.7/site-packages/wifiphisher-1.4-py2.7.egg/wifiphisher/pywifiphisher.py", line 25, in <module>
    import wifiphisher.common.interfaces as interfaces
  File "/Library/Python/2.7/site-packages/wifiphisher-1.4-py2.7.egg/wifiphisher/common/interfaces.py", line 11, in <module>
    import dbus
ImportError: No module named dbus`

**Comment by JetseVerschuren** [comment]
Try `apt-get install python-dbus`

**Comment by linuxbased** [comment]
now it says
```
Traceback (most recent call last):
  File "/usr/local/bin/wifiphisher", line 9, in <module>
    load_entry_point('wifiphisher==1.4', 'console_scripts', 'wifiphisher')()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 565, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 2697, in load_entry_point
    return ep.load()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 2370, in load
    return self.resolve()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 2376, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/Library/Python/2.7/site-packages/wifiphisher-1.4-py2.7.egg/wifiphisher/pywifiphisher.py", line 25, in <module>
    import wifiphisher.common.interfaces as interfaces
  File "/Library/Python/2.7/site-packages/wifiphisher-1.4-py2.7.egg/wifiphisher/common/interfaces.py", line 11, in <module>
    import dbus
ImportError: No module named dbus
```

**Comment by JetseVerschuren** [comment]
And if you run `pip install dbus-python`?

**Comment by linuxbased** [comment]
Sorry, i forgot to say, im using OS X. How can I fix this error? And are there hostapd for OS X?

**Comment by linuxbased** [comment]
`pip install dbus-python`
`Requirement already satisfied: dbus-python in /Library/Python/2.7/site-packages/dbus_python-1.2.4-py2.7-macosx-10.12-intel.egg`

**Comment by JetseVerschuren** [comment]
What version of python are you using?
You can check by using `python --version`

**Comment by anakin1028** [comment]
@linuxbased Hostapd only supports on Linux system, thanks.

**Comment by linuxbased** [comment]
I am using Python 2.7.10

**Comment by anakin1028** [comment]
I'll close this issue since wifiphisher currently not being supported on OSX. Thanks~

**Comment by linuxbased** [comment]
There should be an WiFi hacking script for OS X guys? Or something like **wifiphisher**, please help me.

**Comment by anakin1028** [comment]
What kind of hacking do you want to practice? If you want to get the feel of how to do the passphrase hacking, you can try with aircrack-ng.
From the following link, aircrack-ng supports in OSX. But I still suggest to install Kali or Ubuntu Linux for practice hacking skill. Since most of popular hacking tools already installed in Kali Linux, that's why many people use it.

https://www.aircrack-ng.org/install.html

**Comment by linuxbased** [comment]
macbook's wireless card doesnt work on kali linux, can you give other names about wifi cracking.

**Comment by linuxbased** [comment]
i just want to access to internet
