### ISSUE TITLE
Please Help  wont load

### ISSUE THREAD

**Issue by Mikewins1** [wifiphisher/wifiphisher#875]
Before opening a new issue, please make sure that what you are about to report has not been reported already. If not, use the following template for reporting.

**Version**: 62ebce82fe54a718870afbde1615233ba783db3b
**Description**:
```
wlan1     IEEE 802.11  ESSID:off/any  
          Mode:Managed  Access Point: Not-Associated   Tx-Power=30 dBm   
          Retry short  long limit:2   RTS thr:off   Fragment thr:off
          Encryption key:off
          Power Management:off
          
eth0      no wireless extensions.

wlan0     IEEE 802.11  ESSID:"Phone1"  
          Mode:Managed  Frequency:2.437 GHz  Access Point: B2:72:BF:F3:F8:E4   
          Bit Rate=65 Mb/s   Tx-Power=17 dBm   
          Retry short limit:7   RTS thr:off   Fragment thr:off
          Encryption key:off
          Power Management:off
          Link Quality=70/70  Signal level=-37 dBm  
          Rx invalid nwid:0  Rx invalid crypt:0  Rx invalid frag:0
          Tx excessive retries:0  Invalid misc:2   Missed beacon:0

lo        no wireless extensions.
```
**Output**:
```
root@kali:~# wifiphisher
Traceback (most recent call last):
  File "/usr/local/bin/wifiphisher", line 11, in <module>
    load_entry_point('wifiphisher==1.4', 'console_scripts', 'wifiphisher')()
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 565, in load_entry_point
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 2598, in load_entry_point
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 2258, in load
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 2264, in resolve
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.4-py2.7.egg/wifiphisher/pywifiphisher.py", line 20, in <module>
    import wifiphisher.common.extensions as extensions
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.4-py2.7.egg/wifiphisher/common/extensions.py", line 11, in <module>
    import scapy.layers.dot11 as dot11
  File "/usr/local/lib/python2.7/dist-packages/scapy/layers/dot11.py", line 12, in <module>
    from scapy.packet import *
  File "/usr/local/lib/python2.7/dist-packages/scapy/packet.py", line 39
    class Packet(BasePacket, metaclass = Packet_metaclass):
                                       ^
SyntaxError: invalid syntax
root@kali:~# 
```

**Comment by anakin1028** [comment]
This looks like Python3 syntax for using `metaclass`. 
can you try the following?
```
pip uninstall scapy
pip install -v scapy==2.3.3
```

**Comment by Mikewins1** [comment]
root@kali:~# pip uninstall scapy
DEPRECATION: Uninstalling a distutils installed project (scapy) has been
deprecated and will be removed in a future version. This is due to the fact
that uninstalling a distutils project will only partially uninstall the
project.
Uninstalling scapy-2.3.1:
  /usr/local/lib/python2.7/dist-packages/scapy-2.3.1.egg-info
Proceed (y/n)? y
  Successfully uninstalled scapy-2.3.1
root@kali:~# pip install -v scapy==2.3.3
Converted retries value: Retry(total=5, connect=None, read=None,
redirect=None) -> Retry(total=Retry(total=5, connect=None, read=None,
redirect=None), connect=None, read=None, redirect=None)
Converted retries value: Retry(total=5, connect=None, read=None,
redirect=None) -> Retry(total=Retry(total=5, connect=None, read=None,
redirect=None), connect=None, read=None, redirect=None)
Requirement already satisfied: scapy==2.3.3 in
/usr/lib/python2.7/dist-packages
Cleaning up...
root@kali:~# wifiphisher
Traceback (most recent call last):
  File "/usr/local/bin/wifiphisher", line 11, in <module>
    load_entry_point('wifiphisher==1.4', 'console_scripts', 'wifiphisher')()
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 565,
in load_entry_point
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 2598,
in load_entry_point
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 2258,
in load
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 2264,
in resolve
  File
"/usr/local/lib/python2.7/dist-packages/wifiphisher-1.4-py2.7.egg/wifiphisher/pywifiphisher.py",
line 20, in <module>
    import wifiphisher.common.extensions as extensions
  File
"/usr/local/lib/python2.7/dist-packages/wifiphisher-1.4-py2.7.egg/wifiphisher/common/extensions.py",
line 11, in <module>
    import scapy.layers.dot11 as dot11
  File "/usr/local/lib/python2.7/dist-packages/scapy/layers/dot11.py", line
12, in <module>
    from scapy.packet import *
  File "/usr/local/lib/python2.7/dist-packages/scapy/packet.py", line 39
    class Packet(BasePacket, metaclass = Packet_metaclass):
                                       ^
SyntaxError: invalid syntax
root@kali:~#

**Comment by anakin1028** [comment]
can you show your `pip` version? By `pip --version`.
try:
```
pip uninstall scapy
pip install scapy==2.3.3 --no-cache-dir -v
```

**Comment by Mikewins1** [comment]
Ok

**Comment by anakin1028** [comment]
@Mikewins1 can you refer the solution in #753 and see if this works for you?
