### ISSUE TITLE
???

### ISSUE THREAD

**Issue by chritav** [wifiphisher/wifiphisher#894]
root@chrimoe:~# wifiphisher
Traceback (most recent call last):
  File "/usr/local/bin/wifiphisher", line 11, in <module>
    load_entry_point('wifiphisher==1.4', 'console_scripts', 'wifiphisher')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 587, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2800, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2431, in load
    return self.resolve()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2437, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.4-py2.7.egg/wifiphisher/pywifiphisher.py", line 27, in <module>
    import wifiphisher.common.accesspoint as accesspoint
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.4-py2.7.egg/wifiphisher/common/accesspoint.py", line 8, in <module>
    import roguehostapd.config.hostapdconfig as hostapdconfig
ImportError: No module named config.hostapdconfig

**Comment by chritav** [comment]
I cannot run wifiphisher...why?

**Comment by chritav** [comment]
How can I completely remove wifiphisher for a clean install?

**Comment by chritav** [comment]
I have solved. Thanks anyway
