### ISSUE TITLE
Installed without errors but can't run it

### ISSUE THREAD

**Issue by OnMoGa** [wifiphisher/wifiphisher#900]
I installed wifiphisher and roguehostapd without errors but get this when I try to run it. Instructions on how to fix this or just directions to where I can find some help would be greatly appreciated.

root@kali:/etc/wifiphisher# wifiphisher
Traceback (most recent call last):
  File "/usr/local/bin/wifiphisher", line 11, in <module>
    load_entry_point('wifiphisher==1.4', 'console_scripts', 'wifiphisher')()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 480, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2693, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2324, in load
    return self.resolve()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2330, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.4-py2.7.egg/wifiphisher/pywifiphisher.py", line 20, in <module>
    import wifiphisher.common.extensions as extensions
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.4-py2.7.egg/wifiphisher/common/extensions.py", line 11, in <module>
    import scapy.layers.dot11 as dot11
  File "/usr/local/lib/python2.7/dist-packages/scapy/layers/dot11.py", line 12, in <module>
    from scapy.packet import *
  File "/usr/local/lib/python2.7/dist-packages/scapy/packet.py", line 39
    class Packet(BasePacket, metaclass = Packet_metaclass):
                                       ^
SyntaxError: invalid syntax

**Comment by anakin1028** [comment]
Can you try `apt-get remove python-scapy` and then do `pip install scapy`. After that try to re run WiFiphisher see if the tool works.

**Comment by zyrgo** [comment]
i have reinstalled scapy but still shows the same

**Comment by JetseVerschuren** [comment]
Try removing `scapy` without reinstalling.

**Comment by rochdi3** [comment]
same error , even after reinstalling scapy
