### ISSUE TITLE
/host/run/dbus/system_bus_socket: No such file or directory

### ISSUE THREAD

**Issue by amarahjiwa** [wifiphisher/wifiphisher#901]
I'm currently running nethunter on my OP5T OOS Beta 5 

I went and try to run wifiphisher and I got this error 

```
*] Starting Wifiphisher 1.4GIT ( https://wifiphisher.org ) at 2018-04-07 18:34
Traceback (most recent call last):
  File "/usr/local/bin/wifiphisher", line 11, in <module>
    load_entry_point('wifiphisher==1.4', 'console_scripts', 'wifiphisher')()
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.4-py2.7.egg/wifiphisher/pywifiphisher.py", line 627, in run
    engine.start()
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.4-py2.7.egg/wifiphisher/pywifiphisher.py", line 310, in start
    self.network_manager.start()
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.4-py2.7.egg/wifiphisher/common/interfaces.py", line 711, in start
    interface_property_detector(adapter)
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.4-py2.7.egg/wifiphisher/common/interfaces.py", line 915, in interface_property_detector
    interface_name)
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.4-py2.7.egg/wifiphisher/common/interfaces.py", line 867, in is_managed_by_network_manager
    bus = dbus.SystemBus()
  File "/usr/lib/python2.7/dist-packages/dbus/_dbus.py", line 194, in __new__
    private=private)
  File "/usr/lib/python2.7/dist-packages/dbus/_dbus.py", line 100, in __new__
    bus = BusConnection.__new__(subclass, bus_type, mainloop=mainloop)
  File "/usr/lib/python2.7/dist-packages/dbus/bus.py", line 122, in __new__
    bus = cls._new_for_bus(address_or_type, mainloop=mainloop)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.FileNotFound: Failed to connect to socket /host/run/dbus/system_bus_socket: No such file or directory
```

And I got this error when I run this command
```
root@kali:~# /etc/init.d/dbus restart
[ ok ] Stopping system message bus: dbus.
[....] Starting system message bus: dbusdbus-daemon[16892]: Failed to start message bus: Failed to open "/run/dbus/pid": No such file or directory
```

**Comment by anakin1028** [comment]
@amarahjiwa can you try the following:
```
export DBUS_SYSTEM_BUS_ADDRESS=unix:path=/host/run/dbus/system_bus_socket
```
[ref](https://github.com/resin-io/resin-wifi-connect/issues/72)

**Comment by amarahjiwa** [comment]
@anakin1028 Ok. I tried to run it and I'm still got the that same error
....

> root@kali:~# export DBUS_SYSTEM_BUS_ADDRESS=unix:path=/host/run/dbus/system_bus_socket
> root@kali:~# sudo wifiphisher                                      [*] Starting Wifiphisher 1.4GIT ( https://wifiphisher.org ) at 2018-04-08 23:32
> Traceback (most recent call last):
>   File "/usr/local/bin/wifiphisher", line 11, in <module>
>     load_entry_point('wifiphisher==1.4', 'console_scripts', 'wifiphisher')()
>   File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.4-py2.7.egg/wifiphisher/pywifiphisher.py", line 627, in run
>     engine.start()
>   File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.4-py2.7.egg/wifiphisher/pywifiphisher.py", line 310, in start
>     self.network_manager.start()
>   File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.4-py2.7.egg/wifiphisher/common/interfaces.py", line 711, in start
>     interface_property_detector(adapter)
>   File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.4-py2.7.egg/wifiphisher/common/interfaces.py", line 915, in interface_property_detector
>     interface_name)
>   File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.4-py2.7.egg/wifiphisher/common/interfaces.py", line 867, in is_managed_by_network_manager
>     bus = dbus.SystemBus()
>   File "/usr/lib/python2.7/dist-packages/dbus/_dbus.py", line 194, in __new__
>     private=private)
>   File "/usr/lib/python2.7/dist-packages/dbus/_dbus.py", line 100, in __new__
>     bus = BusConnection.__new__(subclass, bus_type, mainloop=mainloop)
>   File "/usr/lib/python2.7/dist-packages/dbus/bus.py", line 122, in __new__
>     bus = cls._new_for_bus(address_or_type, mainloop=mainloop)
> dbus.exceptions.DBusException: org.freedesktop.DBus.Error.FileNotFound: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory

....

**Comment by amarahjiwa** [comment]
@anakin1028 nice, I think I found the solution. I try to add kali-linux-wireless metapackages and now after updating, the error not showing anymore instead i got this message.

```
[*] Starting Wifiphisher 1.4GIT ( https://wifiphisher.org ) at 2018-04-10 07:56
No handlers could be found for logger "wifiphisher.pywifiphisher"
[!] Failed to find an interface with monitor mode
[+] Show your support!
[+] Follow us: https://twitter.com/wifiphisher
[+] Like us: https://www.facebook.com/Wifiphisher
[+] Captured credentials:
[!] Closing
```

**Comment by amarahjiwa** [comment]
@anakin1028 I think I got some Kind of bad luck cuz after I plug-in my TL-WN722N that same error showed again

```
root@kali:/# wifiphisher
[*] Starting Wifiphisher 1.4GIT ( https://wifiphisher.org ) at 2018-04-10 09:32
Traceback (most recent call last):
  File "/usr/local/bin/wifiphisher", line 11, in <module>
    load_entry_point('wifiphisher==1.4', 'console_scripts', 'wifiphisher')()
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.4-py2.7.egg/wifiphisher/pywifiphisher.py", line 627, in run
    engine.start()
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.4-py2.7.egg/wifiphisher/pywifiphisher.py", line 310, in start
    self.network_manager.start()
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.4-py2.7.egg/wifiphisher/common/interfaces.py", line 711, in start
    interface_property_detector(adapter)
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.4-py2.7.egg/wifiphisher/common/interfaces.py", line 915, in interface_property_detector
    interface_name)
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.4-py2.7.egg/wifiphisher/common/interfaces.py", line 867, in is_managed_by_network_manager
    bus = dbus.SystemBus()
  File "/usr/lib/python2.7/dist-packages/dbus/_dbus.py", line 194, in __new__
    private=private)
  File "/usr/lib/python2.7/dist-packages/dbus/_dbus.py", line 100, in __new__
    bus = BusConnection.__new__(subclass, bus_type, mainloop=mainloop)
  File "/usr/lib/python2.7/dist-packages/dbus/bus.py", line 122, in __new__
    bus = cls._new_for_bus(address_or_type, mainloop=mainloop)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.FileNotFound: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory
```

**Comment by amarahjiwa** [comment]
I solved the problem by creating a folder named "dbus" inside /kali-armhf/run and then run 
/etc/ini.d/dbus start
If the dubs failed, just delete pid file inside dbus folder on /kali-armhf/run
