### ISSUE TITLE
failed to create fake AP

### ISSUE THREAD

**Issue by amarahjiwa** [wifiphisher/wifiphisher#910]
OP5T OOS Beta 6 with NH Kernel version Linux version 4.4.78-ElementalX-Nethunter-OP5-3.01 (root@simonpunk) (gcc version 4.9.x 20150123 (prerelease) (GCC) ) #2 SMP PREEMPT Sun Apr 1 15:10:47 CST 2018

Wifi dongle: TL-WN722N V1

When I try to chose phishing scenario I got this error

``sudo wifiphisher                                     
[*] Starting Wifiphisher 1.4GIT ( https://wifiphisher.org ) at 2018-04-19 10:12                                                       [+] Selecting wlan1 interface for the deauthentication attack
[+] Selecting wlan0 interface for creating the rogue Access Point  
[+] Sending SIGKILL to wpa_supplicant
[+] Sending SIGKILL to avahi-daemon                                
[+] Changing wlan0 MAC addr (BSSID) to 00:00:00:bf:9a:00
[+] Changing wlan1 MAC addr to 00:00:00:f1:b2:91                   
[*] Cleared leases, started DHCP, set up iptables
[+] Selecting Firmware Upgrade Page template                       
Traceback (most recent call last):
  File "/usr/local/bin/wifiphisher", line 11, in <module>              
load_entry_point('wifiphisher==1.4', 'console_scripts', 'wifiphisher')()                                                            
File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.4-py2.7.egg/wifiphisher/pywifiphisher.py", line 630, in run                  engine.start()
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.4-py2.7.egg/wifiphisher/pywifiphisher.py", line 528, in start
    self.network_manager.set_interface_mode(ap_iface, "managed")     File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.4-py2.7.egg/wifiphisher/common/interfaces.py", line 552, in set_interface_mode                                                                  pyw.modeset(card, mode)
  File "/usr/local/lib/python2.7/dist-packages/PyRIC-0.1.6.3-py2.7.egg/pyric/pyw.py", line 1323, in modeset
    if nlsock is None: return _nlstub_(modeset, card, mode, flags)
  File "/usr/local/lib/python2.7/dist-packages/PyRIC-0.1.6.3-py2.7.egg/pyric/pyw.py", line 2236, in _nlstub_
    return fct(*argv)
  File "/usr/local/lib/python2.7/dist-packages/PyRIC-0.1.6.3-py2.7.egg/pyric/pyw.py", line 1340, in modeset
    raise pyric.error(e.errno, e.strerror)
pyric.error: [Errno 19] No such device``

**Comment by sophron** [comment]
Hi @amarahjiwa,

Can you make sure that your card is properly connected while you run the tool?
