### ISSUE TITLE
Wifiphisher can't help me

### ISSUE THREAD

**Issue by Onisakura** [wifiphisher/wifiphisher#911]
root@onisakura:~# wifiphisher
[*] Starting Wifiphisher 1.4GIT ( https://wifiphisher.org ) at 2018-04-26 11:57
[+] Selecting wlan0 interface for the deauthentication attack
[+] Selecting wlan1 interface for creating the rogue Access Point
[+] Changing wlan1 MAC addr (BSSID) to 00:00:00:be:75:97
[+] Changing wlan0 MAC addr to 00:00:00:b6:ad:bc
[*] Cleared leases, started DHCP, set up iptables
Traceback (most recent call last):
  File "/usr/local/bin/wifiphisher", line 11, in <module>
    load_entry_point('wifiphisher==1.4', 'console_scripts', 'wifiphisher')()
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.4-py2.7.egg/wifiphisher/pywifiphisher.py", line 630, in run
    engine.start()
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.4-py2.7.egg/wifiphisher/pywifiphisher.py", line 442, in start
    self.network_manager.up_interface(mon_iface)
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.4-py2.7.egg/wifiphisher/common/interfaces.py", line 455, in up_interface
    pyw.up(card)
  File "/usr/local/lib/python2.7/dist-packages/PyRIC-0.1.6.3-py2.7.egg/pyric/pyw.py", line 572, in up
    if iosock is None: return _iostub_(up, card)
  File "/usr/local/lib/python2.7/dist-packages/PyRIC-0.1.6.3-py2.7.egg/pyric/pyw.py", line 2217, in _iostub_
    return fct(*argv)
  File "/usr/local/lib/python2.7/dist-packages/PyRIC-0.1.6.3-py2.7.egg/pyric/pyw.py", line 577, in up
    _flagsset_(card.dev, _setf_(flags, ifh.IFF_UP), iosock)
  File "/usr/local/lib/python2.7/dist-packages/PyRIC-0.1.6.3-py2.7.egg/pyric/pyw.py", line 1926, in _flagsset_
    raise pyric.error(e.errno, e.strerror)
pyric.error: [Errno 132] Operation not possible due to RF-kill

**Comment by sophron** [comment]
Have a look at this <a href="https://askubuntu.com/questions/62166/siocsifflags-operation-not-possible-due-to-rf-kill">link</a> to unblock your card.
