### ISSUE TITLE
The Provided Mac Adress is Invalid

### ISSUE THREAD

**Issue by mi11even** [wifiphisher/wifiphisher#913]
root@KaliWete:~/wifiphisher# wifiphisher
[*] Starting Wifiphisher 1.4GIT ( https://wifiphisher.org ) at 2018-05-01 15:14
[+] Selecting wlan1 interface for the deauthentication attack
[+] Selecting wlan0 interface for creating the rogue Access Point
[!] The provided MAC address ____________ is invalid
[+] Sending SIGKILL to wpa_supplicant
[+] Changing wlan0 MAC addr (BSSID) to 00:00:00:09:38:ab
[+] Changing wlan1 MAC addr to 00:00:00:77:d8:d2
[*] Cleared leases, started DHCP, set up iptables
Traceback (most recent call last):
  File "/usr/local/bin/wifiphisher", line 11, in <module>
    load_entry_point('wifiphisher==1.4', 'console_scripts', 'wifiphisher')()
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.4-py2.7.egg/wifiphisher/pywifiphisher.py", line 630, in run
    engine.start()
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.4-py2.7.egg/wifiphisher/pywifiphisher.py", line 442, in start
    self.network_manager.up_interface(mon_iface)
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.4-py2.7.egg/wifiphisher/common/interfaces.py", line 455, in up_interface
    pyw.up(card)
  File "/usr/local/lib/python2.7/dist-packages/PyRIC-0.1.6.3-py2.7.egg/pyric/pyw.py", line 572, in up
    if iosock is None: return _iostub_(up, card)
  File "/usr/local/lib/python2.7/dist-packages/PyRIC-0.1.6.3-py2.7.egg/pyric/pyw.py", line 2217, in _iostub_
    return fct(*argv)
  File "/usr/local/lib/python2.7/dist-packages/PyRIC-0.1.6.3-py2.7.egg/pyric/pyw.py", line 577, in up
    _flagsset_(card.dev, _setf_(flags, ifh.IFF_UP), iosock)
  File "/usr/local/lib/python2.7/dist-packages/PyRIC-0.1.6.3-py2.7.egg/pyric/pyw.py", line 1926, in _flagsset_
    raise pyric.error(e.errno, e.strerror)
pyric.error: [Errno 16] Device or resource busy

**Comment by sophron** [comment]
This typically means that your network card is in use. Follow <a href="https://tutorials.technology/solved_errors/11-How-to-solve-iwconfig-device-or-resource-busy.html">instructions found on the Internet</a> to free your card.

**Comment by sophron** [comment]
Having a look at this again, there are two things that we should do from our side:

1) The error message "The provided MAC address ____________ is invalid" should change to "The MAC address <mac addr> could not be set."

2) We should do a check in an earlier stage (before setting the MAC address) and see if the card behaves correctly.

**Comment by anakin1028** [comment]
@mi11even can you try with the option `-iNM` option? This option will not randomize the mac address. If this works, then we may implement what @sophron purposes :)

**Comment by mi11even** [comment]
what is -iNM option?i'm just a beginner here??????

**Comment by mi11even** [comment]
@anakin1028 what is -iNM option?i'm just a beginner here.......thanks for the replys sirs

**Comment by anakin1028** [comment]
`-iNM` means tool will not randomize the mac address of the adaptor

**Comment by sophron** [comment]
@kantorth It's a problem only if you need to remain super stealth. Wifiphisher will operate normally regardless that.

**Comment by ISBaloch** [comment]
Hello plz help me i am having error of mac adress is invalid 
help me out how to fix it
