### ISSUE TITLE
Template external css does not work

### ISSUE THREAD

**Issue by blackHatMonkey** [wifiphisher/wifiphisher#924]
@sophron  @anakin1028 When I was creating a new template I found this wired bug where external CSS won't load in target browser. Here is the [test file](https://github.com/wifiphisher/wifiphisher/files/2019651/test.tar.gz) which I used. On mobile device I have tried multiple browsers with the same result while on the desktop browser everything is fine. Is this a problem on my setup or is it a bug?

**Comment by blackHatMonkey** [comment]
Mange to track the bug down. It seems that all files are treated as `html` and that's why they don't properly work.
![html](https://user-images.githubusercontent.com/25112506/40578636-6d54e12c-60e5-11e8-8cfb-2e700af192a4.png)

**Comment by JetseVerschuren** [comment]
Can you post the response headers?

**Comment by blackHatMonkey** [comment]
@JetseVerschuren Here is the raw headers:

`Request Header`
```
Host: www.google.com
User-Agent: Mozilla/5.0 (Android 7.1.2; Mobile; rv:60.0) Gecko/60.0 Firefox/60.0
Accept: text/css,*/*;q=0.1
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate
Referer: http://www.google.com/
Cookie: 1P_JAR=2018-05-27-21; NID=131=n23GBvxm8Kxm9czteDxm814Fc5tWrbs3ZqeQRdOlsTNg4JnPoxR__9oZn2ODX5U9kwhNpZM5LFLkNXPHEmOROqgjwkK0eIGpFUrWs2nmZ4m1cihq-WQ_9UOmarPghFwD
Connection: keep-alive
If-None-Match: "1ae7f5fcc453bb80f75deedf48ffa8f0982073b9"
Cache-Control: max-age=0
```

`Response Header`
```
HTTP/1.1 304 Not Modified
Date: Tue, 29 May 2018 15:05:54 GMT
Etag: "1ae7f5fcc453bb80f75deedf48ffa8f0982073b9"
Server: TornadoServer/5.0.2
```

**Comment by blackHatMonkey** [comment]
So it seems that the server always responds with `text/html` as the `Content-Type`.

**Comment by greboreda** [comment]
Same exact problem here! All asset files are served with `Content-Type: text/html` header. Same behaviour on all files I've tried: js, css, svg. Server seems to be pretty chill about it.

```
2025-11-28 01:51:13,434 -                   tornado.access - INFO - 200 GET /js/page.js (10.0.0.84) 2.23ms
2025-11-28 01:51:13,434 -  wifiphisher.common.phishinghttp - INFO - GET request from 10.0.0.84 for http://ping.archlinux.org/js/page.js
```

Also tried to retrieve a woff2 file using curl (as the browser rejects content of those files) and I got a 500. 

```
2025-11-28 01:52:15,652 -              tornado.application - ERROR - Uncaught exception GET /assets/CustomSans-Regular.woff2 (10.0.0.84)
HTTPServerRequest(protocol='http', host='detectportal.firefox.com', method='GET', uri='/assets/CustomSans-Regular.woff2', version='HTTP/1.1', remote_ip='10.0.0.84')
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/tornado/web.py", line 1846, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "/usr/lib/python3/dist-packages/wifiphisher/common/phishinghttp.py", line 101, in get
    self.render(file_path, **template.get_context())
    ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/tornado/web.py", line 994, in render
    html = self.render_string(template_name, **kwargs)
  File "/usr/lib/python3/dist-packages/tornado/web.py", line 1140, in render_string
    t = loader.load(template_name)
  File "/usr/lib/python3/dist-packages/tornado/template.py", line 446, in load
    self.templates[name] = self._create_template(name)
                           ~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "/usr/lib/python3/dist-packages/tornado/template.py", line 477, in _create_template
    template = Template(f.read(), name=name, loader=self)
  File "/usr/lib/python3/dist-packages/tornado/template.py", line 317, in __init__
    reader = _TemplateReader(name, escape.native_str(template_string), whitespace)
                                   ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/tornado/escape.py", line 255, in to_unicode
    return value.decode("utf-8")
           ~~~~~~~~~~~~^^^^^^^^^
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xbc in position 10: invalid start byte
2025-11-28 01:52:15,656 -                   tornado.access - ERROR - 500 GET /assets/CustomSans-Regular.woff2 (10.0.0.84) 11.50ms

```
