### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by alimp5** [wifiphisher/wifiphisher#932]
### step1:
```root@kali: git clone https://github.com/wifiphisher/wifiphisher.git wifi-phisher```

### step2:
```root@kali: sudo python setup.py install```

### step3:
```root@kali: wifiphisher```
```
Traceback (most recent call last):
  File "/usr/local/bin/wifiphisher", line 11, in <module>
    load_entry_point('wifiphisher==1.4', 'console_scripts', 'wifiphisher')()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 476, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2700, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2318, in load
    return self.resolve()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2324, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.4-py2.7.egg/wifiphisher/pywifiphisher.py", line 23, in <module>
    import wifiphisher.common.phishinghttp as phishinghttp
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.4-py2.7.egg/wifiphisher/common/phishinghttp.py", line 5, in <module>
    import tornado.ioloop
  File "/usr/lib/python2.7/dist-packages/tornado/ioloop.py", line 51, in <module>
    from tornado.concurrent import Future, is_future, chain_future, future_set_exc_info, future_add_done_callback  # noqa: E501
  File "/usr/lib/python2.7/dist-packages/tornado/concurrent.py", line 47, in <module>
    import asyncio
  File "/usr/local/lib/python2.7/dist-packages/asyncio/__init__.py", line 9, in <module>
    from . import selectors
  File "/usr/local/lib/python2.7/dist-packages/asyncio/selectors.py", line 39
    "{!r}".format(fileobj)) from None
                               ^
SyntaxError: invalid syntax
```

```
root@kali: python -V
2.7.15rc1

root@kali: python3 -V
3.6.5rc1

root@kali: uname -a
Linux kali 4.15.0-kali2-amd64 #1 SMP Debian 4.15.11-1kali1 (2018-03-21) x86_64 GNU/Linux

root@kali: ruby -v
ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux-gnu]

root@kali: pip list | grep torn
tornado                      4.4.3

root@kali: pip list | grep wifi
NOTHING
```

**Comment by JetseVerschuren** [comment]
A quick google search turn up [this](https://github.com/python/asyncio/issues/386). It is a link to a issue on the asyncio repo. It turns out that if you import asyncio in python 2.7 things will break, and according to [this](http://www.tornadoweb.org/en/stable/asyncio.html) link tornado will autodetect and import asyncio. Try removing asyncio. `pip remove asyncio` shoud do the trick.

**Comment by alimp5** [comment]
@JetseVerschuren 

Thank you.
the root cause of problem were `asyncio` and `async'  python modules.
```
pip uninstall asyncio
pip3 uninstall asyncio
pip uninstall async
pip3 uninstall async
```

**Comment by alimp5** [comment]
Error:
wifiphisher 1.4 has requirement tornado==4.5.3, but you'll have tornado 4.4.3 which is incompatible.


root@kali: pip install wifiphisher --upgrade
```
Requirement already up-to-date: wifiphisher in /usr/local/lib/python2.7/dist-packages/wifiphisher-1.4-py2.7.egg (1.4)
Requirement not upgraded as not directly required: PyRIC in /usr/local/lib/python2.7/dist-packages/PyRIC-0.1.6.3-py2.7.egg (from wifiphisher) (0.1.6.3)
Requirement not upgraded as not directly required: tornado==4.5.3 in /usr/local/lib/python2.7/dist-packages (from wifiphisher) (4.5.3)
Requirement not upgraded as not directly required: pbkdf2 in /usr/local/lib/python2.7/dist-packages/pbkdf2-1.3-py2.7.egg (from wifiphisher) (1.3)
Requirement not upgraded as not directly required: roguehostapd in /usr/local/lib/python2.7/dist-packages/roguehostapd-1.2.3-py2.7-linux-x86_64.egg (from wifiphisher) (1.2.3)
Requirement not upgraded as not directly required: scapy in /usr/lib/python2.7/dist-packages (from wifiphisher) (2.4.0)
Requirement not upgraded as not directly required: backports-abc>=0.4 in /usr/lib/python2.7/dist-packages (from tornado==4.5.3->wifiphisher) (0.5)
Requirement not upgraded as not directly required: certifi in /usr/local/lib/python2.7/dist-packages (from tornado==4.5.3->wifiphisher) (2018.4.16)
Requirement not upgraded as not directly required: singledispatch in /usr/lib/python2.7/dist-packages (from tornado==4.5.3->wifiphisher) (3.4.0.3)
Requirement not upgraded as not directly required: six in /usr/local/lib/python2.7/dist-packages (from singledispatch->tornado==4.5.3->wifiphisher) (1.10.0)
mitmproxy 0.18.3 has requirement tornado<4.5,>=4.3, but you'll have tornado 4.5.3 which is incompatible.
```

root@kali: pip install tornado==4.5.3
```
Requirement already satisfied: tornado==4.5.3 in /usr/local/lib/python2.7/dist-packages (4.5.3)
Requirement already satisfied: backports-abc>=0.4 in /usr/lib/python2.7/dist-packages (from tornado==4.5.3) (0.5)
Requirement already satisfied: certifi in /usr/local/lib/python2.7/dist-packages (from tornado==4.5.3) (2018.4.16)
Requirement already satisfied: singledispatch in /usr/lib/python2.7/dist-packages (from tornado==4.5.3) (3.4.0.3)
Requirement already satisfied: six in /usr/local/lib/python2.7/dist-packages (from singledispatch->tornado==4.5.3) (1.10.0)
mitmproxy 0.18.3 has requirement tornado<4.5,>=4.3, but you'll have tornado 4.5.3 which is incompatible.
```

root@kali: pip install mitmproxy==0.18.3
```
Requirement already satisfied: mitmproxy==0.18.3 in /usr/local/lib/python2.7/dist-packages (0.18.3)
Requirement already satisfied: configargparse<0.12,>=0.10 in /usr/lib/python2.7/dist-packages (from mitmproxy==0.18.3) (0.11.0)
Requirement already satisfied: jsbeautifier<1.7,>=1.6.3 in /usr/local/lib/python2.7/dist-packages (from mitmproxy==0.18.3) (1.6.14)
Requirement already satisfied: watchdog<0.9,>=0.8.3 in /usr/lib/python2.7/dist-packages (from mitmproxy==0.18.3) (0.8.3)
Requirement already satisfied: passlib<1.7,>=1.6.5 in /usr/local/lib/python2.7/dist-packages (from mitmproxy==0.18.3) (1.6.5)
Requirement already satisfied: pyperclip<1.6,>=1.5.22 in /usr/local/lib/python2.7/dist-packages (from mitmproxy==0.18.3) (1.5.32)
Collecting tornado<4.5,>=4.3 (from mitmproxy==0.18.3)
Requirement already satisfied: pyOpenSSL<17.0,>=16.0 in /usr/local/lib/python2.7/dist-packages (from mitmproxy==0.18.3) (16.2.0)
Requirement already satisfied: backports.ssl-match-hostname<3.6,>=3.5.0.1 in /usr/lib/python2.7/dist-packages (from mitmproxy==0.18.3) (3.5.0.1)
Requirement already satisfied: brotlipy<0.7,>=0.5.1 in /usr/local/lib/python2.7/dist-packages (from mitmproxy==0.18.3) (0.6.0)
Requirement already satisfied: Flask<0.12,>=0.10.1 in /usr/local/lib/python2.7/dist-packages (from mitmproxy==0.18.3) (0.11.1)
Requirement already satisfied: blinker<1.5,>=1.4 in /usr/lib/python2.7/dist-packages (from mitmproxy==0.18.3) (1.4)
Requirement already satisfied: lxml<=3.6.0,>=3.5.0 in /usr/local/lib/python2.7/dist-packages (from mitmproxy==0.18.3) (3.6.0)
Requirement already satisfied: hyperframe<5,>=4.0.1 in /usr/local/lib/python2.7/dist-packages (from mitmproxy==0.18.3) (4.0.2)
Requirement already satisfied: pyparsing<2.2,>=2.1.3 in /usr/local/lib/python2.7/dist-packages (from mitmproxy==0.18.3) (2.1.10)
Requirement already satisfied: construct<2.6,>=2.5.2 in /usr/local/lib/python2.7/dist-packages (from mitmproxy==0.18.3) (2.5.3)
Requirement already satisfied: cryptography<1.6,>=1.3 in /usr/local/lib/python2.7/dist-packages (from mitmproxy==0.18.3) (1.5.3)
Requirement already satisfied: six<1.11,>=1.10 in /usr/local/lib/python2.7/dist-packages (from mitmproxy==0.18.3) (1.10.0)
Requirement already satisfied: click<7.0,>=6.2 in /usr/lib/python2.7/dist-packages (from mitmproxy==0.18.3) (6.7)
Requirement already satisfied: requests<2.12,>=2.9.1 in /usr/local/lib/python2.7/dist-packages (from mitmproxy==0.18.3) (2.11.1)
Requirement already satisfied: html2text<=2016.9.19,>=2016.1.8 in /usr/local/lib/python2.7/dist-packages (from mitmproxy==0.18.3) (2016.9.19)
Requirement already satisfied: urwid<1.4,>=1.3.1 in /usr/local/lib/python2.7/dist-packages (from mitmproxy==0.18.3) (1.3.1)
Requirement already satisfied: enum34<2,>=1.0.4; python_version == "2.7" in /usr/lib/python2.7/dist-packages (from mitmproxy==0.18.3) (1.1.6)
Requirement already satisfied: certifi>=2015.11.20.1 in /usr/local/lib/python2.7/dist-packages (from mitmproxy==0.18.3) (2018.4.16)
Requirement already satisfied: typing==3.5.2.2; python_version == "2.7" in /usr/local/lib/python2.7/dist-packages (from mitmproxy==0.18.3) (3.5.2.2)
Requirement already satisfied: cssutils<1.1,>=1.0.1 in /usr/lib/python2.7/dist-packages (from mitmproxy==0.18.3) (1.0.2)
Requirement already satisfied: Pillow<3.5,>=3.2 in /usr/local/lib/python2.7/dist-packages (from mitmproxy==0.18.3) (3.4.2)
Requirement already satisfied: ipaddress<1.1,>=1.0.15; python_version == "2.7" in /usr/local/lib/python2.7/dist-packages (from mitmproxy==0.18.3) (1.0.22)
Requirement already satisfied: pyasn1<0.2,>=0.1.9 in /usr/local/lib/python2.7/dist-packages (from mitmproxy==0.18.3) (0.1.9)
Requirement already satisfied: h2<2.5,>=2.4.1 in /usr/local/lib/python2.7/dist-packages (from mitmproxy==0.18.3) (2.4.4)
Requirement already satisfied: editorconfig>=0.12.0 in /usr/local/lib/python2.7/dist-packages (from jsbeautifier<1.7,>=1.6.3->mitmproxy==0.18.3) (0.12.2)
Requirement already satisfied: PyYAML>=3.10 in /usr/lib/python2.7/dist-packages (from watchdog<0.9,>=0.8.3->mitmproxy==0.18.3) (3.12)
Requirement already satisfied: argh>=0.24.1 in /usr/lib/python2.7/dist-packages (from watchdog<0.9,>=0.8.3->mitmproxy==0.18.3) (0.26.2)
Requirement already satisfied: pathtools>=0.1.1 in /usr/lib/python2.7/dist-packages (from watchdog<0.9,>=0.8.3->mitmproxy==0.18.3) (0.1.2)
Requirement already satisfied: backports-abc>=0.4 in /usr/lib/python2.7/dist-packages (from tornado<4.5,>=4.3->mitmproxy==0.18.3) (0.5)
Requirement already satisfied: singledispatch in /usr/lib/python2.7/dist-packages (from tornado<4.5,>=4.3->mitmproxy==0.18.3) (3.4.0.3)
Requirement already satisfied: cffi>=1.0.0 in /usr/local/lib/python2.7/dist-packages (from brotlipy<0.7,>=0.5.1->mitmproxy==0.18.3) (1.11.5)
Requirement already satisfied: Jinja2>=2.4 in /usr/lib/python2.7/dist-packages (from Flask<0.12,>=0.10.1->mitmproxy==0.18.3) (2.10)
Requirement already satisfied: Werkzeug>=0.7 in /usr/lib/python2.7/dist-packages (from Flask<0.12,>=0.10.1->mitmproxy==0.18.3) (0.14.1)
Requirement already satisfied: itsdangerous>=0.21 in /usr/lib/python2.7/dist-packages (from Flask<0.12,>=0.10.1->mitmproxy==0.18.3) (0.24)
Requirement already satisfied: setuptools>=11.3 in /usr/local/lib/python2.7/dist-packages (from cryptography<1.6,>=1.3->mitmproxy==0.18.3) (39.2.0)
Requirement already satisfied: idna>=2.0 in /usr/lib/python2.7/dist-packages (from cryptography<1.6,>=1.3->mitmproxy==0.18.3) (2.6)
Requirement already satisfied: hpack<3,>=2.2 in /usr/local/lib/python2.7/dist-packages (from h2<2.5,>=2.4.1->mitmproxy==0.18.3) (2.3.0)
Requirement already satisfied: pycparser in /usr/local/lib/python2.7/dist-packages (from cffi>=1.0.0->brotlipy<0.7,>=0.5.1->mitmproxy==0.18.3) (2.18)
wifiphisher 1.4 has requirement tornado==4.5.3, but you'll have tornado 4.4.3 which is incompatible.
Installing collected packages: tornado
  Found existing installation: tornado 4.5.3
    Uninstalling tornado-4.5.3:
      Successfully uninstalled tornado-4.5.3
Successfully installed tornado-4.4.3
```

**Comment by sophron** [comment]
Hi @alimp5,

This doesn't seem to be an error with Wifiphisher. Do you have any issues with tornado-4.4.3 when running the script?

**Comment by blackHatMonkey** [comment]
@sophron @alimp5 I believe the problem is multiple versions of the same package. `python` does not allow for that which creates this problem.

**Comment by alimp5** [comment]
@blackHatMonkey @sophron 
Dears,
WiFiPhisher is working fine.
Thank you.

**Comment by nattyo** [comment]
I tired this and it worked for me like a flash, just update it with this command: python wsf-update.py
