### ISSUE TITLE
Exception: Illegal syntax for IP address

### ISSUE THREAD

**Issue by DashHax** [wifiphisher/wifiphisher#938]
Hello there. I've installed wifiphisher using the apt-get command, and I have successfully installed it. But when I try to run it by issuing the "wifiphisher" command on the console, I receive this error :

```
Traceback (most recent call last):

  File "/usr/local/bin/wifiphisher", line 11, in <module>
    load_entry_point('wifiphisher==1.4', 'console_scripts', 'wifiphisher')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 480, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2693, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2324, in load
    return self.resolve()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2330, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.4-py2.7.egg/wifiphisher/pywifiphisher.py", line 20, in <module>
    import wifiphisher.common.extensions as extensions
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.4-py2.7.egg/wifiphisher/common/extensions.py", line 11, in <module>
    import scapy.layers.dot11 as dot11
  File "/usr/lib/python2.7/dist-packages/scapy/layers/dot11.py", line 20, in <module>
    from scapy.layers.inet import IP, TCP
  File "/usr/lib/python2.7/dist-packages/scapy/layers/inet.py", line 1676, in <module>
    import scapy.layers.inet6
  File "/usr/lib/python2.7/dist-packages/scapy/layers/inet6.py", line 56, in <module>
    import scapy.route6
  File "/usr/lib/python2.7/dist-packages/scapy/route6.py", line 273, in <module>
    conf.route6 = Route6()
  File "/usr/lib/python2.7/dist-packages/scapy/route6.py", line 31, in __init__
    self.resync()
  File "/usr/lib/python2.7/dist-packages/scapy/route6.py", line 44, in resync
    self.routes = read_routes6()
  File "/usr/lib/python2.7/dist-packages/scapy/arch/linux.py", line 283, in read_routes6
    cset = scapy.utils6.construct_source_candidate_set(d, dp, devaddrs, LOOPBACK_NAME)
  File "/usr/lib/python2.7/dist-packages/scapy/utils6.py", line 50, in construct_source_candidate_set
    if in6_isgladdr(addr) or in6_isuladdr(addr):
  File "/usr/lib/python2.7/dist-packages/scapy/utils6.py", line 708, in in6_isgladdr
    return in6_isincluded(str, '2000::', 3)
  File "/usr/lib/python2.7/dist-packages/scapy/utils6.py", line 651, in in6_isincluded
    temp = inet_pton(socket.AF_INET6, addr)
  File "/usr/lib/python2.7/dist-packages/scapy/pton_ntop.py", line 40, in inet_pton
    raise Exception("Illegal syntax for IP address")
Exception: Illegal syntax for IP address
```
How do I fix this? Sorry, this is my first time running this. It's for my course assignment.

**Comment by blackHatMonkey** [comment]
@DashHax Thanks for opening a bug report. I have not seen this bug before but maybe @sophron or @anakin1028 have seen it. In the mean time can you uninstall this version and install from `github`?

**Comment by sophron** [comment]
Hi @DashHax,

Did you install the Wifiphisher package on Kali Linux?

You can try our latest development version for now (by using git clone) and see if the problem exists there too.
