### ISSUE TITLE
Different locales and nmcli

### ISSUE THREAD

**Issue by Dissfall** [wifiphisher/wifiphisher#944]
_commit 1a61970e902e3fdb93cec99e55a8b40b0be7fe52_
_elementary OS 0.4.1 Loki (Ubuntu 16.04.3 LTS)_

After running the command `sudo wifiphisher -aI wlp1s0 -eI wlx20e317038ec9 -iI enp0s20u1` i've got:
```
[*] Starting Wifiphisher 1.4GIT ( https://wifiphisher.org ) at 2018-06-10 11:47
ERROR:root:The following error has occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.4-py2.7.egg/wifiphisher/pywifiphisher.py", line 338, in start
    args.extensionsinterface, "monitor"):
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.4-py2.7.egg/wifiphisher/common/interfaces.py", line 426, in is_interface_valid
    raise InterfaceManagedByNetworkManagerError(interface_name)
InterfaceManagedByNetworkManagerError: Interface "wlx20e317038ec9" is controlled by NetworkManager.You need to manually set the devices that should be ignored by NetworkManager using the keyfile plugin (unmanaged-directive). For example, '[keyfile] unmanaged-devices=interface-name:"wlx20e317038ec9"' needs to be added in your NetworkManager configuration file.
[!] Interface "wlx20e317038ec9" is controlled by NetworkManager.You need to manually set the devices that should be ignored by NetworkManager using the keyfile plugin (unmanaged-directive). For example, '[keyfile] unmanaged-devices=interface-name:"wlx20e317038ec9"' needs to be added in your NetworkManager configuration file.
...
```
The program detects that the device `wlx20e317038ec9` is controled by the NetworkManager. I already forced it to ignore and restarted the service, but still get this error...

My network interfaces:
```
docker0   no wireless extensions.

wlp1s0    IEEE 802.11  ESSID:"********"  
          Mode:Managed  Frequency:2.447 GHz  Access Point: 50:0F:F5:59:BB:B0   
          Bit Rate=72.2 Mb/s   Tx-Power=20 dBm   
          Retry short limit:7   RTS thr=2347 B   Fragment thr:off
          Power Management:on
          Link Quality=70/70  Signal level=-34 dBm  
          Rx invalid nwid:0  Rx invalid crypt:0  Rx invalid frag:0
          Tx excessive retries:0  Invalid misc:24   Missed beacon:0

lo        no wireless extensions.

enp0s20u1  no wireless extensions.

wlx20e317038ec9  IEEE 802.11  ESSID:off/any  
          Mode:Managed  Access Point: Not-Associated   Tx-Power=0 dBm   
          Retry short limit:7   RTS thr:off   Fragment thr:off
          Power Management:on
```
wlx20e317038ec9 additional info:
```
wlx20e317038ec9 Link encap:Ethernet  HWaddr 20:e3:17:03:8e:c9  
          BROADCAST MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)
```
My /etc/NetworkManager/NetworkManager.conf file:
```
[main]
plugins = ifupdown,keyfile,ofono
dns = dnsmasq

[ifupdown]
managed = false

[keyfile]
unmanaged-devices=mac:20:e3:17:03:8e:c9
```

**Comment by blackHatMonkey** [comment]
@Dissfall Can you please post the output of `nmcli dev`?

**Comment by Dissfall** [comment]
@blackHatMonkey of course
Original:
![2018-06-10 15-50-16](https://user-images.githubusercontent.com/28986337/41201745-368aea64-6cc6-11e8-9121-021a2de722e4.png)
Approximate translation:
```
DEVICE           TYPE      STATE         CONNECTION         
docker0          bridge    connected     docker0            
enp0s20u2        ethernet  connected     Wired connection 1 
wlp1s0           wifi      connected     .::..::.           
lo               loopback  not configured  --                 
wlx20e317038ec9  wifi      not configured  --     
```

**Comment by blackHatMonkey** [comment]
@Dissfall This is weird. Can you manually kill `network manager` and see what happens?

**Comment by Dissfall** [comment]
@blackHatMonkey np

`# service NetworkManager stop`
`# wifiphisher -aI wlp1s0 -eI wlx20e317038ec9 -iI enp0s20u1`
```
[*] Starting Wifiphisher 1.4GIT ( https://wifiphisher.org ) at 2018-06-10 16:07
Error: NetworkManager is not running.
Error: NetworkManager is not running.
[+] Selecting wlx20e317038ec9 interface for the deauthentication attack
[+] Selecting wlp1s0 interface for creating the rogue Access Point
[+] Changing wlp1s0 MAC addr (BSSID) to 00:00:00:e8:4e:90
[+] Changing wlx20e317038ec9 MAC addr to 00:00:00:92:fd:16
[*] Cleared leases, started DHCP, set up iptables

```
The program is started, but a couple of errors occur `Error: NetworkManager is not running.`. I think this is because NetWorkManager is necessary for `enp0s20u1`.

I try without `enp0s20u1`... Same result(

**Comment by Dissfall** [comment]
@blackHatMonkey that is, all the functionality will work with the disabled NetworkManager?
Maybe I can modify this code to correctly identify the devices controlled by NetworkManager?

**Comment by Dissfall** [comment]
@blackHatMonkey I just realized that the problem is that the result of `ncml dev` on Russian language in my system))))
