### ISSUE TITLE
error launching wifiphisher

### ISSUE THREAD

**Issue by Denzel-Washington** [wifiphisher/wifiphisher#955]
**Version**: Use `git show | grep commit` command and paste here the output.

commit 7c6c5f118aa4865e3eddd150f7dd294cdf8821c7

**Description**: Give a more analytical description here. The output of the `iw list` and `iwconfig` commands may be helpful.

rev_rmnet1  no wireless extensions.

rmnet6    no wireless extensions.

rev_rmnet5  no wireless extensions.

rmnet1    no wireless extensions.

lo        no wireless extensions.

rev_rmnet0  no wireless extensions.

rmnet5    no wireless extensions.

rev_rmnet4  no wireless extensions.

wlan1     IEEE 802.11bgn  ESSID:off/any  
          Mode:Managed  Access Point: Not-Associated   Tx-Power=0 dBm   
          Retry  long limit:7   RTS thr:off   Fragment thr:off
          Encryption key:off
          Power Management:off
          
rmnet0    no wireless extensions.

rev_rmnet8  no wireless extensions.

rmnet4    no wireless extensions.

sit0      no wireless extensions.

rev_rmnet3  no wireless extensions.

wlan0     IEEE 802.11  ESSID:"ICU"  
          Mode:Master  Frequency:2.422 GHz  Access Point: D0:17:C2:34:13:10   
          Bit Rate=72 Mb/s   Tx-Power:32 dBm   
          Retry min limit:7   RTS thr:off   Fragment thr:off
          Encryption key:off
          Power Managementmode:All packets received
          
rev_rmnet7  no wireless extensions.

rmnet3    no wireless extensions.

rev_rmnet2  no wireless extensions.

rmnet7    no wireless extensions.

rev_rmnet6  no wireless extensions.

rmnet2    no wireless extensions.

p2p0      IEEE 802.11abgn  ESSID:off/any  
          Mode:Managed  Access Point: Not-Associated   Tx-Power=1496 dBm   
          Retry  long limit:7   RTS thr:off   Fragment thr:off
          Encryption key:off
          Power Management:on

**Script output**: Paste the output of the tool, including any stack traces.

[*] Starting Wifiphisher 1.4GIT ( https://wifiphisher.org ) at 2018-06-22 05:06
Traceback (most recent call last):
  File "/usr/local/bin/wifiphisher", line 9, in <module>
    load_entry_point('wifiphisher==1.4', 'console_scripts', 'wifiphisher')()
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.4-py2.7.egg/wifiphisher/pywifiphisher.py", line 630, in run
    engine.start()
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.4-py2.7.egg/wifiphisher/pywifiphisher.py", line 306, in start
    self.opmode.initialize(args)
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.4-py2.7.egg/wifiphisher/common/opmode.py", line 51, in initialize
    interfaces.is_add_vif_required(args)
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.4-py2.7.egg/wifiphisher/common/interfaces.py", line 804, in is_add_vif_required
    card = pyw.getcard(vif)
  File "/usr/local/lib/python2.7/dist-packages/PyRIC-0.1.6.3-py2.7.egg/pyric/pyw.py", line 269, in getcard
    if nlsock is None: return _nlstub_(getcard, dev)
  File "/usr/local/lib/python2.7/dist-packages/PyRIC-0.1.6.3-py2.7.egg/pyric/pyw.py", line 2236, in _nlstub_
    return fct(*argv)
  File "/usr/local/lib/python2.7/dist-packages/PyRIC-0.1.6.3-py2.7.egg/pyric/pyw.py", line 270, in getcard
    return devinfo(dev, nlsock)['card']
  File "/usr/local/lib/python2.7/dist-packages/PyRIC-0.1.6.3-py2.7.egg/pyric/pyw.py", line 1057, in devinfo
    'mac': _hex2mac_(nl.nla_find(rmsg, nl80211h.NL80211_ATTR_MAC)),
  File "/usr/local/lib/python2.7/dist-packages/PyRIC-0.1.6.3-py2.7.egg/pyric/pyw.py", line 1821, in _hex2mac_
    return ":".join(['{0:02x}'.format(c) for c in v])
TypeError: 'NoneType' object is not iterable

**Comment by anakin1028** [comment]
Can you try with `-iNM` to see if tool works for you?

**Comment by Denzel-Washington** [comment]
hi, i'm getting the same error.

**Comment by anakin1028** [comment]
Hi, sorry for the late reply. Do you use V2 or V3 version of TL722N? If yes, wifiphisher may not have good compatibility of that adaptor.

**Comment by Denzel-Washington** [comment]
hi i am using Ver 1*

**Comment by jepunband** [comment]
help ?

[*] Starting Wifiphisher 1.4GIT ( https://wifiphisher.org ) at 2019-03-19 06:54
[+] Timezone detected. Setting channel range to 1-13
Traceback (most recent call last):
  File "/usr/local/bin/wifiphisher", line 11, in <module>
    load_entry_point('wifiphisher==1.4', 'console_scripts', 'wifiphisher')()
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.4-py2.7.egg/wifiphisher/pywifiphisher.py", line 693, in run
    engine.start()
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.4-py2.7.egg/wifiphisher/pywifiphisher.py", line 390, in start
    self.opmode.initialize(args)
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.4-py2.7.egg/wifiphisher/common/opmode.py", line 53, in initialize
    interfaces.is_add_vif_required(args)
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.4-py2.7.egg/wifiphisher/common/interfaces.py", line 798, in is_add_vif_required
    card = pyw.getcard(vif)
  File "/usr/local/lib/python2.7/dist-packages/PyRIC-0.1.6.3-py2.7.egg/pyric/pyw.py", line 269, in getcard
    if nlsock is None: return _nlstub_(getcard, dev)
  File "/usr/local/lib/python2.7/dist-packages/PyRIC-0.1.6.3-py2.7.egg/pyric/pyw.py", line 2236, in _nlstub_
    return fct(*argv)
  File "/usr/local/lib/python2.7/dist-packages/PyRIC-0.1.6.3-py2.7.egg/pyric/pyw.py", line 270, in getcard
    return devinfo(dev, nlsock)['card']
  File "/usr/local/lib/python2.7/dist-packages/PyRIC-0.1.6.3-py2.7.egg/pyric/pyw.py", line 1057, in devinfo
    'mac': _hex2mac_(nl.nla_find(rmsg, nl80211h.NL80211_ATTR_MAC)),
  File "/usr/local/lib/python2.7/dist-packages/PyRIC-0.1.6.3-py2.7.egg/pyric/pyw.py", line 1821, in _hex2mac_
    return ":".join(['{0:02x}'.format(c) for c in v])
TypeError: 'NoneType' object is not iterable
