### ISSUE TITLE
Unable to scan for APs

### ISSUE THREAD

**Issue by MinePro120** [wifiphisher/wifiphisher#962]
Hello and sorry if this is a duplicate, I just couldn't find any clear solution for my issue. When I run the wifiphisher, all network connections and the network manager are terminated. So it is unable to scan for access points and so on. I tried to restart the network services with no luck. Could you please help?

**Comment by sophron** [comment]
Wifiphisher will kill network manager and all active connections by default but that doesn't forbid ESSID scanning. 

When you run the tool, give it a few seconds and if everything works properly, you should see a list of all the nearby networks.

**Comment by MinePro120** [comment]
Nothing shows up. I left it for 15' and it is still unable to find the wifi networks around it.

**Comment by blackHatMonkey** [comment]
This is a `pyric` error.

@MinePro120 Does the error happen right after you start or later?

**Comment by MinePro120** [comment]
It happens later.

**Comment by MinePro120** [comment]
Will anyone help?

**Comment by MinePro120** [comment]
I looked at the closed issue #329 that includes the same pyric error (error 22), but as stated, this bug has been patched. Requesting for help.😥

**Comment by blackHatMonkey** [comment]
@MinePro120 This is a bug in another package `PYRIC` that `Wifiphisher` uses. Unfortunately that project is currently not maintained and we are in the process of adopting it. It will take some time before we can fix this :crossed_fingers: .

**Comment by MinePro120** [comment]
Ok, thanks for your help.

**Comment by jepunband** [comment]
hi any fix for this issue?

[*] Starting Wifiphisher 1.4GIT ( https://wifiphisher.org ) at 2019-03-19 06:54
[+] Timezone detected. Setting channel range to 1-13
Traceback (most recent call last):
  File "/usr/local/bin/wifiphisher", line 11, in <module>
    load_entry_point('wifiphisher==1.4', 'console_scripts', 'wifiphisher')()
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.4-py2.7.egg/wifiphisher/pywifiphisher.py", line 693, in run
    engine.start()
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.4-py2.7.egg/wifiphisher/pywifiphisher.py", line 390, in start
    self.opmode.initialize(args)
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.4-py2.7.egg/wifiphisher/common/opmode.py", line 53, in initialize
    interfaces.is_add_vif_required(args)
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.4-py2.7.egg/wifiphisher/common/interfaces.py", line 798, in is_add_vif_required
    card = pyw.getcard(vif)
  File "/usr/local/lib/python2.7/dist-packages/PyRIC-0.1.6.3-py2.7.egg/pyric/pyw.py", line 269, in getcard
    if nlsock is None: return _nlstub_(getcard, dev)
  File "/usr/local/lib/python2.7/dist-packages/PyRIC-0.1.6.3-py2.7.egg/pyric/pyw.py", line 2236, in _nlstub_
    return fct(*argv)
  File "/usr/local/lib/python2.7/dist-packages/PyRIC-0.1.6.3-py2.7.egg/pyric/pyw.py", line 270, in getcard
    return devinfo(dev, nlsock)['card']
  File "/usr/local/lib/python2.7/dist-packages/PyRIC-0.1.6.3-py2.7.egg/pyric/pyw.py", line 1057, in devinfo
    'mac': _hex2mac_(nl.nla_find(rmsg, nl80211h.NL80211_ATTR_MAC)),
  File "/usr/local/lib/python2.7/dist-packages/PyRIC-0.1.6.3-py2.7.egg/pyric/pyw.py", line 1821, in _hex2mac_
    return ":".join(['{0:02x}'.format(c) for c in v])
TypeError: 'NoneType' object is not iterable

**Comment by jepunband** [comment]
hi any fix for this issue?

[*] Starting Wifiphisher 1.4GIT ( https://wifiphisher.org ) at 2019-03-19 06:54
[+] Timezone detected. Setting channel range to 1-13
Traceback (most recent call last):
  File "/usr/local/bin/wifiphisher", line 11, in <module>
    load_entry_point('wifiphisher==1.4', 'console_scripts', 'wifiphisher')()
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.4-py2.7.egg/wifiphisher/pywifiphisher.py", line 693, in run
    engine.start()
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.4-py2.7.egg/wifiphisher/pywifiphisher.py", line 390, in start
    self.opmode.initialize(args)
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.4-py2.7.egg/wifiphisher/common/opmode.py", line 53, in initialize
    interfaces.is_add_vif_required(args)
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.4-py2.7.egg/wifiphisher/common/interfaces.py", line 798, in is_add_vif_required
    card = pyw.getcard(vif)
  File "/usr/local/lib/python2.7/dist-packages/PyRIC-0.1.6.3-py2.7.egg/pyric/pyw.py", line 269, in getcard
    if nlsock is None: return _nlstub_(getcard, dev)
  File "/usr/local/lib/python2.7/dist-packages/PyRIC-0.1.6.3-py2.7.egg/pyric/pyw.py", line 2236, in _nlstub_
    return fct(*argv)
  File "/usr/local/lib/python2.7/dist-packages/PyRIC-0.1.6.3-py2.7.egg/pyric/pyw.py", line 270, in getcard
    return devinfo(dev, nlsock)['card']
  File "/usr/local/lib/python2.7/dist-packages/PyRIC-0.1.6.3-py2.7.egg/pyric/pyw.py", line 1057, in devinfo
    'mac': _hex2mac_(nl.nla_find(rmsg, nl80211h.NL80211_ATTR_MAC)),
  File "/usr/local/lib/python2.7/dist-packages/PyRIC-0.1.6.3-py2.7.egg/pyric/pyw.py", line 1821, in _hex2mac_
    return ":".join(['{0:02x}'.format(c) for c in v])
TypeError: 'NoneType' object is not iterable
