### ISSUE TITLE
The provided MAC address  is invalid.i am using Alfa Usb adapter AWUS036NH 

### ISSUE THREAD

**Issue by CEHFIDA** [wifiphisher/wifiphisher#973]
Traceback (most recent call last):
  File "/usr/local/bin/wifiphisher", line 11, in <module>
    load_entry_point('wifiphisher==1.4', 'console_scripts', 'wifiphisher')()
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.4-py2.7.egg/wifiphisher/pywifiphisher.py", line 638, in run
    engine.start()
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.4-py2.7.egg/wifiphisher/pywifiphisher.py", line 560, in start
    self.stop()
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.4-py2.7.egg/wifiphisher/pywifiphisher.py", line 270, in stop
    self.network_manager.on_exit()
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.4-py2.7.egg/wifiphisher/common/interfaces.py", line 739, in on_exit
    self.set_interface_mac(interface, mac_address)
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.4-py2.7.egg/wifiphisher/common/interfaces.py", line 500, in set_interface_mac
    raise InvalidMacAddressError(mac_address)
wifiphisher.common.interfaces.InvalidMacAddressError: The provided MAC address 00:c0:ca:59:bd:bc is invalid

**Comment by anakin1028** [comment]
Can you proceed the tool with `-iNM` option?

**Comment by techetga** [comment]
I am getting the same error on an rt3070 based interface. Using wifiphisher -fH worked for me.

**Comment by sophron** [comment]
From what I see, this error is happening upon the exit of Wifiphisher. The program should function properly until then.

I also suppose that you are all running the latest version on Github (e.g. you used `git pull`).

**Comment by joj97** [comment]
When I tried wifiphisher -iNM it says roguehostapd is not installed. When I tried to install it says roguehostapd already exist. Please help me

**Comment by joj97** [comment]
Can I know how to change to release 1.3? Sorry I am still a beginner in kali linux

**Comment by techetga** [comment]
What wifi adapter are you using? Only some support AP and deauth at the same time. You can download 1.3 on https://github.com/wifiphisher/wifiphisher/releases

**Comment by joj97** [comment]
I am using blueway wifi adapter that capable of packet injection and supports monitor mode. It has ralink 3070 chipset

**Comment by techetga** [comment]
It should work on the rt3070. It works on mine.

**Comment by joj97** [comment]
I tried wifiphisher version 1.3 just now. It created the fake Ap but I cannot to the fake Ap. Is it because I am using one adapter?

**Comment by sophron** [comment]
@CEHFIDA, @techetga I pushed a commit that fixes this. Can you update to the latest revision and let us know if it works properly for you?
