### ISSUE TITLE
wifiphisher not running

### ISSUE THREAD

**Issue by joj97** [wifiphisher/wifiphisher#979]
After clicking firmware upgrade I'm getting this error

Traceback (most recent call last):
  File "/usr/local/bin/wifiphisher", line 11, in <module>
    load_entry_point('wifiphisher==1.4', 'console_scripts', 'wifiphisher')()
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.4-py2.7.egg/wifiphisher/pywifiphisher.py", line 638, in run
    engine.start()
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.4-py2.7.egg/wifiphisher/pywifiphisher.py", line 560, in start
    self.stop()
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.4-py2.7.egg/wifiphisher/pywifiphisher.py", line 270, in stop
    self.network_manager.on_exit()
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.4-py2.7.egg/wifiphisher/common/interfaces.py", line 739, in on_exit
    self.set_interface_mac(interface, mac_address)
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.4-py2.7.egg/wifiphisher/common/interfaces.py", line 500, in set_interface_mac
    raise InvalidMacAddressError(mac_address)
wifiphisher.common.interfaces.InvalidMacAddressError: The provided MAC address 00:0f:00:61:09:c9 is invalid
  I am getting this error always. I am using one wireless adapter with ralink 3070 chipset. Please help me. Thank you

**Comment by sophron** [comment]
Please see #973.
