### ISSUE TITLE
error: [Errno 98] Address already in use

### ISSUE THREAD

**Issue by energy1984** [wifiphisher/wifiphisher#985]
```
[*] Starting HTTP/HTTPS server at ports 8080, 443
Exception in thread Thread-7:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.4-py2.7.egg/wifiphisher/common/phishinghttp.py", line 171, in runHTTPServer
    app.listen(port, address=ip)
  File "/usr/local/lib/python2.7/dist-packages/tornado-4.5.3-py2.7-linux-i686.egg/tornado/web.py", line 1944, in listen
    server.listen(port, address)
  File "/usr/local/lib/python2.7/dist-packages/tornado-4.5.3-py2.7-linux-i686.egg/tornado/tcpserver.py", line 142, in listen
    sockets = bind_sockets(port, address=address)
  File "/usr/local/lib/python2.7/dist-packages/tornado-4.5.3-py2.7-linux-i686.egg/tornado/netutil.py", line 197, in bind_sockets
    sock.bind(sockaddr)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address already in use
```

**Comment by rollly00** [comment]
You already use port 80 or 443, check netstat -ntlp

**Comment by energy1984** [comment]
root@kali:~/wifiphisher# netstat -ntlp
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 127.0.0.1:3306          0.0.0.0:*               LISTEN      811/mysqld          
tcp        1      0 10.0.0.1:8080           0.0.0.0:*               LISTEN      2664/python         
tcp6       0      0 :::80                   :::*                    LISTEN      580/apache2         
tcp6       0      0 :::443                  :::*                    LISTEN      580/apache2         
 
This'is output.

**Comment by energy1984** [comment]
solved, kill the process! Tank's

**Comment by rela589n** [comment]
what processes should i kill? and how? using system monitor?

**Comment by silentknight2001** [comment]
OSError: [Errno 98] Address already in use
