### ISSUE TITLE
Unable to launch

### ISSUE THREAD

**Issue by Shawn-Wu** [wifiphisher/wifiphisher#994]
root@kali:~/wifiphisher# wifiphisher
[*] Starting Wifiphisher 1.4GIT ( https://wifiphisher.org ) at 2018-08-27 21:50
ERROR:root:The following error has occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.4-py2.7.egg/wifiphisher/pywifiphisher.py", line 392, in start
    mon_iface, ap_iface = self.network_manager.get_interface_automatically(
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.4-py2.7.egg/wifiphisher/common/interfaces.py", line 601, in get_interface_automatically
    monitor_interface = self.get_interface(has_monitor_mode=True)
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.4-py2.7.egg/wifiphisher/common/interfaces.py", line 590, in get_interface
    raise InterfaceCantBeFoundError((has_monitor_mode, has_ap_mode))
InterfaceCantBeFoundError: Failed to find an interface with monitor mode
[!] Failed to find an interface with monitor mode
[+] Show your support!
[+] Follow us: https://twitter.com/wifiphisher
[+] Like us: https://www.facebook.com/Wifiphisher
[+] Captured credentials:
[!] Closing

**Comment by sophron** [comment]
The error is self-explanatory. You need a wireless adapter that supports monitor mode.

**Comment by Shawn-Wu** [comment]
I try some wireless adapters but no one can work in AP mode. I have see #211 but no conclusion which adapter can work in AP mode in kali. Could you please list some wireless adapters that can work in kali. Thanks your time！
